### ISSUE TITLE
Can not create new order

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#1000]
{domain}/markets/1/order_bids         //POST request

it gives 
`ActionController::InvalidAuthenticityToken in Private::OrderBidsController#create
`

**Comment by yivo** [comment]
Hi @martianatwork 

I believe you tried to use this like API endpoint. This is not correct. Use APIv2 for this kind of tasks. Also read more about CSRF: http://guides.rubyonrails.org/security.html

**Comment by martianatwork** [comment]
@yivo I believe this is not a CSRF issue as btc/usd trade is working but usd/btc is not. 

The error is because I have 0 balance. the api throws 500 error in this case. 

This is a bug, if you have 0 balance and try to make a trade you will get blank error and api endpoint will throw 500 error
