### ISSUE TITLE
Support Zcash

### ISSUE THREAD

**Issue by btcindonesia** [openware/peatio#1001]
Hi,

Thanks for great job. I added Zcash, but i faced error like:

> F, [2018-04-29T22:10:38.162778 #22553] FATAL -- : {"code"=>-32601, "message"=>"Method not found (disabled)"} (CoinRPC::JSONRPCError)

> F, [2018-04-29T22:13:09.189342 #22553] FATAL -- : {"code"=>-11, "message"=>"Accounts are unsupported"} (CoinRPC::JSONRPCError)

I really need help thanks.

**Comment by yivo** [comment]
Hi @btcindonesia 

You should enable legacy JSON RPC on your ZCASH node. For this please contact ZCASH support.
If they don't provide this feature – you will need to write own CoinAPI client.

Happy coding!
