### ISSUE TITLE
Ethereum setup on Peatio

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#1006]
Hi Team,

Can anyone please confirm if Peatio is enabled/configured for Ethereum or not? Kindly help me to implement the same.

Regards

**Comment by yivo** [comment]
Hi @sharmaabhishek2207 

Yes, Peatio supports ETH and we are working on ERC20. Docs are poor at this moment so please ask community in Telegram chat. Check more info at config/seed/currencies.yml.erb

Thanks
