### ISSUE TITLE
[Mac OS Development Environment] Trading url is not reachable

### ISSUE THREAD

**Issue by uguracar** [openware/peatio#1013]
Hi, 

I followed the instructions in below page to setup dev. environment on Mac. 
https://github.com/rubykube/peatio/blob/master/docs/setup-osx.md

After calling the following url:  http://localhost:3000/trading/1, I'm getting following response:
**Response:**
The URL you requested was not found.
Rails.root: /Users/spidrweb/peatio

Application Trace | Framework Trace | Full Trace
app/routers/routing_essentials.rb:3:in `not_found!'
app/routers/black_hole_router.rb:5:in `call'
lib/middleware/security.rb:11:in `call'
lib/middleware/i18n_js.rb:9:in `call'

All other pages are ok. I might be missing any configuration, any help is appreciated. 

thanks
Ugur

**Comment by endofthepain** [comment]
`bundle exec rake db:drop db:create db:migrate db:seed` try this first

**Comment by yivo** [comment]
Hi @uguracar 

Please don't follow docs inside folder. They are lot outdated. The best choice for you will be https://github.com/rubykube/workbench. Please try this.
