### ISSUE TITLE
Setup Ethereum

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#1019]
Hi Team,
I am working on configuring Ethereum in peatio. I have installed geth and connected it to Rinkeby testnet. I  have also configured RPC detail in currencies.yml file. But when I deposit ether to my public address, it is not getting updates in peatio. In case of BTC, wallet notify peatio about the transaction but how we can achieve it in case of ether.

Please help me to resolve it. I will update the document once it started working for me.

Regards

**Comment by yivo** [comment]
Hi @sharmaabhishek2207 

You should run all Peatio daemons so exchange will work.

Wallet notify is custom thing for ETH. Consider coding your own (available in Google).
