### ISSUE TITLE
How to make withdraw in case the ether amount is bigger than charged corresponding address

### ISSUE THREAD

**Issue by top1st** [openware/peatio#1020]
@yssavchuk 
Some exchange sites collect all ether to base address and all withdraw from the coinbase address.
In case the withdraw ether amount bigger than current charged amount how peatio can solve this?
And if we are going to withdraw erc20 token we have to use ether
That also can use base address ether.
How do you think the best solution?

**Comment by yivo** [comment]
Hi. We have this issue on our book. Now Peatio doesn't handle this well (each address works separately). We are going to learn more and solve it.

I will link issue.
See https://github.com/rubykube/peatio/issues/1031
Thanks for the report.
