### ISSUE TITLE
Need a possibility to understand,  through api, if fiat is present in current deployment

### ISSUE THREAD

**Issue by ec** [openware/peatio#1021]

**Comment by yivo** [comment]
@mafarain I think you can use `/api/v2/fees/deposit` as temporary solution.

It returns ```
[{"currency":"uah","type":"fiat","fee":{"type":"fixed","value":"1.0"}},{"currency":"btc","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"xrp","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"bch","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"ltc","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"dashd","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"ethd","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"usd","type":"fiat","fee":{"type":"fixed","value":"1.0"}},{"currency":"btcd","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"xrpd","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"bchd","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"ltcd","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"eur","type":"fiat","fee":{"type":"fixed","value":"1.0"}},{"currency":"eth","type":"coin","fee":{"type":"fixed","value":"0.0"}},{"currency":"trstd","type":"coin","fee":{"type":"fixed","value":"0.0"}}]
```

You can collects values of `type` and check if any currency is fiat.
