### ISSUE TITLE
Can not cancel orders.

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#1029]
The orders are not canceling as well as they are not appearing in order book(Amount volume Bid ask volume amount section, is it an order book or match history?).
![image](https://user-images.githubusercontent.com/11189687/39547225-8c118f30-4e74-11e8-9abc-dcbf83a4873e.png)

Similar to
#1045

**Comment by yivo** [comment]
Hi @martianatwork  I am unable to help without reproduction steps.
Please, include in your ticker: all Peatio configs (application.yml, currencies.yml, deposit_channels.yml, withdraw_channels.yml, markets.yml, plugins.yml), Peatio trading UI configs (application.yml), Peatio version, Peatio trading UI version, dump of environment variables and logfile for Rails, daemons & trading UI containers, NGINX config (if available), browser name & version, RKCP version, include any customisations you made.

**Comment by martianatwork** [comment]
Hey @yivo, Im sorry for late response i was digging up the erro and found this:
`Connection-level error: INTERNAL_ERROR - access to vhost '/' refused for user 'guest': vhost '/' is down`
`Rails.root: /home/app Application Trace app/models/amqp_queue.rb:6:in `block in connection' `
Im getting all the config files will post the reply with the data asap.
It looks like the rabbit mq is not connected, am i right?

**Comment by martianatwork** [comment]
Hey I just went through the logs and the peatio cannot connect to rabbitmq. This is weird because the container is running. but the ports are not exposed can that cause issues?

`33e46ab1ccb8        rabbitmq:3.7.4-alpine       "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        4369/tcp, 5671-5672/tcp, 25672/tcp   compose_rabbitmq_1`

**Comment by martianatwork** [comment]
Okay so i exposed the ports and the rabbitmq is connected but orders are not canceling, heres the log: 
`Started POST "/markets/btcusd/orders/clear" for 172.20.0.1 at 2018-05-05 21:15:46 +0000
  Market Load (0.2ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`id` = 'btcusd'  ORDER BY `markets`.`position` ASC LIMIT 1
Processing by Private::OrdersController#clear as JS
  Parameters: {"market_id"=>"btcusd", "market"=>"btcusd", "ask"=>"btc", "bid"=>"usd"}
  Member Load (0.2ms)  SELECT  `members`.* FROM `members` WHERE `members`.`disabled` = 0 AND `members`.`id` = 1  ORDER BY `members`.`id` ASC LIMIT 1
  CACHE (0.0ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`id` = 'btcusd'  ORDER BY `markets`.`position` ASC LIMIT 1  [["id", "btcusd"]]
   (0.2ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'btcusd' AND (created_at > '2018-05-04 21:15:46.900287')
Scoped order and limit are ignored, it's forced to be batch order and batch size
  Market Load (0.2ms)  SELECT  `markets`.* FROM `markets`  ORDER BY `markets`.`id` ASC LIMIT 1000
  Currency Load (0.2ms)  SELECT `currencies`.* FROM `currencies` WHERE `currencies`.`visible` = 1
   (0.2ms)  SELECT `currencies`.`code` FROM `currencies` WHERE `currencies`.`type` = 'fiat'
  Market Load (0.2ms)  SELECT `markets`.* FROM `markets`  ORDER BY `markets`.`position` ASC
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'usdbtc' AND (created_at > '2018-05-04 21:15:46.908986')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'usdxrp' AND (created_at > '2018-05-04 21:15:46.909892')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'usdbch' AND (created_at > '2018-05-04 21:15:46.910621')
   (0.2ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'usdltc' AND (created_at > '2018-05-04 21:15:46.911341')
   (0.2ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'usddash' AND (created_at > '2018-05-04 21:15:46.912101')
   (0.2ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'usdeth' AND (created_at > '2018-05-04 21:15:46.912876')
   (0.2ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'btcxrp' AND (created_at > '2018-05-04 21:15:46.913906')
   (0.2ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'btcbch' AND (created_at > '2018-05-04 21:15:46.914691')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'btcltc' AND (created_at > '2018-05-04 21:15:46.915478')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'btcdash' AND (created_at > '2018-05-04 21:15:46.916229')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'btceth' AND (created_at > '2018-05-04 21:15:46.916944')
   (0.2ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'xrpusd' AND (created_at > '2018-05-04 21:15:46.917680')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'xrpbtc' AND (created_at > '2018-05-04 21:15:46.920807')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'xrpbch' AND (created_at > '2018-05-04 21:15:46.921489')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'xrpltc' AND (created_at > '2018-05-04 21:15:46.922153')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'xrpdash' AND (created_at > '2018-05-04 21:15:46.922793')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'xrpeth' AND (created_at > '2018-05-04 21:15:46.923428')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'bchusd' AND (created_at > '2018-05-04 21:15:46.924078')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'bchbtc' AND (created_at > '2018-05-04 21:15:46.924710')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'bchxrp' AND (created_at > '2018-05-04 21:15:46.925343')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'bchltc' AND (created_at > '2018-05-04 21:15:46.925995')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'bchdash' AND (created_at > '2018-05-04 21:15:46.926647')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'bcheth' AND (created_at > '2018-05-04 21:15:46.927296')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ltcusd' AND (created_at > '2018-05-04 21:15:46.927959')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ltcbtc' AND (created_at > '2018-05-04 21:15:46.928597')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ltcxrp' AND (created_at > '2018-05-04 21:15:46.929234')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ltcbch' AND (created_at > '2018-05-04 21:15:46.929880')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ltcdash' AND (created_at > '2018-05-04 21:15:46.930532')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ltceth' AND (created_at > '2018-05-04 21:15:46.931451')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'dashusd' AND (created_at > '2018-05-04 21:15:46.932208')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'dashbtc' AND (created_at > '2018-05-04 21:15:46.932903')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'dashxrp' AND (created_at > '2018-05-04 21:15:46.933600')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'dashbch' AND (created_at > '2018-05-04 21:15:46.934289')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'dashltc' AND (created_at > '2018-05-04 21:15:46.934972')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'dasheth' AND (created_at > '2018-05-04 21:15:46.935618')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ethusd' AND (created_at > '2018-05-04 21:15:46.936289')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ethbtc' AND (created_at > '2018-05-04 21:15:46.936944')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ethxrp' AND (created_at > '2018-05-04 21:15:46.937600')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ethbch' AND (created_at > '2018-05-04 21:15:46.938259')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ethltc' AND (created_at > '2018-05-04 21:15:46.938919')
   (0.1ms)  SELECT SUM(`trades`.`volume`) FROM `trades` WHERE `trades`.`market_id` = 'ethdash' AND (created_at > '2018-05-04 21:15:46.939569')
  Account Load (0.1ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`member_id` = 1
  Currency Load (0.1ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 1 LIMIT 1
  Currency Load (0.1ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 2 LIMIT 1
  Currency Load (0.1ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 3 LIMIT 1
  Currency Load (0.1ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 4 LIMIT 1
  Currency Load (0.1ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 5 LIMIT 1
  Currency Load (0.1ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 6 LIMIT 1
  Currency Load (0.1ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 7 LIMIT 1
  Order Load (0.1ms)  SELECT `orders`.* FROM `orders` WHERE `orders`.`member_id` = 1 AND `orders`.`market_id` = 'btcusd' AND `orders`.`state` = 100
  CACHE (0.0ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`id` = 'btcusd'  ORDER BY `markets`.`position` ASC LIMIT 1  [["id", "btcusd"]]
  CACHE (0.0ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`id` = 'btcusd'  ORDER BY `markets`.`position` ASC LIMIT 1  [["id", "btcusd"]]
  CACHE (0.0ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`id` = 'btcusd'  ORDER BY `markets`.`position` ASC LIMIT 1  [["id", "btcusd"]]
  CACHE (0.0ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`id` = 'btcusd'  ORDER BY `markets`.`position` ASC LIMIT 1  [["id", "btcusd"]]
  Rendered text template (0.0ms)
Completed 200 OK in 48ms (Views: 0.2ms | ActiveRecord: 6.7ms)`

**Comment by martianatwork** [comment]
Okay so, i installed rabbitmq management plugin and found out that all queues are not being registered. In my case, only 9 of there were registered and then I added the 'peatio.matching' queue which was not registered. 

The queues were working properly but it is not getting processed. can you tell me what service/daemon is supposed to process the queue?

![image](https://user-images.githubusercontent.com/11189687/39668248-04e034de-50e6-11e8-8d18-ba40feef0eda.png)

![image](https://user-images.githubusercontent.com/11189687/39668258-68b21ab8-50e6-11e8-844b-247e71a30f75.png)

**Comment by martianatwork** [comment]
Fixed it by reinstalling

**Comment by sharmaabhishek2207** [comment]
Hi Martianatwork,
Have your reinstalled Peatio or rabbitmq? Is trade screen working fine post resinstallation?

**Comment by martianatwork** [comment]
@sharmaabhishek2207  Reinstalled both. Also, update the peatio code to the latest version 1.8
