### ISSUE TITLE
trading page 404, why close issues? same problem

### ISSUE THREAD

**Issue by kuaipao** [openware/peatio#1030]
trading page 404, why close issues? same problem

https://github.com/rubykube/peatio/issues/981
https://github.com/rubykube/peatio/issues/1013

The URL you requested was not found.
Rails.root: /home/app

Application Trace | Framework Trace | Full Trace
app/routers/routing_essentials.rb:3:in `not_found!'
app/routers/black_hole_router.rb:5:in `call'
lib/middleware/security.rb:11:in `call'
lib/middleware/i18n_js.rb:9:in `call'

**Comment by yivo** [comment]
Hi @kuaipao 

They are closed because people are unable to complete to migration correctly.

Please exec `bin/init_config && bundle exec rake db:drop db:create db:migrate db:seed` on master.

Better use https://github.com/rubykube/workbench to run Peatio faster

**Comment by kuaipao** [comment]
@yivo but this error from https://github.com/rubykube/workbench , use docker install
