### ISSUE TITLE
Withdraw needs refactoring for non-BIP* currencies (HD protocol in ETH and XRP)

### ISSUE THREAD

**Issue by yivo** [openware/peatio#1031]

**Comment by jdowning100** [comment]
Don't mean to be pushy, but has there been an update on non-BIP withdraws? Specifically for ERC20 withdraws. Perhaps an HD wallet solution? Like this https://github.com/meth/eth-hd-wallet
Or maybe a script that automatically sends a small amount of ETH to an ERC20 address when it receives a deposit?

**Comment by yivo** [comment]
We need support HD protocol in ETH.

**Comment by yivo** [comment]
I am not able to withdraw money after trading but I must be able to do it.

**Comment by yivo** [comment]
Each member receives his own wallet and that's why he is not able to do withdraw after trading because he doesn't have money on it.

**Comment by ysv** [comment]
Solved in #1404
