### ISSUE TITLE
Peatio daemons reconnection failure on RabbitMQ Fail

### ISSUE THREAD

**Issue by ElviraMiro** [openware/peatio#1032]
In case of Rabbit MQ restart Peatio Daemons do not reconnect and / or resubscribe on channels.

### Steps to reproduce:

1. Restart rabbit mq (for example in workbench)
2. Place orders and/or clear orders

Result orders are neither matched nor cleared

### Manual recovery:
1. Restart Peatio Daemons after RabbitMQ is restarted

### Defect:

Orders will not be matched correctly. The worst rate will be used. 

### Possible solution:

1. Reject placing orders in queues with 500 (without writing to DB)
2. Reconnect and resubscribe to channels on Rabbit MQ restarts (network failure, instance failure or per-channel error)

**Comment by yivo** [comment]
Progress in #1212.

**Comment by yivo** [comment]
![image](https://user-images.githubusercontent.com/7421323/40770560-b0708998-64c3-11e8-876c-75e50100933b.png)

**Comment by ritesh-skyach** [comment]
@yivo I have checked this and god daemons are auto reconnecting when rabbitmq-server is restarted.

**Comment by yivo** [comment]
@ritesh-skyach Thanks. I am closing this issue.
