### ISSUE TITLE
trade_executor daemon crashes 

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#1035]
See the attachment
<img width="1680" alt="screen shot 2018-05-01 at 11 33 19 am" src="https://user-images.githubusercontent.com/29736025/39575771-68cfad0c-4ee4-11e8-8f6b-1b52b270cf94.png">

**Comment by yivo** [comment]
@mkuvshynnikov I am unable to help without reproduction steps.
Please, include in your ticker: all Peatio configs (application.yml, currencies.yml, deposit_channels.yml, withdraw_channels.yml, markets.yml, plugins.yml), Peatio trading UI configs (application.yml), Peatio version, Peatio trading UI version, dump of environment variables and logfile for Rails, daemons & trading UI containers, NGINX config (if available), browser name & version, RKCP version, include any customisations you made.

**Comment by yivo** [comment]
Fixed by #1055.
