### ISSUE TITLE
Canceling orders at first try doesn't works

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#1036]
You have to cancel orders  a multiple times and it goes through randomly.
<img width="1675" alt="screen shot 2018-05-01 at 11 47 30 am" src="https://user-images.githubusercontent.com/29736025/39575846-b43e49d8-4ee4-11e8-8739-beebc3b8b0f8.png">

**Comment by yivo** [comment]
@mkuvshynnikov I am unable to help without reproduction steps.
Please, include in your ticker: all Peatio configs (application.yml, currencies.yml, deposit_channels.yml, withdraw_channels.yml, markets.yml, plugins.yml), Peatio trading UI configs (application.yml), Peatio version, Peatio trading UI version, dump of environment variables and logfile for Rails, daemons & trading UI containers, NGINX config (if available), browser name & version, RKCP version, include any customisations you made.

**Comment by yivo** [comment]
Could not confirm this and no additional info received. Closed.

**Comment by yivo** [comment]
I think I have found the problem

**Comment by yivo** [comment]
It is probably problem with Thread created inside Worker::OrderExecutor

**Comment by yivo** [comment]
Closed via #1245.
