### ISSUE TITLE
configurable min_confirmations for different coins in DB based on contribution amount

### ISSUE THREAD

**Issue by NQA1** [openware/peatio#1038]
Administrator should be able to log into peatio admin and configure the min_confirmation for each coin based on the deposit amount. For example

Coin Type: BTC
Number of Coin: 0 to 10 BTC
Min_confirmation: 3

Coin Type: BTC
Number of Coin: 10.1 btc to 100 btc
min_confirmations: 6

Coin Type: BTC
Number of Coin: 100.1 btc and above
min_confirmations: 12

The same thing for other coins.

**Comment by mod** [comment]
Suggestion in DB:
```
currency: BTC
low_limit_amount: 10
low_limit_min_confirmations: 3
high_limit_min_confirmations: 6
```

**Comment by mod** [comment]
```
currency: BTC
low_amount: 10
med_amount: 100
low_confirmations: 3
med_confirmations: 6
high_confirmations: 12
```
