### ISSUE TITLE
bundle install error: gem install ffi -v '1.9.23 ERROR

### ISSUE THREAD

**Issue by auvilink** [openware/peatio#1042]
bundle install error:

An error occurred while installing ffi (1.9.23), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.23'` succeeds before bundling.

1-8-stable

**Comment by yivo** [comment]
@auvilink Please use correct version of Ruby and make sure all C/C++ include dependencies are present in your system. For more info please refer to repository of gem `ffi`.
