### ISSUE TITLE
Manage Withdraw option not available

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#1044]
Hi, 
I am not able to see "Manage Withdraw" option in Peatio 1.7 instead it is asking for WithdrawRID. How do i provide the  Withdraw RID? Will it be any random number or string? Please suggest.

Regards

**Comment by yivo** [comment]
Hi @sharmaabhishek2207 

Please read the paragraph near `#800` in release notes.
https://github.com/rubykube/peatio/blob/master/docs/releases/1.7.0.md#breaking-changes

It contains the answer.

Thanks.
