### ISSUE TITLE
Trade Screen not working properly

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#1045]
Hi,
Trade screen is not working properly in Peatio version 1.7 though nothing seems suspicious in logs. We can buy/sell the coins but the order is not getting populated in order book section (refer attached screen shot). 

Also the following call always return blank result and hence the chart is also not plotting.
http://ec2-54-224-105-248.compute-1.amazonaws.com/api/v2/k_with_pending_trades.json?market=btcusd&limit=768&period=60&trade_id=0

In logs. the only thing which i find suspicious is below message but not sure if it could be the reason of above issues.

Scoped order and limit are ignored, it's forced to be batch order and batch size.

Please help me in resolving this issue.

Regards

**Comment by sharmaabhishek2207** [comment]
![trade_screen](https://user-images.githubusercontent.com/15141642/39666998-8f2ea1a0-50ca-11e8-8b12-6730084824c0.png)

**Comment by sharmaabhishek2207** [comment]
Hi Martianatwork,
Have your reinstalled Peatio or rabbitmq? Is trade screen working fine post resinstallation?

I have reinstalled Peatio but still the same issue.

**Comment by yivo** [comment]
Hi @sharmaabhishek2207 

Can you try to reproduce it on `http://peatio.trade`? If you unable it means bad Peatio installation. Maybe some daemon is not running or bad configuration or invalid migration. Many reasons.

**Comment by sharmaabhishek2207** [comment]
Hi Yivo,

The issue is resolved and screen is working. Thanks a lot for your support.
