### ISSUE TITLE
Withdraw all bug with low coin amount, 0.0000000000000001

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#1050]
STR:

1. Set up your wallet (any coin wallet) so it contains 0.5 coins (the amount to reproduce may be from 0.9 to 0.5).
2. Go to the Withdraw part of the same coin wallet.
3. Input the address you would like to withdraw to (another peatio account or BitGo account).
4. Click "Withdraw all" button 
5. Check if the amount in the "Withdraw amount" field is 0.5.
6. Click Submit
7. check the "Actual Amount" in the "Withdraw History"
8. See that amount you are trying to withdraw with "Withdraw all" is higher on 0.0000000000000001.

![selection_221](https://user-images.githubusercontent.com/38254545/39707841-32bbe108-521e-11e8-8db1-007c649bbc54.png)

**Comment by yivo** [comment]
Closed via #1099.
