### ISSUE TITLE
Trade CryptoCurrency

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#1054]
Hi,

When we buy/sell any cryptocurrency (say BTC) with another one (say ETH) then on successful trade (one user do sell operation while another user do buy operation for it) then we see the success message on trade screen but actually there is no deduction or addition of cryptocurrencies in the wallet. Is there any issue in the code or my understanding is wrong w.r.t trade? Please help me.

Regards

**Comment by yivo** [comment]
Hi,

Trading doesn't interact with blockchain. It only changes balance in user account which is stored in database.

Regards
