### ISSUE TITLE
Error when you try to copy the address

### ISSUE THREAD

**Issue by gfedorenko** [openware/peatio#107]

**Comment by gfedorenko** [comment]
![screenshot from 2017-12-15 13-22-30](https://user-images.githubusercontent.com/25289193/34040241-8685fcfe-e19b-11e7-839d-1f48768858b2.png)

**Comment by gfedorenko** [comment]
ZeroClipboard wouldn't run if flash disabled or not installed. It would be better to replace it with clipboard.js later( https://clipboardjs.com/ )

**Comment by yivo** [comment]
@gfedorenko It is the single solution.

**Comment by yivo** [comment]
Fixed in #117
