### ISSUE TITLE
Peatio daemons container size goes above 300gb

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#1076]
The peatio daemon logs gets too big
![image](https://user-images.githubusercontent.com/11189687/39885732-f2266b9c-54aa-11e8-8cc5-ba1ba78a1f23.png)

![image](https://user-images.githubusercontent.com/11189687/39885741-fa0d8552-54aa-11e8-98f1-1fd4f2251725.png)

also i have noticed this https://pastebin.com/QsrgzRRn in amqp_matching.log

**Comment by yivo** [comment]
@martianatwork Why you run Peatio in dev move? In production it logs to STDOUT everywhere. We will later prepare patch to tweak logger level.

**Comment by yivo** [comment]
https://github.com/rubykube/peatio/blob/master/lib/daemons/daemons.god#L35

**Comment by yivo** [comment]
Also see https://github.com/rubykube/peatio/issues/1079
