### ISSUE TITLE
Not possible to generate new address (403 Forbidden)

### ISSUE THREAD

**Issue by gfedorenko** [openware/peatio#108]
![screenshot from 2017-12-15 13-27-43](https://user-images.githubusercontent.com/25289193/34040352-f82054d6-e19b-11e7-900a-ec5bf4aef15f.png)

**Comment by gfedorenko** [comment]
Works the same as in demo. Need to dig in more into the logic behind

**Comment by yivo** [comment]
This error occurs on fresh peatio installation.

**Comment by scatterp** [comment]
@yivo revert gems to peatio/peatio

**Comment by yivo** [comment]
@gfedorenko Issue is related to terminated daemons.
