### ISSUE TITLE
Minimum price for orders 

### ISSUE THREAD

**Issue by TasyaBykova** [openware/peatio#1088]
The Request: 

We can set a minimum price that a certain erc20 coin where the user will not be able to sell it under this price. 
The system will refuse the sell order if the selling price is less than specified in our 'minimum price' field.

**Comment by martianatwork** [comment]
Can we make this as a global option for all currencies?

**Comment by yivo** [comment]
This should be done via Peatio plugin for Peatio v1.8.

**Comment by yivo** [comment]
Completed by @dinesh-skyach. cc @TasyaBykova
