### ISSUE TITLE
Ability for User to Generate API Key (removed?)

### ISSUE THREAD

**Issue by Sambusik** [openware/peatio#1091]
Users had the ability in previous versions to generate an API key. Currently the Profile (/settings) of the user does not display anything. 

Ideally, have the ability to enable API keys (with features for that API key to: Read, Enable Trading, and Withdraw) options.

n.b. I would assume the API key would be the **Access Token** (?) used in peatio-sdk: https://github.com/rubykube/peatio-sdk/blob/27b1f7b25f0370c50e5279274c62d1085bdb0812/src/ApiClient.js

**Comment by yivo** [comment]
This moved to https://github.com/rubykube/barong/pull/441
