### ISSUE TITLE
Fresh install of Peatio does not have a string for market ID

### ISSUE THREAD

**Issue by kriskelly** [openware/peatio#1104]
If you install Peatio from scratch and run `rake db:setup`, it loads the db schema from schema.rb instead of running the migrations directly. schema.rb does not have string ID declared in the `markets` table definition.

This breaks the peatio-trading-ui repo in a way pointed out in this PR:

https://github.com/rubykube/peatio-trading-ui/pull/32

See my last comment there.

**Comment by kriskelly** [comment]
Notice also there is some branching logic in `bin/setup` that runs `rake db:setup` if you're using `RAILS_ENV=development`, so this is broken by default in that case.

**Comment by shingonoide** [comment]
@kriskelly There's comment about that in bin/setup script.
`# in production we run db:setup and solvency:liability_proof tasks as k8s jobs`
I guess if you run with production environment, you have to manually bootstrap database or create tasks as k8s jobs for example.
I would like to know more about that if it is ok or will go to change in a near future.

**Comment by yivo** [comment]
This is known Rails issue. See https://github.com/rails/rails/issues/16599#issuecomment-177036440

**Comment by kriskelly** [comment]
Ah, I see now. Yes so rake db:setup currently produces an invalid database
in peatio. I think a workaround could be to remove references to db:setup
in the code and use db:migrate instead, and maybe put something in the docs
to that effect.

A more robust solution would be to use a field not called “id” and then
set_primary_key in the Market model.

This may not seem like a high priority fix but it has tripped up a lot of
people, you see comments in the telegram channel every now and then by
people who have run into this.

**Comment by yivo** [comment]
So this is Rails bug, probably this was fixed in Rails 5. Use rake db:create db:migrate db:seed instead of db:setup.

**Comment by yivo** [comment]
@k1T4eR Please, update bin/setup

**Comment by yivo** [comment]
See #1259 #1260 #1261 #1262
