### ISSUE TITLE
Changing market precision, while trading is going, can block creation of new orders that should match to the old once

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#1106]
STR:

1. Set up a market pare with ask/bid precision = "3".
2. Go to the trading ui, to the preset pare.
3. Create ask order request with volume 0.001, price 0.001.
4. Change preset market pare precision to "2" or "1", "0".
5. Try to create bid order request that will mach previously (with volume 0.001, price 0.001) created ask order.

You will fail to create an matching order as maximum precision is changed to lesser value. 

Possible solution is to save market configurations (precision) in the ask/bid orders in the moment of creation.

**Comment by yivo** [comment]
Now it is denied to change precisions for markets.
