### ISSUE TITLE
Currency#enabled functionality should work in pair with Market#enabled

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#1109]
#855 
In case we will make some currency invisible the market with the same currency will still be displayed on trading UI. This may lead to sucked orders.

STR:

1. Create an order on market pare usd/xrp.
2. Go to admin panel and remove check box from XRP Currency#visible.
3. Go back to market usd/xrp (update the page). Already created trades are saved there but cannot be canceled by user.
4. Click on the, previously created, order.
5. Click on create order (orders should be on the same side buy/sell).
![selection_241](https://user-images.githubusercontent.com/38254545/40112526-e23064b4-590e-11e8-8ff5-2be3ce5b56c4.png)
6. Tho the trading UI will response with "Fail" the order will be created (it can be checked in the order history of your account)
7.  Go to admin panel and click check box from XRP Currency#visible.
8. Go back to market usd/xrp (update the page).
9. Find that your order is displayed on your orders panel but not on the all orders panel.
![selection_242](https://user-images.githubusercontent.com/38254545/40112790-e01c6f0a-590f-11e8-9f94-8b61007a2d67.png)
10. Try to delete order that was created while the XRP Currency#visible was disabled by any means available to a customer.
11. Try to create a matching order to move the order to the Done state.

Result: You will fail to delete or match this order and you will stack with frozen balance.

**Comment by yivo** [comment]
@yssavchuk If we disable currency we should also disable markets in after_update.

**Comment by yivo** [comment]
When I disable currency it should also disable all related markers in after_update callback.

**Comment by yivo** [comment]
Fixed via #1233.
