### ISSUE TITLE
Question: Setting up bank connectivity

### ISSUE THREAD

**Issue by Developer1123** [openware/peatio#111]
How do you setup a bank account, that should be used as the platform deposit and withdraw account(fiat)?
Do you need a bank API or something, as I cannot seem to wrap my head around it?
I cannot seem to find any documentation on it?

Thank you in advance.

**Comment by scatterp** [comment]
you can contact peatio.tech (commercial support) direct speak with louis who will handle this internally with me

**Comment by yivo** [comment]
Moved to https://github.com/rubykube/peatio/issues/558.
