### ISSUE TITLE
Replace account versions and balance calculations to queries to deposit / withdraw / order / trade + use paper_trail

### ISSUE THREAD

**Issue by yivo** [openware/peatio#1111]

**Comment by yivo** [comment]
Now Peatio stores balance in columns of account model. To update balance it performs many locks to database using legacy code from early Rails 4 driven by Stackoverflow posts. We need to get rid of it because: 1) it is slow and not guaranteed to work good under heavy load; 2) it is dangerous to store such variable because anytime race conditions may occur. Instead we need to calculate balance every time by using existing deposits, withdraws, orders & trades. This moves all responsibilities to database.

**Comment by calj** [comment]
Do you think we can cache this information and invalidate the cache in case of withdrawal, deposit, orders, trade?

**Comment by yivo** [comment]
@calj We should not cache anything related to money. This may hurt well. We just need several fast SQL queries which use index.
