### ISSUE TITLE
gem 'digest-sha3' conflict with ubuntu 16.04

### ISSUE THREAD

**Issue by lizhuomeng71** [openware/peatio#1114]
On ubuntu 16.04

When try bundle install

Get error message 

current directory: /var/lib/gems/2.5.0/gems/digest-sha3-1.1.0/ext/digest
make "DESTDIR="
compiling KeccakF-1600-reference.c
compiling KeccakNISTInterface.c
compiling KeccakSponge.c
compiling displayIntermediateValues.c
displayIntermediateValues.c: In function ‘displayText’:
displayIntermediateValues.c:113:9: error: format not a string literal and no format arguments
[-Werror=format-security]
         fprintf(intermediateValueFile, text);
         ^
cc1: some warnings being treated as errors
Makefile:241: recipe for target 'displayIntermediateValues.o' failed
make: *** [displayIntermediateValues.o] Error 1

make failed, exit code 2

--
Note:
uncomparability is noticed the ethwork in their git repo

https://github.com/EthWorks/ethereum.rb/issues/11

**Comment by yivo** [comment]
Hi @lizhuomeng71 

We don't support Ubuntu or other deployments. Please, use Docker which works stable.
