### ISSUE TITLE
1.8-stable Google signin error

### ISSUE THREAD

**Issue by frivolous106** [openware/peatio#1120]
Hi,
In 1.8-stable, google signin doesnot work.
I set correctly google api client.
But 127.0.0.1:3000 is always attached.

![google-signin-error](https://user-images.githubusercontent.com/34869694/40242319-09ef2c70-5ac6-11e8-9802-9705e00ae42b.png)
Please solve this issue.

**Comment by yivo** [comment]
Please use your custom Google credentials.

**Comment by frivolous106** [comment]
Thank for your quick response.
Of course, i used my Google credentidals.
This is my application.yml:

development:
  <<: *defaults

  # Development configuration variables for sign in with Google.
  #GOOGLE_CLIENT_ID:           1044454023387-emhp5vmfnp5cf1n9juk09g8gcckrova7.apps.googleusercontent.com
  #GOOGLE_CLIENT_SECRET:       tAFZvO200-0z3MpCyOpkPH0G
  GOOGLE_CLIENT_ID:           495160712466-2pv2i3l5757sv66k9ccmhelmqk8kcuv6.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET:       LaFPbhFWLnWxKYLlTT0KMs9F
  GOOGLE_OAUTH2_REDIRECT_URL: http://koinde.com/auth/google_oauth2/callback # Specify URL address to which user will be redirected after successful sign in.

**Comment by frivolous106** [comment]
Why closed this issue?
I donot understand this manner.
