### ISSUE TITLE
1.8-stable Google signin error

### ISSUE THREAD

**Issue by frivolous106** [openware/peatio#1121]
Hi, I used my Google credentials.
Please check my application.yml.

development:
  <<: *defaults

  # Development configuration variables for sign in with Google.
  #GOOGLE_CLIENT_ID:           1044454023387-emhp5vmfnp5cf1n9juk09g8gcckrova7.apps.googleusercontent.com
  #GOOGLE_CLIENT_SECRET:       tAFZvO200-0z3MpCyOpkPH0G
  GOOGLE_CLIENT_ID:           495160712466-2pv2i3l5757sv66k9ccmhelmqk8kcuv6.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET:       LaFPbhFWLnWxKYLlTT0KMs9F
  GOOGLE_OAUTH2_REDIRECT_URL: http://koinde.com/auth/google_oauth2/callback # Specify URL address to which user will be redirected after successful sign in.

  # Development configuration variables for sign in with Auth0.
  AUTH0_OAUTH2_DOMAIN:        peatio-playground.auth0.com
  AUTH0_OAUTH2_CLIENT_ID:     lGKS9ADpknQr415RNZrrQTf3Jh8k2Fvc
  AUTH0_OAUTH2_CLIENT_SECRET: LxUPnrrrpRHSB-vVgWU3TwmakQ8acY5mYVTaVgkREQL3i9avjpOnWTXSSEsrbLzK

**Comment by yivo** [comment]
Leave this blank: `GOOGLE_OAUTH2_REDIRECT_URL`. It is not callback URL.

And set `OAUTH2_SIGN_IN_PROVIDER` to `google`.

**Comment by yivo** [comment]
Hi @frivolous106 

I assume your issue is solved.

Please refer to https://developers.google.com/identity/sign-in/web/sign-in for more details.

**Comment by frivolous106** [comment]
@yivo 
Thank for your response.
Thank very much.
But it doesnot still work.
This is my questions.
1. Google sign in.
   If i correct the redirect url as the exact domain url forcefully, it soon redirected to Google sign url.
   Where is my mistake?
2. Which version is correct?
3. I want to KYC functions.
   In your document,  Barong supports this function.
   So i must install both of Barong and peatio platform?
   What is your solution?
4. Now your document is written that your peatio platform supports BTC, BCC, BCH, XRP, DASH and ETH.
    It is exact?
    Are you all confirmed?
5. I cannot access admin panel.
    How can i access it?

I tried to install peatio-1.8.0 stable as both setup-ubuntu doc and workbench.
But in workbench, i cannot know where your peatio platform is installed.
Please give me the exact document or install guide.
Please give me your skype id if possible.
I trust you can solve those issues as enough.
Please teach and help me.
