### ISSUE TITLE
How add the Cryptonote coin

### ISSUE THREAD

**Issue by EarlVadim** [openware/peatio#113]
Hello.
How can add the cryptonote coin to exchange. Kindly help to solve the issue.

**Comment by mod** [comment]
We are sound going to add XMR with a documentation and manual on how to add other CryptoNotes based coins, we will update the progress here.

**Comment by olehif** [comment]
@mod Hi, any updates on topic?

**Comment by EarlVadim** [comment]
Any news?

**Comment by yivo** [comment]
We have created issue for this #345.
