### ISSUE TITLE
google sign problem

### ISSUE THREAD

**Issue by touristcoin** [openware/peatio#1131]
i have problem with sign google
back in 127.0.0.1
The redirect URI in the request, http://127.0.0.1:3000/auth/google_oauth2/callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs
But application is configured good
host my dns

**Comment by blockChn** [comment]
This issue occurs when  redirect URL is different between "Google Authentication" and "/config/application.yml".
If you are using in dev environment,  scroll down the file "/config/application.yml" till the end. It has one more entry for development.

**Comment by yivo** [comment]
@touristcoin Please, follow the instructions on the https://developers.google.com/identity/sign-in/web/sign-in

Google Sign in is not broken. Please, use your credentials.
