### ISSUE TITLE
Deposit update message always has empty attributes in payload

### ISSUE THREAD

**Issue by sramsden** [openware/peatio#1132]
The pusher message relies on attributes from `self.changes_attributes_as_json` which is always empty for `after_update`

**Comment by sramsden** [comment]
This applies to Withdraw, and Member also.

**Comment by yivo** [comment]
Hi @sramsden 

The reasons we are not going to fix this:
1) You are browsing outdated version of Peatio. We removed this method probably in 1.6 or 1.7.
2) This Pusher call is for old Peatio frontend which we use ONLY for QA. We don't focus much on this. Peatio 1.8 UI works fine with this event.

Thanks you for the report.
