### ISSUE TITLE
Support dynamic levels feature

### ISSUE THREAD

**Issue by m-an** [openware/peatio#1134]
From version 1.8 Barong supports dynamic levels feature, which means what levels are defined in the process of installation. So now we can change order of levels, requirements needed for getting each of levels and their amount. We need Peatio to be able to specify minimum required level for tradind(for example, by ENV variable), instead of a static number 3 like it is now.

**Comment by yivo** [comment]
https://gist.github.com/yivo/2d610244ed4b0f97e8505efa93aa2207

**Comment by yivo** [comment]
![image](https://user-images.githubusercontent.com/7421323/40714889-7fe12948-640c-11e8-835a-43290f725368.png)

**Comment by yivo** [comment]
Closed by #1222.
