### ISSUE TITLE
Error getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by rahulkhairnarr** [openware/peatio#114]
SocketError at /

getaddrinfo: Name or service not known

when starting exchange

**Comment by mod** [comment]
@rahulkhairnarr Hello,
We recommend you to try running from the workbench
https://github.com/rubykube/peatio-workbench

Don't forget to run bin/init_config with proper environment variables.
We will soon publish a tutorial and a new set of documentations.

**Comment by yivo** [comment]
Hi @rahulkhairnarr

Please, check issue https://github.com/rubykube/peatio/issues/36

**Comment by yivo** [comment]
@rahulkhairnarr The fix is at https://github.com/rubykube/peatio/issues/36#issuecomment-348679433

**Comment by yivo** [comment]
We have also prepared PR with fix #143
