### ISSUE TITLE
Trading Page is blank /markets/btccny

### ISSUE THREAD

**Issue by khalidNascenia** [openware/peatio#115]
I can log in with the seed user to the system. But I cannot see any activity on the trading page within the seed user account. I can see the trading console skeleton, but it is almost blank in terms of contents. 

I want to configure trading for at least 2 currencies for the seed user. Can you please let me know:

- How can I add currency balance to the seed user?
- How can I make the trading platform functional (for buying and selling currencies)?

I would appreciate if you could share some insight on those? 

Thank you in advance.

**Comment by yivo** [comment]
Hi @khalidNascenia 

You can check how factories are implemented and grab required code to manually feed database with demo data. You should also check cryptocurrency test networks. There are no currently any one-line command to achieve this.

**Comment by yivo** [comment]
@khalidNascenia I hope your issue is resolved. You may open the issue again if you have more questions.

**Comment by khalidNascenia** [comment]
@yivo Yeah, the issue is resolved.
