### ISSUE TITLE
Withdraw and Member update message always has empty attributes in payload 

### ISSUE THREAD

**Issue by sramsden** [openware/peatio#1152]
Although the behaviour has been changed for the Deposit model (#1132) it has not been changed for Withdraw and Member.

The pusher message relies on attributes from changed_attributes which is always empty for after_update

The messages should be fixed or removed.

**Comment by yivo** [comment]
Hi @sramsden 

These messages are too for old frontend. Which we use **only for QA**. We don't aim to spend time on fixing it.

**Comment by yivo** [comment]
I think we can remove these calls later. See https://github.com/rubykube/peatio/issues/1153
