### ISSUE TITLE
BTC wallet activation 

### ISSUE THREAD

**Issue by matrixkloud** [openware/peatio#1173]
I have installed latest repo. Everything is going good till now. Setup completed. without any issue. But BTC wallet not working for deposit. 

Need proper idea how  BTC will work here and other coin also. 

Sorry for the beginner level of question and poor English writing . 

Thanks.

**Comment by yivo** [comment]
Hi @ArifulIslamSonnet 

Please check legacy Peatio docs for these or use Telegram channel or buy plan at peatio.tech.

The issues at GitHub are for problem resolving, not for support. Thanks.

**Comment by matrixkloud** [comment]
Thanks. Keep looking at instagram  group.
