### ISSUE TITLE
Bitcon address not visible

### ISSUE THREAD

**Issue by touristcoin** [openware/peatio#1176]
![schermata 2018-05-23 alle 09 10 09](https://user-images.githubusercontent.com/38797338/40408857-3c82ceac-5e69-11e8-85d4-d299caa02335.png)

All installed correctly and bitcoind running, i have also waiting 24 our for sync but the address wallet is not visible. Why ?

**Comment by Mishul-G** [comment]
@touristcoin were you able to fix this issue? How did you get the address to appear on the funds page?
