### ISSUE TITLE
Btc Private keys does not stored in Database and test btc Blances not confirmed

### ISSUE THREAD

**Issue by HafeezRai** [openware/peatio#1177]
Hi sorry for inconvenience I have installed peatio It generate btc address But It does do following:
1- It does not store btc private keys in Database
2- Not confirm btc wallet balance

do any one have this problem or this just on my end
if this just on my side can anyone tell me solution for this.

Thanks is advance

**Comment by yivo** [comment]
Hi @HafeezRai 

The GitHub issues are not for support. They are used for bugs & feature & refactoring.

Please, use Telegram channel or peatio.tech for support.

BTW: We don't store any private keys in DB.

**Comment by HafeezRai** [comment]
thanks for your reply it means i can access private keys from btc daemon can you tell me telegram channel?

**Comment by yivo** [comment]
@HafeezRai Sure. https://t.me/peatio
