### ISSUE TITLE
Remove deprecated POST /api/v2/withdraws

### ISSUE THREAD

**Issue by yivo** [openware/peatio#1178]

**Comment by yivo** [comment]
Closed by #1284.

**Comment by sramsden** [comment]
@yivo I assume this functionality is replaced with some alternative workflow?
For example, member makes request to applogic and an admin then makes request to peatio via the management api.
Is that outlined somewhere?

**Comment by nchigwamba** [comment]
@yivo I am also interested in the response to the question from @sramsden
