### ISSUE TITLE
Currency Deposit Address Not Displaying

### ISSUE THREAD

**Issue by jdowning100** [openware/peatio#1182]
Hi, I have tried to get help in the telegram for this issue to no avail. This may be an issue caused by workbench, as other people have gotten this to work when building from source.
I am running the latest master workbench with Peatio v1.8 and cannot generate a deposit address with Peatio. Right now I am trying to set up BTC deposits.
Here you can see the issue:

![deposit](https://user-images.githubusercontent.com/26939949/40444007-bb52d546-5e8d-11e8-9e3e-561efef01929.PNG)

The deposit address is blank. When I try to copy it I copy nothing. There are no script errors in the console.
The following is my workbench/config/peatio/currencies.yml file:

![currency](https://user-images.githubusercontent.com/26939949/40444207-5342230c-5e8e-11e8-9744-249ee970dd3c.PNG)

The following is my database entry for BTC:

![btc](https://user-images.githubusercontent.com/26939949/40444533-3cdc9970-5e8f-11e8-801d-22c9a5f3cb03.PNG)

I have tried almost everything to get the deposit addresses working. I have dropped and reseeded the database, restarted the server, changed the currency settings in the database, checked to make sure pusher is working, god daemons are up, etc.
Strangely, god does not log anything when I navigate to the BTC deposit page.

![deposit_coin](https://user-images.githubusercontent.com/26939949/40444336-b8e9fcde-5e8e-11e8-8a41-0d028e9d60bb.PNG)

But god is up:

![god](https://user-images.githubusercontent.com/26939949/40444518-3231574a-5e8f-11e8-8f90-bbdbc2244adb.PNG)

And my RPC server is up and can generate an address:

![curl](https://user-images.githubusercontent.com/26939949/40444557-4f8f2d1c-5e8f-11e8-81e3-7b03f50e8b91.PNG)

So, what am I doing wrong? What do I have to do to generate a simple deposit address?

**Comment by frivolous106** [comment]
@jdowning100 ,
Hi, how are you?
How did you set your workbench proxy setting?
Can you tell me your skype id?

**Comment by ZohairZaman** [comment]
@frivolous106 I am facing the same issue.
add me on skype zohair@blockverse.io
Looking forward to hearing back, thanks

**Comment by jdowning100** [comment]
@frivolous106 not sure what difference the proxy makes but here it is:

![proxy](https://user-images.githubusercontent.com/26939949/40448879-691623aa-5e9c-11e8-9e3c-0c613f00190c.PNG)

I don't use skype but I'm in the telegram, my user is @jdowning

**Comment by ZohairZaman** [comment]
@jdowning100 
could you please tell me the password for admin@barong.io ?
cant seem to find it, and im stuck. would appreciate it. thanks

**Comment by jdowning100** [comment]
@ZohairZaman With all due respect, that has nothing to do with my question. The password is given when you build the barong database for the first time, but I am using auth0. You'll have to rebuild the barong database if you missed it.

**Comment by minersbad** [comment]
can you contact me for fix issue minersbad@gmail.com

**Comment by minersbad** [comment]
https://github.com/rubykube/peatio/issues/1173

**Comment by jdowning100** [comment]
For reference, rails log is able to generate an address. 
I think the issue may be related to rabbitmq, which is up and running but message transmission seems wonky (I am not experienced in using rabbitmq)

![rails](https://user-images.githubusercontent.com/26939949/40455195-824fa5de-5eb1-11e8-9ff0-665070e64c1c.PNG)

**Comment by jdowning100** [comment]
Update: I have built/installed Peatio 1-8-stable from source and ran it without docker and address generation works. This is thus an issue with workbench or docker. I am closing this issue and moving it to rubykube/workbench
