### ISSUE TITLE
Excessive call to localtime form daemons

### ISSUE THREAD

**Issue by mod** [openware/peatio#1184]
We noticed too many call to stat(/etc/localtime)

https://stackoverflow.com/questions/7243046/excessive-stat-calls-on-etc-localtime-in-rails-application/7249409#7249409

Apparently we need to set the timezone before hand in daemons.

**Comment by subaru9** [comment]
@mod pls assign this to me and put appropriate labels. I don't have permissions..

**Comment by yivo** [comment]
This is fine and no actions should be performed. I noticed very big amounts of this call in many problematic active_support/all projects. Implementing this issue will make things complicated or ever break a lot of stuff. We don't have much tests to cover daemons.

**Comment by yivo** [comment]
Time zone is set somewhere in config/*. Next active_support makes many manipulations to get correct Time.

**Comment by mod** [comment]
I suggest if timezone is supposed to be set,
We set a default value in case of missing environment value.
We should also show a Warning if default value is used
@mitjok @yivo

**Comment by mod** [comment]
Default timezone should be UTC

**Comment by subaru9** [comment]
Daemons receive the timezone set to 'Paris'.
Verified it on macOS by adding `logger.info { "Current time zone: #{Time.zone.name}" }` to `lib/daemons/amqp_daemons.rb` and restarting the daemons.

**Explanation**: 
1. Every daemon loads environment which initializes the application. 
2. Time zone got set from application.yml via TIMEZONE proxy env var.

**Comment by subaru9** [comment]
@mod @yivo how can I verify that demons call frequently /etc/localtime?

**Comment by yivo** [comment]
We just need to set TZ in container. https://stackoverflow.com/questions/7243046/excessive-stat-calls-on-etc-localtime-in-rails-application

**Comment by yivo** [comment]
Closed by #1205.
