### ISSUE TITLE
Bring back legacy Peatio benchmark

### ISSUE THREAD

**Issue by yivo** [openware/peatio#1189]
These benchmarks SHOULD NOT touch existing Peatio code. They must be isolated.

**Comment by mod** [comment]
@yivo do you mean this patch, should change anything else than code in lib/benchmark ?

**Comment by yivo** [comment]
@mod yes, they should be isolated in lib/benchmark

**Comment by mod** [comment]
Make sure we can have a rake task

rake benchmark:profiling[execution]

to run the benchmark with the gem ruby-prof

**Comment by dinesh-skyach** [comment]
@yivo @mod I did use the ruby-prof gem, As this gem provides the complete internal details of the methods and variables used, so the output is enormously big and if we print the output then it crashes our system. My system Specs are the folllowing:- 

- Processor:-  Core i5 ( 7th generation )

- Memory:-    16 GB ( DDR4 )

- Storage:-    240 GB SSD

Please let me know your thoughts on this.

**Comment by dinesh-skyach** [comment]
@yivo @mod we can also print the output to a specific file. Let me try this.

**Comment by yivo** [comment]
Closed via #1202.

**Comment by mod** [comment]
We need less iterations and output into a file

For example 50 or 100 orders is plenty enough for Ruby Prof.
