### ISSUE TITLE
Create liveness/readiness endpoints

### ISSUE THREAD

**Issue by mod** [openware/peatio#1190]
For kubernetes and container env. we need to implement the standard of liveness and readiness

I suggest /health/ready
                 /health/alive

ready must return 200 if app is ready (db loaded and seeded)
you can also return NOT 200 if you are too loaded, to receive less traffic
and alive should run few VITAL cheks like is mysql work, is rabbit connection ok yes, like 5 sanity tests

@yivo can you suggest 4-5 simple and fast tests we can do ?

**Comment by yivo** [comment]
@mod Hmm, let me some time to think about this.

**Comment by yivo** [comment]
`class Public::HealthController`

`GET /health/liveness_probe`
`GET /health/readiness_probe`

See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by yivo** [comment]
Closed via #1197.
