### ISSUE TITLE
Too many SQL market requests, maybe move markets table into memory?

### ISSUE THREAD

**Issue by sergii-savchenko** [openware/peatio#1199]
Per 27K Commits in log we have 78K queries like:
```sql

SELECT `markets` . * FROM `markets` WHERE `markets` . `id` = ? ORDER BY `markets` . `position` ASC LIMIT ? 
```
This is most popular query. Can we just move this table to in-memory storage?

**Comment by yivo** [comment]
I don't think this will help. I removed some of them in https://github.com/rubykube/peatio/pull/1195

@sergii-savchenko cc

How many requests for currency table we have?

**Comment by yivo** [comment]
Closed via https://github.com/rubykube/peatio/pull/1245
