### ISSUE TITLE
Documentation Update: Trading UI

### ISSUE THREAD

**Issue by ZohairZaman** [openware/peatio#1201]
I do not see any documentation whatsoever on how the trading ui refactor to a seperate project can be linked to the peatio project. I deployed the project through docker, but I can not access the trade screen. Any guidance on how that can be fixed

**Comment by yivo** [comment]
Please see the migration steps at https://github.com/rubykube/peatio/blob/master/docs/releases/1.5.0.md#breaking-changes

We have the tickets for updating docs.
