### ISSUE TITLE
Add Support Tradingview Chart

### ISSUE THREAD

**Issue by greo2017** [openware/peatio#1207]
Hello,

Can you guys add Tradingview Chart ? It looks more better and usefull.

Thanks.

**Comment by sergii-savchenko** [comment]
This chart is licensed. So it can be added on per project basis

**Comment by Sambusik** [comment]
Anybody can just fill out a form, and then have access to their Github. I assume most of us here have replaced the default chart with TradingView. The challenging part is the data feed for live real time data.

**Comment by irlecoin** [comment]
@sergii-savchenko  I already have access on tradingview cart. It is not hard to take it. I think tw is more better than basic chart.

@Sambusik yes i aggree with you.

**Comment by greo2017** [comment]
@sergii-savchenko You can take TW licence easly. It is not hard.

@Sambusik Yes i aggree with you.

**Comment by yivo** [comment]
@greo2017 This is stuff for TradingUI. See https://github.com/rubykube/peatio-trading-ui
