### ISSUE TITLE
Changing market list dropdown menu to horizontal

### ISSUE THREAD

**Issue by greo2017** [openware/peatio#1209]
Hi,

I tried to change market list dropdown menu to horizontal, but it doesnt work. When i click "BTC" button the BTC market doesnt show up. I need help for it. Can you guys assist me, please?

Thanks.

**Comment by Sambusik** [comment]
This should be part of the [Trading UI repo](https://github.com/rubykube/peatio-trading-ui), since it has been _(rightfully)_ split into two separate projects.

**Comment by yivo** [comment]
Thanks @Sambusik
