### ISSUE TITLE
Migrate markets.yml into database

### ISSUE THREAD

**Issue by mod** [openware/peatio#121]
Patch 1:

Migrate markets.yaml using db seeds
and create a markets migration and model

Patch 2:
Add the edition CRUD into the current peatio admin panel

**Comment by mod** [comment]
https://github.com/rubykube/peatio/tree/master/lib/generators/config/templates
Once this task is finished
please create tasks and define for 
- banks.yaml
- currencies.yaml

**Comment by yivo** [comment]
Closed via #412.
