### ISSUE TITLE
Why the redirect url was still 127.0.0.1:3000?

### ISSUE THREAD

**Issue by frivolous106** [openware/peatio#1210]
Hi, everybody!
Hope you are good.
I have a issue while signining with barong.
The callback url was still 127.0.0.1 :3000.

barong.mypeatio.com/oauth/authorize?client_id=94fa515f74664b335a93e88fc5c25c5b0ba07fae51b1a1c3687b34181bdab76f&redirect_uri=http%3A%2F%2F127.0.0.1%3A3000%2Fauth%2Fbarong%2Fcallback&response_type=code&state=82e9b2a5e3497ba8fefb3ac5e4c4f33dd13e91acdc49b862
![image](https://user-images.githubusercontent.com/34869694/40618563-88e213d6-629a-11e8-8435-627adaa62cea.png)

I already appended barong sid, secret, domain and redirect_url in peatio/config/application.yml.
![image](https://user-images.githubusercontent.com/34869694/40618480-426b816c-629a-11e8-9ab7-33eb06df3c24.png)

Please solve my issue.

**Comment by touristcoin** [comment]
launch daemon with -b host domain

**Comment by frivolous106** [comment]
Thank @touristcoin

**Comment by hasanaliqureshi** [comment]
``
![image](https://user-images.githubusercontent.com/12941929/52540980-ac9de100-2db1-11e9-9799-ebece62c9c3f.png)
 
URL : http://auth.inspon.com/oauth/authorize?client_id=a68be319fca51caca60eed5711226e568bd1c1d13ff452b945515f1a6ffbaca4&redirect_uri=http%3A%2F%2Fapi.inspon.com%2Fauth%2Fbarong%2Fcallback&response_type=code&state=a526d51d8e71927be24d600039ad28f35106dac72290611a
