### ISSUE TITLE
Installation completed with all coins

### ISSUE THREAD

**Issue by go-apollyon** [openware/peatio#1211]
![schermata 2018-05-28 alle 19 31 10](https://user-images.githubusercontent.com/39408509/40645529-eb3b949e-6326-11e8-916d-c97e58e361b5.png)
![schermata 2018-05-29 alle 08 53 49](https://user-images.githubusercontent.com/39408509/40645533-ec899486-6326-11e8-88c6-f1a7e7c3ea30.png)

**Comment by Mishul-G** [comment]
@coinlisting Great to see this. We are done with the entire setup, just having some problems connecting the nodes from a separate server to our Peatio deployment. Would greatly appreciate your help - my skype id is - zohair@blockverse.io
