### ISSUE TITLE
BTC Address not being generated

### ISSUE THREAD

**Issue by Mishul-G** [openware/peatio#1218]
We have the entire infrastructure deployed & setup. Currently, we have btc node setup on a separate server, with appropriate changes made to rabbitmq and config files to send/receive messages accordingly.

I am not sure how to generate address since the button is removed. Does it generate via some command? How in real time would anyone get an address? Would really appreciate any help. Thanks

**Comment by yivo** [comment]
Please exec `CoinAPI[:btc].create_address!`. If it doesn't work you will see the problem, if it works – you have broken daemons. Please, use Telegram channel for support. GH issues is not correct place.

**Comment by Mishul-G** [comment]
Hey can you tell me where to run this command from? Does not seem to work from the command line, where can I insert this code and see the results in realtime. Thanks

**Comment by Mishul-G** [comment]
This is what I tried through terminal -  ruby -r "./lib/coin_api/btc.rb" -e "CoinAPI[:btc].create_address!"
& I tried - ruby -r "./lib/coin_api/btc.rb" -e "CoinAPI.BTC.create_address!"

@yivo Would appreciate your help. Thanks alot

**Comment by HafeezRai** [comment]
Rub bundle exec rails console and than run 
CoinAPI[:btc].create_address!
You will see error

**Comment by ianeinser** [comment]
@HafeezRai @yivo can you explain more specific?
how can i execute CoinAPI[:btc].create_address!

**Comment by endofthepain** [comment]
rails console
