### ISSUE TITLE
Wrong customer ID or password,please try again.

### ISSUE THREAD

**Issue by fouvy** [openware/peatio#1223]
I setting peatio with barong auth. after login barong, and redirect back to peatio, I cannot login, and get "Wrong customer ID or password,please try again.". how can I setting peatio with barong right in production environment?

**Comment by mephiroth** [comment]
i have the same question,i checked the log ,it turned out that 
(barong) Callback phase initiated.
(barong) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
@yivo

**Comment by yivo** [comment]
Usually it works second time. Try in browser without any extensions installed. If it doesn't work – get your own Google OAuth credentials and try with them. For me both Auth0 & Google work fine every day with default configs.

**Comment by mephiroth** [comment]
Google work fine for me too , but with barong i got the error everytime

**Comment by yivo** [comment]
I think this issue is related to omniauth-barong or barong itself. You can open issues in their repos.

**Comment by fouvy** [comment]
Same issue with @mephiroth , @yivo I have opened an issue on barong repo.
