### ISSUE TITLE
eth address wallet created but dont see deposit

### ISSUE THREAD

**Issue by touristcoin** [openware/peatio#1231]
All ok peatio create address wallet, checked also in geth is present, but we have do a deposit. In peatio NO PRESENCE and in geth i see balance correctly.

**Comment by touristcoin** [comment]
deploy@loft9064:~/peatio$ bundle exec rake solvency:liability_proof
/home/deploy/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in key_skipped!' : WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/home/deploy/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:inkey_skipped!' : WARNING: Skipping key "URL_SCHEME". Already set in ENV. (StructuredWarnings::StandardWarning)/home/deploy/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SENTRY_DSN_BACKEND". Already set in ENV. (StructuredWarnings::StandardWarning)Fetching accounts balances is not implemented yet
Fetching accounts balances is not implemented yet
Fetching accounts balances is not implemented yet
Fetching accounts balances is not implemented yet
Fetching accounts balances is not implemented yet
Fetching accounts balances is not implemented yet
Fetching accounts balances is not implemented yet
deploy@loft9064:~/peatio$

**Comment by yivo** [comment]
Hi @touristcoin 

GitHub issues is not correct place for support. Please, refer to peatio.tech.

**Comment by yivo** [comment]
I suggest to use Telegram channel for free support.
