### ISSUE TITLE
Version 1.7 Management API Cannot Cancel Withdraws

### ISSUE THREAD

**Issue by sramsden** [openware/peatio#1232]
I know this is changed in 1.8 so no big deal but thought I'd mention it in case you want to fix it if for 1.7.
It is not possible to cancel because the demanded param name does not match the expected param name.

![image](https://user-images.githubusercontent.com/8897694/40816142-87fe65a4-658e-11e8-974d-35aa705dcce3.png)

**Comment by yivo** [comment]
Thanks for the bug report.

**Comment by yivo** [comment]
Fixed in #1236.
