### ISSUE TITLE
New API method for getting currencies prices (as well as volume and change) for a specific currency

### ISSUE THREAD

**Issue by berezh** [openware/peatio#1234]
Need new method to display information about currency on next way: http://grabilla.com/08601-98b949a7-547e-431f-acdd-4f691a735218.png

Method should return list of currencies with next data:
[{
"currency": "ltc",
"price": 0.02248000,
"volume": 611.8759,
"change": -1.36
},
{
"currency": "bch",
"price": 0.13814600,
"volume": 4248.5263,
"change": -1.41
},
...
where:
currency - id of the currency
price - price of the currency (the costs of currency compare to the selected currency that passed in param)
volume - volume of the currency
change - the percent value of changing currency price during some period (default can be a day)

Method should has next params:
currency - the current currency to get info about (required)
period - a period of time to check the change value(optional)

Additional method to get the list of available currencies. for example the result of this method should be a list of available currencies ids(keys): ['ltc', 'bch', ...]

**Comment by berezh** [comment]
What details needed?

**Comment by yivo** [comment]
Use existing API methods:

* http://peatio.trade/api/v2/tickers
* http://peatio.trade/api/v2/members/me
* http://peatio.trade/api/v2/order_book?market=uahusd&asks_limit=200&bids_limit=200

Based on these method it is possible to implement the feature you want. 

See https://github.com/rubykube/peatio/blob/1-8-stable/docs/api/member_api_v2.md

**Comment by zlip2x** [comment]
@yivo How to get my current order_book by api ?
