### ISSUE TITLE
v1.8 Management Create Withdraw API Error Messages

### ISSUE THREAD

**Issue by sramsden** [openware/peatio#1239]
For v1.8 if you attempt to create a withdraw with amount exceeding the fee then you simply get..
`Amount must be greater than 0.0`
.. which is not technically wrong because the model's amount in peatio is less than zero, however it is misleading.  
Perhaps a more meaningful error message would be more appropriate here.

Also, when attempting to create a withdraw with a blank amount then the error message is received in duplicate .. 
`{"errors":["Amount must be greater than 0.0","Amount must be greater than 0.0"]}`
.. which is wrong, but it's obviously not a big problem.

**Comment by yivo** [comment]
We have on TODO list to fully redesign errors in APIs. The errors behavior you see is from legacy Peatio API.
