### ISSUE TITLE
Deposit bug with ETH and ETC 

### ISSUE THREAD

**Issue by go-apollyon** [openware/peatio#1240]
Hi there, 
we have created in coinapi other one file for ETC like ETH name etc.rb and with this config. We have copy ETH conf and added ETC and rpc call id 1. 
we did this because when you install both wallets with 2 different rpc servers, we have noticed that neither of them receives deposits, but in blockchain they are present. If we only activate the ETC rpc and disable ETH, then the deposit works. Is there any way to make them work together?

# encoding: UTF-8
# frozen_string_literal: true

module CoinAPI
  class ETC < BaseAPI
    def initialize(*)
      super
      @json_rpc_call_id  = 1
      @json_rpc_endpoint = URI.parse(currency.json_rpc_endpoint!)
    end

**Comment by yivo** [comment]
I don't understand what you are trying to get. Everything works fine with multiple JSON RPC nodes. It doesn't matter.

**Comment by go-apollyon** [comment]
If work ETH only yes without problem, if i install ETC and i give API Coin ETH, both take wallet address succesfuly but dont take deposit.

**Comment by go-apollyon** [comment]
I have installed 10 time with different method, same problem

**Comment by go-apollyon** [comment]
Problem issue fixed. The problem is in the file eth.rb that going in conflict with other coins

**Comment by mod** [comment]
@coinlisting Do you have a fix ?

**Comment by go-apollyon** [comment]
@mod no Louis. practically if eth is alone as an ethash algorithm it works perfectly. The moment I add a new coin with the same algorithm, the wallets are both generated perfectly but both of them do not see the deposits anymore. Since I only see eth.rb in coinapi, do I have to add another .rb file with a different rpc id? Because I did this too but the problem was not solved. Basically coming back to the fact that ETH alone works, as soon as I find myself adding, for example, ETC, PIRL or another always as fork ethereum, I'm in conflict. What client api should I choose?

under you see screenshot of etherscan that funds are in balance, i have also checked blockchain eth in server and balance is present, but in peatio i dont see it. If i disable other coin i see deposit. What happening?

![schermata 2018-06-06 alle 00 05 34](https://user-images.githubusercontent.com/39408509/41005925-b75262ee-691f-11e8-9db9-8d65942287e9.png)
![schermata 2018-06-06 alle 00 17 28](https://user-images.githubusercontent.com/39408509/41005936-bd43c8aa-691f-11e8-8f42-7c58c4c32a0b.png)

**Comment by go-apollyon** [comment]
@mod no answer about this bug?

**Comment by go-apollyon** [comment]
???

**Comment by yivo** [comment]
Having multiple currencies connected to the same Go Ethereum is well supported and we use it in production longer than month. Unless you give any specific code, environment, configurations and other stuff I can't help you. If you want to get free premium support this is not right place. We all spend big amounts of time maintaining this project. You can always contact http://peatio.tech/ for paid support.

**Comment by go-apollyon** [comment]
we have contacted a lot of time them, but no answer about it. no way, support very low. How you can request payment withous support?

**Comment by yivo** [comment]
Sorry I don't do business. I will send your request to sales.

**Comment by peatiotech** [comment]
@coinlisting hello!
Please feel free to contact me at dtun@heliostech.fr. I don't see any contacts under your github name Mark Weir. Cheers!

**Comment by go-apollyon** [comment]
contact for what, for a bug of code and payed 16k € ?

**Comment by go-apollyon** [comment]
i have re-installed all with same issue

**Comment by go-apollyon** [comment]
if i have more coins that use same ETH coinapi
this value "json_rpc_call_id = 0" need to be ever 0 ?
