### ISSUE TITLE
Nokogiri error

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1246]
Hi.
When I tried to run "bundle install", I got an error related to nokogiri.  

Fetching nokogiri 1.8.2
Bundler::GemspecError: Could not read gem at /home/evgheni_melnic/.rvm/gems/ruby-2.5.0/cache/nokogiri-1.8.2.gem. It
may be corrupted.
An error occurred while installing nokogiri (1.8.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.8.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  datagrid was resolved to 1.5.7, which depends on
    rails was resolved to 4.2.10, which depends on
      actionmailer was resolved to 4.2.10, which depends on
        actionpack was resolved to 4.2.10, which depends on
          actionview was resolved to 4.2.10, which depends on
            rails-dom-testing was resolved to 1.0.8, which depends on
              nokogiri

I am not sure why that is happened and how to fix it.
My server is Ubuntu 14.04 and current ruby version is 2.5.0.

Please let me know if you have any hint about this problem.
Thanks.

**Comment by yivo** [comment]
Install DevTools. Please, refer to Nokogiri repo for this problem.
