### ISSUE TITLE
COIN API Algo ETH

### ISSUE THREAD

**Issue by go-apollyon** [openware/peatio#1250]
Hi there, 
if i add other coins with same fork ETH which coin api need to add?
Because if i use ETH Coin api dont receive deposit

**Comment by yivo** [comment]
`class ETHFork < ETH`
`+ Custom code for ETH fork behaviour`

If you don't receive deposits start to debug daemons. Use `pry-byebug`.

**Comment by go-apollyon** [comment]
What you mean custom code

**Comment by yivo** [comment]
Code which implements behaviour of ETH fork based on ETH.

**Comment by go-apollyon** [comment]
I do not think you're giving the solution to the problem. It's like saying he plays the lottery. 
the change was made that you said but the problem is the same. This is a big bug on the coin API, I can guarantee it. If you only use eth it works as soon as you add more coins, the system crashes. We will probably abandon this fork and project, because there are too many problems of integration and scalability

**Comment by go-apollyon** [comment]
no answer?
