### ISSUE TITLE
GET /api/v2/trades always returns side value as null

### ISSUE THREAD

**Issue by sramsden** [openware/peatio#1252]
As per issue title ... `GET /api/v2/trades` always returns side value as null .. eg,

`[{"id":1724,"price":"10000.0","volume":"0.0001","funds":"1.0","market":"btcusd","created_at":"2018-06-06T06:00:53+02:00","side":null}]`

However `GET /api/v2/trades/my` is okay .. eg,

`[{"id":1724,"price":"10000.0","volume":"0.0001","funds":"1.0","market":"btcusd","created_at":"2018-06-06T06:00:53+02:00","side":"ask","order_id":5632}]`

I have seen this in 1.8 but in versions prior to 1.8 also.

**Comment by yivo** [comment]
See https://github.com/rubykube/peatio/issues/1052

**Comment by sramsden** [comment]
@yivo Then side should not appear in the results from `/trades`

**Comment by thomasdavis** [comment]
@yivo How does one get a trade history for a market to make a trade history UI widget? 


![download 9](https://user-images.githubusercontent.com/416209/47330343-a03b2e80-d6c3-11e8-80c8-0ccd9396409a.png)

They color code their market history based on the side
