### ISSUE TITLE
FalseClass, Fresh Install

### ISSUE THREAD

**Issue by mochfauz** [openware/peatio#1253]
Hello guy's, when I try to install this software, i got this error, with ruby 2.3

root@exchange:/usr/local/share/code/peatio# bundle exec rails server
/Usr/local/share/code/peatio/config/plugins.rb:1:in `<top (required)>': undefined method `yield_self' for false:FalseClass (NoMethodError)

Thanks

**Comment by yivo** [comment]
Use Ruby 2.5
