### ISSUE TITLE
Trading page no UI

### ISSUE THREAD

**Issue by tzman89** [openware/peatio#1268]
I made setup of peatio and everything works fine except trading page UI
Can someone please help?

This is how it looks
![trade](https://user-images.githubusercontent.com/35830811/41142981-fa98ab60-6af7-11e8-803c-def7cdfa4c97.png)

- I've done bin/init_config and assets precompile
- Peatio and trading ui are the both 1.8

**Comment by yivo** [comment]
I don't know your setup but you probable need to browse network calls and see what's wrong.

**Comment by yivo** [comment]
You can also use Telegram channel for quick community support https://t.me/peatio
