### ISSUE TITLE
When I click on the command to run the server, is the error of the content of the picture the reason for the error of the environment variable?

### ISSUE THREAD

**Issue by molisehao** [openware/peatio#1273]
<img width="915" alt="2018-06-09 11 56 06" src="https://user-images.githubusercontent.com/35921075/41193594-bcbca6b2-6c40-11e8-81e6-9c7e7fd83793.png">
When I click on the command to run the server, is the error of the content of the picture the reason for the error of the environment variable?

**Comment by yivo** [comment]
You should use `bundle exec rails s` and the latest stable 1-8. We don't support anything except Docker environment.
