### ISSUE TITLE
Daemon status issue?

### ISSUE THREAD

**Issue by ZohairZaman** [openware/peatio#1274]
When i run god status, i see that all the daemons are up. However, for each of the daemons, I need to do a bundle exec command for them to actually work. For example, in order to get deposits working on an address, I had to run:
bundle exec ruby lib/daemons/amqp_daemon.rb deposit_coin

on a seperate ssh instance. I feel like this should not be required. Is there some better way of going about this, and is there a better way of ensuring these are being run properly besides god status, as that seems to tell me the all the daemons are up even when they do not seem to be functioning properly (like I said, deposits only work when I have the above command running separately)

**Comment by mochfauz** [comment]
Are you running on production env, or development env?
I had strage issues also, everything goes well when I develop on development mode except for withdraw. After I move to production env, I can't get deposit_address. It's so strage. There is specific command that I should to do?

Thanks

**Comment by Regzaenal** [comment]
@zohair are u  run all  daemon in 1 server ? I mean all blockchain in 1 server ? If yes u need to separated some of them. Some of daemons wont works when other damons is active

**Comment by yivo** [comment]
If god status outputs «up» it means daemon works. If it works but nothing happens (like for deposit address) – check you configuration and do everything manually first. god works stable now and we use it in production more than 5 months so it seems like problem in your environment.

@candrawahyudi everything can run on single machine. I don't see any reasons for this not to work. 

Double-check you configs please!
