### ISSUE TITLE
Ability to select the order type (market) at the time of trading.

### ISSUE THREAD

**Issue by antechdemo** [openware/peatio#1289]

**Comment by yivo** [comment]
Not clear.

**Comment by antechdemo** [comment]
When we put the order on the trade page,by default the order type set  to "Limit". please add support for choose the different orders type like "Market", "Stop-Limit".

**Comment by yivo** [comment]
We don't add any new features to trading UI. Only bugfixes. You can do it by yourself.

**Comment by martianatwork** [comment]
Hey, @yivo I'd like to work on this, can you guide me a bit?
