### ISSUE TITLE
How can i get data in specific time interval from GET /api/v2/k?

### ISSUE THREAD

**Issue by Liubyvyi** [openware/peatio#1290]
I need to get data in specific time interval, for example from 'timestamp1' to 'timestamp2'. How can i do this? For now I can specify only one interval boundary using the 'timestamp' parameter, but this is not enough

peatio version: 1.8.25

**Comment by yivo** [comment]
OK. I will check this.

**Comment by yivo** [comment]
Closed via #1342.
