### ISSUE TITLE
Support ERC20 using BitGo

### ISSUE THREAD

**Issue by yivo** [openware/peatio#1291]

**Comment by Sambusik** [comment]
On another note, BitGo doesn't support all ERC20 tokens... 


_ERC20 tokens are available to enterprise clients with a BitGo contract. More tokens are being added on a regular basis and customers are advised to check back often for updates to the list._

_Augur Augur (REP)Basic Attention Token Basic Attention Token (BAT)Bread Bread (BRD)Civic Civic (CVC)Funfair Funfair (FUN)Golem Golem (GNT)Kyber Network Kyber Network (KNC)Maker Maker (MKR)Numeraire Numeraire (NMR)OmiseGo OmiseGo (OMG)Quantum Resistant Ledger Quantum Resistant Ledger (QRL)RDN Raiden Network Token (RDN)TenX TenX (PAY)WAX Wax (WAX)ZIL Zilliqa (ZIL)0x 0x (ZRX)_

**Comment by yivo** [comment]
I hope they will add more soon like EOS, NEM

**Comment by hagadawi** [comment]
@yivo dear could you plz guide me how can i install peatio on ubunto 18 and test this open source environment?

**Comment by yivo** [comment]
@hagadawi Answered you in issue.

**Comment by mod** [comment]
@Sambusik @yivo for now we will focus in ERC20 using geth especially that bitgo limit the list of supported tokens.

also for test purposes we need a geth working implementation

**Comment by Sambusik** [comment]
Update... BitGo just added a whole lot of ERC20 Tokens last week. https://www.bitgo.com/info/resources#multi-currency

On another note, we've tested with their testnet "ERC" token, and it worked.
