### ISSUE TITLE
new flag coin

### ISSUE THREAD

**Issue by go-apollyon** [openware/peatio#1292]
I have added new coin, but is not present flag icon. I have added svg file in svg/color but i continued to not show flag on funds page

**Comment by yivo** [comment]
We don't support existing UI. It is deprecated and used only for QA. See packages in https://github.com/rubykube/peatio/blob/master/package.json 
If icon doesn't exist in these packages you have to find different or fork peatio.

**Comment by BitenCoin** [comment]
@go-apollyon I just found out how to add it, create folders like this:
/peatio/public/images/yarn_components/cryptocurrency-icons/svg/color
and put svg files into color folder
