### ISSUE TITLE
Installation issues on Ubunto 18

### ISSUE THREAD

**Issue by hagadawi** [openware/peatio#1303]
Could anybody explain the steps of installation on ubunto 18. i have performed all the steps as mentioned in ubunto readme still no gui.

**Comment by yivo** [comment]
Ubuntu is not supported. Only Docker environment is supported. See https://github.com/rubykube/workbench

**Comment by Regzaenal** [comment]
@hagadawi i am not yet test peatio with ubuntu 18 but i already test peatio with ubuntu 17
