### ISSUE TITLE
Google Authentication Redirect URI error

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1316]
Now I am trying to install Rubykube Peatio on my EC2.
I have set variables(client_id, client_secret, etc) correctly for Google Authentication.

But when I click "Sign in with Google" button, then it displays a google error page like the below.

"The redirect URI in the request, http://127.0.0.1:3000/auth/google_oauth2/callback, does not match the ones authorized for the OAuth client."

I am not sure why the redirect URI is showing as 127.0.0.1:3000 in spite of I have set it correctly on Google as well as config/application.yml file.

Please let me know once you know it.
Thanks.

**Comment by k1T4eR** [comment]
@Coding-Jewelry Please ensure that nginx forwards `Host` header to upstream. For correct up to date nginx config see ci/nginx/server.conf in 1.8 branch.

**Comment by Coding-Jewelry** [comment]
It works correctly.
Thanks.

**Comment by goodstardust** [comment]
@Coding-Jewelry me too help me
