### ISSUE TITLE
How can I see admin dashboard?

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1317]
Now I am trying to install Rubykube peatio on my EC2 instance.
I am using Google auth instead of Barong for users authentication.
I login successfully with my Google account, but I am not sure how I can see Peatio's admin dashboard.

Please let me know if you have any hint.
Thanks.

**Comment by yivo** [comment]
Just modify the variable: https://github.com/rubykube/peatio/blob/1-8-stable/config/templates/application.yml.erb#L9

**Comment by Coding-Jewelry** [comment]
Thank you for letting me know.
