### ISSUE TITLE
Markets page error on daemon way

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1319]
I have installed rubykube peatio on my ec2 instance.  Everything seems to be setup.
The problem is that an internal server error is occurred on markets page when I run Peatio as daemon way ("bundle exec rails server -e production -d").
So, if I navigate "http://ec2-xx-xx-xx-xx.eu-central-1.compute.amazonaws.com/markets/usdbtc.json" on the browser, then it shows the result below.
{"status":"500","error":"Internal Server Error"}

But when I run Peatio as standard way ("bundle exec rails server -e production"), then the markets page is successfully loaded without any error.

I am not sure what the reason is.

Please let me know if you have any hint about this.
Thanks.

**Comment by yivo** [comment]
We don't support any deployment except Docker-based. Please use Docker. Check out typical commands in workbench.

**Comment by yivo** [comment]
You have to view the logs.
