### ISSUE TITLE
Barong doesn't seem to work correctly

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1320]
I have installed rubykube peatio on my instance (http://35.226.198.87), and currently Barong authentication is used.
I think that configuration settings related Barong is already setup.
The problem is, when I click "Sign in With Barong" button, then it goes to Barong login page.  And when I login successfully, then it doesn't redirect to Peatio page, still remains on Barong page.
I am not sure how I can fix this problem.

Please let me know if you have a solution.
Thanks.

**Comment by yivo** [comment]
Can you show your `BARONG_OAUTH2_REDIRECT_URL`?

**Comment by Coding-Jewelry** [comment]
Current BARONG_OAUTH2_REDIRECT_URL is:
"http://<%= ENV.fetch('SERVER_IP', '127.0.0.1') %>/auth/barong/callback"

Is this incorrect?  If yes, how should I change it?

**Comment by yivo** [comment]
Leave it blank.
