### ISSUE TITLE
Mark withdraw as pending while waiting bitgo admin approval

### ISSUE THREAD

**Issue by mod** [openware/peatio#1325]
Currently peatio will automatically fail for all withdrawals while waiting for Bitgo admin to approve the transaction. Withdrawals should be pending till status changed to success after success approval. I'll update the description.

**Comment by yivo** [comment]
See more details https://github.com/rubykube/peatio/issues/1011

**Comment by mod** [comment]
Can this be connected to our generic behavior intended.
connected to waiting confirmations:  #1276

**Comment by ysv** [comment]
closed in v1.9
