### ISSUE TITLE
Failed to run benchmark tools

### ISSUE THREAD

**Issue by shal** [openware/peatio#1329]
**Environment**: [Workbench](https://github.com/rubykube/workbench)

**Command**:
```sh
$ rake benchmark:execution
```
Peatio version: `1.8.39`

I got **error**:

```
NoMethodError: undefined method `update!' for nil:NilClass
/home/app/lib/benchmark/helpers.rb:15:in `block in lock_funds'
/home/app/lib/benchmark/helpers.rb:14:in `each'
/home/app/lib/benchmark/helpers.rb:14:in `lock_funds'
/home/app/lib/benchmark/matching.rb:26:in `block (3 levels) in run_prepare_orders'
/home/app/lib/benchmark/matching.rb:26:in `block (2 levels) in run_prepare_orders'
/home/app/lib/benchmark/matching.rb:24:in `block in run_prepare_orders'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/core_ext/range/each.rb:7:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
/home/app/lib/benchmark/matching.rb:22:in `map'
/home/app/lib/benchmark/matching.rb:22:in `run_prepare_orders'
/home/app/lib/benchmark/matching.rb:15:in `run'
/home/app/lib/tasks/benchmark.rake:18:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => benchmark:execution
(See full trace by running task with --trace)
```

Same issue with `rake benchmark:matching` command.

**Comment by shal** [comment]
Steps to reproduce:

- Start workbench.

- Run toolbox tests in workbench.
```sh
$ bundle exec rake toolbox:run
```
- Exec to peatio container.
```sh
$ docker-compose exec peatio bash
```

- Run.
```sh
$ rake benchmark:xxxxx
```

**Comment by shal** [comment]
https://github.com/rubykube/peatio/blob/8537db2b28e35ff71b64a35d494207bd302e6739/lib/benchmark/helpers.rb#L15

Here is hardcoded `btc`.

**Comment by ianeinser** [comment]
@shal @mod 
Hi everyone, I got this error when running with RC12 (dynamic jwt keys), the benchmark used to work but now it doesn't. Please advise

Creating 10 traders... OK
Making each trader billionaire... error: -- HTTP 401 Unauthorized --

-- Request URL --
https://www.plutonext.com/management_api/v1/deposits/new

-- Request Method --
POST

-- Request headers --
{"User-Agent":"Faraday v0.15.1","Content-Type":"application/json"}

-- Request body --
{"payload":"eyJpYXQiOjE1Mzk1NjM1MTAsImV4cCI6MTUzOTU2MzgxMCwianRpIjoiODc2MTNiNDQtYzcwMS00ZTZjLWE4YjQtNmI5ODMwOTRlN2M3IiwiaXNzIjoidG9vbGJveCIsImRhdGEiOnsidWlkIjoiVUlEMjM0RDRGNDY5QyIsImN1cnJlbmN5IjoidXNkIiwiYW1vdW50IjoxMDAwMDAwMDAwLCJzdGF0ZSI6ImFjY2VwdGVkIn19","signatures":[{"protected":"eyJhbGciOiJSUzI1NiJ9","header":{"kid":"toolbox"},"signature":"U6mWW33ACdiebr651Fs3u3qchCS4llwoiOAyq7VqV3pqWWImngTFTpDGN2ANyMC7Tm2tWXNKIVLdK-NkxDI8jUQ8K1gC3Qv_E45nvG1BqbABGGCkF5Fwaxn-7ZZriXkgJiC_9YanSkW0R9HMNISdLmZ1QZQhz2FyUheFKwVE4dfjafr6ypZ562u5U72BtY1cwAM_w2dkIY8tUF-oBVR_IAWSzSk3xjbDGQZ9mI22QtkTNtyg3HeoVmXoRb_9aEcsq9NQRHj8qjheE6sBI-RUmfD_UWQgRTWzSJ2dQm16AEgv_UnC2Ye0d4KK-TZHBvGoAqXa77ix-TKfuVfa-B4mXA"}]}

-- Response headers --
{"cache-control":"no-cache","content-length":"33","content-type":"application/json","x-request-id":"cfac642e-55a1-42ac-bf6a-494c2dd997fb","x-runtime":"0.042454","date":"Mon, 15 Oct 2018 00:31:50 GMT","connection":"close"}

-- Response body --
{"error":"Failed to verify JWT."}
. Use --trace to view backtrace
rake aborted!
Command failed with status (1): [docker-compose run --rm toolbox run --root...]
