### ISSUE TITLE
How can I do trading with only Google authentication?

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1330]
I have installed Rubykube Peatio on my ec2 instance, and currently Google authentication is used.

When I click "Funds" tab, then it shows an error message like:

"Please, pass the corresponding verification steps to enable trading."

How can I trade in this case?  And what is needed to enable trading for users?

**Comment by yivo** [comment]
You have to set variables https://github.com/rubykube/peatio/blob/1-8-stable/config/templates/application.yml.erb#L167 to zeros and it will do the trick.
