### ISSUE TITLE
Trading interface results in to Routing error

### ISSUE THREAD

**Issue by JaapHaitsma** [openware/peatio#1334]
When I build the workbench and then login to peatio and go to trading
http://api.wb.local/trading/1
I get an routing error

<img width="1174" alt="screen shot 2018-06-21 at 07 51 35" src="https://user-images.githubusercontent.com/905295/41717529-049454fe-7528-11e8-8064-565864a5c816.png">

**Comment by JaapHaitsma** [comment]
I also get the same error if I just build the peatio module

**Comment by yivo** [comment]
Please post workbench issues in workbench repo. 

Also you have to use https://github.com/rubykube/peatio-trading-ui if you don't.
