### ISSUE TITLE
After post to /v2/sessions "sessions are not synchronized" 

### ISSUE THREAD

**Issue by m-an** [openware/peatio#1336]
After creating a peatio session from frontend side it is created, but after some time it "disappears" and you are still logged in in frontend, but not in peatio and trading-ui. So, to actually start trading at trading-ui you should log in again.

**Comment by yivo** [comment]
Are you sure you issue request exactly evert time you get JWT?

**Comment by dinesh-skyach** [comment]
@yivo I have checked this and  it's working as per the required behavior i.e When requested to /api/v2/sessions it creates a cookie session with the expiration time of JWT token. If JWT token expires after 1 hour then the cookie session created will also expire after 1 hour.

**Comment by yivo** [comment]
Closing this. Not confirmed.
