### ISSUE TITLE
Missing a step in Ubuntu deployment

### ISSUE THREAD

**Issue by snowsky** [openware/peatio#1338]
After ruby is installed:
\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.5.0 --gems=rails
there should be a source command to use ruby 2.5.0:
source /usr/local/rvm/scripts/rvm

Otherwise it will still use the system ruby, which is 2.3.1 on Ubuntu 16.

**Comment by Regzaenal** [comment]
Use rbenv instead of rvm

**Comment by yivo** [comment]
This type of deployment is not supported.
