### ISSUE TITLE
Access denied for user 'root'@'

### ISSUE THREAD

**Issue by TheHolyRoger** [openware/peatio#1346]
On changing the mysql password in the various config env and yml files
I'm only able to get as far as: Access denied for user 'root'@'172.18.0.21' (using password: YES)Please provide the root password for your MySQL installation
Whilst running `make run`

I can not work out how to send the mysql password to the docker containers, changing the env files doesn't seem to be enough.

**Comment by Regzaenal** [comment]
Hit me up on whatsapp i can help you!

Whatsapp : +6285790752549

**Comment by yivo** [comment]
You have to take a look in config/database.yml and update the password. If this is related to workbench you have to open issue there.

**Comment by ghost** [comment]
Mine is related to workbench, please let me know how to set the password properly for the database
