### ISSUE TITLE
Notify when receiving ethereum coins.

### ISSUE THREAD

**Issue by antechdemo** [openware/peatio#1351]
I want to send payment to eth base account once i receive ethers in my account. But the ether is not reflected in my account.How we can set the wallet notification for ethereum?
Like in btc we can set the walletnotify in the bitcoin.conf file.

**Comment by yivo** [comment]
How does this is related to Peatio? Please, google for `walletnotify eth`.

**Comment by yivo** [comment]
You can also try Event API.

**Comment by antechdemo** [comment]
Thanks,But in peatio ,how get notified when any of the ETH address receive deposits.

**Comment by BitenCoin** [comment]
@antechdemo 
Maybe we can use crontab for this, if anyone can figure it out it will be great.
It's related to peatio, if there is no balance change after deposit in Peatio accounts then eth is not working properly.
