### ISSUE TITLE
Can create new endpoint in API

### ISSUE THREAD

**Issue by ElviraMiro** [openware/peatio#1356]
For frontend we need next endpoint - something same /v2/trades/{currency}
GET
Description: Get currency's trades at last 24h
Param name: currency (Currency value contains usd,btc,xrp,bch,ltc,dash,eth,trst,USD,BTC,XRP,BCH,LTC,DASH,ETH,TRST) which located in path
Example: 
`GET /v2/trades/eth`
response:
```json
[{
"btc": {"price": 0.074587, "volume": 80120, "change": 0.36},
"usd": {"price": ..., "volume": ..., "change": ...}
}]
```
when:
- volume - sum last 24h purchased ETH on market for eth & btc currencies
- price - average ETH price in BTC
- change - ratio price last 24h to an earlier period (in percentages)

**Comment by yivo** [comment]
Closed via #1368.
