### ISSUE TITLE
Unable to generate deposit address

### ISSUE THREAD

**Issue by TheHolyRoger** [openware/peatio#1359]
Hello, I'm unable to generate deposit addresses. I think it's not connecting to my node RPCs but I'm not sure, there's nothing helpful in the console.

How can I debug? How can I verify its connected to the node wallet?
Thanks

**Comment by mishul** [comment]
@TheHolyRoger Have deployed multiple working exchanges. Message us on skype or email: mgupta14@illinois.edu
