### ISSUE TITLE
Replace all calls to pusher / slanger by AMQP calls

### ISSUE THREAD

**Issue by mod** [openware/peatio#1360]
In this patch we need to remove gems and configs related to pusher
we will entirely replace it with an event queue.

A daemon will consume those events and forward them to slanger.

**Comment by dinesh-skyach** [comment]
@mod @yivo  Do we need to push the pusher calls to rabbitmq queue and then trigger pusher events from queue. Is this right?

**Comment by yivo** [comment]
@dinesh-skyach Yes, ideally we need to:
1) Delete duplicate Pusher calls which are also sent to EventAPI
2) Replace all the left Pusher calls with calls to EventAPI

Event API serializers:
1) https://github.com/rubykube/peatio/blob/1-8-stable/app/serializers/serializers/event_api/order_event.rb

Event API specs:
1) https://github.com/rubykube/peatio/blob/1-8-stable/spec/serializers/serializers/event_api/order_created_spec.rb

Event API docs:
1) https://github.com/rubykube/peatio/blob/1-8-stable/docs/specs/event_api.md

**Comment by vitorgamer58** [comment]
It is already running? Are not we dependent on Pusher?

**Comment by ysv** [comment]
@vitorgamer58 https://github.com/rubykube/peatio/pull/1591
