### ISSUE TITLE
Epic: Separate deposit and withdrawal wallet called Hot and Warm

### ISSUE THREAD

**Issue by mod** [openware/peatio#1361]
We need an unified interface to manage hot and warm wallet

hot should be used only for deposits
warm should be used only for withdrawal

A process should move the money regularly between Hot and Warm

Peatio must support many HOT, many warm wallet per currency.

**Comment by yivo** [comment]
Can you explain the details? I don't understand.

**Comment by ysv** [comment]
closed in 1.9
