### ISSUE TITLE
KYC system with verification levels

### ISSUE THREAD

**Issue by MariaBog** [openware/peatio#1362]
Hello is it possible to improve the following KYC system.
and which version.

Once the user logs in, the user should not be forced to do the phone verification immediately. Instead, the user will see the platform and have the option to verify afterwards in order to make use of the platform.

Level 1 (Only Email verification): Can do nothing on the platform.

Level 2 (Only Phone, Full address, Full Name, Date Of Birth verification): Can only withdraw and deposit fiat 25000. (Once the client reaches this limit he/she cannot make any further deposits till gaining level 3)  Cryptocurrency deposits/withdrawals are unlimited. 

Level 3 (All of the above + ID/Passport/Drivers license confirmation:  Unlimited withdraws/deposits

+ When asking for a ID/Passport/Drivers license photo, that it also asks for a selfie with the same ID/Passport/Drivers license to avoid identity fraud.

**Comment by mod** [comment]
@MariaBog can you move this issue to Jira, this is a frontend story to me, let's speak about it
