### ISSUE TITLE
Frontend modifications not registering. Caching issue?

### ISSUE THREAD

**Issue by ZohairZaman** [openware/peatio#1364]
With one of the recent updates in the possible states a withdraw can be in, I am getting the following error on the UI:

[missing "en.funds.withdraw_history.confirmed" translation]

I have ensured that the mapping for this exists, so the translation certainly exists in the code base. However, i think that during compilation, the front end assets are being cached, which is why this error is happening. To verify this was the issue indeed, I changed the translation "State/Action" to "Current State", and I still see the old "State/Action" label appearing on the UI. I was wondering how I could go about fixing this issue, as I am sure I will continue to tackle this as I keep making changes to the frontend.

**Comment by yivo** [comment]
The current front is deprecated and used only for QA. Stop using it and develop your own. I18n data can be refreshed by `bundle exec rake assets:precompile` because I18n data is delivered in stupid legacy way at in original peatio.
