### ISSUE TITLE
BitGo Wallet Transactions Query Parameter Incorrect

### ISSUE THREAD

**Issue by sramsden** [openware/peatio#1365]
In BitGo class..

`query          = { limit: 100, nextBatchPrevId: next_batch_ref }`
.. should be ..
`query          = { limit: 100, prevId: next_batch_ref }`

The only reason this bug does not surface is because the hardcoded `limit: 100` matches the hardcoded `break if processed >= 100` in the coins daemon.
If you set the query to `limit: 1` you'll see it fetch the same transaction 100 times.

**Comment by sramsden** [comment]
I should clarify that the `prevId` is as documented here..
https://www.bitgo.com/api/v2/#list-wallet-transactions
.. and also specify that I was using the testnet bitgo api ..
https://test.bitgo.com/api/v2

**Comment by sramsden** [comment]
Also, is there any reason ..
`peatio/spec/lib/coin_api/bit_go.rb`
.. is not ..
`peatio/spec/lib/coin_api/bit_go_spec.rb`
.. ie, `_spec.rb`

**Comment by ysv** [comment]
@sramsden Thanks!
