### ISSUE TITLE
Why BitGo wallet info is needed?

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1366]
Hi.
I have installed Peatio platform on my EC2 instance, and I am going to test some exchange between coins (e.g. BTC and XMR).

When I add new currencies on admin panel, I am seeing that there are several fields related to BitGo:
BitGo wallet ID,
BitGo wallet address,
BitGo wallet passphrase,
BitGo REST API root URL,
BitGo REST API access token

What I am not sure is why these BitGo info is needed.
BitGo info should be needed for exchanging here?  Or these are optional fields?

For example, what should I do in order to implement exchanging between BTC and XMR on Peatio?
I appreciate you if you let me know detailed steps about it.

Thank you.

**Comment by yivo** [comment]
Hi

You have to read BitGo docs if you want to use it. If you don't want BitGo skip these fields. Better hire some expert in Telegram channel who can help you with this.

**Comment by yivo** [comment]
If you will pass BitGo registration you will understand.

**Comment by mafingumu** [comment]
This is not closed...you didn't answer
