### ISSUE TITLE
High Severity Security Issue: DLL Loading Issue

### ISSUE THREAD

**Issue by Sambusik** [openware/peatio#1371]
DLL Loading Issue (https://snyk.io/vuln/SNYK-RUBY-FFI-22037)
Vulnerable module: ffi
Introduced through: sass-rails@5.0.7, selenium-webdriver@3.11.0 and others
Detailed paths and remediation
Introduced through: project@* › sass-rails@5.0.7 › sass@3.5.3 › sass-listen@4.0.0 › rb-inotify@0.9.10 › ffi@1.9.23
Remediation: Your dependencies are out of date, otherwise you would be using a newer ffi than ffi@1.9.23. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.
Introduced through: project@* › selenium-webdriver@3.11.0 › childprocess@0.9.0 › ffi@1.9.23
Remediation: Your dependencies are out of date, otherwise you would be using a newer ffi than ffi@1.9.23. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.
Introduced through: project@* › font-awesome-sass@4.7.0 › sass@3.5.3 › sass-listen@4.0.0 › rb-inotify@0.9.10 › ffi@1.9.23
Remediation: Your dependencies are out of date, otherwise you would be using a newer ffi than ffi@1.9.23. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.
Introduced through: project@* › bourbon@4.3.4 › sass@3.5.3 › sass-listen@4.0.0 › rb-inotify@0.9.10 › ffi@1.9.23
Remediation: Your dependencies are out of date, otherwise you would be using a newer ffi than ffi@1.9.23. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.
Introduced through: project@* › bootstrap@4.0.0 › sass@3.5.3 › sass-listen@4.0.0 › rb-inotify@0.9.10 › ffi@1.9.23
Remediation: Your dependencies are out of date, otherwise you would be using a newer ffi than ffi@1.9.23. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.

**Comment by mod** [comment]
@yivo can you upgrade ffi to version 1.9.24 or higher ?
It seems to be selenium-webdriver

**Comment by yivo** [comment]
Fixed in #1393.
