### ISSUE TITLE
ActiveRecord::NoDatabaseError: Unknown database 'peatio_production

### ISSUE THREAD

**Issue by ghost** [openware/peatio#1372]
Hi,

Peatio did a new installation but can not connect to MySQL.

![image](https://user-images.githubusercontent.com/14098096/42097162-176356a4-7bc0-11e8-9c27-ccc368091811.png)

**Comment by vitorgamer58** [comment]
You are trying to install this fork or Peatio original?

**Comment by ghost** [comment]
This fork,

**Comment by vitorgamer58** [comment]
https://github.com/rubykube/peatio/blob/master/config/database.yml#L8

I think your problem may be around here, in the original peatio is set here the user "root" and the respective password, but it seems that in this fork the username, password and database are defined elsewhere, take a look at Peatio Original ;

https://github.com/peatio/peatio/blob/master/config/database.yml.example#L6

**Comment by ghost** [comment]
Ok very thank problem solved.
