### ISSUE TITLE
ECR20 and Peatio Original

### ISSUE THREAD

**Issue by vitorgamer58** [openware/peatio#1373]
Hello, I have seen the commit that adds support for ECR20 tokens https://github.com/rubykube/peatio/commit/aebf82f2c8923ada8444ce81588e3d56b46148b6, but how could this commit be used to add ECR20 token support for Peatio Original?

**Comment by yivo** [comment]
I would suggest to try `git cherry-pick aebf82f2c8923ada8444ce81588e3d56b46148b6`.
