### ISSUE TITLE
Solvency Liability Proof likely to cause Out of Memory Issues

### ISSUE THREAD

**Issue by sramsden** [openware/peatio#1381]
The rake task does ..
```    
Currency.find_each do |ccy|
      logger.info { "*** Starting #{ccy.code.upcase} liability proof generation ***" }
      accounts = Account.with_currency(ccy).includes(:member)
```
.. which is loading the entire membership with accounts into memory.
NOTE that this may be moot if https://github.com/rubykube/peatio/issues/1112 is actioned but until then it's a potential issue.

**Comment by mod** [comment]
I am considering remove proof of solvency feature
I find this a bit pointless and I am not sure it's relevant to disclose your private cold wallet address.
but by providing all your deposits address can simply verify your solvency, say for example in your support desk.

**Comment by yivo** [comment]
This feature has been removed in 1.9.
