### ISSUE TITLE
Additional market features

### ISSUE THREAD

**Issue by BitenCoin** [openware/peatio#1383]
Is it possible to add market features like graviex have ?
Market sorting,search and stars since its very useful

https://github.com/go-apollyon/exchange

**Comment by go-apollyon** [comment]
:) hello. this is my repo :)

**Comment by BitenCoin** [comment]
@go-apollyon hello,
I know, you did a great job with it :)
I tried to add those features but rubykube peatio version is changed alot and your code is not working on it.I managed to do almost full UI redesign but market ui and engine on this version is hard to work with.

**Comment by mod** [comment]
We can provide those feature on the API
but most users of our fork have their own UI

**Comment by BitenCoin** [comment]
@mod 
There should be at least market search option in your fork, it is very helpful when there are more coins added and it's only small code change.

**Comment by yivo** [comment]
@BitenCoin You can download all markets to front and implement search in UI. See https://github.com/rubykube/peatio/blob/master/docs/api/member_api_v2.md#v2markets
