### ISSUE TITLE
who know google oauth2 set

### ISSUE THREAD

**Issue by goodstardust** [openware/peatio#1385]
GOOGLE_CLIENT_ID: <Google id>
  GOOGLE_CLIENT_SECRET: <Google secret>
  GOOGLE_OAUTH2_REDIRECT_URL: http://ec2-xx-xx-xx-xx.compute-1.amazonaws.com:3000/auth/google_oauth2/callback

i can't  post
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=1044454023387-emhp5vmfnp5cf1n9juk09g8gcckrova7.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Fexchange.stardustcoin.org%3A3000%2Fauth%2Fgoogle_oauth2%2Fcallback&response_type=code&scope=email+profile&state=feebda67c3a7c30a8bef0ab551b1ebd6ebee705bcab2c669

**Comment by KunwarCG** [comment]
There are 2 GOOGLE_CLIENT_ID setting in the same file. You might have changed it in one location (production) and may have missed it for development or viceversa.
