### ISSUE TITLE
Wrong customer ID or password,please try again.

### ISSUE THREAD

**Issue by A4Logic** [openware/peatio#1388]
Hello,

When i am trying sign in with google showing me this error 
Wrong customer ID or password,please try again. i installed this on my ubuntu server please help asap

**Comment by yivo** [comment]
This usually happens because of CSRF issues. Be sure you are on fresh browser with cookies enabled and try multiple times.

**Comment by A4Logic** [comment]
I am doing fresh browser but still error

**Comment by ghost** [comment]
I  having this kind of problem

**Comment by andyduong1920** [comment]
Same with me
