### ISSUE TITLE
Which coins does Peatio support currently?

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1394]
Now I am seeing that there are some coins in config/template/currencies.yml file.
So it means that Peatio currently supports only USD, BTC, ETH, XRP, LTC, BCH, DASH, TRST coins?
Or can I add other alt coins like USDT and XMR in Peatio?

**Comment by endofthepain** [comment]
you can, but you need write your own coinAPI its self

**Comment by Coding-Jewelry** [comment]
Can you please explain about it in detail?

And another question is: When I add new currencies on admin panel, I am seeing that there are several fields related to BitGo:
BitGo wallet ID,
BitGo wallet address,
BitGo wallet passphrase,
BitGo REST API root URL,
BitGo REST API access token

What I am not sure is why these BitGo info is needed.
BitGo info should be needed for exchanging here? Or these are optional fields?

Thank you.

**Comment by yivo** [comment]
Supported list: BTC, ETH, XRP, LTC, BCH, DASH, any ERC20 token, any fiat currency, any BitGo currency.

@Coding-Jewelry Please read BitGo docs.

**Comment by Coding-Jewelry** [comment]
@yivo  so you mean that Peatio doesn't support Monero coin?
Thank you for letting me know.

**Comment by yivo** [comment]
@Coding-Jewelry Yes, XMR is not supported.

**Comment by Coding-Jewelry** [comment]
Okay, thank you.

**Comment by Coding-Jewelry** [comment]
@yivo 
maybe can I customize the server code in order to exchange XMR?
