### ISSUE TITLE
Configuration for Barong

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1414]
I can make Peatio working by Auth0 or Google authentication, but I can't with Barong so far.
So, when you installed Peatio, how did you set nginx configuration for Barong?  
There is an example in Peatio installing guide for Peatio and Trading UI.  But not for Barong.
In my case, I have installed Peatio, Trading UI, Barong in an instance.  
So can you please give me a hint how to run Barong server and how to set Nginx configuration for Barong?
Another one is: Does Barong work without DNS?
Thank you.

**Comment by mod** [comment]
I think workbench would be the best example in installing both
We don't have a better example at the moment.

**Comment by ysv** [comment]
@Coding-Jewelry please reopen issue if you still have question.
