### ISSUE TITLE
rails error

### ISSUE THREAD

**Issue by Elektryon-Dev** [openware/peatio#1415]
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
  actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.10) lib/rails/rack/logger.rb:22:in `call'
  request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.10) lib/rack/runtime.rb:18:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
  scout_apm (2.4.11) lib/scout_apm/instruments/middleware_summary.rb:58:in `call'
  railties (4.2.10) lib/rails/engine.rb:518:in `call'
  railties (4.2.10) lib/rails/application.rb:165:in `call'
  rack (1.6.10) lib/rack/content_length.rb:15:in `call'
  puma (3.11.4) lib/puma/configuration.rb:225:in `call'
  puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
  puma (3.11.4) lib/puma/server.rb:446:in `process_client'
  puma (3.11.4) lib/puma/server.rb:306:in `block in run'
  puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

also the page has no css

**Comment by mod** [comment]
be sure to install yarn
run yarn install verify how we build in the Dockerfile
