### ISSUE TITLE
I am not able to withdraw ETH or ERC20 tokens

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1416]
Dear.
Currently I am not able to withdraw ETH because it is not in my deposit address.  It looks like Peatio only allows withdrawals for BIP currencies or HD wallets.   So if the ETH or ERC20 token is not in my deposit address, I can't withdraw it (e.g. in case of the ETH that was bought by BTC).
I had installed Peatio a few months ago, so this problem is already fixed for now?  Or this is still a problem?
Please let me know how I can handle this issue.
Thank you.

**Comment by amarian12** [comment]
check this approach i did for eth, it's the solution you need:

https://github.com/InfraexDev/peatio/commit/3cd79c5e2979f8995842c73046d68c24c029bc34

**Comment by jdowning100** [comment]
@amarian12 Not a bad approach. You will need to modify the withdraws to only withdraw from the aggregate address. And you'll need to do the same for ERC20

**Comment by ysv** [comment]
@Coding-Jewelry Hello!
Thanks for you question.
We are working on it now.
Progress in https://github.com/rubykube/peatio/pull/1404
