### ISSUE TITLE
Pusher --> Slanger (Question)

### ISSUE THREAD

**Issue by vitorgamer58** [openware/peatio#1423]
How to configure the Slanger correctly? how to replace the Pusher with it? I'm trying to do it in the original Peatio (InfraexDev fork)

Refer to https://github.com/Brexchange/Brexchange/issues/15, https://github.com/rubykube/peatio/issues/830 and to https://github.com/rubykube/peatio/issues/464

**Comment by vitorgamer58** [comment]
This commit https://github.com/rubykube/peatio/commit/22bad80ac27c1f69523ab96c9dd87e9746cfaf85#diff-81b753b02c902d26e3b837d7814c5244 does not specify what needs to be done for Slanger to work with 100% Pusher, using Slanger Peatio did not generate a deposit address, and he continued to keep connections open with Pusher but stopped sending messages.

using Slanger should I use encrypted connection? should I use ip 127.0.0.1 or my external IP?

I already managed to run Slanger, but Peatio does not seem to have worked very well with him.

```
  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8081
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # pusher settings
  # --------------------------------------------------------------
  PUSHER_APP: ******
  PUSHER_KEY: *****
  PUSHER_SECRET: ******
  PUSHER_HOST: 127.0.0.1
  PUSHER_PORT: 4567
  PUSHER_WS_PORT: 8080
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true

```

  WEBSOCKET_PORT: 8081   it was necessary to modify this data of the Original Peatio, because this port is also used by the Slanger.

**Comment by ysv** [comment]
@vitorgamer58 Please use [workbench](https://github.com/rubykube/workbench) for local development and testing of rubykube fork.
Also here you can find examples of Slanger configuration.
If you still have some questions you can post it here.
