### ISSUE TITLE
Coins with different conf names - withdrawal fails

### ISSUE THREAD

**Issue by BitenCoin** [openware/peatio#1425]
I have added over 10 coins on peatio and having some problems with withdrawing some of them.

All coins which have different .conf names than coin code name are failing to withdraw.
For example config name .madbyte (madbyted) and coin code mbyt - deposit works but withdrawals not
For example config name .KONA (KONAd) and coin code kona - deposit works but withdrawals not

What is the best way to fix this?

**Comment by ysv** [comment]
@BitenCoin https://github.com/rubykube/peatio/issues/1394#issuecomment-402680139

**Comment by BitenCoin** [comment]
@ysv 
I know, those are all dash based coins and some work but some don't due to problem above.Those that don't work have different -cli name but there is no option to change it in coin api
