### ISSUE TITLE
POST /management_api/v1/timestamp

### ISSUE THREAD

**Issue by ElviraMiro** [openware/peatio#1426]
When send post request to - http://api.wb.local/management_api/v1/timestamp
400 status received + error messsage:
{"error": "Only JSON body is accepted."} 

Can add to documentation notify about need to add header {'Content-Type': 'application/json'}?

When send get request without JWT - get shows  '"error": "Only POST, PUT, and DELETE verbs are allowed."' - may be we need receive authentication error?

**Comment by ysv** [comment]
We can add documentation that we need header
But this behavior looks correct for me

**Comment by ysv** [comment]
@rxx What do you think ?

**Comment by tamadamas** [comment]
We can add documentation. Some behaviors of this api is strange. It's better to fix it to let every developer understand what they should do
