### ISSUE TITLE
I guess the coin daemon should ignore disabled currencies.

### ISSUE THREAD

**Issue by shingonoide** [openware/peatio#1428]
I guess the coin daemon should not verify for disabled currency.
Can I create a pull request to fetch only for enabled currencies?

https://github.com/rubykube/peatio/blob/dc52324d4be87ab725056d922d5058b4ed60eda4/lib/daemons/coins.rb#L10

**Comment by ysv** [comment]
@shingonoide thanks for opening issue, your question makes sense. 
But we can't ignore disabled currencies because we can lose some deposits .
We will solve this issue in https://github.com/rubykube/peatio/pull/1404
