### ISSUE TITLE
Sign out from Peatio does not work.

### ISSUE THREAD

**Issue by umaimehm** [openware/peatio#1445]
User cannot sign out from peatio UI, they have to go to barong UI to sign out.

Under user profile, on clicking "Exit", user does not sign out. The session is still maintained even though the message is shown "Sign in with Barong".
Clicking, "Sign in with barong", redirects the user to the profile page.

workbench: master
peatio: 1-8-stable
barong: 1-8-stable

**Comment by ysv** [comment]
@umaimehm Yes because you are still signed in Barong
For example you sign out from some service which uses Google OAuth you still signed in Google

Reopen this issue if you still have question
