### ISSUE TITLE
Can you set up a stop loss function module in Trading UI?（Stop-Profit）

### ISSUE THREAD

**Issue by molisehao** [openware/peatio#1466]
Can you set up a stop loss function module in Trading UI?

Just like the selling price of the list is 5USD, the function module is set to sell automatically when the price is higher than 7usd, and automatically sell when the price is lower than 3usd.

Stop-Profit/Stop Profit, I think this function is very practical.

**Comment by ysv** [comment]
@molisehao All trading automatization will provided by [arbitrage platform](https://github.com/rubykube/arke)

**Comment by martianatwork** [comment]
@ysv I think this should be implemented by adding a new trade daemon and an option in trading UI for selecting order type. Ex. Limit Order, Market Order, Stop Loss Order. Which will make things easy. 

This should be a peartio core functionality.

**Comment by ysv** [comment]
@martianatwork Got it now. Thanks !
Need to discussion

**Comment by mnaichuk** [comment]
Stop Loss order will be implemented in OpenFinex soon.
