### ISSUE TITLE
auth google_oauth2 callback return http code 504

### ISSUE THREAD

**Issue by zouzehe** [openware/peatio#1467]
i use google oauth 2.0 ,
when i sign in ,  
http url : xxxxxxxxx/auth/google_oauth2/callback?state=7a42ad1dd036025c4b0f8c7b1783fa9a83a00dd2c84d767b&code=4/AADIYqyXPz9f5tZRZ-CmqKxAeUo7Vi-oj7uyT8kH1H15uGUBoxyY5jLcOMpyGuhU6uYaP8N9vsiqcUG_7s_MDNo#
return  nginx 504 Gateway Time-out

**Comment by ysv** [comment]
@zouzehe do you still have this issue ?
