### ISSUE TITLE
Issue with Proxy using Traefik

### ISSUE THREAD

**Issue by asheeshmathur** [openware/peatio#1472]
Proxy module is using traefik's image. However this image has issues it's unable to come up, keeps iterating.
This requires setting up additional parameter, useAPIV3 = true.

This needs to be corrected.
After setting it up, its listens.

**Comment by ianeinser** [comment]
@asheeshmathur where can we set the parameter?

**Comment by asheeshmathur** [comment]
Hi,
1. Location of file is : workbench/compose/proxy.yaml
Changes are as follows, add following

    environment:
       "useAPIV3" : “true"

Please find attached working file for your reference.


2. Apart from this there’s another change required. 
    workbench/app/peatio/Dockerfile

   Add following :
   RUN echo '{ "allow_root": true }' > /root/.bowerrc
   After ENV entry, also attached is the illustrative file.


Regards
Asheesh

**Comment by ysv** [comment]
@shal Can you help please

**Comment by shal** [comment]
@asheeshmathur  Now proxy works fine for me.
I don't see the point in information above, as we don't even have `bower` in peatio.
