### ISSUE TITLE
Enabling/Disabling deposits per currency

### ISSUE THREAD

**Issue by TheHolyRoger** [openware/peatio#1481]
Can I request this as a feature please?

Can I also request blocking self/wash trading?

Who can I talk to about paying for things to be expedited?

**Comment by ysv** [comment]
1. What do you mean by disabling deposits ? Now you can set blockchain status to disabled and this will stop synchronization. But if user saved deposit address somewhere he can deposit funds. Of course this deposit will not appear unless blockchain active.

2. Not yet

3. Please contact https://peatio.tech/
