### ISSUE TITLE
Paid Installation tutorial

### ISSUE THREAD

**Issue by lucidddreams** [openware/peatio#1487]
I'm willing to pay for someone who can teach me how to install this project for school purposes.

telegram @hesoyam88

**Comment by mishul** [comment]
@regedittap 
We deploy industry level Peatio. Have an entire team working with it - can add any infrastructure modifications, wallet integrations and scalable solutions. If you just need an MVP, we charge $2,500 and we will provide you with working code (bugs in uploaded code/configs) and show you the setup.

Please reach out on skype/email: mgupta14@illinois.edu

Looking forward to hear from you!

**Comment by ysv** [comment]
@regedittap Hello
We have a great installation tutorial https://www.youtube.com/watch?v=JWTtwKpkkYI&feature=youtu.be
But if you still need paid installation plase contact https://peatio.tech/#/
