### ISSUE TITLE
BUG: BTC Address Generation Error in Workbench

### ISSUE THREAD

**Issue by ianeinser** [openware/peatio#1488]
Hi. I manage to get the bitcoind running in a container and the container is active but I got this error

Currency Load (0.7ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 'btc' LIMIT 1
  Member Load (0.6ms)  SELECT  `members`.* FROM `members` WHERE `members`.`id` = 1 LIMIT 1
   (0.7ms)  SELECT  `authentications`.`uid` FROM `authentications` WHERE `authentications`.`provider` = 'barong' AND `authentications`.`member_id` = 1 LIMIT 1
   (0.3ms)  ROLLBACK
#<Faraday::ConnectionFailed wrapped=#<Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:18332 (Connection refused - connect(2) for "127.0.0.1" port 18332)>>

I managed to registers all coins in master mode but when I try to do the same things in workbench. It fails. I use the same currencies.yml as that in master mode. I am very sure this is docker or traefik issue but i cant find it bug. Any hint guys?

**Comment by ianeinser** [comment]
would you guys help me ? @ysv @yivo .. Thanks

**Comment by TheHolyRoger** [comment]
your bitcoin daemon is refusing peatio connections to the RPC API

**Comment by ianeinser** [comment]
Thanks @TheHolyRoger . I solved that
