### ISSUE TITLE
Any reason why MySql 5.7 prerequesite is such a hard requirement?

### ISSUE THREAD

**Issue by skatkov** [openware/peatio#1494]
List of requirements in README suggest that only MySql 5.7 is acceptable for this project.
https://github.com/rubykube/peatio#requirements

Currently, MySql is at 8.0 version and while configuring it locally I've ran into some issues. (I did manage to find workarounds, so it works...locally)

Is there any code in this project that makes this such a hard requirement? Will anything go wrong if I'll use greater version of mysql on production?

**Comment by skatkov** [comment]
So, I had time to explore code, tried deploying it... I will share some findings in case someone else wonders...

It seems that project target production depoyment platform is Google Cloud Platform. Rubykube guys seem to be planning to work on AWS integration after 3 months. 

Having 5.7 as a hard requirement makes total sense for AWS. AWS RDS supports 5.7 version. I only can wonder why version parity is so far away from current MySql 8.0... But it seems to be a common case.

I didn't found any signs of anyone doing RAW SQL in a project, so theoretically it should not be that hard to switch to PG gem. It's hard to imagine anyone doing MySql without having to tweak something, while PG offers very reasonable defaults. 

Rails developers are much more used to PG. Default database in rails is sqlite, but defacto-default is pg :-P 

Any chance anyone from the team considered replacing some dependencies?

**Comment by ysv** [comment]
@skatkov We did't try to use another MySql version
Please update us regarding this

**Comment by skatkov** [comment]
@ysv will do!

I've been considering switching to PostgreSql, mostly for performance benefits. But while building workbench locally I noticed that mariadb was pulled. 
<img width="495" alt="screen shot 2018-08-13 at 18 23 40" src="https://user-images.githubusercontent.com/544377/44029013-1099af1a-9f26-11e8-9d26-2ddbf6642e7d.png">

MariaDB seems like more feasible alternative to Mysql that old. [According to wikipedia](https://en.wikipedia.org/wiki/MariaDB) (see Versions section), they offers compatibility to MySql 5.* versions.

Do you (or anyone else) have any experience running MariaDB on production?

**Comment by oskanddr** [comment]
Such important thing as exchange should be designed exactly for single database. 

@skatkov This repo is not a cool oneclick wordpress site as you like and can setup with any DB. I think you are a well kid when delivering unproper information about MySQL. So, remember: 1) MySQL 5.7 is still the most important version; 2) PG is not faster (you havent ever put any comments why it should be faster LOL); 3) such projects as exchanges which require a high value of RPM MUST and WILL depend on database-specific features.

**Comment by skatkov** [comment]
@oskanddr  you wrote a lot of stuff, but I have problems dissecting any valuable information.

do you have benchmarks of any kinds? numbers from production? links to database-specific code? Any explanation why workbench uses mariadb?

**Comment by ysv** [comment]
@skatkov Nope 
We use only MySQL 5.7 on production

Mariadb should be fully compatible

**Comment by ysv** [comment]
@skatkov Hello
Do you have any conclusion about databases requirements ?
