### ISSUE TITLE
Support bech32 addresses

### ISSUE THREAD

**Issue by TheHolyRoger** [openware/peatio#1498]
The Bech32 address limit is 90 characters, peatio needs some changes to support this.

RAW SQL:
ALTER TABLE deposits MODIFY address VARCHAR(90);
ALTER TABLE payment_addresses MODIFY address VARCHAR(90);
ALTER TABLE withdraws MODIFY rid VARCHAR(90);

Affected files:
db/schema.rb Lines 77, 168, 233
app/models/deposit.rb Lines 79
app/models/payment_address.rb Lines 41
app/models/withdraw.rb Lines 151
app/models/deposits/coin.rb Lines 44
app/models/deposits/fiat.rb Lines 24
app/models/withdraws/coin.rb Lines 70
app/models/withdraws/fiat.rb Lines 26

Will also need a migrate file

**Comment by ysv** [comment]
@TheHolyRoger Thanks 
Agree I will left bech32 specification [here](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#specification)

**Comment by dinesh-skyach** [comment]
@ysv I have checked regarding some popular coins address formats and i found `Monero` is only exception here with 95 characters length except that i didn't found any address exceeding 90 characters.

You can generate Monero address [here](https://moneroaddress.org/)

**Comment by ysv** [comment]
closed in #1701
