### ISSUE TITLE
Member api v2 trades side is null

### ISSUE THREAD

**Issue by almantasr** [openware/peatio#1508]
api/v2/trades?market=eurusd&limit=50 returns all data but side property is null for all trades. Same is for my last trades

**Comment by oskanddr** [comment]
Maybe it is time to read docs again man?

**Comment by ysv** [comment]
@almantasr /trades is public API so it doesn't know who are you and can't determine side

**Comment by almantasr** [comment]
@ysv  You don't need authorization to know if the transaction was buy or sell for public transactions.

**Comment by ysv** [comment]
@almantasr it's for orders
But trades can't be sell or buy

**Comment by almantasr** [comment]
@ysv so having such property doesn't make any sense. Maybe it should be trend. By the way on peatio trading ui, you set the color green/yelow based on trend, maybe it should be the same on the api

**Comment by ysv** [comment]
@almantasr no trend in another 
Side is always null on both "/trades" and "/trades/my"
But we expose side on Order entity
https://github.com/rubykube/peatio/blob/master/app/api/api_v2/entities/order.rb#L31

**Comment by thomasdavis** [comment]
@ysv How does one get a trade history for a market to make a trade history UI widget? 


![download 9](https://user-images.githubusercontent.com/416209/47330343-a03b2e80-d6c3-11e8-80c8-0ccd9396409a.png)

They color code their market history based on the side
