### ISSUE TITLE
Remove outdated documentation

### ISSUE THREAD

**Issue by rraallvv** [openware/peatio#1523]
In the section **Setup bitcoind rpc endpoint** in [the documentation.](https://github.com/rubykube/peatio/blob/master/docs/setup-osx.md#setup-bitcoind-rpc-endpoint) the step to change the file `config/currencies.yml` might be outdated, the file is not located at that path, it's actually located at `config/seed/currencies.yml`, which makes me think that the file could be a sample file that needs to ve copied somewhere else, maybe to `config/`, but then in the file there is no placeholders for the values `username` or `password ` so I don't know where to put that information.

**Comment by ysv** [comment]
@rraallvv yeah this part of doc is outdated

**Comment by rraallvv** [comment]
@ysv I've found [this](tutorial), although it's not for patio or rubykube, but a different fork, so I'm not sure if it'll work.

**Comment by ysv** [comment]
@rraallvv your link seems to doesn't work

**Comment by rraallvv** [comment]
@ysv  Wow! I have no idea what happened to the link, and now I can't find it in my favorites.
I found this other link though:
https://steemit.com/rails/@bilal-haider/setting-up-rubykube?sort=author_reputation
It's for Linux, I hope it can be of some help, however I'm interested in macOS

**Comment by rraallvv** [comment]
I'm following the instructions in the previous post but got stuck at installing RabbitMQ, any idea what could be causing the installation to fail?

Currently I'm running 14.04.5 LTS, Trusty Tahr on codeanywhere.com
The reason is that don't have Linux box with me at the moment, but still wanted to try the whole installation process, before I actually get a VPS

```
$ sudo apt-get install rabbitmq-server
...
Setting up rabbitmq-server (3.7.7-1) ...
 * Starting message broker rabbitmq-server
 * FAILED - check /var/log/rabbitmq/startup_\{log, _err\}
                                                                                                                                    [fail]
invoke-rc.d: initscript rabbitmq-server, action "start" failed.
dpkg: error processing package rabbitmq-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 rabbitmq-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
deploy@box-codeanywhere:~$ sudo find / -name "rabbitmq-env.conf"
```

**Comment by ysv** [comment]
@rraallvv I advice you to follow this doc https://github.com/rubykube/peatio#minimalistic-local-development-environment-with-docker-compose

**Comment by rraallvv** [comment]
@ysv thanks.
