### ISSUE TITLE
Websocket not working

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#1524]
Overall Ajax-like functionality in the project is not working. 
Pages:
Trading UI, Deposit funds

Using workbench on mac os. Had the same issue in the past on Ubuntu 

Video:
https://youtu.be/NJsN06Y6qvY

**Comment by ysv** [comment]
@martianatwork Thanks for your issue
We will check
@odidukh can you check ?

**Comment by martianatwork** [comment]
@ysv Im using peatio 1.8 stable is this only 1.8 related issue? or are you having same issue on 1.9?

**Comment by ysv** [comment]
@martianatwork We did change nothing related to WS in 1.9 so probably could be the same issue
I could be some workbench issue

**Comment by shingonoide** [comment]
@ysv any help to solve page update without refresh?
