### ISSUE TITLE
Seeding protection needed for Wallets in v1.9

### ISSUE THREAD

**Issue by ianeinser** [openware/peatio#1535]
Hello,

i just discovered probably a bug. I got this error when I did make start/run. The error occurs when peatio tries to write the same wallet data in the db even though the same data is already in the db. Thus, instead of ignoring and move on like what Barong and currency do, peatio stops. The solution is to remove the wallets from the db manually so that one can run peatio again. BTW, this happens in workbench version. 

Model files unchanged.
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Name has already been taken
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/validations.rb:79:in `raise_record_invalid'

**Comment by ysv** [comment]
@ianeinser We have fixed this issue recently https://github.com/rubykube/peatio/blob/master/lib/tasks/seed.rake#L40

**Comment by ysv** [comment]
Closed in #1518
