### ISSUE TITLE
Blockchain falling handling

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#1549]
Today i have encountered unstable work of rinkeby eth blockchain that caused issues with accepting deposit with min required conformations amount.

I have made a deposit of ETH that was Submitted but never accepted (min conformation amount was 6)

![selection_602](https://user-images.githubusercontent.com/38254545/44262552-1a62b900-a224-11e8-974c-78eaf0b879f2.png)

Updating the Height of blocks to lower amount wont help (so it can recalculate). Therefore if the conformation amount is beyond the min requirement it will not be successful.

In case of deposit we can Confirm deposit manually, but no such option in the withdraw, and i think that adding it will be a bad idea. 

How can we handle such mass issue that is not depending from us but can lead to issues on platform in the most important aspect, financial.

**Comment by pkucherenk0** [comment]
It might happens due to block_number mismatch. It's like deposit came with block_number `123` and when fetched next time it's present in different block `124`.

**Comment by samsoft00** [comment]
Hi @pkucherenk0 
How do you set up your eth-testnet, i have install go-ethereum on ubuntu and run geth (eth-testnet), my questions are
1. How do I run geth as service/deamon
2. What are the things to configure, so Peatio can connect to the running geth
Your answer will be appreciated.
cc @ysv
