### ISSUE TITLE
Can't sign in with Google Auth

### ISSUE THREAD

**Issue by samsoft00** [openware/peatio#1553]
Good day, please I'm having an issue with Peatio installation, can't "sign in with Google", display the following message "Wrong customer ID or password, please try again.", using the latest version. see the link below http://qybit.com, please how can i resolve this? Thanks

**Comment by Regzaenal** [comment]
Put apikey from google auth and make sure everything is correct Or if u still struggling i can help u aswell chat me on whatsapp : +6285790752549

**Comment by ysv** [comment]
@samsoft00 I've signed successfully to qybit.com
I hope you have resolved this issue

**Comment by samsoft00** [comment]
Thanks @ysv and @Regzaenal 
Issue resolved, but I was faced with another issue, after authentication, it displays this => "Please, pass the corresponding verification steps to enable trading." under "fund" menu, please where can i get the verification steps.? Thanks

**Comment by ysv** [comment]
@samsoft00 Update 
```
  MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT:  '0'
  MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW: '0'
  MINIMUM_MEMBER_LEVEL_FOR_TRADING:  '0'
```
In application.yml
