### ISSUE TITLE
Error running peatio server as deamon

### ISSUE THREAD

**Issue by samsoft00** [openware/peatio#1558]
Hi, well-done guyz, 

I'm almost done with the installation but there's a little problem with the following sections, if I run peatio backend as a deamon, it generates the error below
1. Fund: No such file or directory @ rb_sysopen - app/views/private/funds/index.json.jbuilder
2. Trade: Faraday::Error in MarketsController#show, HTTP 500 Internal Server Error -- -- Request URL -- GET http://localhost:3000/markets/usdbtc.json

Secondly, how can generate wallet addresses for each currency and I can I load test demo for each.

Kindly login with to see errors.

http://qybit.com
Username: admin@qybit.com
Password: faMRoFH6CdxmfxEkLydzEKKYK8p/sWM2QzccuS1P

**Comment by gsilvestri** [comment]
I have the same error: solved by running peatio with the coomand `bundle exec rails server -p 3000 &`

**Comment by ysv** [comment]
@samsoft00 don't run peatio as a deamon
Why do you need this ?
Check updated version of wallets.yml.erb and blockchain.yml.erb you will find all of the answers in comments

**Comment by gsilvestri** [comment]
@ysv : the two files you indicated have no information about how to run Peatio as a daemon
https://github.com/rubykube/peatio/blob/master/config/templates/seed/blockchain.yml.erb
https://github.com/rubykube/peatio/blob/master/config/templates/seed/wallets.yml.erb

I understand that running Peatio with Docker is another alternative to use Peatio as a daemon

**Comment by ysv** [comment]
@gsilvestri  You can find answer for this question 
`Secondly, how can generate wallet addresses for each currency and I can I load test demo for each.`
https://github.com/rubykube/peatio/blob/master/config/templates/seed/blockchain.yml.erb
https://github.com/rubykube/peatio/blob/master/config/templates/seed/wallets.yml.erb

**Comment by ysv** [comment]
@gsilvestri @samsoft00 can we close the issue ?

**Comment by gsilvestri** [comment]
For me this issue can be closed: you need to ask @samsoft00
