### ISSUE TITLE
Peatio as trade engine

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#1569]
It is possible to use peatio as trade matching system only?

I would like to use peatio for matching trades only. other parts such as orders, user management, etc will be handled by another system built on different language.

**Comment by ysv** [comment]
@martianatwork You can but if you use matching system you will need to inherit Trade which depends on Order and Member, Order depends on Market, Market depends on Currency etc

I advice no to do it

**Comment by martianatwork** [comment]
@ysv I understand, do we have any documentation for adding new currency (waves token)?
 I have sent an email for the same on the official email address provided on your website. 

I'd like to finish this integration asap so let me know the best and fastest way to contact you guys
