### ISSUE TITLE
Remove webhooks controller and dependencies

### ISSUE THREAD

**Issue by ysv** [openware/peatio#1582]

**Comment by ysv** [comment]
@dinesh-skyach don't forget about env variable in application.yml

**Comment by andyduong1920** [comment]
Hi @ysv may I ask you a question, why do we remove it?

**Comment by ysv** [comment]
@anduonghien for API simplification we have never ever used this controller
If you need it you can add using peatio plugin system

**Comment by andyduong1920** [comment]
Thanks @ysv
