### ISSUE TITLE
Solutions for errors related to no minimum deposit and no gas price specified (v1.9)

### ISSUE THREAD

**Issue by jdowning100** [openware/peatio#1589]
Hi rubykube devs,
There are a couple of issues I experienced when building and running the new Peatio master (v1.9) from source. One is related to the lack of a minimum deposit threshold. 
The issue is in the collect_eth_deposit function [here](https://github.com/rubykube/peatio/blob/master/app/services/wallet_service/geth.rb#L54). Specifically, this line: 
`amount = deposit.amount_to_base_unit! - options[:gas_limit] * options[:gas_price]`

`amount` will be negative if the deposit is lower than the fees. Temporarily, the solution is to use an if statement, like so:

```
def collect_eth_deposit!(deposit, destination_address, options={})
      if(deposit.amount_to_base_unit! > options[:gas_limit] * options[:gas_price])
      	# Default values for Ethereum tx fees.
      	options = DEFAULT_ETH_FEE.merge options

      	# We can't collect all funds we need to subtract gas fees.
      	amount = deposit.amount_to_base_unit! - options[:gas_limit] * options[:gas_price]
      	pa = deposit.account.payment_address
      	client.create_eth_withdrawal!(
        	{ address: pa.address, secret: pa.secret },
        	{ address: destination_address },
        	amount,
        	options
      	)
	else
		# Do something like lower the gas price or throw error
    end
end
```

A second issue I encountered was with the create_erc20_withdrawal function [here](https://github.com/rubykube/peatio/blob/master/lib/wallet_client/geth.rb#L40) specifically with the [json_rpc part](https://github.com/rubykube/peatio/blob/master/lib/wallet_client/geth.rb#L40). There is no gas limit or gasPrice specified, so Geth will use a gas limit and gas price that it estimates is correct based on the ERC20 contract and the mempool usage, respectively. But this is bad for deposit collection, because only 0.001 ETH is sent to the deposit address as a fee by default ([here](https://github.com/rubykube/peatio/blob/master/app/services/wallet_service/geth.rb#L9)) so if Geth estimates that the fee should be bigger than 0.001 ETH, the deposit will never move to the hotwallet.
I recommend specifying a gasPrice and gas limit, like so:  
```
json_rpc(
          :eth_sendTransaction,
          [{
               from: normalize_address(issuer.fetch(:address)),
               to:   options[:contract_address],
		gas: "0x186A0",
		gasPrice: "0x2540BE400",
               data: data
           }]
```
This sets the gasPrice to 10 gwei and the gas limit to 100k which should be enough for almost any ERC transfer function (note that this is also exactly the amount speicified [here](https://github.com/rubykube/peatio/blob/master/app/services/wallet_service/geth.rb#L9)). But this is only a temporary solution, because if more than 100k gas is required the transfer will fail on the blockchain. I recommend using [web3.eth.estimateGas](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethestimategas) as a full solution. 

Finally, as the Ethereum network is constantly being overworked and does not scale well, the recommended gas limit fluctuates constantly. Generally 10 gwei is enough to get a transaction mined quickly but not always, so I recommend using the [ethgasstation API](https://ethgasstation.info/json/ethgasAPI.json) "fast" as the default fee and `{ gas_limit: 21_000, gas_price: 10_000_000_000 }` as a fallback if the ethgasstation API is down or returns nil. Note that the number returned for "fast" will have to be multiplied by 100_000_000 to convert it to Wei for the gasPrice. 

Thank you for all your work.

**Comment by ysv** [comment]
@jdowning100 Thanks a lot for your advices !
Using estimateGas that is what we were going to implement in the nearest future if we will not have luck with smart contract

About ethgasstation API we don't want to depend on other external services we suppose that hot/warm/cold wallets have enough funds for performing withdraw

**Comment by ysv** [comment]
closed in https://github.com/rubykube/peatio/commit/db9d354216781f75d3e8b0aeff15478ffdb3b60f
