### ISSUE TITLE
Accounts don't get cascade deleted after a Member is deleted

### ISSUE THREAD

**Issue by vshatravenko** [openware/peatio#1594]
Accounts and their PaymentAddresses don't get cascade deleted after their Member account is which can cause the `deposit_coin` daemon to malfunction.

**Comment by ysv** [comment]
@dinesh-skyach nope we need to talk about this
I'm not sure if we will implement this

**Comment by ysv** [comment]
@kaiten-mahajan Don't start to work on this

**Comment by ysv** [comment]
@vshatravenko We don't support Member deletion at all because this will cause accounting problem 
Same for Accounts & PaymentAddresses & Orders which should get cascade deleted as Member dependency
