### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by ghost** [openware/peatio#1596]
i am get this NoMethodError (undefined method `attributes' for nil:NilClass):
  app/controllers/application_controller.rb:50:in `set_gon' when running bundle exec rails server -p 3000

i have looked into this in peatio/app/controllers/application_controller.rb, i cant get what the problem is actually. 
 def set_gon
    gon.environment = Rails.env
    gon.local = I18n.locale
    gon.market = current_market.attributes
    gon.ticker = current_market.ticker
    gon.markets = Market.enabled.each_with_object({}) { |market, memo| memo[market.id] = market.as_json }
    gon.host = request.base_url
    gon.pusher = {
      key:       ENV.fetch('PUSHER_CLIENT_KEY'),
      wsHost:    ENV.fetch('PUSHER_CLIENT_WS_HOST'),
      httpHost:  ENV['PUSHER_CLIENT_HTTP_HOST'],
      wsPort:    ENV.fetch('PUSHER_CLIENT_WS_PORT'),
      wssPort:   ENV.fetch('PUSHER_CLIENT_WSS_PORT'),
    }.reject { |k, v| v.blank? }

also this two are not working 
bundle exec rake currencies:seed
bundle exec rake markets:seed

**Comment by ysv** [comment]
rake db:seed

**Comment by laugh26** [comment]
rake db:seed failed with this error
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Ask unit is not included in the list, Bid unit is not included in the list
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/validations.rb:43:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `block in save!'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/scout_apm-2.4.15/lib/scout_apm/instruments/active_record.rb:378:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/persistence.rb:51:in `create!'
/home/deploy/peatio/lib/tasks/seed.rake:31:in `block (4 levels) in <top (required)>'
/home/deploy/peatio/lib/tasks/seed.rake:29:in `each'
/home/deploy/peatio/lib/tasks/seed.rake:29:in `block (3 levels) in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/deploy/peatio/lib/tasks/seed.rake:28:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/db/seeds.rb:7:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => seed:markets

and i ran a trace and it shows 
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations
** Invoke seed:blockchains (first_time)
** Invoke environment 
** Execute seed:blockchains
** Invoke seed:currencies (first_time)
** Invoke environment 
** Execute seed:currencies
** Invoke seed:markets (first_time)
** Invoke environment 
** Execute seed:markets
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Ask unit is not included in the list, Bid unit is not included in the list
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/validations.rb:43:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `block in save!'
