### ISSUE TITLE
switching from \ruby to \Go language 

### ISSUE THREAD

**Issue by ndaxio** [openware/peatio#1615]
any plans to switch from ruby to Go language for trade engine. we can dedicate some resources to help with the transition if possible. also if you know of any Peatio go language github would be great to share. 

Thanks

**Comment by mod** [comment]
Hello,

Yes we already started writing a trading engine in Go; we are interested in collaboration.

**Comment by ysv** [comment]
@ndaxio Please closes issue if you don't have more questions
