### ISSUE TITLE
Restore walletnotify event in Peatio 1.9 for bitcoin-like blockchains

### ISSUE THREAD

**Issue by gsilvestri** [openware/peatio#1621]
The new blockchain daemon intruduced in Peatio 1.9 is adding to every deposit an delay of 15-30 minutes depending on the blockchain type.

For example in Bitcoin TestNET the deposit is appearing 15 minutes after the transaction is received from the LOCAL HOT wallet.

With the `walletnotify` event into the `bitcoin.conf` file configured the notification to the Peatio UI for an incoming transaction was immediate.

Can the `walletnotify` evend added again in Peatio 1.9??
Is there anybody working on adding again the `peatio.deposit.coin` message queue to be used with the `walletnotify` event??

```walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "currency":"btc"}'
```

**Comment by ysv** [comment]
@gsilvestri Thanks
I agree that we have this delay for bitcoin-like blockchains and it's terrible
We are going to make some research on this topic to keep it simple

**Comment by gsilvestri** [comment]
any update on this??

**Comment by jonn4y** [comment]
would also love an update on this, we notice all blockchains lag behind after so long
