### ISSUE TITLE
[Member API v2] endpoint to initialise withdraw

### ISSUE THREAD

**Issue by almantasr** [openware/peatio#1627]
It is not possible to initialize withdraw via member api. Building custom UI requires ability to initialize withdraw via API. #

**Comment by ysv** [comment]
@almantasr this API call was removed recently https://github.com/rubykube/peatio/pull/1284
Use management API for performing withdrawals. 
Also check please https://github.com/rubykube/peatio/issues/1629#issuecomment-418025460
