### ISSUE TITLE
2FA for withdrawal?

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#1629]
2FA is removed from peatio, how are we handling 2FA for withdrawals??

**Comment by ysv** [comment]
@martianatwork check applogic https://github.com/rubykube/applogic/blob/master/app/api/api_v1/withdraw.rb
We will update applogic README soon.

**Comment by martianatwork** [comment]
@ysv Hey thanks, but how do I connect Peatio & barong with Applogic?

**Comment by ysv** [comment]
@martianatwork I think we will prepare some demo in md
For now you can check how it works [here](https://github.com/ysv/applogic/tree/update-readme#multisignature-withdrawal-request-using-management-api)
