### ISSUE TITLE
Why removed email notification to user when they have deposit and withdrawal?

### ISSUE THREAD

**Issue by top1st** [openware/peatio#1640]

**Comment by martianatwork** [comment]
@top1st switching the email  and OTP logic to new service called applogic
https://github.com/rubykube/applogic

**Comment by ysv** [comment]
@top1st Instead of sending email we publish message to RabbitMQ and you can implement your custom handlers in applogic
https://github.com/ysv/applogic/blob/update-readme/doc/using_event_api.md
