### ISSUE TITLE
Plugin like structure for Currencies.

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#1642]
I love the new method for currency but the files are scattered in multiple folders we can create a new folder
"Coins" in the root folder, Inside it we can have sub-directories for each coin.

Each sub-directory will contain a coin.yml which will define blockchain service provider and stuff. It can also provide Currency name, etc.

This will be similar to the plugins.

**Comment by ysv** [comment]
@martianatwork You can develop plugin by yourself where you will implement custom rake tasks
