### ISSUE TITLE
Update Setup Doc

### ISSUE THREAD

**Issue by knkrth** [openware/peatio#1657]
Hi, Can you update the [setup-ubuntu.md](https://github.com/rubykube/peatio/blob/master/docs/setup-ubuntu.md)? Is there any easy setup guide?

**Comment by shal** [comment]
Hi @knkrth, better use workbench to try peatio.
Here is it https://github.com/rubykube/workbench
Good luck 👍

**Comment by knkrth** [comment]
Ok, Thanks. But still there is some update need to be done on setup readme.
