### ISSUE TITLE
Add New Coin Via Admin Panel

### ISSUE THREAD

**Issue by knkrth** [openware/peatio#1658]
Hi, Can you add a feature to add new coin via admin panel like blockchain ie. `rpcusername` ,`rpcpassword`,  `ip:port`

**Comment by endofthepain** [comment]
<img width="1773" alt="ss 2018-09-09 at 12 42 26" src="https://user-images.githubusercontent.com/11496089/45261486-daab7d80-b42d-11e8-8df1-5bb7d28b8bf0.png">

**Comment by knkrth** [comment]
Thank you.
