### ISSUE TITLE
The confirmation amount upon deposit and withdraw are late for one confirmation.

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#1673]
The txid will have 6 confirmation blocks while Peatio will only sees 5 of them.
This make our minimum conformation amount from actual 6 to 7 in blockchain.
In case of some blockchains it may take 30 min to wait for another confirmation.

**Comment by gsilvestri** [comment]
This can be related to issue #1621 for _Bitcoin-like_ coins.

**Comment by gsilvestri** [comment]
any update on this??
