### ISSUE TITLE
API for users?

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#1680]
Do we have any api endpoints which we can give to end users?

**Comment by ysv** [comment]
@martianatwork member_api_v2 can be accessible

**Comment by martianatwork** [comment]
@ysv yeah i fixed it

For anyone looking to integrate

For now I have added this lines in Member model

    #
    # Generates valid JWT for member, allows to pass additional payload.
    #
    def jwt_for(member, payload = { x: 'x', y: 'y', z: 'z' })
      jwt_build(payload.merge(email: member.email))
    end

    #
    # Generates valid JWT. Accepts payload as argument. Add fields required for JWT to be valid.
    #
    def jwt_build(payload)
      jwt_encode payload.reverse_merge \
      iat: Time.now.to_i,
      exp: 20.minutes.from_now.to_i,
      jti: SecureRandom.uuid,
      sub: 'session',
      iss: 'peatio',
      aud: ['peatio']
    end
    #
    # Generates JWT token based on payload. Doesn't add any extra fields to payload.
    #
    def jwt_encode(payload)
      OpenSSL::PKey.read(Base64.urlsafe_decode64(jwt_keypair_encoded[:private])).yield_self do |key|
        JWT.encode(payload, key, ENV.fetch('JWT_ALGORITHM'))
      end
    end

    def jwt_keypair_encoded
        { public:  ENV['JWT_PUBLIC_KEY'],
          private: ENV['JWT_PRIVATE_KEY'] }
    end
