### ISSUE TITLE
HELP!! to install Peatio exchange on my VPS

### ISSUE THREAD

**Issue by wepobid** [openware/peatio#1710]
someone may be install this repo on my vps .. I test 3 types of this and no way to install for me... thanks.. please .. you can send email to wepobid@gmail.com

**Comment by seletskiy** [comment]
@wepobid: Hello!

GitHub Issues is not appropriate place for such requests.

Please, consider asking specific questions on RubyKube community forums: https://discuss.rubykube.io/c/community-support

Also, check out telegram channel where you can get specific help regarding peatio: https://telegram.im/@Peatio
