### ISSUE TITLE
how to config the ranger?

### ISSUE THREAD

**Issue by zhangatle** [openware/peatio#1712]
when i open the peatio-trading-ui,there is an error ,how to solve it ,or should i config the peatio to support it ?

![image](https://user-images.githubusercontent.com/10345661/46240821-bf55e180-c3df-11e8-96d2-c7db8feda47a.png)

**Comment by ysv** [comment]
@zhangatle https://github.com/rubykube/workbench/blob/master/compose/backend.yaml#L56

**Comment by ysv** [comment]
@zhangatle do you still have a question ?

**Comment by zhangatle** [comment]
@ysv yes,the problem has been solved ,thanks

**Comment by ysv** [comment]
@zhangatle can you close issue please
