### ISSUE TITLE
XRP withdraw 

### ISSUE THREAD

**Issue by antechdemo** [openware/peatio#1713]
XRP withdraw is not working it's given error "Signing is not supported by this server"

**Comment by ysv** [comment]
@antechdemo probably problem with your xrp node

**Comment by antechdemo** [comment]
Hey @ysv 
I am using https://s.altnet.rippletest.net:51234 address to connect to the XRP Test Net.

**Comment by tamadamas** [comment]
It will not work. It requires personal node server only

**Comment by tamadamas** [comment]
You can try using bitgo

**Comment by antechdemo** [comment]
Ok.
Thanks @rxx

**Comment by antechdemo** [comment]
Hey ,Ripple address is not generate using "wallet_propose" methog, given error “Forbidden”,When we use personal node server..
