### ISSUE TITLE
Cant change to auth0 login

### ISSUE THREAD

**Issue by huuhait** [openware/peatio#1714]
![image](https://user-images.githubusercontent.com/40519768/46339174-529b4b00-c65c-11e8-92fc-bee9c978293a.png)
my conf:

> OAUTH2_SIGN_IN_PROVIDER: auth0
> 
>   GOOGLE_CLIENT_ID:
>   GOOGLE_CLIENT_SECRET:
>   GOOGLE_OAUTH2_REDIRECT_URL: ~
> 
>   AUTH0_OAUTH2_DOMAIN: ######.auth0.com
>   AUTH0_OAUTH2_CLIENT_ID: ############
>   AUTH0_OAUTH2_CLIENT_SECRET: #############################
>   AUTH0_OAUTH2_REDIRECT_URL:  ~ # Specify URL address to which user will be redirected after successful sign in.

**Comment by ysv** [comment]
I've tried locally everything works for me
double check your configurations in `rails console` using your specific environment
`ENV.fetch('OAUTH2_SIGN_IN_PROVIDER')`
