### ISSUE TITLE
XRP wallet_propose not working, given error “Forbidden”

### ISSUE THREAD

**Issue by antechdemo** [openware/peatio#1720]
Hey,
My Ripple address is not generate using "wallet_propose" method, given error “Forbidden”,When we use personal node server..

**Comment by gfedorenko** [comment]
Hello @antechdemo 
`wallet_propose` is an admin method. So please be sure to set this line in your config file https://github.com/ripple/rippled/blob/develop/cfg/rippled-example.cfg#L195

Your config should look smth like the following  snippet
```
[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = 51234
ip = 0.0.0.0
admin = 0.0.0.0
user=user
password=password
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

[node_size]
medium

[node_db]
type=RocksDB
path=/home/ripple/.ripple/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
/home/ripple/.ripple/db

[debug_logfile]
/home/ripple/.ripple/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235

[validators_file]
/etc/opt/ripple/validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1
```

But you should set all ips and credentials to your values

**Comment by antechdemo** [comment]
Hi @gfedorenko 
I did like that. But given Forbidden error.

[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = 5005
ip = 127.0.0.1
admin = 127.0.0.1
protocol = http

[port_peer]
port = 51235
ip = 127.0.0.1
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

[node_size]
medium

[node_db]
type=RocksDB
path=/home/ripple/.ripple/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
/home/ripple/.ripple/db

[debug_logfile]
/home/ripple/.ripple/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.altnet.rippletest.net 51235
 52.11.28.194 51235
 54.94.245.104 51235
 54.201.240.60 51235
 54.238.143.216 51235

[validators_file]
/etc/opt/ripple/validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[signing_support]
true

[ssl_verify]
1

**Comment by gfedorenko** [comment]
If you put `127.0.0.1` as admin configuration all admin methods will be available only from the node  directly. 
Put `0.0.0.0` there and try again.

**Comment by antechdemo** [comment]
Ok.
Thanx @gfedorenko ..
