### ISSUE TITLE
Install on digital ocean

### ISSUE THREAD

**Issue by albertusQuelle** [openware/peatio#1723]
Hi, 
even as its recommended to intall on Amazon, Google or Azure: https://github.com/rubykube/peatio/blob/master/docs/architecture.md
Has anybody successfull installed it on digital Ocean?
The three above mentioned services are compared to DO horrible and uncomfortable ;)

**Comment by ysv** [comment]
@lordvalium we don't have much experience with DO, but I think that there is no much difference in running workbench because you just need a VM
