### ISSUE TITLE
How to run MySQL commands and bitcoin-cli

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1727]
Dear Peatio team.

Now I am trying to setup and consider Rubykube Peatio exchange.
I have already installed Peatio running by using workbench.git.
What I want to do is to run MySQL queries and bitcoin-cli for considering Peatio's back-end, but unfortunately I am not sure how I can enter it.
I appreciate you if you let me know how to do this.

Thank you.

**Comment by ysv** [comment]
@Coding-Jewelry Hello as I understood you want to have this cli tool in peatio container, am I wrong ?
we have such [issue in workbench](https://github.com/rubykube/workbench/issues/185)
Temporary solution for now is 
1. Execute to peatio container as root user `docker exec -it -u 0 ... bash`
2. Install dependencies `apt install ...`
