### ISSUE TITLE
Order update event is not firing

### ISSUE THREAD

**Issue by advanceditsolutions** [openware/peatio#1729]
We are using `after_commit` on create method for publishing `trigger_pusher_event`
this will only publish orders with wait state, orders with done, cancel will not be triggered

**Comment by ysv** [comment]
@advanceditsolutions We have fixed this issue in 1-9 https://github.com/rubykube/peatio/blob/master/app/models/order.rb#L36

**Comment by martianatwork** [comment]
@ysv Yes but it does not trigger `trigger_pusher_event` which is required for changing the orders state on peatio-trading-ui

**Comment by advanceditsolutions** [comment]
Hey im talking about `trigger_pusher_event` which pushes events to pusher_member.

https://github.com/rubykube/peatio/blob/41bc0a3cdd7805440c583635b70fcb2d91dddc91/app/models/order.rb#L14

This triggers a event for new order 

https://github.com/rubykube/peatio-trading-ui/blob/67f2e9d0133df852568c1c6a1b4193254ca4b615/app/assets/javascripts/component_ui/my_orders.js.coffee#L28

This listens to order states and process the front-end work like removing or updating orders.

So we are not triggering order wait or cancel pusher/ranger events from peatio itself

**Comment by ysv** [comment]
@advanceditsolutions yes because this event is duplication of EventAPI call and we deprecate pusher so this call will be removed soon 

Here is right eventing which you should use

https://github.com/rubykube/peatio/blob/444bf2b1fb8dc51b77abdd3f6a290c88acf0e27a/app/models/order.rb#L30-L46

**Comment by ysv** [comment]
Some duplicated events should be removed as implemented [here](https://github.com/rubykube/peatio/pull/1379/files)
