### ISSUE TITLE
Bitcoin not generating address

### ISSUE THREAD

**Issue by poseidon-j** [openware/peatio#1730]
I cant able to generate bitcoin address in test net and mainnet in 1.9 rc 11

**Comment by ysv** [comment]
@bjay27 did you setup bitcoin node ?
Try to generate new address using bitcoin-cli

**Comment by bjay27** [comment]
Please check this here https://ibb.co/hb4GOp

**Comment by ysv** [comment]
@bjay27 This screenshot is not informative for me
Check your configurations 
This issue is similar to https://github.com/rubykube/peatio/issues/1731

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
