### ISSUE TITLE
Bitcoin deposit list is empty.  How to fix it?

### ISSUE THREAD

**Issue by Coding-Jewelry** [openware/peatio#1731]
Dear @ysv , hope you are doing well today.

Now I am trying to install and test Rubykube Peatio exchange.  I've already installed Peatio by using workbench.git and tested BTC, ETH deposit functionalities.
The problem is:  Bitcoin was already deposited to one of addresses (created via my Peatio), and I can see the transactions on the BTC wallet.  But unfortunately it is not displaying in deposit history on admin panel as well as on My Profile page.  Actually the transactions are not saved in deposits table.
On the other hand, ETH depositing is correctly working and I can see the history.

So could you please let me know how the workflow for depositing is, and also how I can resolve it?
Thank you.

**Comment by ysv** [comment]
@Coding-Jewelry Thanks!

Can you check that 
1. Bitcoin node is running and set up correctly 
2. Check daemons logs
3. Try to access bitcoin node via `bitcoin-cli`
4. Check that blockchain height is updating and is almost the same as current blockchain height  
(-5-7 blocks)

**Comment by Coding-Jewelry** [comment]
Hi @ysv , thank you for replying.

So, 
1.  Bitcoin node is setup correctly and running exactly.
2.  How and where can I check daemons logs in workbench docker container?
3.  bitcoin-cli works great. 
4.  How can I check the blockchain height?  Probably are you meaning "getblockcount"?  If then, "bitcoin-cli getblockcount" gives me a result.

**Comment by ysv** [comment]
2. To check daemon logs run `docker logs -f YOUR-CONTAINER`
4. I mean height of blockchain in database you can check it in admin panel blockchain section

**Comment by Coding-Jewelry** [comment]
Hi @ysv , the current docker containers are as follows:
workbench_trading_ui_1
workbench_pusher_member_1
workbench_deposit_collection_1
workbench_withdraw_coin_1
workbench_market_ticker_1
workbench_trade_executor_1
workbench_deposit_collection_fees_1
workbench_global_state_1
workbench_pusher_market_1
workbench_k_1
workbench_matching_1
workbench_blockchain_1
workbench_withdraw_audit_1
workbench_order_processor_1
workbench_slave_book_1
workbench_deposit_coin_address_1
workbench_peatio_1
workbench_barong_1
workbench_geth_1
workbench_proxy_1
workbench_ranger_1
workbench_phpmyadmin_1
workbench_redis_1
workbench_mailcatcher_1
workbench_vault_1
workbench_coinhub_1
workbench_rabbitmq_1
workbench_db_1
workbench_bitcoind_1

Can you please let me know which container I need to review for daemon logs among them.
And the current Bitcoin blockchain height is 1414701 on admin panel.   Do you think this is a correct one?
Thank you.

**Comment by Coding-Jewelry** [comment]
Hi @ysv , If I run "sudo docker logs -f workbench_deposit_collection_1", the the output is only as follows:

Link /opt/peatio/config/management_api_v1.yml -> /home/app/config/management_api_v1.yml
Link /opt/peatio/config/seed/currencies.yml -> /home/app/config/seed/currencies.yml
Link /opt/peatio/config/seed/blockchains.yml -> /home/app/config/seed/blockchains.yml
Link /opt/peatio/config/seed/wallets.yml -> /home/app/config/seed/wallets.yml
Link /opt/peatio/config/seed/markets.yml -> /home/app/config/seed/markets.yml
Link /opt/peatio/config/plugins.yml -> /home/app/config/plugins.yml

When I run on the other containers like "workbench_deposit_collection_fees_1" or "workbench_deposit_coin_address_1", the same result is outputted.

**Comment by ysv** [comment]
you need logs of `workbench_blockchain_1 ` daemon
you can compare number of current block in database with block number of your transaction in blockchain explorer

**Comment by ysv** [comment]
@Coding-Jewelry Do you still have any issue ?
