### ISSUE TITLE
bundle exec rake currencies:seed not working

### ISSUE THREAD

**Issue by huuhait** [openware/peatio#1736]
Hello i need help!

I used rake db: seed and then executed the bundle exec rake currencies: seed
and it failed

> peatio@DESKTOP-APLICPP:~/peatio$ bundle exec rake currencies:seed
> rake aborted!
> Don't know how to build task 'currencies:seed' (see --tasks)
> /home/peatio/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
> /home/peatio/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
> (See full trace by running task with --trace)
> peatio@DESKTOP-APLICPP:~/peatio$ bundle exec rake markets:seed
> rake aborted!
> Don't know how to build task 'markets:seed' (see --tasks)
> /home/peatio/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
> /home/peatio/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
> (See full trace by running task with --trace)

**Comment by ysv** [comment]
@Thedabest Hello. Check words order
```bash
rake -T
...
rake seed:blockchains                   # Adds missing blockchains to database defined at config/seed/blo...
rake seed:currencies                    # Adds missing currencies to database defined at config/seed/curr...
rake seed:markets                       # Adds missing markets to database defined at config/seed/markets...
rake seed:wallets                       # Adds missing wallets to database defined at config/seed/wallets
...
```

**Comment by huuhait** [comment]
> @Thedabest Hello. Check words order
> 
> ```shell
> rake -T
> ...
> rake seed:blockchains                   # Adds missing blockchains to database defined at config/seed/blo...
> rake seed:currencies                    # Adds missing currencies to database defined at config/seed/curr...
> rake seed:markets                       # Adds missing markets to database defined at config/seed/markets...
> rake seed:wallets                       # Adds missing wallets to database defined at config/seed/wallets
> ...
> ```

not working :(

**Comment by huuhait** [comment]
i run 
rake seed:blockchains
rake seed:currencies
rake seed:markets
rake seed:wallets
working normal and run 
bundle exec rake currencies:seed
rake aborted! :|

**Comment by ysv** [comment]
@Thedabest Why do you need to run `rake currencies:seed` ? I don't understand

**Comment by huuhait** [comment]
I reinstall on Debian
i run `rake db:seed` error on `rake seed:markets`

> root@DESKTOP-APLICPP:~/peatio/config/seed# rake db:seed
> (in /root/peatio)
>   ActiveRecord::SchemaMigration Load (0.2ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
>    (0.2ms)  BEGIN
>   Blockchain Exists (0.2ms)  SELECT  1 AS one FROM `blockchains` WHERE `blockchains`.`key` = 'eth-rinkeby' LIMIT 1
>   Blockchain Exists (0.1ms)  SELECT  1 AS one FROM `blockchains` WHERE `blockchains`.`key` = 'eth-mainet' LIMIT 1
>   Blockchain Exists (0.1ms)  SELECT  1 AS one FROM `blockchains` WHERE `blockchains`.`key` = 'btc-testnet' LIMIT 1
>   Blockchain Exists (0.1ms)  SELECT  1 AS one FROM `blockchains` WHERE `blockchains`.`key` = 'bch-testnet' LIMIT 1
>   Blockchain Exists (0.1ms)  SELECT  1 AS one FROM `blockchains` WHERE `blockchains`.`key` = 'ltc-testnet' LIMIT 1
>   Blockchain Exists (0.1ms)  SELECT  1 AS one FROM `blockchains` WHERE `blockchains`.`key` = 'dash-testnet' LIMIT 1
>   Blockchain Exists (0.1ms)  SELECT  1 AS one FROM `blockchains` WHERE `blockchains`.`key` = 'xrp-testnet' LIMIT 1
>    (0.1ms)  COMMIT
>    (0.1ms)  BEGIN
>   Currency Exists (0.2ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1
>   Currency Exists (0.3ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 0 LIMIT 1
>   SQL (0.3ms)  INSERT INTO `currencies` (`options`, `id`, `symbol`, `type`, `precision`, `quick_withdraw_limit`, `created_at`, `updated_at`) VALUES ('{\"erc20_contract_address\":null}', 0, '$', 'fiat', 2, 1000.0, '2018-10-11 19:39:08', '2018-10-11 19:39:08')
>   Member Load (0.2ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
>   Currency Exists (0.2ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1
>   Currency Exists (0.2ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 0 LIMIT 1
>    (0.2ms)  SELECT `blockchains`.`key` FROM `blockchains`
>   SQL (0.3ms)  INSERT INTO `currencies` (`options`, `id`, `blockchain_key`, `symbol`, `base_factor`, `quick_withdraw_limit`, `created_at`, `updated_at`) VALUES ('{\"erc20_contract_address\":null}', 0, 'btc-testnet', '฿', 100000000, 0.1, '2018-10-11 19:39:08', '2018-10-11 19:39:08')
>   Member Load (0.2ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
>   Currency Exists (0.1ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1
>   Currency Exists (0.1ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 0 LIMIT 1
>    (0.1ms)  SELECT `blockchains`.`key` FROM `blockchains`
>   SQL (0.1ms)  INSERT INTO `currencies` (`options`, `id`, `blockchain_key`, `symbol`, `base_factor`, `quick_withdraw_limit`, `created_at`, `updated_at`) VALUES ('{\"erc20_contract_address\":null}', 0, 'xrp-testnet', 'ꭆ', 1000000, 1000.0, '2018-10-11 19:39:08', '2018-10-11 19:39:08')
>   Member Load (0.2ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
>   Currency Exists (0.2ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1
>   Currency Exists (0.1ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 0 LIMIT 1
>    (0.2ms)  SELECT `blockchains`.`key` FROM `blockchains`
>   SQL (0.1ms)  INSERT INTO `currencies` (`options`, `id`, `blockchain_key`, `symbol`, `base_factor`, `quick_withdraw_limit`, `created_at`, `updated_at`) VALUES ('{\"erc20_contract_address\":null}', 0, 'bch-testnet', '฿', 100000000, 1.0, '2018-10-11 19:39:08', '2018-10-11 19:39:08')
>   Member Load (0.1ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
>   Currency Exists (0.3ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1
>   Currency Exists (0.1ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 0 LIMIT 1
>    (0.1ms)  SELECT `blockchains`.`key` FROM `blockchains`
>   SQL (0.2ms)  INSERT INTO `currencies` (`options`, `id`, `blockchain_key`, `symbol`, `base_factor`, `quick_withdraw_limit`, `created_at`, `updated_at`) VALUES ('{\"erc20_contract_address\":null}', 0, 'ltc-testnet', 'Ł', 100000000, 5.0, '2018-10-11 19:39:08', '2018-10-11 19:39:08')
>   Member Load (0.2ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
>   Currency Exists (0.2ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1
>   Currency Exists (0.1ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 0 LIMIT 1
>    (0.1ms)  SELECT `blockchains`.`key` FROM `blockchains`
>   SQL (0.1ms)  INSERT INTO `currencies` (`options`, `id`, `blockchain_key`, `symbol`, `base_factor`, `quick_withdraw_limit`, `created_at`, `updated_at`) VALUES ('{\"erc20_contract_address\":null}', 0, 'dash-testnet', 'Đ', 100000000, 2.0, '2018-10-11 19:39:08', '2018-10-11 19:39:08')
>   Member Load (0.1ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
>   Currency Exists (0.2ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1
>   Currency Exists (0.1ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 0 LIMIT 1
>    (0.1ms)  SELECT `blockchains`.`key` FROM `blockchains`
>   SQL (0.1ms)  INSERT INTO `currencies` (`options`, `id`, `blockchain_key`, `symbol`, `base_factor`, `quick_withdraw_limit`, `created_at`, `updated_at`) VALUES ('{\"erc20_contract_address\":null}', 0, 'eth-rinkeby', 'Ξ', 1000000000000000000, 2.0, '2018-10-11 19:39:08', '2018-10-11 19:39:08')
>   Member Load (0.1ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
>   Currency Exists (0.1ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1
>   Currency Exists (0.2ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 0 LIMIT 1
>    (0.1ms)  SELECT `blockchains`.`key` FROM `blockchains`
>   SQL (0.2ms)  INSERT INTO `currencies` (`id`, `blockchain_key`, `symbol`, `base_factor`, `quick_withdraw_limit`, `options`, `created_at`, `updated_at`) VALUES (0, 'eth-rinkeby', 'Ξ', 1000000, 3000.0, '{\"erc20_contract_address\":\"0x0000000000000000000000000000000000000000\"}', '2018-10-11 19:39:08', '2018-10-11 19:39:08')
>   Member Load (0.2ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
>    (42.5ms)  COMMIT
>    (0.1ms)  BEGIN
>   Market Exists (0.2ms)  SELECT  1 AS one FROM `markets` WHERE `markets`.`id` = 0 LIMIT 1
>   Market Exists (0.3ms)  SELECT  1 AS one FROM `markets` WHERE `markets`.`id` = BINARY 0 LIMIT 1
>    (0.2ms)  SELECT `currencies`.`id` FROM `currencies`
>    (0.3ms)  SELECT `currencies`.`id` FROM `currencies`
>   Currency Load (0.2ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1 FOR UPDATE
>   Currency Load (0.1ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1 FOR UPDATE
>    (0.1ms)  ROLLBACK
> rake aborted!
> ActiveRecord::RecordInvalid: Validation failed: Ask unit is not included in the list, Bid unit is not included in the list
> /root/peatio/lib/tasks/seed.rake:31:in `block (4 levels) in <top (required)>'
> /root/peatio/lib/tasks/seed.rake:29:in `each'
> /root/peatio/lib/tasks/seed.rake:29:in `block (3 levels) in <top (required)>'
> /root/peatio/lib/tasks/seed.rake:28:in `block (2 levels) in <top (required)>'
> /root/peatio/db/seeds.rb:7:in `<top (required)>'
> Tasks: TOP => seed:markets
> (See full trace by running task with --trace)
> root@DESKTOP-APLICPP:~/peatio/config/seed#

**Comment by ysv** [comment]
@Thedabest please do everything very carefully
1. drop database
2. `./bin/init_config` and make sure that you have default seed files in config/seed/
3. run `rake db:seed`

**Comment by ysv** [comment]
@Thedabest do you still have an issue ?
