### ISSUE TITLE
POST /v2/deposit_address issue with collection daemon

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#1742]
When you are making deposit to a anycoin address, collection daemon will wait till min conformation amount will be reached. If you will do POST /v2/deposit_address  while min conformation is not reached you will generate new address and collection daemon will try to withdraw amount from new, empty wallet to a hot wallet.

**Comment by ysv** [comment]
This api endpoint need to be hidden before we fix this
https://github.com/ruby-grape/grape#describing-methods

**Comment by ysv** [comment]
Removed in v2
