### ISSUE TITLE
ERC20 Deposit issue -  1000 becomes Trillions  , 

### ISSUE THREAD

**Issue by AnthonyRex** [openware/peatio#1748]
this is the code 

- id:                   GBX
  symbol:               'Îž'
  type:                 coin
  precision:            8
  base_factor:          1_000_000 # IMPORTANT: Don't forget to update this variable according
  enabled:              true      #            to your ERC20-based currency requirements
  quick_withdraw_limit: 10      #            (usually can be found on the official website).
  options:
    #
    # Generic configuration variables.
    case_sensitive:            false # IMPORTANT: Be sure to set the correct value!
    deposit_confirmations:     1 # Set to zero to stop processing all incoming deposits.
    supports_cash_addr_format: false # Set to Â«trueÂ» for Bitcoin Cash or any other currency which supports CashAddr format.
    #
    # API client configuration (BitGo is not currently supported).
    api_client: ERC20
    #
    # Ethereum node specific configuration.
    json_rpc_endpoint: http://127.0.0.1:8545
    #
    # ERC20 configuration.
    erc20_contract_address: '0x25967e15D498714804D4aeDa0687213AB63A38EA' # Always wrap this value in quotes!
    #
    # Block explorer configuration.
    wallet_url_template:      https://etherscan.io/address/#{address}
    transaction_url_template: https://etherscan.io/tx/#{txid}

deposit was 1000 when reaches peatio becomes Trillions and rinkeby won't accept withdrawal 

have anyone one seen this before ?

![2018-10-13 2](https://user-images.githubusercontent.com/43102294/46904435-83aa3400-cf16-11e8-8899-f4dd8ec09e62.png)
![2018-10-13 4 _li](https://user-images.githubusercontent.com/43102294/46904436-8442ca80-cf16-11e8-9015-e2abf455271d.jpg)

**Comment by AnthonyRex** [comment]
it was base factor problem , solved

**Comment by msembinelli** [comment]
Hi there. I am having the same issue with peatio 2.0.xx. What did you change the base factor to?

**Comment by msembinelli** [comment]
Figured it out. Needed to set it higher to `1_000_000_000_000_000_000` in the seed file. This is based on the number of decimals used when creating the ERC20 token. I got this confused with precision, but it seems like precision in peatio is just used for display and rounding purposes and doesn't actually correspond to the smart contract.
