### ISSUE TITLE
Account pusher event not firing

### ISSUE THREAD

**Issue by advanceditsolutions** [openware/peatio#1749]
Peatio is not firing Account updated event which causes the trading-ui to not update the balance on frontend.

heres the ref. code for trading-ui

https://github.com/rubykube/peatio-trading-ui/blob/67f2e9d0133df852568c1c6a1b4193254ca4b615/app/assets/javascripts/component_ui/account_balance.js.coffee#L25

https://github.com/rubykube/peatio-trading-ui/blob/67f2e9d0133df852568c1c6a1b4193254ca4b615/app/assets/javascripts/component_data/member.js.coffee#L6

**Comment by ysv** [comment]
@advanceditsolutions Thanks, yes this should be updated

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
