### ISSUE TITLE
Improve accounting system

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#1751]
we should use database logging or similar so that we can filter the data when needed

My suggestions:
Use Order ID for every order
User execution ID for every execution
log execution details such as ask order and bid order, trade engine decisions such as income and outcome amounts
Log everything to database or similar log driver
Make use of transactions table

**Transactions table fields:**
`id, member_id, account_id, amount, action, direction, type, reference_id, reference_description, token, deleted, delete_motive, created_at, updated_at `

where
action = lock, unlock, deposit, withdraw, add, remove 
direction = credit, debit, lock, unlock
type = amount (can be used in future for other stuff like referral transaction type)
reference_id = order_id, trade_id, etc
reference_description = order, trade, etc
token = transaction unique id
deleted = will be used as a scope, 0 or 1 if 1 then the transaction will be ignored while calculating total balance

In a transactions table we can log every transaction such as locking funds, etc....
What we should do is a transaction table will have lock, unlock, deposit, withdraw, add, remove actions
this actions will be used accordingly to audit users balance, we can do 
`(deposit - withdraw) + (unlock - lock) + (add - remove) = user_balance`

this will make life easy for audits in case  system makes some conflicts somewhere 

i have a system ready for transactions but it is built in laravel (PHP) we can use the code for ref.

**Comment by ysv** [comment]
@martianatwork Hello
You have a good point that is what we are prototyping now.
We have stopped in general ledger accounting system right now

**Comment by martianatwork** [comment]
@ysv let me know if you need any help :)

**Comment by ysv** [comment]
@martianatwork Thanks
Progress in https://github.com/rubykube/peatio/tree/feature/accounting

**Comment by martianatwork** [comment]
@ysvI have some code ready in ruby which can save some time, I have built it the same way as I have mentioned in the issue

**Comment by ysv** [comment]
@martianatwork can you share it ?
