### ISSUE TITLE
how to get JWT in api/v2?

### ISSUE THREAD

**Issue by zhangatle** [openware/peatio#1752]
I want to use api/v2 ,but how to get the JWT?

**Comment by martianatwork** [comment]
There is no pre-built function for getting a jwt but you can use this code to sign one

    def jwt_for(member, payload = { x: 'x', y: 'y', z: 'z' })
      jwt_build(payload.merge(email: member.email))
    end

    #
    # Generates valid JWT. Accepts payload as argument. Add fields required for JWT to be valid.
    #
    def jwt_build(payload)
      jwt_encode payload.reverse_merge \
      iat: Time.now.to_i,
      exp: 20.minutes.from_now.to_i,
      jti: SecureRandom.uuid,
      sub: 'session',
      iss: 'peatio',
      aud: ['peatio']
    end
    #
    # Generates JWT token based on payload. Doesn't add any extra fields to payload.
    #
    def jwt_encode(payload)
      OpenSSL::PKey.read(Base64.urlsafe_decode64(jwt_keypair_encoded[:private])).yield_self do |key|
        JWT.encode(payload, key, ENV.fetch('JWT_ALGORITHM'))
      end
    end

    def jwt_keypair_encoded
        { public:  ENV['JWT_PUBLIC_KEY'],
          private: ENV['JWT_PRIVATE_KEY'] }
    end

    then just run member = Member.find(1)
    member.jwt_for(member)

**Comment by zhangatle** [comment]
@martianatwork you mean there has no api to generate an JWT?

**Comment by ysv** [comment]
@zhangatle there is api to generate an JWT but it is in Barong

**Comment by zhangatle** [comment]
@ysv the JWT generated by barong can be used in peatio?

**Comment by ysv** [comment]
@zhangatle yes
JWT is signed by private key in Barong and validated by public in peatio

**Comment by Joan1590** [comment]
Hi ! 
@martianatwork I use your code, but i get this error.
<img width="1044" alt="captura de pantalla 2018-10-30 a la s 6 56 29 p m" src="https://user-images.githubusercontent.com/10948409/47757699-942c0f80-dc75-11e8-8849-c3d0e8aa6dd9.png">

how you use that ?? 

Thank you !

**Comment by Joan1590** [comment]
@martianatwork Im sorry, i solved that changing the "JWT_PRIVATE_KEY" by EVENT_API_JWT_PRIVATE_KEY and "JWT_ALGORITHM" by EVENT_API_JWT_ALGORITHM but this time with that i get unauthorized with the API :(

**Comment by ysv** [comment]
@Joan1590 Do you still have a question ?

**Comment by Joan1590** [comment]
Nop, Im solved that !! Thank you !
