### ISSUE TITLE
BUG in jwt.rb and jwt_authentication_middleware.rb

### ISSUE THREAD

**Issue by ianeinser** [openware/peatio#1756]
Hello, i just found that the custom configuration

Rails.configuration.x.security_configuration = x (in jwt.rb)

and then it is used in 

security_configuration = Rails.configuration.x.security_configuration (in jwt_authentication_middlware.rb)

doesn't work ...

security_configuration is empty

**Comment by ysv** [comment]
@ianeinser can you share permalink please ?

**Comment by djoffrey** [comment]
I meet the same problem

**Comment by ysv** [comment]
@ianeinser @djoffrey please describe problem with more details
May be you have empty management_api_v1.yml ?
