### ISSUE TITLE
Question about Ripple

### ISSUE THREAD

**Issue by ianeinser** [openware/peatio#1761]
Hi guys,

what does this error suggest?

Ian Einser, [19.10.18 12:02]
Blockchain Load (0.4ms)  SELECT  blockchains.* FROM blockchains WHERE blockchains.key = 'xrp-testnet' LIMIT 1
  Blockchain Load (0.3ms)  SELECT  blockchains.* FROM blockchains WHERE blockchains.key = 'xrp-testnet' LIMIT 1
### **#<BlockchainClient::Error: "noNetwork">**
/home/app/lib/blockchain_client/ripple.rb:102:in `block (4 levels) in json_rpc'
/home/app/lib/blockchain_client/ripple.rb:101:in `tap'
/home/app/lib/blockchain_client/ripple.rb:101:in `block (3 levels) in json_rpc'
/home/app/lib/blockchain_client/ripple.rb:100 in `tap'

**Comment by ysv** [comment]
@ianeinser It's probably issue with your ripple node https://github.com/ripple/rippled/issues/31

**Comment by ianeinser** [comment]
I made a wrong configuration.. now it is working
