### ISSUE TITLE
Pool Deposits broken

### ISSUE THREAD

**Issue by greatplaces** [openware/peatio#1767]
Pool deposits require the ability to accept multiple deposits from one TX id.

Version 1.8 and previous, had this ability for bitcoin based blockchains.

Version 1.9, fails when there is more than one deposit on a TX.  It only accepts the first one.     

For example, in Peatio 1.9, if each of the following addresses on this TX were exchange addresses, it would only credit a deposit to the first address:  (1JUNs2h2c5YN4ntqEadehrgwxQwrAtzfqh )
https://www.blockchain.com/btc/tx/4f44d9db153ff9345b62bb3e5bb0c91dc079fe4683a126262e8a80ff6f71a9e0

In Peaito 1.8, all of these addresses would be correctly credited.

Please restore this functionality, if possible.  For exchanges that don't want to accept pool deposits, a solution was already provided for them on issue #1744

**Comment by ysv** [comment]
@greatplaces Hello, thanks for your issue !
We will debug and fix this issue if are able to confirm

**Comment by pkucherenk0** [comment]
I have checked couple of times with 1.9 and can confirm, that accepted will be only first address in the list.
In case if we have other, not related to Peatio addresses it will ignore them, find first one, that is related to Peatio and accepted it, other ones will be ignored.
TX:
[c53dbe5a5a4575a4b2c72d27bbc186018d212949a9d22a322c679b0b7aeb782e](https://testnet.blockchain.info/tx/c53dbe5a5a4575a4b2c72d27bbc186018d212949a9d22a322c679b0b7aeb782e)
[e949c0d090ab97200e91ad4f84300161837a3267552276d4d0eac0f29465b7da](https://testnet.blockchain.info/tx/e949c0d090ab97200e91ad4f84300161837a3267552276d4d0eac0f29465b7da)

**Comment by greatplaces** [comment]
Should this be given a priority?    This could make up a significant percentage of deposits for many exchanges that would show as uncredited.

**Comment by mnaichuk** [comment]
There is same problem for erc20 tokens. Ripple is based around accounts instead of UTXOs (which allow several inputs and outputs), so it's not possible to do `sendmany` transaction. The recipient of an Ethereum transaction can only ever be a single entity, as specified by the Yellow Paper (http://gavwood.com/paper.pdf) page 4, section 4.2, to field.
This issue will fix in #1792
