### ISSUE TITLE
Parity Ethereum client support 

### ISSUE THREAD

**Issue by Digitelex** [openware/peatio#1768]
Peatio 1.8 Stable:

 I am using Parity Ethereum, as it is good in syncing.
The Address generation is working perfect
Daemons are running
Other coins Withdrawal/Deposit working 
Eth Deposit Working
But I am not Able to withdraw ETH from Peatio.
Dont know whats the error when i click on APprove the withdrawal from the Admin Panel (It gets Failed Instantly)

Can anyone help?
@Muahmmadnegi?
@mod ?

**Comment by ysv** [comment]
@Digitelex The issues caused because we don't support parity-ethereum. As you can see we have only geth in list of available gateways https://github.com/rubykube/peatio/blob/76320abc2fcef080da0403d2bcfa5a183e0ebe43/app/models/wallet.rb#L6

**Comment by adarshdubeytech** [comment]
I am using parity with geth gateway, its the same , we have to modify some lines in geth.rb and ethereum.rb

**Comment by ysv** [comment]
@adarshdubeytech What exactly could you share code snippet ?

**Comment by adarshdubeytech** [comment]
@ysv 
https://github.com/rubykube/peatio/pull/1839
and Yep, No need to change gateway names and other things, but it will be better to go with geth or pairty and setup only 1 gateway client.
Geth and Parity are same things like rubykube and peatio, but as rubykube has more functions, parity is with more functions.
geth+some more functions = parity.

**Comment by huuhait** [comment]
not support

**Comment by adarshdubeytech** [comment]
It supports, can you tell me the error you are facing?
@Thedabest
