### ISSUE TITLE
How to display coin icon in production mode?

### ISSUE THREAD

**Issue by ianeinser** [openware/peatio#1772]
Hello guys,

may i know how to display coin icons in production mode? the icons are correctly displayed in development mode but not in production mode

ActionController::RoutingError (No route matches [GET] "/assets/bch.svg"):
  actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'

**Comment by ysv** [comment]
@ianeinser Looks like a bug. We will take a look. Thanks!

**Comment by ysv** [comment]
closed in https://github.com/rubykube/peatio/pull/1807
