### ISSUE TITLE
Error when GET /v2/accounts/{currency}

### ISSUE THREAD

**Issue by endofthepain** [openware/peatio#1775]
hello we have little problem when GET /v2/accounts/{currency} you can see my example like on this screenshot. i am using version 1.9.1-rc.15

<img width="1022" alt="ss 2018-10-22 at 22 42 29" src="https://user-images.githubusercontent.com/11496089/47381835-1fb01880-d72b-11e8-82c8-2612e81b7f4e.png">

**Comment by endofthepain** [comment]
@ysv can u help me ?

**Comment by ysv** [comment]
@endofthepain Thanks for contribution !
