### ISSUE TITLE
Trading UI bid/ask cancellation doesn't work

### ISSUE THREAD

**Issue by shal** [openware/peatio#1776]

**Comment by shal** [comment]
Redirected from rubykube/workbench#216

**Comment by huuhait** [comment]
for test
I tried on the latest workbench not customizing anything.
Orders history update
Orders Book update
Chart update
update update
my open orders not update
When refreshing the orders page, the order is canceled, but it does not update directly.
i will update video soon.

**Comment by huuhait** [comment]
https://streamable.com/7cf9v
video testing
Mine orders not working
my orders not delete rows when orders are complete
Balance not update when place orders
Click to Cancel All, Cancel Bids, Cancel Asks not update

**Comment by huuhait** [comment]
The 1.8-stable version has the same bug

**Comment by martianatwork** [comment]
This is a bug related to Model events

Because the trading engines runs raw sql quries update events are never published so

what we have to do is to publish Pusher events on update.

I have fixed this by adding 


    after_commit :trigger_pusher_event, on: [:create, :update]
    def trigger_pusher_event
        Member.trigger_pusher_event member_id, :account, currency.id => {
            currency: currency.id,
            balance: balance,
            locked: locked,
            margin: margin
            }
      end
      def trigger_pusher_event
        Member.trigger_pusher_event member_id, :order, \
          id:            id,
          at:            at,
          market:        market_id,
          kind:          kind,
          price:         price&.to_s('F'),
          state:         state,
          volume:        volume.to_s('F'),
          origin_volume: origin_volume.to_s('F'),
          stop:          stop.to_s('F'),
          type:          ord_type
      end

to Account and Order models. 

also triggered this events from trading executor

**Comment by ghost** [comment]
@martianatwork were did you put that because thats my problem too

**Comment by martianatwork** [comment]
@laugh26 in executor.rb and order.rb I will push some code on Sunday which will fix most of issues like this

**Comment by ghost** [comment]
@martianatwork thats great my friend  i will wait for that. Please inform me when you do.

**Comment by ghost** [comment]
@martianatwork 

Hi ! It's been a while but have you got the trading-ui to update the orders without having to refresh browser page ?

**Comment by guru260** [comment]
I am also facing same problem. I am using v 1-9-stable. How to fix this problem.
