### ISSUE TITLE
Add new altcoins/coins via JSON RPC

### ISSUE THREAD

**Issue by knkrth** [openware/peatio#1778]
Like the original [peatio/peatio](https://github.com/peatio/peatio) is there's a way to add coins via JSON RPC commands only? It will be easy to add & manage the exchange coins.

**Comment by Joan1590** [comment]
Hi, Do you can add new coins by RPC in the admin panel, only do you need, if your coin have different commands that DASH or litecoin or bitcoin, add thats differents commands in the lib/blockchainclients !

**Comment by ysv** [comment]
@knkrth Adding a new coin is very dangerous and if you do some mistake this can brake everything.
We are working on adding coins via management API https://github.com/rubykube/peatio/pull/1638

Where did you find call for adding currencies in legacy Peatio ?

**Comment by martianatwork** [comment]
@ysv what do you mean by dangerous?

**Comment by Joan1590** [comment]
Is easy not dangerous xD

**Comment by ysv** [comment]
@martianatwork @Joan1590 Add new currencies is not dangerous ? Are u sure ?

**Comment by Joan1590** [comment]
Yes 👍 not dangerous !!

**Comment by ysv** [comment]
if you put some wrong options for currency it will brake everything

**Comment by Joan1590** [comment]
No problem, the log will advice you, if you put some wrong information!

**Comment by ysv** [comment]
@Joan1590 yes but you are not able to delete currencies at all because Peatio doesn't support it

**Comment by Joan1590** [comment]
You right ! 😄

**Comment by knkrth** [comment]
Refer: https://github.com/rubykube/microkube/issues/111
