### ISSUE TITLE
How to use api on peatio?

### ISSUE THREAD

**Issue by huuhait** [openware/peatio#1790]
![image](https://user-images.githubusercontent.com/40519768/47739467-03baf280-dca8-11e8-891b-216c37aaf35c.png)

**Comment by huuhait** [comment]
curl -H "Authorization: Bearer TOKEN" http://localhost:3000/api/v2/members/me
Example TOKEN pls

**Comment by Joan1590** [comment]
Hi !, Do you can use the tokens generated by barong in the table authentications in the database peatio !

**Comment by huuhait** [comment]
@Joan1590 pls example config :|

**Comment by Joan1590** [comment]
Go to database peatio_development, and the table "authentications", and use one token in that list with your comand, example:

curl -H "Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1NDA2NzM2NDMsImV4cCI6MTU0MDY4ODA0Mywic3ViIjoic2Vzc2lvbiIsImlzcyI6ImJhcm9uZyIsImF1ZCI6WyJwZWF0aW8iLCJiYXJvbmciXSwianRpIjoiNjVENzAwNkQyMDU1MThBRDM5QkFCNkIxIiwidWlkIjoiSUQxMzM4RDg5NUMzIiwiZW1haWwiOiJwcnVlYmFAcHJ1ZWJhLmNvbSIsInJvbGUiOiJtZW1iZXIiLCJsZXZlbCI6MSwic3RhdGUiOiJhY3RpdmUifQ.F8Cg0gsvt3c2pvk5duoCSLC4SW9S7Wp33D0N0IjN9ylJDoEx_5TZ3Nh6OkiQqAqIwQ-bl3OmViLp2NO4NJd7L7RLEOW043DhmAmSet9M3meOYhNHujMbZ8ksxUe5aLOQilGRxWndXqNH8fZ8722rnIf0M85krKFIkkAHefvIsyJG7Rv1b78PVNp5jBn5t3jG42lCMtnNdPgAPMOUBuMHTclcLM0eD017l9q9M5EE0fUUzYIL2n7MQ1lyY9gnWKUOFS1J2YflFx5Tji_75SL7sFdwOECvCRMaYalONkSYMn-VweS3VsFnkwFAERSReP2ymyd745X2rOPAPv4hq0Zl8A" http://localhost:3000/api/v2/members/me

**Comment by huuhait** [comment]
Tks
