### ISSUE TITLE
Remove need to refresh page to see deposit address

### ISSUE THREAD

**Issue by rraallvv** [openware/peatio#1799]
Sometimes when I visit the page to get the address where to deposit funds I see an empty field where the address is supposed to appear and a QR code that is not the actual code for the generated address.

The problem seems to be Peatio requesting the address from the JSON-RPC server and not updating that information once it's generated.

Would it be possible to add some mechanism either to auto-refresh the page once the address is generated, or maybe generate the address when a new user is registered. 

Keep up the good work.

**Comment by huuhait** [comment]
use javascript to auto refresh page if deposit address is none
like JQuery

**Comment by algobasket** [comment]
Vulnerable, beware people!

**Comment by rraallvv** [comment]
@algobasket Do you mean refreshing the page from the client side is vulnerable?

**Comment by martianatwork** [comment]
We have a websocket event for this

https://github.com/rubykube/peatio/blob/db539da8ed826a6665473d4d6058f40aea43d0d8/app/assets/javascripts/funds/events.js.coffee#L4

and 

https://github.com/rubykube/peatio/blob/db539da8ed826a6665473d4d6058f40aea43d0d8/app/workers/worker/deposit_coin_address.rb#L46

This should be working you gotta check your websocket request

**Comment by rraallvv** [comment]
@martianatwork I'll check them out. Thanks.

**Comment by ysv** [comment]
@rraallvv @martianatwork I agree that we have this issue and we can fix it easily because we have event for new address.
But bugfixing of legacy ui isn't high priority now.
If you are able to fix this we will appreciate !

**Comment by martianatwork** [comment]
@ysv I haven’t checked the latest events api yet, I will go thorough it and fix this issues

**Comment by ysv** [comment]
@martianatwork Cool !
The event you need is here https://github.com/rubykube/peatio/blob/76320abc2fcef080da0403d2bcfa5a183e0ebe43/app/workers/worker/deposit_coin_address.rb#L34

**Comment by martianatwork** [comment]
@ysv yeah ik that, I feel like this is an issue because of the new ranger integration. Someone has removed the  pusher_subscriber.js.coffee and forgot to add a replacement for same.

Pusher Subscriber was the one listening to the events and handling the events.

**Comment by rraallvv** [comment]
@martianatwork So, 1.9 has no mechanism for subscribing to that notification?

**Comment by martianatwork** [comment]
@rraallvv yes

**Comment by rraallvv** [comment]
@ysv  Let me see if I understand correctly, 1.9 doesn't have this issue, but only 1.8 does, am I right?
I'm asking because I haven't tried 1.9 yet, I'm going to stick to 1.8 stable at least until a stable release for 1.9 so I'm not sure what you mean by legacy ui.

**Comment by ysv** [comment]
by legacy UI I mean funds page

**Comment by ysv** [comment]
@rraallvv @martianatwork please don't spend your time on this topic. 
We deprecate legacy UI so probably it will be removed soon
