### ISSUE TITLE
[Bug] The order creation with `price:0` by the Peation API endpoint  /api/v2/orders

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#1802]
![selection_723](https://user-images.githubusercontent.com/38254545/48262015-a81c0200-e429-11e8-8e0f-66d12b34a48e.png)
The limit order with `price:0` will break the matching engine.
The expected result is to block users in creation orders with volume and price equal or lower then 0.0

**Comment by mod** [comment]
@pkucherenk0 what version ?

**Comment by ymasiuk** [comment]
@mod 1.9.1-rc.12
