### ISSUE TITLE
New Features to Add

### ISSUE THREAD

**Issue by Digitelex** [openware/peatio#1810]
The developers should add these features for a better exchange:
1. Funds/Crypto Transfer from one user to Another Users Using Email address
2. Search Box for Currencies on Trading ui and Funds page
3. Status page for The Status of Blockchains of every currencies ( Eg. https://tradesatoshi.com/status )
4. Chat Box for Online Users
5. Add Coin Forms/Lists 
6. Blog for News, or only single page with News
7. In the funds page in coin section there should be a line showing current block 
8. Google 2FA / Authy
More Features will be Recommended if Developers Integrate these.

**Comment by martianatwork** [comment]
I think the 4, 5, and 6 are supposed to stay out of Peatio. You can use a third party provider or a make peatio plugin for chat.

5 and 6 should be done using WordPress I’m my opinion. WordPress will be running on main domain and you can create a subdomain for peatio

I think we should change the UI of funds page

**Comment by huuhait** [comment]
you can use it on 5 year ago

**Comment by Digitelex** [comment]
> I think the 4, 5, and 6 are supposed to stay out of Peatio. You can use a third party provider or a make peatio plugin for chat.
> 
> 5 and 6 should be done using WordPress I’m my opinion. WordPress will be running on main domain and you can create a subdomain for peatio
> 
> I think we should change the UI of funds page

Point 1,2,3,4,5,7 and 8  are really needed in 2019 (Just like Support form, A Add coin request form should be Created)
Coin Voting System is also a Recommendation.

**Comment by ysv** [comment]
@Digitelex this issue has 
1. - yes we are working on this now
2. - it's on frontend side and we deprecate legacy UI for now so you need to write your own UI on Angular, React, Vue ... And you put this in UI part
3. - it's interesting feature and needs discussion
4. - nothing to do in Peatio. Can be implemented in separate component
5. - didn't get you
6. - nothing to do in Peatio. Can be implemented in separate component
7. - it's interesting feature and needs discussion
8. - we have it in our backlog. For now only Barong supports 2fa
