### ISSUE TITLE
btc Hot-Wallet Balance show the coins but in btc fund does not

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [openware/peatio#1811]
I wondering why i can't see the btc wallets address in funds? but I can see the the full balance of the wallet in my hot wallet.

I am wondering what it is going on? what it is wrong? for sure the btc wallet it is connect, if it was not I could not be able to see my full balance of my wallet right?

what do you guys think can be? how can I debug this?

thank you.

**Comment by martianatwork** [comment]
I guess the daemons are not running and you require to add deposit address for the currency

**Comment by openbooknoobdeveloper** [comment]
@martianatwork  good point man, ta

**Comment by ysv** [comment]
@openbooknoobdeveloper do you still have a question ?
