### ISSUE TITLE
how can edit frontpage

### ISSUE THREAD

**Issue by cryptonana** [openware/peatio#1813]
Hi.

I deployed Peatio, and im trying to edit the login and registration
I looked for the file but could not find it.
could someone please help me?

**Comment by Joan1590** [comment]
Yes, if the login and the registration page, is in barong, because thats pages dont exists in peatio !

**Comment by ysv** [comment]
@cryptonana we advice not to use Peatio with auth login
Better use Barong API for login and Peatio API so you can build separate fronted application
