### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by ExchangeTime** [openware/peatio#1818]
Stupid question, but what is the easiest way to deploy the exchange in a safe way from workbench exchange? I have mostly worked in Javascript and C / C#. I have been working with the exchange awhile, but seems like everything is accessible for everyone when its hosted in workbench mode?

**Comment by ysv** [comment]
@ExchangeTime First of all don't use workbench to run exchange in production !
Right solution is to use [kubernetes](https://kubernetes.io)

**Comment by ysv** [comment]
@ExchangeTime First of all don't use workbench to run exchange in production !
Right solution is using[kubernetes](https://kubernetes.io)
