### ISSUE TITLE
spelling fix:  "_address" should be "address"?

### ISSUE THREAD

**Issue by Fair-Exchange** [openware/peatio#1819]
https://github.com/rubykube/peatio/blob/771bf9078ce4f9bb31b894a6c3269654588cc27c/lib/blockchain_client/ethereum.rb#L142

**Comment by ysv** [comment]
@Fair-Exchange There is no misspelling.
```Prefix with _ unused block parameters and local variables. It's also acceptable to use just _ (although it's a bit less descriptive). This convention is recognized by the Ruby interpreter and tools like RuboCop and will suppress their unused variable warnings. ```

https://github.com/rubocop-hq/ruby-style-guide#underscore-unused-vars

**Comment by Fair-Exchange** [comment]
thank you kindly for the explanation

**Comment by ysv** [comment]
@Fair-Exchange Please close issue if you don't have question anymore
