### ISSUE TITLE
Refreshing the page creates new API token

### ISSUE THREAD

**Issue by gfedorenko** [openware/peatio#182]
When you refresh this page it creates new tokens with the same label

![screenshot from 2017-12-22 20-03-37](https://user-images.githubusercontent.com/25289193/34307980-88a4117a-e753-11e7-937c-4b9994cf12ff.png)

**Comment by yivo** [comment]
@gfedorenko does this occurs after HTTP POST?

**Comment by yivo** [comment]
Please base your branch on master and target your PR to branch devel. Push PR as you start working.

**Comment by yivo** [comment]
Fixed in #356.
