### ISSUE TITLE
need full tutorial to install peatio

### ISSUE THREAD

**Issue by aminaqi** [openware/peatio#1824]
my skype is 
 Skype: amin_1375.kr

if anyone can help me to install peatio on my VPS i would appreciate 
Thanks

**Comment by ExchangeTime** [comment]
@aminaqi If you dont know how to set it up. Dont host it.

Letting anyone setting it up for you are even worse. Please dont host a exchange if you dont know anything about coding.

**Comment by huuhait** [comment]
> @aminaqi If you dont know how to set it up. Dont host it.
> 
> Letting anyone setting it up for you are even worse. Please dont host a exchange if you dont know anything about coding.

nice

**Comment by ysv** [comment]
@ExchangeTime I fully agree with you


@aminaqi Try https://github.com/rubykube/microkube or https://github.com/rubykube/workbench

**Comment by raidray** [comment]
> @ExchangeTime I fully agree with you
> 
> @aminaqi Try https://github.com/rubykube/microkube or https://github.com/rubykube/workbench

it is not working do you have complete tutorial then please upload it hear

**Comment by ysv** [comment]
@maulikbhai1 if it doesn't work please report issues in appropriate repository
