### ISSUE TITLE
KeyError: key not found: "TIMEZONE"

### ISSUE THREAD

**Issue by glaksmono** [openware/peatio#1830]
I'm getting this error, any ideas?

```
➜  peatio git:(master) bundle exec rake yarn:install
rake aborted!
KeyError: key not found: "TIMEZONE"
/Users/glaksmono/Documents/peatio/config/application.rb:35:in `fetch'
/Users/glaksmono/Documents/peatio/config/application.rb:35:in `<class:Application>'
/Users/glaksmono/Documents/peatio/config/application.rb:18:in `<module:Peatio>'
/Users/glaksmono/Documents/peatio/config/application.rb:17:in `<top (required)>'
/Users/glaksmono/Documents/peatio/Rakefile:8:in `require'
/Users/glaksmono/Documents/peatio/Rakefile:8:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.5.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/Users/glaksmono/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
```

**Comment by glaksmono** [comment]
Pretty sure there are other alternative solution, but here's what I did to solve this:

1. Create `.env` with `TIMEZONE` key value pair

2. Add the following to the Gemfile
```
gem 'dotenv-rails', groups: [:development, :test]
```

**Comment by IMPERIUM-main-dev** [comment]
how do you create .env with TIMEZONE key value pair

I'm having the same issue

**Comment by IMPERIUM-main-dev** [comment]
here is another solution :

~/peatio/config/application.rb    line 35 :

replace  config.time_zone = ENV.fetch('TIMEZONE')

by   config.time_zone = 'Eastern Time (US & Canada)'    or your own timezone

**Comment by IMPERIUM-main-dev** [comment]
after that I had another error :

rake aborted!
Errno::ENOENT: No such file or directory - yarn

which I resolved by :
npm install -g yarn

**Comment by IMPERIUM-main-dev** [comment]
Actually I think all these errors happen when using ruby 2.5.3 instead of ruby 2.5.1

**Comment by IMPERIUM-main-dev** [comment]
So I guess this information will be needed for updating to ruby 2.5.3
