### ISSUE TITLE
Peatio Production Setup 

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#1843]
Hi Team,

I am working on setting up the peatio in production mode with better performance. The below url has suggested to setup multiple threads of daemons to achieve the same. 

https://github.com/rubykube/peatio/issues/1145

But am not sure how to do this. Can anyone please help me with the steps to achieve the same?

**Comment by Thedabest** [comment]
this is toolbox test only for fait ccy, not for coin

**Comment by sharmaabhishek2207** [comment]
Thanks for your response. Can you please help me with the steps to setup multiple daemons to get better performance in prod envrionemnt.
