### ISSUE TITLE
Admin Panel Deposits/Withdraws Table Issue

### ISSUE THREAD

**Issue by rahul-ranchal** [openware/peatio#1853]
Hi, 
I have noticed these queries are wrong

https://github.com/rubykube/peatio/blob/master/app/controllers/admin/deposits/fiats_controller.rb#L11-L12

`All Deposits` showing `Latest Deposits` and `Latest Deposits` showing `All Deposits`
Same issue for withdraws.

![image](https://user-images.githubusercontent.com/488095/49373298-99bcbf80-f723-11e8-9eff-45571978d87c.png)

**Comment by ysv** [comment]
yes I agree
this issue fixed in https://github.com/rubykube/peatio/pull/1846
