### ISSUE TITLE
Pool deposits stay in "accepted" status

### ISSUE THREAD

**Issue by Fair-Exchange** [openware/peatio#1859]
Hi there,

#1767 seems to correctly recognize pool deposits, but does not "accept" them.   

They stay in "submitted" status perpetually, and users are not credited for their deposits.

At least, in my implementation.   Is it possible that another mechanism is still questioning them as duplicate?

**Comment by ysv** [comment]
@Fair-Exchange which currency did you test ?

**Comment by Fair-Exchange** [comment]
Wow that was the fastest response ever.    Currencies using the BTC API, mostly.

**Comment by Fair-Exchange** [comment]
Hi there,  

I would like to retract this issue.  It turned out to be blockchain related, and was resolved.

**Comment by ysv** [comment]
@Fair-Exchange Could you please describe what exactly happened with blockchain ?
Or you put wrong configuration ?

**Comment by ysv** [comment]
@Fair-Exchange please reopen if you have an answer

**Comment by Fair-Exchange** [comment]
Hi there,

What seems to be happening, is that deposits with large numbers of vouts are not properly accepted.

Here is an example:   https://insight.ritocoin.org/tx/67d0986cf4f412e1a324a367eaa367f976604bd275af28e38f38f214f9c37a72

Most of these outputs are individual deposits.    Peatio is unable to process them past "accepted".    They exceed some kind of limit
