### ISSUE TITLE
NoMethodError in WelcomeController#index

### ISSUE THREAD

**Issue by cryptobot123** [openware/peatio#1862]
**Hello  i got this error** 
 I  followed  https://github.com/rubykube/peatio/blob/master/docs/setup-ubuntu.md

![peatioerror](https://user-images.githubusercontent.com/36717883/49484847-7012ae00-f873-11e8-8120-b0a6a8063f29.PNG)

`root@loremz:~/code/peatio# bundle exec rails server -b 0.0.0.0
/root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)=> Booting Puma
=> Rails 4.2.10 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.3-p105), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop

Started GET "/signin" for 110.54.150.12 at 2018-12-05 01:38:48 +0000
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT `schema_migrations`.* FROM `schema_migrations`

ActionController::RoutingError (No route matches [GET] "/signin"):
  actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.10) lib/rails/rack/logger.rb:22:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.11) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.11) lib/rack/runtime.rb:18:in `call'
  rack (1.6.11) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.11) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.10) lib/rails/engine.rb:518:in `call'
  railties (4.2.10) lib/rails/application.rb:165:in `call'
  rack (1.6.11) lib/rack/content_length.rb:15:in `call'
  puma (3.11.4) lib/puma/configuration.rb:225:in `call'
  puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
  puma (3.11.4) lib/puma/server.rb:446:in `process_client'
  puma (3.11.4) lib/puma/server.rb:306:in `block in run'
  puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

  Rendered /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.0ms)
  Rendered /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/routes/_route.html.erb (2.3ms)
  Rendered /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/routes/_table.html.erb (8.1ms)
  Rendered /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (2.0ms)
  Rendered /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (47.2ms)

Started GET "/" for 110.54.150.12 at 2018-12-05 01:38:54 +0000
Processing by WelcomeController#index as HTML
  Market Load (0.6ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 15ms (ActiveRecord: 1.3ms)

NoMethodError (undefined method `attributes' for nil:NilClass):
  app/controllers/application_controller.rb:50:in `set_gon'

  Rendered /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.9ms)
  Rendered /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.6ms)
  Rendered /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (18.4ms)`

**Comment by AnythingLinux** [comment]
![Screenshot from 2019-05-04 23-42-58](https://user-images.githubusercontent.com/1058663/57182861-5dee7780-6ec6-11e9-87a0-5b47cbf78c34.png)
same here

**Comment by ruiandrada** [comment]
@khay12 and @saydulk  I guess you didn't created any market. Did you seed the database?
