### ISSUE TITLE
Add a new Gateway client within Admin Panel

### ISSUE THREAD

**Issue by MerlinMagic2018** [openware/peatio#1863]
Could it be possible ?

**Comment by marlinnemo** [comment]
scammer

**Comment by huuhait** [comment]
> scammer

really?

**Comment by marlinnemo** [comment]
he installed a version of peatio for me and added in code that would grant access to various accounts.

**Comment by ysv** [comment]
@MerlinMagic2018 you need to implement this client.
We are working on dynamic gatawey & blockchain clients as plugins so now you can't
