### ISSUE TITLE
Admin rubric "Documents" doesn't work at all

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#187]
Documents ( /admin/documents )

- documents do not create

**Comment by yivo** [comment]
@mkuvshynnikov @mod I believe this rubric should be stripped from Peatio. What do you think?

**Comment by yivo** [comment]
Approved by Louis

**Comment by yivo** [comment]
![screencapture-localhost-3000-admin-documents-new-1514485701006](https://user-images.githubusercontent.com/7421323/34424984-a6de5bbe-ec30-11e7-977a-d21cae9a4055.png)

**Comment by gfedorenko** [comment]
@yivo  should I remove the section with Korean and Chinese texts?

**Comment by yivo** [comment]
@gfedorenko We should remove this rubric entirely including database stuff. Have you started the task?

**Comment by yivo** [comment]
Closed via #217.
