### ISSUE TITLE
Settlement Process in Peatio

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#1873]
Please help me in understanding the settlement process in Peatio. 
Let say user A has 5 ETH in his wallet and he did some trade on peatio and purchased 2 more ETH. Since trade in peatio is happened in database only not on real blockchain then if user want to exit from peatio and want to withdraw his ETH coins in some external wallet then how does it happen?

Kindly help me to understand the flow of it.

**Comment by ysv** [comment]
@sharmaabhishek2207 First of all you need to understand that member funds are collected to withdraw wallets (hot,warm,cold). So when member creates withdrawal transaction will be send from one of withdraw wallets depending on amount.

**Comment by abhisheksharmatech** [comment]
Thanks Ysv for your response. So when the withdraw transaction is initiated using the withdrawal screen, then what RID I have to provide? It will be great if you can elaborate your point. Thanks in advance.

**Comment by ysv** [comment]
<img width="829" alt="screen shot 2018-12-13 at 1 57 42 pm" src="https://user-images.githubusercontent.com/19859122/49937353-282d0000-fedf-11e8-8f1b-c3bebbdf2331.png">
<img width="852" alt="screen shot 2018-12-13 at 1 58 07 pm" src="https://user-images.githubusercontent.com/19859122/49937354-282d0000-fedf-11e8-9e8a-899327cffb44.png">

**Comment by ysv** [comment]
RID - recipient ID 
on the other words it's address in blockchain
