### ISSUE TITLE
Button «Reject» doesn't work while editing KYC document 

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#188]
- Enter to any registered member by clicking button "View"

Button "Rejected" doesn't work

**Comment by yivo** [comment]
@mkuvshynnikov Please write details. I can't reproduce.

**Comment by mkuvsh** [comment]
@yivo with the latest update, bug was fixed

**Comment by mkuvsh** [comment]
![screen shot 2018-01-10 at 2 21 56 pm](https://user-images.githubusercontent.com/29736025/34772892-5c3cb29a-f612-11e7-8913-a617d7c95678.png)
