### ISSUE TITLE
SMS verification code does not come

### ISSUE THREAD

**Issue by UfukAntep** [openware/peatio#1885]
Hi,

I open a new membership. SMS verification code does not come. I made changes to the sections below. I deleted the "changeme" parts and added my own information. But the error did not recover.

TWILIO_ACCOUNT_SID=changeme
TWILIO_AUTH_TOKEN=changeme
TWILIO_PHONE_NUMBER=changeme

Thank you.

**Comment by andyduong1920** [comment]
On which environment @UfukAntep ?
The SMS feature was disable as default on Development mode, if you want to test your feature, just enable it in here **barong_app/config/initializers/fake_twilio.rb**

**Comment by UfukAntep** [comment]
Hello, I'm testing in my own local area. I went to the address you said. How do I activate? Is it enough to write my own Client instead of FakeSms?

if Rails.env.development?
  Twilio::REST::Client = FakeSMS
end

Thank you.

**Comment by andyduong1920** [comment]
Just comment all of that @UfukAntep

**Comment by UfukAntep** [comment]
Thank you problem solved

**Comment by UfukAntep** [comment]
Can I ask you one more question? How can I produce the test bitcoin?
