### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/"):

### ISSUE THREAD

**Issue by dudetheman** [openware/peatio#1889]
_**I am using Peatio 1.8-Stable for Peatio and Trading UI. I cannot figure out for the life of my how to route the UI properly.**_ 

**This is whats in my trading UI config/application.yml for URLs**

> 
> #Set root URL to Peatio platform. It will be used to fetch variables which is trading interface driven by.
> PLATFORM_ROOT_URL: http://ec2-x-x-xxx-xxx.eu-west-2.compute.amazonaws.com:3000
> 
>   #Set URL where you wan to redirect from trading ui menubar
> FRONTEND_ROOT_URL: http://ec2-x-x-xxx-xxx.eu-west-2.compute.amazonaws.com:4000
> 

**This is what my /etc/nginx/sites-available/default looks like**

> # 
> #ATTENTION!
> #
> #Make sure to add the next line to /etc/hosts.
> #
> #127.0.0.1 peatio.tech <--- Added this to /etc/hosts with my domain
> #
> 

> server {
>   server_name      ec2-x-x-xxx-xxx.eu-west-2.compute.amazonaws.com;
>   listen           80;
>   proxy_set_header Host redacted-exchange.io;
> 
>   location ~ ^/(?:trading|trading-ui-assets)\/ {
>     proxy_pass http://127.0.0.1:4000;
>   }
> 
>   location / {
>     proxy_pass http://127.0.0.1:3000;
>   }
> }
> 

**This is the error I get on terminal, along with "The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved." on Chrome. Tried few browsers and cleared cache, no dice.** 

> ActionController::RoutingError (No route matches [GET] "/"):  actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call' actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call' railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app' railties (5.1.6) lib/rails/rack/logger.rb:26:in `call' actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call' actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call' rack (2.0.5) lib/rack/method_override.rb:22:in `call' rack (2.0.5) lib/rack/runtime.rb:22:in `call' activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call' actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call' rack (2.0.5) lib/rack/sendfile.rb:111:in `call' railties (5.1.6) lib/rails/engine.rb:522:in `call' puma (3.11.3) lib/puma/configuration.rb:225:in `call' puma (3.11.3) lib/puma/server.rb:624:in `handle_request' puma (3.11.3) lib/puma/server.rb:438:in `process_client' puma (3.11.3) lib/puma/server.rb:302:in `block in run' puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by cryptobot123** [comment]
change : 
http://127.0.0.1:4000;
http://127.0.0.1:3000; 
to: 
http://ec2-x-x-xxx-xxx.eu-west-2.compute.amazonaws.com:4000;
http://ec2-x-x-xxx-xxx.eu-west-2.compute.amazonaws.com:3000;

**Comment by dudetheman** [comment]
Tried that already

**Comment by huuhait** [comment]
sloved?
