### ISSUE TITLE
ActiveRecord should respect database column types limits (it should validate lengths)

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#189]
Fill in more then 150 symbols to the field  > Click "Save" button

![screen shot 2017-12-21 at 8 01 09 pm](https://user-images.githubusercontent.com/29736025/34309276-cf51d4b2-e759-11e7-9b94-27f8142c622f.png)

**Comment by yivo** [comment]
We need to use gem `validates_lengths_from_database` and remove existing validations for lengths. Also we need to check if all features work as expected.
