### ISSUE TITLE
Block height in admin panel  not increasing. Version v1.9.1-rc.26

### ISSUE THREAD

**Issue by cryptobot123** [openware/peatio#1891]
![height issue](https://user-images.githubusercontent.com/36717883/49977967-5532ee80-ff83-11e8-9677-6c4be2ecd605.PNG)

I added altcoin which is base from BITCOIN , i notice that the  block height in admin  panel is not moving anymore it's already  1 day passed but the height still  not moving .   coin daemon is running , all daemon running , coin daemon full synced ,  
 i am able to generate wallet address  only problem is the height not increasing in  admin panel ,  is it a bug ?   please help Thank you so much

**Comment by mnaichuk** [comment]
@khay12 You can try to get error through `blockchain daemon` logs, because it updates block height in admin panel and in db.

**Comment by cryptobot123** [comment]
> @khay12 You can try to get error through `blockchain daemon` logs, because it updates block height in admin panel and in db.



 there's is no logs , folder empty in config/daemon/

**Comment by cryptonana** [comment]
i still face same issue @khay12 how you resolve this
