### ISSUE TITLE
Routing to new UI assets

### ISSUE THREAD

**Issue by dudetheman** [openware/peatio#1899]
Can someone for the love of god explain to me how to fix the "Routing Error" "URL you requested was not found" I was able to get backend up but I am about to shoot myself trying to figure out how to implement the trading-ui. Any help would be appreciated.

**Comment by nantestdeveloper** [comment]
@dudetheman  you need to do reverse proxy setting like
server {
  server_name      peatio.tech;
  listen           80;
  proxy_set_header Host peatio.tech;

  location ~ ^/(?:trading|trading-ui-assets)\/ {
    proxy_pass http://127.0.0.1:4000;
  }

  location / {
    proxy_pass http://127.0.0.1:3000;
  }
}

You can find setup in docs of peatio

**Comment by dudetheman** [comment]
@nantestdevoloper 

I already did that. Still cant access trading page. Do I need to change the http://127.0.0.1 to my host ip?

**Comment by nantestdeveloper** [comment]
@dudetheman yes that will  be your peatio host ip . Like if you are running peatio on local environment it  http://localhost:3000 .restart the ngnix server

**Comment by shal** [comment]
Thanks @nantestdevoloper.
