### ISSUE TITLE
OAuth Barong - Redirect URL includes Token information.

### ISSUE THREAD

**Issue by andyduong1920** [openware/peatio#1900]
Hi, I'm login through Barong app, everything works fine except the redirect URL

Here is my configuration:

I set the redirect URL in the Barong Doorkeeper Application is `http://localhost:3000/auth/barong/callback`

In Peatio app, I set the BARONG_OAUTH2_REDIRECT_URL is `http://localhost:3000/`

After I login through Barong, the address bar looks like this  `localhost:3000/?expires=true&expires_at=1545045046&token=eyJhbGcxxxxxxxx`

I'm not sure what was the reasons that we need to keep the Token, Expires and Expires At on the query params 🤔. Should we remove them?

**Comment by nantestdeveloper** [comment]
@anduonghien  Peatio and Barong keep listening to each other using jwt token,barong provide the jwt issue jwt token. To maintain session timespan expire and expires_at params are used.No need to remove it
