### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by ghost** [openware/peatio#191]
hi, how to install rubykube peatio ?

**Comment by yivo** [comment]
There is a good guide on [askubuntu](https://askubuntu.com/questions/340965/how-do-i-install-ubuntu-server-step-by-step).

**Comment by ghost** [comment]
Hi.

thank you for your reply.

Rubykube Peatio install ?

**Comment by yivo** [comment]
@melmali2828 Regarding of your previous question how to install ubuntu server 14 you can use the link above ;)

As for getting everything prepared you can read about it at https://github.com/rubykube/peatio/blob/master/docs/dev/setup/ubuntu.md

You can also use peatio-workbench to get peatio which runs using docker: https://github.com/rubykube/peatio-workbench

**Comment by ghost** [comment]
Production install ?

**Comment by ghost** [comment]
I think you guys update the deploy docs :) Its still old peatio docs

**Comment by yivo** [comment]
Duplicate of #325.
