### ISSUE TITLE
Update height problem

### ISSUE THREAD

**Issue by UfukAntep** [openware/peatio#1923]
Hello,
I don't see the ethereum I sent. I think that's the problem. "After deployment, height of blockchains should be updated to start receiving deposits. Go to Blockchains Tab in Peatio Admin Panel and update height" I need to use the place in the picture, right? But it doesn't work. Is my field wrong?

![alt text](https://u-chest.com/wp-content/uploads/2018/12/bumu.png)

**Comment by shal** [comment]
Moved to https://github.com/rubykube/workbench/issues/268.
