### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/trading/usdbtc/ws"):

### ISSUE THREAD

**Issue by not-a-dev0** [openware/peatio#1928]
![screen shot 2018-12-22 at 12 11 47 am](https://user-images.githubusercontent.com/46028023/50371343-531df080-057e-11e9-8a7b-683ae2d00d93.png)

this is what I keep getting on the terminal when i try to access the trading page. I am using AWS for host. I updated the proxy already  

app/views/markets/show.html.erb:2:in `_app_views_markets_show_html_erb__217976389657218588_70189027852200'
Started GET "/trading/usdbtc/ws" for 127.0.0.1 at 2018-12-22 05:56:01 +0000

ActionController::RoutingError (No route matches [GET] "/trading/usdbtc/ws"):

actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
puma (3.11.3) lib/puma/configuration.rb:225:in `call'
puma (3.11.3) lib/puma/server.rb:624:in `handle_request'
puma (3.11.3) lib/puma/server.rb:438:in `process_client'
puma (3.11.3) lib/puma/server.rb:302:in `block in run'
puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2018-12-22 05:56:50 +0000 ===
- Goodbye!

**Comment by huuhait** [comment]
what verison?

**Comment by not-a-dev0** [comment]
@Thedabest 1.9

**Comment by huuhait** [comment]
you need trading-ui

**Comment by not-a-dev0** [comment]
@Thedabest I added the peatio-trading-ui to the code folder like the instruction said. Is there another one?

**Comment by huuhait** [comment]
> I added the peatio-trading-ui to the code folder like the instruction said. Is there another one?

check your proxy

**Comment by not-a-dev0** [comment]
@Thedabest 

This is whats in my /etc/nginx/sites-available/default


#
#ATTENTION!
#
#Make sure to add the next line to /etc/hosts.
#
#127.0.0.1 peatio.tech
#

server {
  server_name      trade.ExchangeURL.io;
  listen           80;
  proxy_set_header Host trade.ExchangeURL.io;

  location ~ ^/(?:trading|trading-ui-assets)\/ {
    proxy_pass http://x.xx.xxx.xxx:4000;
  }

  location / {
    proxy_pass http://x.xx.xxx.xxx:3000;
  }
}

**Comment by huuhait** [comment]
![image](https://user-images.githubusercontent.com/40519768/50380765-9ecaba00-06a4-11e9-86af-6c50757d09ff.png)
server_name trade.ExchangeURL.io;
listen 80;
proxy_set_header Host trade.ExchangeURL.io;
what 127.0.0.1 peatio.tech and trade.ExchangeURL.io ?? :D ??

**Comment by not-a-dev0** [comment]
![screen shot 2018-12-22 at 10 32 28 pm](https://user-images.githubusercontent.com/46028023/50380808-9a1cec00-0639-11e9-8e60-09cb32341c82.png)

Sorry.  
127.0.0.1 peatio.tech is just the there from the instructions i copied, see picture i attached. 
and trade.ExchangeURL.io is just my way of censoring the actual domain name haha

**Comment by not-a-dev0** [comment]
Also, why does it keep adding /ws to the end

ActionController::RoutingError (No route matches [GET] "/trading/usdbtc/ws"):

**Comment by not-a-dev0** [comment]
@Thedabest

**Comment by huuhait** [comment]
/trading/usdbtc/ws
what /ws??
only /trading/usdbtc

**Comment by not-a-dev0** [comment]
@Thedabest it keeps adding the /ws automatically. 

config/initializers/faraday.rb:10:in `run_request'
app/controllers/markets_controller.rb:6:in `show'
Started GET "/trading/usdbtc/ws" for 127.0.0.1 at 2018-12-23 04:52:19 +0000

ActionController::RoutingError (No route matches [GET] "/trading/usdbtc/ws"):    <--------- **See**

**Comment by huuhait** [comment]
> @Thedabest it keeps adding the /ws automatically.
> 
> config/initializers/faraday.rb:10:in `run_request' app/controllers/markets_controller.rb:6:in `show'
> Started GET "/trading/usdbtc/ws" for 127.0.0.1 at 2018-12-23 04:52:19 +0000
> 
> ActionController::RoutingError (No route matches [GET] "/trading/usdbtc/ws"): <--------- **See**


I am also using version 1.9 and there is no error like you please check back!

**Comment by huuhait** [comment]
sloved?

**Comment by not-a-dev0** [comment]
@Thedabest Nope. Still same issue. Still getting same thing. I even did fresh install. :(

**Comment by not-a-dev0** [comment]
this is the guide that i followed if it clears things. But instead of his github i used rubykube git clone


https://steemit.com/rails/@bilal-haider/setting-up-rubykube
