### ISSUE TITLE
Altcoin Blockheight Error Not increasing=>>  "JSON value is not a boolean as expected"

### ISSUE THREAD

**Issue by cryptobot123** [openware/peatio#1936]
**Hello i am using 1.9 stable version** 

#<Faraday::Error: -- HTTP 500 Internal Server Error --

-- Request URL --
http://127.0.0.1:32323/

-- Request Method --
POST

-- Request headers --
{"Authorization":"SECRET","User-Agent":"Faraday v0.14.0","Accept":"application/json","Content-Type":"application/json"}

-- Request body --
{"jsonrpc":"1.0","method":"getblock","params":["bbeb0d6822758f02658e60d7bb4282eeff709f16831c66fd8ccdcbe63f5da144",2]}

-- Response headers --
{"date":"Thu, 27 Dec 2018 10:59:27 +0000","connection":"close","content-length":"98","content-type":"application/json","server":"esbcoin-json-rpc/2.0.4.2"}

-- Response body --
{"result":null,"error":{"code":-1,"message":"JSON value is not a boolean as expected"},"id":null}

Thank you for the help .

**Comment by sundanny26** [comment]
You need to change requests accordingly to the Altcoin. some altcoin take 0,1 or None into the last parameter. What altcoin is it ?

**Comment by ghost** [comment]
the same issue ,how to solve ? @sundanny26

**Comment by martianatwork** [comment]
I had this issue with multichain I just created my own blockchain and wallet services

**Comment by cryptobot123** [comment]
how you solve

**Comment by ghost** [comment]
> I had this issue with multichain I just created my own blockchain and wallet services

You have telegram or discord? can you help me ?

**Comment by martianatwork** [comment]
@zantix-coin telegram “martianatwork”

**Comment by zantix-coin** [comment]
@martianatwork  I can't DM you in telegram it say "Sorry you can only message to mutual contacts"
My telegram : @Goods_Larva (https://t.me/Goods_Larva)
