### ISSUE TITLE
add new coin to peatio

### ISSUE THREAD

**Issue by nantestdeveloper** [openware/peatio#1939]
I want to add new NEO currency to the exchange.
I added the coin from admin panel .How to do setup the blockchain, Server,Client and Explorer Address?
How do I  find  test server to use for neo coin?

**Comment by huuhait** [comment]
peatio don't support neo

**Comment by nantestdeveloper** [comment]
@Thedabest  How can I add new currency if I want to add? What type of currencies peatio support

**Comment by martianatwork** [comment]
@nantestdevoloper check the blockchain_client, wallet_client, blockchain_service, wallet_service in the code
