### ISSUE TITLE
LoadError: cannot load such file -- bump

### ISSUE THREAD

**Issue by luislagardera** [openware/peatio#1940]
I have this problem after execute this line:

bundle exec rake db:setup

any help???

**Comment by nantestdeveloper** [comment]
@feltoxXx have you run   bin/init_config command?

**Comment by luislagardera** [comment]
@nantestdevoloper yes

**Comment by shal** [comment]
Hey @feltoxXx,

```sh
$ bundle install
```

**Comment by ghost** [comment]
@shal bundle install did not solve the problem for me. Version 2.1.4

**Comment by nantestdeveloper** [comment]
@laugh26  what error you are getting after using this version?
Try ruby 2.5.1
