### ISSUE TITLE
Trading between local accounts

### ISSUE THREAD

**Issue by UfukAntep** [openware/peatio#1941]
I'm working in a development environment. I'm sending Ethereum between 2 accounts. But nothing happens. I checked the wallet numbers of the accounts in the local area from the console and nothing is visible. Then I downloaded the ethereum wallet application and created a new account. This account appears on the console. Then I sent Ethereum to my new account and it worked. However, when I send it to the accounts in the project it looks ethereum 0. Please help me.

**Comment by nantestdeveloper** [comment]
@UfukAntep  ethereum node  need to be sych ,then only you can see the transaction.

**Comment by UfukAntep** [comment]
How can I do that? What is sych?

**Comment by nantestdeveloper** [comment]
@UfukAntep  you need to setup ethereum node as server for peatio and  connect .It will start synchronising once it started ,similar you may  setup for blockchain bitcoind

**Comment by UfukAntep** [comment]
Do you mean geth? Because geth installed

**Comment by nantestdeveloper** [comment]
@UfukAntep  Is your problem fix ?
yes geth.

**Comment by UfukAntep** [comment]
I still can't solve the error. (Geth rinkeby is synchronized) Can the panel not show the rinkeby network?

**Comment by shal** [comment]
Is it still relevant? 

The flow is easy: 
-  Sync geth.
- Add it's ip/hostname to peatio admin panel. 

If you have issues with it: Show us blockchain daemon logs.

**Comment by UfukAntep** [comment]
Hello @shal ,

I am using Linux 14.04. 
I am using this command for Geth Rinkeby -> `geth --rinkeby --rpc --rpcaddr "0.0.0.0"`
Height : 2000000

Are there any errors here? Which logs would you like to see?  (withdraw_auidit, k, blockchain ?)

![alt text](https://i.imgyukle.com/2019/02/27/lmJd1.png)


![image](https://user-images.githubusercontent.com/28463089/53784526-9d303480-3f26-11e9-8a54-d9ef773ae3b6.png)
![image](https://user-images.githubusercontent.com/28463089/53784667-0ca62400-3f27-11e9-8a18-ebe73c7057d2.png)

**Comment by UfukAntep** [comment]
@shal  
withdraw_audit, blockchain, global_state, deposit_collection, deposit_collection_fees, deposit_coin_address, slave_book market_ticker, pusher_market, pusher_member, matching, order_processor, trade_executor, withdraw_coin, k

**### withdraw_audit log**
![image](https://user-images.githubusercontent.com/28463089/54013507-6b1f0c80-418a-11e9-9ea8-8dc5e334ff53.png)

**### blockchain log**
![image](https://user-images.githubusercontent.com/28463089/54013697-2f387700-418b-11e9-9a6f-f6d888393bae.png)

**### global_state log**
![image](https://user-images.githubusercontent.com/28463089/54013757-5b53f800-418b-11e9-9516-8d583864c7b8.png)

**### deposit_collection log**
![image](https://user-images.githubusercontent.com/28463089/54015712-935e3980-4191-11e9-8c2a-0b7f6008aceb.png)

**### deposit_collection_fees log**
![image](https://user-images.githubusercontent.com/28463089/54015801-dd471f80-4191-11e9-9195-16e24dfdf92e.png)

**### deposit_coin_address log**
![image](https://user-images.githubusercontent.com/28463089/54015820-f4860d00-4191-11e9-898f-3ad5ef429c27.png)

**### slave_book log**
![image](https://user-images.githubusercontent.com/28463089/54015854-141d3580-4192-11e9-9d2d-c043a6dc8083.png)

**### market_ticker log**
![image](https://user-images.githubusercontent.com/28463089/54015914-4fb7ff80-4192-11e9-9640-72fcaf354ba7.png)![image](https://user-images.githubusercontent.com/28463089/54015932-5e061b80-4192-11e9-8694-4bf28408ed49.png)

**### pusher_market log**
![image](https://user-images.githubusercontent.com/28463089/54015973-87bf4280-4192-11e9-9c13-7badaf7824c9.png)

**### pusher_member log**
![image](https://user-images.githubusercontent.com/28463089/54016077-d967cd00-4192-11e9-8931-890e7efda11e.png)

**### matching log**
![image](https://user-images.githubusercontent.com/28463089/54016141-09af6b80-4193-11e9-8d0e-fd5946d2d4f2.png)![image](https://user-images.githubusercontent.com/28463089/54016160-19c74b00-4193-11e9-9d7e-df7f8b4a7519.png)

**### order_processor log**
![image](https://user-images.githubusercontent.com/28463089/54016209-3ebbbe00-4193-11e9-846c-5b9af4f137a4.png)

**### trade_executor log**
![image](https://user-images.githubusercontent.com/28463089/54016270-61e66d80-4193-11e9-864b-0c94f51846de.png)

**### withdraw_coin log**
![image](https://user-images.githubusercontent.com/28463089/54016315-83475980-4193-11e9-9354-ce28aa45e72d.png)

**### k log**
![image](https://user-images.githubusercontent.com/28463089/54016337-98bc8380-4193-11e9-8446-6dc4d39cd69b.png)

**Comment by UfukAntep** [comment]
Hello @shal 

I've reinstalled Workbench. All of these problems have been improved, but I have these errors. That's why it's not working, is it?

### peatio log
![image](https://user-images.githubusercontent.com/28463089/54197734-c710ca80-44d5-11e9-99e9-c3334dd12dfb.png)

### ethereum/client-go:stable log
![image](https://user-images.githubusercontent.com/28463089/54197803-ef98c480-44d5-11e9-832c-256d67128030.png)
