### ISSUE TITLE
peatio session API

### ISSUE THREAD

**Issue by nantestdeveloper** [openware/peatio#1945]
I have  jwt token generated from the barong using API  ,now I want to create session using jwt token in peatio .How do I do that?
Following the doc https://github.com/rubykube/peatio/blob/1-9-stable/docs/api/member_api_v2.md
Please suggest.
Thanks!

**Comment by Thedabest** [comment]
use it
https://github.com/rubykube/peatio/blob/1-9-stable/docs/api/event_api.md

**Comment by martianatwork** [comment]
You just make the api request using the token

**Comment by nantestdeveloper** [comment]
@martianatwork  yes I am using token to call API in peatio,after calling API getting errors 

Started POST "/api/v2/sessions" for ::1 at 2018-12-01 16:01:32 +0530
Parameters: {"token "=>"eyJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1NDUyMTM2ODQsImV4cCI6MTU0NTIyODA4NCwic3ViIjoic22cxHejFx25Fz6bCyFBhpC5wMLz18ihJprP76Yx2KXFxMyVXK9grdF6Q4rnLzVamZatL0zJn10FEiZXEpQDpzkZTqVWiiTDBWSNc5Mc28jewpBIRXQXztv6tjlyqteUJW2eU9k1OYyHNJ-VB04z6f4dof97dnlfXk6HEhhTZ_noVE_tkZA6nMxbdCN9ZkjprZDiXOCq3mpQpYUhS3m_Y5T669SJ3wh3xND5AUOOwsHP5g"}
Completed 500 Internal Server Error in 1.09ms (Views: 1.09ms | DB: 0ms)

Warning! ActionDispatch::Session::RedisStore failed to save session. Content dropped.

with API response code 2001 as mentioned  document of API.
