### ISSUE TITLE
Transaction successful but doesn't look ethereum local

### ISSUE THREAD

**Issue by UfukAntep** [openware/peatio#1957]
Transaction successful but doesn't look ethereum local. Please see the 2 pictures below

![alt text](https://i.imgyukle.com/2019/01/04/1Jsr0.png)

![alt text](https://i.imgyukle.com/2019/01/04/1Jplx.png)

**Comment by martianatwork** [comment]
Daemons are not running

**Comment by UfukAntep** [comment]
make daemons running :/

**Comment by UfukAntep** [comment]
I did make daemons. But the problem is the same
