### ISSUE TITLE
market.id  may cause conflects between pairs like usd/trst and usdt/rst

### ISSUE THREAD

**Issue by hardywu** [openware/peatio#1962]
Have the coin name `rst` taken someday, the market.id would have an conflict for pairs like usd/trst and usdt/rst. 

I suggest adding slash "/" or ":" to market.id

**Comment by huuhait** [comment]
on url trading-ui?

**Comment by shal** [comment]
Hi @hardywu,

You can always do mirror pair, use `rst/usdt` instead of `usdt/rst`.
