### ISSUE TITLE
how to start slanger services for local development 

### ISSUE THREAD

**Issue by nantestdeveloper** [openware/peatio#1965]
how to start  `slanger/pusher services `for peatio in development env.

Beacuse in trading dashboard getting` errors for websocket` and not auto updating  dashboard for trades and order. I'm using peatio 1.8.58 version. 
![screenshot from 2019-01-09 13-31-35](https://user-images.githubusercontent.com/33446749/50885202-0f970380-1413-11e9-8967-0b1f71ec9ccd.png)

**Comment by shal** [comment]
Hi, unfortunately `slanger/pusher` is already deprecated in favor of `ranger`.

Here are
- Docker image for slanger: https://hub.docker.com/r/rubykube/slanger.
- Pusher documentation: https://pusher.com/docs/
