### ISSUE TITLE
BitGO, setup

### ISSUE THREAD

**Issue by not-a-dev0** [openware/peatio#1971]
Is there a more detailed guide for bitgo setup?

**Comment by shal** [comment]
Hey @not-a-dev0, 

Unfortunately we don't have detailed bitgo setup guide.

It is not needed, because you just need to create wallets on BitGo and then add credentials into peatio seed files.

**Comment by streetcrypto7** [comment]
@shal can you tell me how to add those.credentials?

**Comment by lekabyte** [comment]
even some informations about how to set it up would be great.

for instance blockchain -> client bitgo -> server ?

what to put there...

**Comment by mnaichuk** [comment]
Hello @lekabyte there is the documentation for wallet configuration
https://github.com/openware/peatio-contrib/tree/master/peatio-bitgo/docs
We detect deposits via webhooks and create transactions with WalletService.
