### ISSUE TITLE
FIAT DEPOSIT CLAIM REFERENCE NUMBER OPTION

### ISSUE THREAD

**Issue by codeqpay** [openware/peatio#1974]
ADD CLAIM REFERENCE NUMBER OPTION IN USER PANEL AFTER THAT ADMIN JUST NEED TO VERIFY THAT DEPOSIT NO NEED TO TYPE IT.

**Comment by shal** [comment]
Hey @coinsure,

Unfortunately, this is not possible. 
Admin required to know the amount of deposit, this is one of extra security steps.
