### ISSUE TITLE
Block height in admin panel not increasing. Version v1.9.1-rc.23

### ISSUE THREAD

**Issue by soxar** [openware/peatio#1983]
I added altcoin which is base from BITCOIN , i notice that the block height in admin panel is not moving anymore it's already 1 day passed but the height still not moving . coin daemon is running , all daemon running , coin daemon full synced ,
i am able to generate wallet address only problem is the height not increasing in admin panel , is it a bug ? please help Thank you so much

**Comment by nantestdeveloper** [comment]
@soxar  Are you able fix this issue for bitcoind? height of btc is updating?

**Comment by shal** [comment]
@soxar It means there is an issue with connection to your node or it is nor fully synced. 
Take a look at blockchain daemon.

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
