### ISSUE TITLE
mac os rails server

### ISSUE THREAD

**Issue by nazarpechka** [openware/peatio#1987]
When starting rails server on mac os,
`JWT_PUBLIC_KEY=$(cat config/secrets/rsa-key.pub| base64 -w0) rails s -b0.0.0.0`
should be changed to
`JWT_PUBLIC_KEY=$(cat config/secrets/rsa-key.pub| base64 -b0) rails s -b0.0.0.0`

**Comment by shal** [comment]
Well done @nazarpechka, Could you submit a PR ?
