### ISSUE TITLE
Missing translation at «Trade»

### ISSUE THREAD

**Issue by yivo** [openware/peatio#199]
<img width="404" alt="screen shot 2017-12-27 at 6 04 30 pm" src="https://user-images.githubusercontent.com/7421323/34386271-8201b300-eb30-11e7-86de-e42e6e6b2077.png">

**Comment by emasiuk** [comment]
@yivo I don't have this changes(fetched and rebased on master) and when i change in translation from renminbi to dollar i have some errors
![deepinscreenshot_select-area_20171229105842](https://user-images.githubusercontent.com/26141524/34433398-b9d08ba0-ec87-11e7-8c0a-82ccd91bcea3.png)

**Comment by yivo** [comment]
Closed by #209.
