### ISSUE TITLE
need help on POST api

### ISSUE THREAD

**Issue by huuhait** [openware/peatio#2003]
![image](https://user-images.githubusercontent.com/40519768/51430977-44962800-1c55-11e9-9852-bbe6c02557dc.png)

LINK: https://pastebin.com/mdx3pwx5

I'm using peatio 1.9
Thanks for the help :D

**Comment by mnaichuk** [comment]
Hello @huuhait. Check peatio logs when perform this request.

**Comment by huuhait** [comment]
sloved
sorry i forgot close issue :D
