### ISSUE TITLE
"Make Test" Error (wallets.spec.js)

### ISSUE THREAD

**Issue by UfukAntep** [openware/peatio#2006]
Transaction successful but doesn't look ethereum local. That's why. I did an "make test" to test the system. But gives this error.

![alt text](https://i.imgyukle.com/2019/01/21/qdvoe.png)
![alt text](https://i.imgyukle.com/2019/01/21/qdzLN.png)

**Comment by not-a-dev0** [comment]
What software are you using, that does this?

**Comment by UfukAntep** [comment]
Rubykube Workbench -> https://github.com/rubykube/workbench

**Comment by not-a-dev0** [comment]
@UfukAntep I apologize. I meant this UI 
![screen shot 2019-01-24 at 1 13 33 am](https://user-images.githubusercontent.com/46028023/51661063-4a517d80-1f75-11e9-9a65-3ff41d940d6b.png)

**Comment by UfukAntep** [comment]
I'm running a "make test" in my workbench file. (I am using ubuntu 14.04 as operating system)

**Comment by mnaichuk** [comment]
This issue related to workbench repo. Workbench is no longer supported, you can try microkube with new rubykube stack.
