### ISSUE TITLE
Logs should go to stdout/stderr especially when running in Docker/Kubernetes

### ISSUE THREAD

**Issue by ApsOps** [openware/peatio#201]

**Comment by yivo** [comment]
Hello @ApsOps,

I agree with you. We should symlink `log/production.log` to STDOUT/STDERR Linux devices in Dockerfile like so:

```
 # Redirect NGINX logs to standard streams.
 && ln -sf /dev/stdout /var/log/nginx/access.log \
 && ln -sf /dev/stderr /var/log/nginx/error.log \
```

**Comment by ApsOps** [comment]
Hi @yivo . I'm kinda against the symlink approach since files keep increasing inside the container.
Isn't there a way to directly write ROR logs to stdout/stderr? That would be better IMHO 🙂

**Comment by yivo** [comment]
@ApsOps Configuring `Rails.logger` to output to STDOUT is also possible. Actually, `/dev/stdout` & `/dev/stderr` are virtual devices (not real files) so you will not stuck with large log files (nothing will be written inside container). Docker daemon will receive STDOUT/STDERR output and then you can decide what to do with it: you can limit the size, you can choose logger driver and so on. Check Docker docs.

**Comment by ApsOps** [comment]
Ah, right. Makes sense 👍

**Comment by yivo** [comment]
Cool. We will work on it :)

**Comment by yivo** [comment]
@ApsOps Fixed in https://github.com/rubykube/peatio/commit/00b8c0bdb807e231c0309122b665a79e4b9f7440
