### ISSUE TITLE
Display all Deposits and Withdraws in admin on one page

### ISSUE THREAD

**Issue by jonn4y** [openware/peatio#2025]
Is it possible to create an 'All deposits' and 'All Withdraws' page in the admin panel such as /admin/deposits/all

displaying all the deposits and all withdrawals (limited to around 25 results or so) so you don't have to go into each listed currency checking over them?

**Comment by shal** [comment]
Hi @jonn4y,

Unfortunately this feature is not possible, we will drop Admin UI soon.
