### ISSUE TITLE
on Funds tab getting error

### ISSUE THREAD

**Issue by nantestdeveloper** [openware/peatio#2027]
Faraday::Error in Private::FundsController#index
-- HTTP 401 Unauthorized -- -- Request URL -- http://127.0.0.1:18332/ -- Request Method -- POST -- Request headers -- {"Authorization":"SECRET","User-Agent":"Faraday v0.14.0","Accept":"application/json","Content-Type":"application/json"} -- Request body -- {"jsonrpc":"1.0","method":"getblockcount","params":[]} -- Response headers -- {"www-authenticate":"Basic realm=\"jsonrpc\"","content-length":"0","content-type":"text/html; charset=ISO-8859-1","connection":"close"} -- Response body --

**Comment by ysv** [comment]
@nantestdevoloper did you setup bitcoin node locally ?

**Comment by nantestdeveloper** [comment]
@ysv  yes and its working properly.
