### ISSUE TITLE
JWT Authentication troubleshooting 

### ISSUE THREAD

**Issue by ianeinser** [openware/peatio#2031]
Hi @ysv @mod  ,

I have battled with this bug for days, but i cannot find the solution. Why are the users admin@barong.io and john@barong.io not created in peatio production? 

at barong side

D, [2019-01-30T05:17:21.034494 #1] DEBUG -- :   User Update (1.1ms)  UPDATE `users` SET `level` = 3, `updated_at` = '2019-01-30 05:17:21' WHERE `users`.`id` = 2
D, [2019-01-30T05:17:21.077982 #1] DEBUG -- :    (42.3ms)  COMMIT
D, [2019-01-30T05:17:21.086735 #1] DEBUG -- : 
Produced new event at 2019-01-30 05:17:21 UTC: 
name    = system.document.verified
payload = {"payload":"eyJpc3MiOiJiYXJvbmciLCJqdGkiOiJlMWFkNzlmOC03ODBkLTQ0NzctYjJiOC00NzZmMGI0ZjA5OWEiLCJpYXQiOjE1NDg4MjU0NDEsImV4cCI6MTU0ODgyNTUwMSwiZXZlbnQiOnsidWlkIjoiSUQ2NzIxQUI5QzY3IiwiZW1haWwiOiJqb2huQGJhcm9uZy5pbyIsIm5hbWUiOiJzeXN0ZW0uZG9jdW1lbnQudmVyaWZpZWQifX0","signatures":[{"protected":"eyJhbGciOiJSUzI1NiJ9","header":{"kid":"barong"},"signature":"oJ9JIwD_yQ94xYKZffqxzfExieT3WTkMf3lRW5NCCLUUsONUKCWiDbcMn55KshdViyp79Wv4WZetTegMRUF2QKxY3Z7YH2FXkQZncrAqpOrobmfkWFh4bGSfMF78Q5wrwcpGb99cxQ6eh20cbRoJ1eCvN5LdT_cB4qmNlD9_nfaZb-353h0hCBUf4Rh8ks2sSTo0f-QrZdNqo0nSP8YAfsLyR_ulEEI5N-Uing23pC3o0DGFzN8XnC3BRRerydMC4FXPCAVZsa5FhcsKeuBN14TlfI_WOUtxzlWiubyl_rhEmU5lQpjeyi7Ne035KqYl9rIImRTqd-ZkyGDObPchZQ"}]}

D, [2019-01-30T05:17:21.086944 #1] DEBUG -- : 
Publishing document.verified (routing key) to barong.events.system (exchange name).

Seeded users:
Email: admin@barong.io, password: 0lDHd9ufs9t@
Email: john@barong.io, password: Am8icnzEI3d!

at peatio side

Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.3-p105), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: production
WARNING: API_CORS_ORIGIN is set to '*'
WARNING: Incorect or missing API_CORS_MAX_AGE value. Using default value: 3600
* Listening on tcp://0.0.0.0:8000
Use Ctrl-C to stop
Started GET "/api/v2/account/balances" for 172.20.0.10 at 2019-01-30 09:35:59 +0000
Started GET "/api/v2/public/currencies" for 172.20.0.10 at 2019-01-30 09:35:59 +0000
  Parameters: {}
Completed 500 Internal Server Error in 5.18ms (Views: 5.18ms | DB: 0ms)
#<Peatio::Auth::Error: 2001: Authorization failed: Failed to decode and verify JWT: Signature verification raised>
/opt/vendor/bundle/ruby/2.5.0/gems/peatio-0.4.5/lib/peatio/auth/jwt_authenticator.rb:124:in `rescue in decode_and_verify_token'
/opt/vendor/bundle/ruby/2.5.0/gems/peatio-0.4.5/lib/peatio/auth/jwt_authenticator.rb:117:in `decode_and_verify_token'
/opt/vendor/bundle/ruby/2.5.0/gems/peatio-0.4.5/lib/peatio/auth/jwt_authenticator.rb:93:in `authenticate!'
/home/app/lib/authorization/bearer.rb:13:in `authenticate!'
/home/app/app/api/v2/auth/jwt_authenticator.rb:23:in `authenticate'
/home/app/app/api/v2/auth/middleware.rb:12:in `before'
/opt/vendor/bundle/ruby/2.5.0/gems/grape-1.1.0/lib/grape/middleware/base.rb:29:in `call!'
/opt/vendor/bundle/ruby/2.5.0/gems/grape-1.1.0/lib/grape/middleware/base.rb:24:in `call'

Regards,

Ian

**Comment by ysv** [comment]
@ianeinser hello!
Actually the users are not synced between Peatio and Barong 
Users are created in Peatio side on the first request with valid JWT

But issue you have faced is because of wrong JWT_PUBLIC_KEY in peatio which is not a pair with Barong private key.
You can use this script to fetch right JWT_PUBLIC_KEY https://gist.github.com/ysv/9d3daae36f341108a85cc2a6c6d759c5 run it from barong rails console

**Comment by ysv** [comment]
@ianeinser Also it's strange that you have got an authorization problem for public endpoint /api/v2/public/currencies

**Comment by ianeinser** [comment]
@ysv yes you are right. But the JWT_PUBLIC_KEY is automatically rendered by lib/microkube/renderer.rake

The JWT_PUBLIC_KEY in both /config/peatio.env and /config/barong.env of microkube is generated by renderer.rake

Can you check? I know how to fix but it is better that Helios does that otherwise i should do a PR. 

No. Public endpoint /public/currencies  works fine but /account/balances and FETCH_WALLET_FAIL

**Comment by ianeinser** [comment]
I found the bug and filed the patch to Yehor in telegram channel
