### ISSUE TITLE
Futures market support

### ISSUE THREAD

**Issue by ianeinser** [openware/peatio#2033]
@ysv any comments

_Originally posted by @hardywu in https://github.com/rubykube/peatio/pull/1884#issuecomment-458119858_s

Bro,

There are conflicting files, would you please check it. I am interested in this feature and would be very happy to see it in rubykube. The futures market is huge

**Comment by ysv** [comment]
@ianeinser I will review it as soon as I have some time
We are working on finalize and stabilization of 2.0 now

I think this feature will be added in 2.1

**Comment by ianeinser** [comment]
Hello @ysv,
when will this be merged? Need this product badly

@hardywu can we use this to create perpetual contract and CFD too?
