### ISSUE TITLE
Link is absolute in application.yml

### ISSUE THREAD

**Issue by sd189** [openware/peatio#2038]
In application.yml 
https://github.com/rubykube/peatio/blob/master/config/templates/application.yml.erb#L89

endpoint `api/v2/members/me` dosen't exists any more

**Comment by huuhait** [comment]
what version are u using?

**Comment by sd189** [comment]
latest `2.0.20-alpha`

**Comment by huuhait** [comment]
read it
https://github.com/rubykube/peatio/blob/master/docs/api/peatio_user_api_v2.md

**Comment by ysv** [comment]
@sd189 Agree 
could you submit pr ?

**Comment by sd189** [comment]
@ysv is the plan to add `members/me` again to the api or just remove it from the docs?

**Comment by ysv** [comment]
@sd189  Just rename to another route which exists in current API version
