### ISSUE TITLE
TRON and TRX-10 token support 

### ISSUE THREAD

**Issue by koinkaro** [openware/peatio#2040]
Implementation of `TRON` and `TRX-10` currencies support.
Useful links:
- [Full API documentation](https://github.com/tronscan/tronscan-frontend/blob/dev2019/document/api.md)
- https://github.com/tronprotocol/Documentation/blob/master/TRX/Tron-exchange.md
- https://developers.tron.network/docs/tron-grid-intro

**Comment by ulshare** [comment]
https://developers.tron.network/docs/tron-grid-intro

**Comment by ulshare** [comment]
@mod @ysv and @mnaichuk

**Comment by ulshare** [comment]
full api documentation https://github.com/tronscan/tronscan-frontend/blob/dev2019/document/api.md

**Comment by shal** [comment]
Hey @ulshare, I edited your issue, because it was messy.

We will get back to this feature suggestion in some time, but for now it is postponed.

**Comment by crackfoo** [comment]
Any more thoughts on adding TRC10/20?

Thanks
