### ISSUE TITLE
Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by AnkitRathore175** [openware/peatio#2042]
Hi,
I m facing this issue on new markets only, during the order creations,
any help?
Thanks

```
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)
```

**Comment by ysv** [comment]
@AnkitRathore175 Did you use peatio-trading UI ?

**Comment by AnkitRathore175** [comment]
Hi @ysv 
sorry for late reply
yes i m using peatio-trading UI 
it's not allowing me to create order and order cancellation due to same issue
