### ISSUE TITLE
eth and erc20 token withdraw no working

### ISSUE THREAD

**Issue by AkashiFeng** [openware/peatio#2049]
Hello
I have the problem of Ethereum and ERC20 token withdraw parts.
It can't withdraw to select address and all coins move to Hot wallet.
So the coins is "Frozen" state.
How to solve this problem?

**Comment by shal** [comment]
Hi @AkashiHidaka,

Sorry, your query is not clear, can you make a video/photo record and put more details?

**Comment by AkashiFeng** [comment]
Yes , I will add print screen image.
![image](https://user-images.githubusercontent.com/44053447/53194513-7d5b5f80-364e-11e9-9091-7f24dd443485.png)
![image](https://user-images.githubusercontent.com/44053447/53194624-c3182800-364e-11e9-8ac8-4e34e8cdf43c.png)

I added frontend and backend panel print screen image.
If you want , I can provide credentials and you can check of it.

**Comment by shal** [comment]
Ah, it is `processing` state. Yeah, there was an issue in 1.9 with this. This is already solved in `1-9-stable`.

**Comment by AkashiFeng** [comment]
So it is need update peatio codes to 1-9-stable version?
other part no need update?

**Comment by AkashiFeng** [comment]
Now I using workbench and in there peatio module will change?

**Comment by shal** [comment]
I guess updating to `1-9-stable` will not solve your problem, because this withdraw was already created with broken version. Let's wait for @mnaichuk comment

**Comment by AkashiFeng** [comment]
I hope quickly solve this problem.
I will wait.
Thanks

**Comment by mnaichuk** [comment]
Hi @AkashiHidaka 
Please check `withdraw_coin` daemon logs it can be some errors there. And this bug can be related to blockchain. You can reject this withdraw and increase gas_limit/price in currency configs and try again.

**Comment by AkashiFeng** [comment]
How to check the logs data?

**Comment by mnaichuk** [comment]
docker logs `container id`

**Comment by AkashiFeng** [comment]
![image](https://user-images.githubusercontent.com/44053447/53234360-593d6400-36ca-11e9-82f3-877a593ab27f.png)
I can't see of log

**Comment by mnaichuk** [comment]
`docker ps`, then find `container id` for `withdraw_coin daemon` (first column) and then check logs for this `container id`

**Comment by AkashiFeng** [comment]
I see this is and it is right?
![image](https://user-images.githubusercontent.com/44053447/53234735-29db2700-36cb-11e9-839f-e8b77cd72ca9.png)

**Comment by mnaichuk** [comment]
Please update peatio to 1-9-stable, reject this withdraw and try again.

**Comment by AkashiFeng** [comment]
Yes

**Comment by AkashiFeng** [comment]
Hello 
I updated 1-9-stable version and still no working of withdraw part.
I checked log data and it show mysql query and some texts.
In there other things is same and I will attach the withdraw relation part log data.

![image](https://user-images.githubusercontent.com/44053447/53293216-b6403380-380a-11e9-989f-28048a88e54b.png)
What is the reason of it?
I updated peatio to 1-9-stable version.
