### ISSUE TITLE
Question about withdraw API regarding the OTP

### ISSUE THREAD

**Issue by sd189** [openware/peatio#2059]
What are the steps to generate the OTP and pass it to the withdraw endpoint

https://github.com/rubykube/peatio/blob/master/docs/api/peatio_user_api_v2.md#accountwithdraws

**Comment by sd189** [comment]
I Installed the vault as a docker image 
and i accessed it api through the token in https://github.com/rubykube/peatio/blob/master/config/backend.yml#L67
i opened a pull request #2065 to add the backend.yml to .gitignore so i can set my own token

and fot the vault api you can follow functions here to generate the otp needed for the withdraw
https://www.vaultproject.io/api/secret/totp/index.html

**Comment by ysv** [comment]
@sd189 you need to use barong auth provider it will manage OTP and vault 
We need only validate code on peatio side

**Comment by martianatwork** [comment]
@ysv I feel like we should give an option to choose an otp validator, this will be used in cases where user wants an SMS OTP or in some cases where we dont use barong as auth provider.

**Comment by sd189** [comment]
@ysv actually i'm not using barong as auth provider i'm using my own auth provider
and as i mentioned before i managed to figure out how to generate the OTP correctly using the vault API
