### ISSUE TITLE
insuficient funds for gas*price + value

### ISSUE THREAD

**Issue by HafeezRai** [openware/peatio#2064]
hi I ma getting following error when withdraw ethereum 
in peatio 1.8 
Can anyone help in this problem?
<CoinAPI::Error: {"code"=>-32000, "message"=>"insufficient funds for gas * price + value"

**Comment by shal** [comment]
Hi @HafeezRai,

I guess your ethereum balance is too low to perform withdraw request.

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
