### ISSUE TITLE
Adding markets to funds page for each currency

### ISSUE THREAD

**Issue by brandonflowers** [openware/peatio#2067]
I know you are planning on removing the UI in future versions but just wondering if anyone knows how i could get the active markets for each currency and display them in accounts on the funds page like the example below or if someone wants to take this on as a little task.

<img width="375" alt="screenshot 2019-02-14 at 22 26 34" src="https://user-images.githubusercontent.com/47646648/52821803-d6078700-30a7-11e9-85ef-ab636f898d92.png">

Thanks in advance

**Comment by huuhait** [comment]
my:
![image](https://user-images.githubusercontent.com/40519768/52917471-8088df80-331e-11e9-81ff-9b089c8c3411.png)

**Comment by ysv** [comment]
@brandonflowers using Peatio API you can implement this feature in custom FE

**Comment by brandonflowers** [comment]
@ysv Sorry i dont understand what you mean by FE? 
im using 1.9 and i have tried to pull the markets with
`@markets			 = Market.enabled.sort`
inside funds_controller.rb

not sure if im on the right track or if you mean i should use the api functions located in /peatio/app/api


Thanks
