### ISSUE TITLE
Dynamic Withdrawal Limit

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#2073]
This should close #1950 
Most of the Exchanges has 3 types of withdrawal limit structure.

1. Email verified: ex 2BTC, if user has email verified then he can withdraw upto 2BTC each day
2. KYC Verified: ex 10BTC, if user has kyc verified then he can withdraw upto 10BTC each day
3. Custom: ex 20BTC, admin can set the withdrawal limit for the user

The idea is simple, we use labels like barong.
we can use a label with key being the level and time in hours and value being the limit, ex. `key:value = level3_24h:10`.
if user contains a label then this label will be used to calculate the limit.

this way we can create multiple withdrawal limits for the same level or user but a different time.

**Comment by shal** [comment]
Hi @martianatwork,

I like this idea, we will need to discuss and define priority for this feature.

**Comment by endofthepain** [comment]
hope can be realize ✌️

**Comment by martianatwork** [comment]
Hey @shal let me know your inputs
