### ISSUE TITLE
No websockets for Balance, Deposit, Withdraw

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#2074]

**Comment by ysv** [comment]
@martianatwork nice point
We will add this in 2.1

**Comment by ianeinser** [comment]
And also no markets, currencies and market depth.

**Comment by martianatwork** [comment]
@ysv Looks like we have private WebSocket for `deposit_address` but it is not documented.
I will create a PR with the required changes. Currently im testing  Account & Deposit WebSocket.

**Comment by ianeinser** [comment]
@ysv we suggest that you also add TRANSFER to complete the trio namely DEPOSIT, TRANSFER and WITHDRAW

**Comment by martianatwork** [comment]
@ianeinser Transfer as in?

**Comment by ianeinser** [comment]
@martianatwork as in #2023. I suggest that transfer function not be done through management api because the fund is still inside the system.. it is the withdraw which should be done through management api and preferrably with multi-sig

**Comment by ianeinser** [comment]
@ysv would it be possible to include buy/sell too for ranger to support, then we can do bidirectional websocket connection. Or buy/sell should be provided as RESTful only?

**Comment by ianeinser** [comment]
would like to get user activities and activities delivered through ranger..

**Comment by martianatwork** [comment]
@ianeinser I dont think that we need the transfers as WebSocket those are for management and not for user. 

For user we just need Deposit, Withdraw, Account (balance, locker, payment address), Order, Trades, Tickers, K line should be enough.

**Comment by ianeinser** [comment]
> @ianeinser I dont think that we need the transfers as WebSocket those are for management and not for user.
> 
> For user we just need Deposit, Withdraw, Account (balance, locker, payment address), Order, Trades, Tickers, K line should be enough.
@martianatwork 
what about market depth? it is available in user api

**Comment by martianatwork** [comment]
@ysv Hey any plans to implement this?

**Comment by TheHolyRoger** [comment]
No news on this balance websocket feed?

**Comment by mnaichuk** [comment]
Implemented in Finex
