### ISSUE TITLE
How can I change the address of the admin wallet?

### ISSUE THREAD

**Issue by UfukAntep** [openware/peatio#2082]
How can I change the address of the admin wallet? Where is this address?

![alt text](https://i.imgyukle.com/2019/02/19/8noxH.png)

**Comment by shal** [comment]
Hi @UfukAntep,

Admin user is **same** as all users on the platform, except one detail: *He has access to admin panel*.
You can't change generated address for admin user.

You can change currency wallet settings in admin panel.
