### ISSUE TITLE
Withdraw 

### ISSUE THREAD

**Issue by vpavlikk** [openware/peatio#2084]
I can reject withdraw from admin panel when it has already appeared in blockchain

**Comment by endofthepain** [comment]
no you cant because your transaction has appeared in blockchain

**Comment by shal** [comment]
@vpavlikk Could you send us video/photo approval of this bug please?

**Comment by vpavlikk** [comment]
https://streamable.com/eggqu
https://streamable.com/g57w5

**Comment by martianatwork** [comment]
@shal i can confirm that this bug is present, 
The issue is here:
https://github.com/rubykube/peatio/blob/e0cc1f0f4f3c1b97cc70a35bb34f3f21695a3908/app/models/withdraw.rb#L82

Withdraws with confirming status should not be rejected.
it may make sense for fiat but not for crypto.

**Comment by ysv** [comment]
closed in #2135
