### ISSUE TITLE
Integrate market order

### ISSUE THREAD

**Issue by rastislavcore** [openware/peatio#2097]
Some plans for "market order" functionality?

Definition:
A market order is a buy or sell order to be executed immediately at the current market prices. As long as there are willing sellers and buyers, market orders are filled. Market orders are used when the certainty of execution is a priority over the price of execution. A market order is the simplest of the order types.

Most exchanges have it as standard.

**Comment by mod** [comment]
Hello, Market order is already supported.

**Comment by nantestdeveloper** [comment]
@mod To make  market type order to sell and buy work, what are the changes I have to do get it work in peatio-trading-ui?

I think limit order type is already integrated.
I added new " bid and ask" order with price and amount fields and order type "market".
In peatio getting error while selling coin with market type order
raise "Market is not deep enough" unless expected_volume.zero?
