### ISSUE TITLE
Clean up database seeds, generate admin account from Helm

### ISSUE THREAD

**Issue by yivo** [openware/peatio#21]

**Comment by mod** [comment]
About Database seed the file is irrelevant, seeds are for production records such as a list of product, or countries...

Process for creation of Admin user can be through seeds using information from Environment variable or application.yml

regarding helm, helm can generate the admin password and mount it as ENV variable for the seed, I still consider the admin should change the password after anyway.

**Comment by yivo** [comment]
Solved for enterprise clients.
