### ISSUE TITLE
how to use rubykube without using docker 

### ISSUE THREAD

**Issue by guru260** [openware/peatio#2102]
I tried to install rubykube-peatio, barong and peatio-trading-ui in development mode as the following,
`peatio setup:
-------------
git clone https://github.com/rubykube/peatio.git
bundle install
Changed DB password at config/database.yml
./bin/setup
god -c lib/daemons/daemons.god
JWT_PUBLIC_KEY=$(cat config/secrets/rsa-key.pub| base64 -w0) rails s -b0.0.0.0

peatio-trading-ui setup:
------------------------
I followed this guide https://github.com/not-a-dev0/peatio-trading-ui-guide/blob/master/Setup%20guide for peatio-trading-ui setup.

git clone https://github.com/rubykube/peatio-trading-ui.git
git checkout 1-9-stable
bin/init_config
I have changed platform and front-end url config/application.yml as mentioned below
PLATFORM_ROOT_URL: http://localhost:3000 #peatio is running in 3000 
FRONTEND_ROOT_URL: http://localhost:4000 #frontend is running in 4000
bundle exec rake tmp:create yarn:install
bundle exec rails server -p 4000

barong setup:
-------------
bin/init_config
bundle exec rake db:create db:migrate
yarn install
bundle exec rails server -p 8001
`
But If I try to access http://localhost:4000 or http://localhost:3000, I get the default rails page. How to make this work?

**Comment by zacsan** [comment]
Did you solve it?
