### ISSUE TITLE
TypeError: wrong argument type Hash (expected String)

### ISSUE THREAD

**Issue by guru260** [openware/peatio#2107]
I am getting the following error when running Rake::Task['seed:markets'].invoke
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
/home/ /.rvm/gems/ruby-2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)   (0.2ms)  BEGIN
  Market Exists (0.3ms)  SELECT  1 AS one FROM `markets` WHERE `markets`.`id` = 'usdbtc' LIMIT 1
  Market Exists (0.4ms)  SELECT  1 AS one FROM `markets` WHERE `markets`.`id` = 'usdbtc' LIMIT 1
   (0.4ms)  SELECT `currencies`.`id` FROM `currencies`
   (0.3ms)  SELECT `currencies`.`id` FROM `currencies`
  Currency Load (0.4ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 'btc' LIMIT 1 FOR UPDATE
   (0.2ms)  ROLLBACK
rake aborted!
TypeError: wrong argument type Hash (expected String)
/home/ /.rvm/gems/ruby-2.6.0/gems/structured_warnings-0.3.0/lib/structured_warnings/warning.rb:62:in `warn'
/home/ /.rvm/gems/ruby-2.6.0/gems/structured_warnings-0.3.0/lib/structured_warnings/warning.rb:62:in `warn'
/home/ /.rvm/gems/ruby-2.6.0/gems/structured_warnings-0.3.0/lib/structured_warnings/kernel.rb:3:in `warn'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `each'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `to_a'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `exec_query'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/querying.rb:39:in `find_by_sql'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation.rb:639:in `exec_queries'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation.rb:515:in `load'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation.rb:243:in `to_a'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation/finder_methods.rb:475:in `find_take'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation/finder_methods.rb:105:in `take'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation/finder_methods.rb:84:in `find_by'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/querying.rb:7:in `find_by'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/core.rb:163:in `find_by'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/dynamic_matchers.rb:70:in `find_by_id'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/dynamic_matchers.rb:24:in `method_missing'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation/delegation.rb:94:in `public_send'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation/delegation.rb:94:in `block in method_missing'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation.rb:302:in `scoping'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/relation/delegation.rb:94:in `method_missing'
/home/ /hack/delete/bkup/peatio/app/models/market.rb:123:in `block in units_must_be_enabled'
/home/ /hack/delete/bkup/peatio/app/models/market.rb:122:in `each'
/home/ /hack/delete/bkup/peatio/app/models/market.rb:122:in `units_must_be_enabled'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:182:in `block in conditional'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:504:in `block in call'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:504:in `each'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:504:in `call'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'
/home/ /.rvm/gems/ruby-2.6.0/gems/activemodel-4.2.11/lib/active_model/validations.rb:399:in `run_validations!'
/home/ /.rvm/gems/ruby-2.6.0/gems/activemodel-4.2.11/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:117:in `call'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:505:in `call'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/ /.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
/home/ /.rvm/gems/ruby-2.6.0/gems/activemodel-4.2.11/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
/home/ /.rvm/gems/ruby-2.6.0/gems/activemodel-4.2.11/lib/active_model/validations.rb:338:in `valid?'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/validations.rb:58:in `valid?'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/validations.rb:83:in `perform_validations'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/validations.rb:43:in `save!'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/transactions.rb:291:in `block in save!'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/transactions.rb:220:in `transaction'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/transactions.rb:291:in `save!'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/persistence.rb:51:in `create!'
/home/ /hack/delete/bkup/peatio/lib/tasks/seed.rake:31:in `block (4 levels) in <top (required)>'
/home/ /hack/delete/bkup/peatio/lib/tasks/seed.rake:29:in `each'
/home/ /hack/delete/bkup/peatio/lib/tasks/seed.rake:29:in `block (3 levels) in <top (required)>'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/ /.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/transactions.rb:220:in `transaction'
/home/ /hack/delete/bkup/peatio/lib/tasks/seed.rake:28:in `block (2 levels) in <top (required)>'
Tasks: TOP => seed:markets
(See full trace by running task with --trace)

**Comment by mnaichuk** [comment]
Hi, @guru260! Use ruby 2.5.x.
