### ISSUE TITLE
Deposit address daemon breaks

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#2120]
The deposit address daemon breaks and dosent generate payment address if there are blockchain with incorrect url or config.

Steps to reproduce:
1. Add 4 currencies(BTC, ETH, LTC, DASH in the same order
2. Add blockchains & wallets for BTC & LTC and use dummy URLs for ETH & DASH
3. Request for address, 
4. BTC address will be generated but as ETH has the wrong URL the daemon will throw an error and it won't continue to generate further address i.e LTC & DASH

**Comment by mnaichuk** [comment]
Hi @martianatwork. Yes, we know about this issue, will fix it in next versions, thank you!

**Comment by martianatwork** [comment]
@mnaichuk is it fixed?

**Comment by crackfoo** [comment]
Seems DASH still isn't working properly.  The blockchain runner reports no errors but tip is never updated and user deposit addresses are not getting created...
