### ISSUE TITLE
Peatio and Ethereum/client-go:stable 

### ISSUE THREAD

**Issue by UfukAntep** [openware/peatio#2122]
Hello Everyone,

I have these errors. That's why it's not working Funds Panel, is it?

![alt text](https://i.imgyukle.com/2019/01/04/1Jsr0.png)

### peatio log
![image](https://user-images.githubusercontent.com/28463089/54197734-c710ca80-44d5-11e9-99e9-c3334dd12dfb.png)

### ethereum/client-go:stable log
![image](https://user-images.githubusercontent.com/28463089/54197803-ef98c480-44d5-11e9-832c-256d67128030.png)

**Comment by legends420** [comment]
the first image is only because you did not add trst.svg file for logo

**Comment by UfukAntep** [comment]
Bitcoin and ethereum seems 0

**Comment by martianatwork** [comment]
Your chain is invalid check the chain id and resync the chain

**Comment by UfukAntep** [comment]
Do you know what should be written in bitcoin and ethereum? 

Example: Ethereum Rinkeby
![image](https://user-images.githubusercontent.com/28463089/55400437-8cd79d80-5556-11e9-9d39-09f293f5a35d.png)

**Comment by mnaichuk** [comment]
Hello @UfukAntep. This issue related to your ethereum node and it configs.
