### ISSUE TITLE
Retrun only coin withdraws it should return any currency withdraw history

### ISSUE THREAD

**Issue by HafeezRai** [openware/peatio#2128]
https://github.com/rubykube/peatio/blob/6d8f57b24d4420928677e707c01a45b9c04614f6/app/api/v2/account/withdraws.rb#L17

Please change it to 
values: { value: -> { Currency.enabled.codes(bothcase: true) }, message: 'account.currency.doesnt_exist'},

**Comment by mnaichuk** [comment]
Hi @HafeezRai, you are right! We will change it.

**Comment by ysv** [comment]
@mnaichuk @HafeezRai @msembinelli
I think what we need to update error message for post '/withdraws' also:
1. If currency doesn't exist return account.currency.doesnt_exist
2. If fiat currency return account.currency.non_crypto
