### ISSUE TITLE
My money appears in the "admin panel", but the money don't appear "funds panel"

### ISSUE THREAD

**Issue by UfukAntep** [openware/peatio#2137]
Hello,

My money appears in the "admin panel", but the moneyt don't appear "funds panel"

![image](https://user-images.githubusercontent.com/28463089/54977565-ccc6df80-4fae-11e9-9c00-a98fbcb24946.png)

![image](https://user-images.githubusercontent.com/28463089/54977508-96896000-4fae-11e9-9354-dbd3e8fc64fd.png)

**Comment by dagnyc** [comment]
Can anyone help with this please? I have the same issue

**Comment by mnaichuk** [comment]
Hello @dagnyc and @UfukAntep, this funds may belong to another account, you can check Account balance db through rails console.
