### ISSUE TITLE
can't see sign in page

### ISSUE THREAD

**Issue by ahmedsalihh** [openware/peatio#2139]
hello

I've cloned the app, checkout to 2-0-stable version and executed the installation steps.everything was successful. But when I got to www.app.local I just get a page with peatio icon in it.

![Screenshot from 2019-03-26 14-01-56](https://user-images.githubusercontent.com/13359680/54992191-c72dc180-4fcf-11e9-81bd-a6a2e70631fb.png)

I can't see login page or any other page.

how can I see the login page?

**Comment by guru260** [comment]
I am facing the same problem. I do not know why It is not working in **2-0-stable**.  But It is working properly in **1-9-stable**.

**Comment by ahmedsalihh** [comment]
> I am facing the same problem. I do not know why It is not working in **2-0-stable**. But It is working properly in **1-9-stable**.

**Comment by ahmedsalihh** [comment]
hi @guru260 thank you for your answer.
 when i try to install 1-9-stable i couldnt execute one of the steps on installation instruction.
when i tried to execute `bundle exec rake yarn:install` I get below error.

> Don't know how to build task 'yarn:install' (See the list of available tasks with `rake --tasks`)

I've executed `rake --tasks` and actually there is no task like this.

do you have any suggestion or if you know what does `yarn:install` do can i execute this manually ?

**Comment by guru260** [comment]
@ahmedsalihh It seems like yarn is not installed in your machine. Install yarn and try. For installation refer [here](https://yarnpkg.com/en/docs/install#debian-stable)

**Comment by ahmedsalihh** [comment]
thank you @guru260 it worked now.
do you know how can we login as admin user ?

**Comment by guru260** [comment]
Hope you are using Barong. After completing barong setup, the console will show admin password. Otherwise reset yourself either forget password option in UI or using rails console.

**Comment by ahmedsalihh** [comment]
@guru260 so you're saying we also need to clone barong and and run it right ?
is there any version limitation on barong?
