### ISSUE TITLE
Is SlaveBook worker needed?

### ISSUE THREAD

**Issue by elias19r** [openware/peatio#2144]
Hi,

I've been playing with some Peatio fork for a while and I came up with an effort to remove SlaveBook worker because I think it may be not necessary to have and it slows the user experience when watching orderbooks in a trading UI.

I wrote an experimental branch (https://github.com/rubykube/peatio/pull/2143) making the necessary adjustments and removing `SlaveBook` worker based on changes I made in another fork. Unfortunately, I couldn't conclude RubyKube's Peatio setup yet to run the branch locally (I would appreciate any help with the development setup).

So, I'd like to know what you think about this subject, if we could work to speed up `SlaveBook` worker or if it isn't really needed and we could remove following along the lines shown in that branch.

**Comment by huuhait** [comment]
yeah SlaveBook very slow
your pull fixed it
