### ISSUE TITLE
Bitcoin Withdrawal Issue

### ISSUE THREAD

**Issue by endofthepain** [openware/peatio#2152]
Hi i ve gotten error when make a withdrawal request using management API and this error log of this problem

<img width="1220" alt="Screen Shot 2019-04-01 at 01 34 15" src="https://user-images.githubusercontent.com/11496089/55294140-7c290980-5428-11e9-82cb-3ad8b4792f7d.png">

**Comment by martianatwork** [comment]
Your blockchain address is wrong

**Comment by endofthepain** [comment]
ah i ll look it, thank you
