### ISSUE TITLE
Docker Setup for Production Environment

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#2154]
Hi All,

I want to setup Peatio in production envrionment using Docker. Can anybody please help me with the steps?

**Comment by sharmaabhishek2207** [comment]
Can anybody please help me?

**Comment by kaleemullah360** [comment]
setting up, Peatio, Barong and Trading UI is simple using docker container.
Docker does it all `installation/setup/settings` for you.

please view instruction [here](https://github.com/rubykube/workbench)

**Comment by blacklevel7** [comment]
Anybody was setup Peatio in **production** (Docker or Ubuntu)?:)

**Comment by peatioinstall** [comment]
Contact me in my telegram https://t.me/Poseidon_j
Thanks

**Comment by ruiandrada** [comment]
@blacklevel7 Yes, Docker and Kubernetes.
You can easy find me if look for my username.

**Comment by shingonoide** [comment]
@blacklevel7 Yes, Docker and Kubernetes.
You can easy find me if look for my username.
