### ISSUE TITLE
ERC20 Gas limit & Gas price Withdrawal bug

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#2155]
In Peatio (v2) admin panel we have Gas price and Gas limit for transaction fees in Ethereum BC, its working fine with ETH it self, but with ERC20 withdrawal you will have an issue with insufficient funds a lot.

STR:
1. Set up ERC20 currency with expected and sufficient gas price per transaction  
2. Set up Fee wallet in ETH and feed it with coins to pay fees
3. ERC20 Deposit/Hot/Warm wallet with Maximum Balance 0.0/0.5/1.0 respectively (Main idea to get deposit amount split between wallets, so check your Hot and Warm wallet for current balance) 
4. Make a deposit to a user deposit address in amount of 0.6+ 

Expected:
Now we should receive to user Deposit wallet amount that is equal to our Gas limit*Gas price in ETH from fee wallet, after what withdraw of ERC20 should happen to Hot and Warm wallets.

Actual:
We do receive Gas limit*Gas price in ETH from fee wallet, but the Collection process will not be continued, our deposit will be Skipped.

Reason:
The Fee we are expecting to use in ERC20 transaction are meant only for one withdrawal, instead we have splitted our deposit into two withdrawal operations and fee amount taken from the fee wallet will not be sufficient.

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
