### ISSUE TITLE
What does it mean *LOCKING_BUFFER_FACTOR*? Why do we use it?

### ISSUE THREAD

**Issue by VmpKalin** [openware/peatio#2181]
Why do we need to lock on 10% more?

![image](https://user-images.githubusercontent.com/25912915/56507499-25e04f80-652a-11e9-8630-9f47a8a7a1cd.png)

**Comment by martianatwork** [comment]
I think this is to have enough funds in account when the order type is market.

Am I correct? @ysv or @mod

**Comment by mnaichuk** [comment]
Hello @VmpKalin !
@martianatwork yes, you are right.
