### ISSUE TITLE
NoMethodError (undefined method `attributes' for nil:NilClass):

### ISSUE THREAD

**Issue by AnythingLinux** [openware/peatio#2196]
Ned help for NoMethodError  ubuntu 18.04 LTS 

NoMethodError (undefined method `attributes' for nil:NilClass):
  app/controllers/application_controller.rb:50:in `set_gon'

![Screenshot from 2019-05-05 01-35-47](https://user-images.githubusercontent.com/1058663/57183979-212a7c80-6ed6-11e9-9989-73029e91a934.png)
![Screenshot from 2019-05-05 01-36-20](https://user-images.githubusercontent.com/1058663/57183985-34d5e300-6ed6-11e9-8843-93a11ec4cb9e.png)
![Screenshot from 2019-05-05 01-36-36](https://user-images.githubusercontent.com/1058663/57183986-3bfcf100-6ed6-11e9-82e3-9e985a67d4fb.png)

**Comment by ruiandrada** [comment]
I guess you didn't not seed the database.

Give a try `rake db:seed`

**Comment by AnythingLinux** [comment]
after try rake db:seed

I got this

root@back:~/peatio-1-9-stable# rake db:seed
/usr/local/rvm/gems/ruby-2.5.3/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Ask unit is not included in the list, Bid unit is not included in the list
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/validations.rb:79:in `raise_record_invalid'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/validations.rb:43:in `save!'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:291:in `block in save!'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:291:in `save!'
/usr/local/rvm/gems/ruby-2.5.3/gems/scout_apm-2.4.24/lib/scout_apm/instruments/active_record.rb:378:in `save!'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/persistence.rb:51:in `create!'
/root/peatio-1-9-stable/lib/tasks/seed.rake:31:in `block (4 levels) in <top (required)>'
/root/peatio-1-9-stable/lib/tasks/seed.rake:29:in `each'
/root/peatio-1-9-stable/lib/tasks/seed.rake:29:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:220:in `transaction'
/root/peatio-1-9-stable/lib/tasks/seed.rake:28:in `block (2 levels) in <top (required)>'
/root/peatio-1-9-stable/db/seeds.rb:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/engine.rb:547:in `load_seed'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => seed:markets
(See full trace by running task with --trace)




![Screenshot from 2019-05-05 05-21-26](https://user-images.githubusercontent.com/1058663/57185860-abcea400-6ef5-11e9-8ccd-b2f99ba694b0.png)

**Comment by mnaichuk** [comment]
Hello @saydulk ! You got this error: `Validation failed: Ask unit is not included in the list, Bid unit is not included in the list`. This error raises when you try to create market with nonexistent currency.
try `.bin/init_config` and then rake db:create db:migrate db:seed.

**Comment by AnythingLinux** [comment]
@mnaichuk thanks for your reply I just did it what you says and get :

Tasks: TOP => seed:markets

![Screenshot from 2019-06-02 00-12-41](https://user-images.githubusercontent.com/1058663/58752121-45747b80-84cb-11e9-806a-84a928f41c93.png)
