### ISSUE TITLE
Remove built-in ticketing system

### ISSUE THREAD

**Issue by yivo** [openware/peatio#22]

**Comment by mod** [comment]
The problem is that before removing a feature we need to have the alternative ready.
Eventually a 3rd party solution with OAuth support.
There is also Rails Help desks systems or Redmine too.

**Comment by yivo** [comment]
@mod I think peatio customers will be happy with just simple support by the email. The current ticketing system is so poor (it allows only to send messages, that's all). Most of companies deploy their own website for support as they love it. 

BTW I think we will remove this feature in all cases since peatio is not a place for tickets. The question is when. Will we wait alternatives or start the work right now?

**Comment by yivo** [comment]
We will need to remove gem for it also, check #40

**Comment by dmk** [comment]
@mod we can use **RocketChat**'s livechat 😄

**Comment by yivo** [comment]
Progress in #222.

**Comment by yivo** [comment]
Closed via #222.
