### ISSUE TITLE
application.yml not seen on 1.9 stable tree

### ISSUE THREAD

**Issue by AnythingLinux** [openware/peatio#2202]
Hello, I don't see application.yml into 1.9 source tree please check https://github.com/rubykube/peatio/tree/master/config

![Screenshot from 2019-05-07 01-26-30](https://user-images.githubusercontent.com/1058663/57249780-a6916680-7067-11e9-9456-532d2ba8bdda.png)
![Screenshot from 2019-05-07 01-26-56](https://user-images.githubusercontent.com/1058663/57249784-a729fd00-7067-11e9-81b1-cbb8c06ac4a0.png)

**Comment by ec** [comment]
@saydulk Hello!

There is template for application.yml please see
https://github.com/rubykube/peatio/blob/1-9-stable/config/templates/application.yml.erb

You should run ./bin/init_config to transform templates into config files.

This is, probably, the first step of starting peatio locally

**Comment by AnythingLinux** [comment]
@ec Thanks :) 

![Screenshot from 2019-05-07 21-39-52](https://user-images.githubusercontent.com/1058663/57313090-aac58e80-7110-11e9-9301-3e85589d4cfe.png)
