### ISSUE TITLE
Any step by step production setup deployment guide?

### ISSUE THREAD

**Issue by zaxonlinecom** [openware/peatio#2209]
Hello,
Is there any Any step by step production setup deployment guide available?
Thanks.

**Comment by zaxonlinecom** [comment]
what are the differences between local development and production? can i use development deployment with docker as a production setup?

**Comment by shal** [comment]
Hey @altcoin-services,

We advice to use docker image with peatio.

Guide: https://github.com/rubykube/peatio/blob/master/docs/ops/deploy/ubuntu.md

Production mode is completely different!
We advice you to be careful with your exchange, never use peatio in development mode.
