### ISSUE TITLE
Coin plugins approving

### ISSUE THREAD

**Issue by ysv** [openware/peatio#2212]

**Comment by streetcrypto7** [comment]
Peatio-cpuchain for [CPUchain](https://cpuchain.org) now available https://github.com/streetcrypto7/peatio-cpuchain

**Comment by ysv** [comment]
@streetcrypto7 Thanks for your contribution to Peatio !
RubyKube team really appreciate your work. 

We will review plugin soon

**Comment by minkcrypto-zz** [comment]
Repo moved to https://github.com/minkcrypto/peatio-cpuchain

**Comment by andrew-thought** [comment]
Thank you for this great exchange! I would like to submit Thought AI Blockchain plugin for consideration to be included with Peatio.

https://github.com/thoughtnetwork/peatio-thought

**Comment by salinana** [comment]
Is there a coin plugin for EOS coin?
