### ISSUE TITLE
Litecoin block time  / Or request for configurable block times in database / console

### ISSUE THREAD

**Issue by Fair-Exchange** [openware/peatio#2214]
Hi  there,

Litecoin is currently configured for 10 minute block times in peatio, but it actually has 2.5 minute block times.  Would suggest changing its block time, or better yet (depending on priority), making block time a configurable value.

**Comment by martianatwork** [comment]
@Fair-Exchange this may be a mistake but I don't think so, instead of making a call every 3 min and getting just 1 block it is better to wait for 10 min and get at least 3-4 blocks this way we get time to scan other blockchains

**Comment by Fair-Exchange** [comment]
You make a good point.  It might be something to consider in periods of high load when a lot of coins are listed.  But if nobody else is having LTC lag as we did then I'll assume it's an isolated issue.

**Comment by martianatwork** [comment]
No I don’t think so because you won’t accept the deposit right away, you will wait for the confirmation which should be greater that 4 considering LTC block time,
