### ISSUE TITLE
cant create ERC20 Deposit Address

### ISSUE THREAD

**Issue by huuhait** [openware/peatio#2216]
Hi i have tried create deposit address but i dont know why it not work

ETH Deposit Address working normal
![image](https://user-images.githubusercontent.com/40519768/58384588-8709b000-800d-11e9-9f30-c423602a57ad.png)
![image](https://user-images.githubusercontent.com/40519768/58384603-b8827b80-800d-11e9-8293-0808f96172bb.png)

TST(test token testnet) Deposit Address not work
![image](https://user-images.githubusercontent.com/40519768/58384587-81ac6580-800d-11e9-8fdf-86e815511f3b.png)
![image](https://user-images.githubusercontent.com/40519768/58384601-b28c9a80-800d-11e9-9395-8e78810f52a8.png)

Daemon log
![image](https://user-images.githubusercontent.com/40519768/58384629-f7183600-800d-11e9-9529-bcc5614de22d.png)

**Comment by adarshdubeytech** [comment]
Send API request to generate address.
Re-Check Blockchain configuration.
Re-Check Contract address.
Re-Check Deposit wallet and Hot wallet address, and blockchain info in wallet section (for tst).
Check Log of geth/parity to verify the RPC queries and response.

**Comment by huuhait** [comment]
> Send API request to generate address.
> Re-Check Blockchain configuration.
> Re-Check Contract address.
> Re-Check Deposit wallet and Hot wallet address, and blockchain info in wallet section (for tst).
> Check Log of geth/parity to verify the RPC queries and response.

hi adarshdubeytech
erc20 working normal
just ask

**Comment by huuhait** [comment]
now work
forgot add deposit wallet
