### ISSUE TITLE
Yay! You’re on Rails!

### ISSUE THREAD

**Issue by AnythingLinux** [openware/peatio#2223]
Hello, i deploy peatio-2.1.20 into Ubuntu 16 but when i run $ bundle exec rails server -b 0.0.0.0
is show Rails app not Peatio 2.1.20 running

![Screenshot from 2019-06-01 21-37-28](https://user-images.githubusercontent.com/1058663/58750551-b6109d80-84b5-11e9-951d-ed54b2ce36ca.png)

**Comment by martianatwork** [comment]
UI for the peatio & barong is deprecated and removed at 2.0. 
close this issue
