### ISSUE TITLE
Rake seed:blockchain fail

### ISSUE THREAD

**Issue by huuhait** [openware/peatio#2225]
hi Rubykube

I can't create seed for blockchain
i have added `step` to blockchains.yml

but still cannot create seed @@!
`ActiveModel::UnknownAttributeError: unknown attribute 'step' for Blockchain.`
![image](https://user-images.githubusercontent.com/40519768/58984927-68bd6480-8804-11e9-84ff-8bc4b34ea54b.png)

**Comment by mnaichuk** [comment]
Hello @huuhait make sure that you make rake db:migrate cause we have migration with adding this column.
