### ISSUE TITLE
What is the use of REDIS and MySQL databases

### ISSUE THREAD

**Issue by KabDeveloper** [openware/peatio#2229]
Hi

Is there a way to get technical details about Peatio exchange please ?

I noticied that there 2 kind of database: MySQL and REDIS

Redis is used for what in your case please ?

And what about MySQL ?

Thank's

**Comment by martianatwork** [comment]
Redis is for cache and quick access

**Comment by KabDeveloper** [comment]
@martianatwork 

Thank you for answering my question.

What kind of informations are saved into redis please ? Full list if possible.

**Comment by mnaichuk** [comment]
@bcashier you can search `Rails.cache.write` or `Rails.cache.read` by project.

**Comment by KabDeveloper** [comment]
@mnaichuk I did a search inside the project but it seem that there no such code in it :(

Purhapse Redis is used nly for user sessions ?

**Comment by martianatwork** [comment]
@bcashier are you sure?
https://github.com/rubykube/peatio/blob/6ed8be3bc0ee8fe52c377d2dc6bfd02ffe1040cc/lib/daemons/k.rb#L97

Don’t use github search, use Rubymine or Sublime

**Comment by KabDeveloper** [comment]
@martianatwork You are awesome, thank you for your help !
