### ISSUE TITLE
Leftovers after removal of 2FA: member phone number & Phonelib

### ISSUE THREAD

**Issue by yivo** [openware/peatio#225]

**Comment by yivo** [comment]
<img width="1100" alt="screen shot 2018-01-05 at 3 23 14 pm" src="https://user-images.githubusercontent.com/7421323/34611000-5f03b72e-f22c-11e7-8346-2b50a9377238.png">

**Comment by dan-turner** [comment]
Hi guys,

What was the reason for removing all the 2FA stuff?

**Comment by yivo** [comment]
Hi @dan-turner,

Our plan is not to remove 2FA. We just want to move it to different place. These days we are starting to work hard on [barong](https://github.com/rubykube/barong) OAuth2 server for peatio which will handle 2FA and identity.

**Comment by yivo** [comment]
Closed via #245.
