### ISSUE TITLE
Start using Yarn for asset dependencies

### ISSUE THREAD

**Issue by yivo** [openware/peatio#23]

**Comment by mod** [comment]
Are you referring to yarn? I don't know what is yard
I think this is not necessary because we won't maintain frontend
for the admin panel we will decide later we should simplify code first

**Comment by yivo** [comment]
@mod Yes, it is actually yarn.

**Comment by mod** [comment]
@dkkoval can you invite Simon on this issue

**Comment by scatterp** [comment]
me?

**Comment by yivo** [comment]
We have added Yarn to Peatio and used it for some new assets like raven-js & country-flags. I see this task is not required anymore since we plan to craft brand new UI for Peatio.
