### ISSUE TITLE
ethereum withdrawl is still in  confirming  state

### ISSUE THREAD

**Issue by HafeezRai** [openware/peatio#2314]
Hi Ethereum withdrawl still in confirming state not updating

**Comment by growersun** [comment]
yes, same problem, and balance in locked

**Comment by doug420** [comment]
Any relpy on this...!

**Comment by martianatwork** [comment]
@doug420 this happens because of low gas price, you have to manually increase the gas price by rebroadcasting the same transaction with same nonce on blockchain 

Ref: https://kb.myetherwallet.com/en/transactions/checking-or-replacing-a-tx-after-sending/
