### ISSUE TITLE
Disable self trading

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#2315]
This is useless and causes some issues with arke. ex the bot orders getting matched with self.

This is also kinda confusing to some traders who are new.

**Comment by streetcrypto7** [comment]
Does the arke works?

**Comment by martianatwork** [comment]
@streetcrypto7 with 2.1 yes

**Comment by streetcrypto7** [comment]
How about 2.2 and what does it do?

**Comment by krtschmr** [comment]
if bots trade with themself, it's infinity money!

**Comment by streetcrypto7** [comment]
I don't think it is a good idea to block self-trade

**Comment by SimonVillage** [comment]
> if bots trade with themself, it's infinity money!

it's called wash trading

> A wash trade is a form of market manipulation in which an investor simultaneously sells and buys the same financial instruments to create misleading, artificial activity in the marketplace. First, an investor will place a sell order, then place a buy order to buy from themself, or vice versa.
https://en.wikipedia.org/wiki/Wash_trade
