### ISSUE TITLE
withdraw infinity transfer bug!

### ISSUE THREAD

**Issue by evan-labs** [openware/peatio#2326]
i am use peatio 2.1.20

withdraw_coin.rb call.

txid = wallet_service.build_withdrawal!(withdraw)  --> work well.

 withdraw.txid = txid
 withdraw.dispatch
 withdraw.save!    --> occured error!!   <ActiveRecord::RecordInvalid: Validation failed: Txid is too long (maximum is 128 characters)
 

And... withdraw_coin loop call... 

forevere transfer coin....

**Comment by ysv** [comment]
@ss-code-x Which blockchain do you use to get such a long txid ?
We have fixed this in 2-2-stable consider switching to 2-2 this version since even numbers are long supported stable branches

**Comment by evan-labs** [comment]
EOS blockchain ~
