### ISSUE TITLE
Potential Feature: Module/Plugin Functionality

### ISSUE THREAD

**Issue by HysMagus** [openware/peatio#2362]
Hi Guys,

This is a feature proposal aimed towards addressing the problem of common modifications on Peatio exchanges. 

**Problem Statement**

Peatio Exchanges of all fork derivations often have similar modifications done to the code locally upon install, for the purpose of implementing or integrating commercial, proprietary, needed software. Due to the nature of Peatio, and the RubyKube flavor being an MIT License codebase, integrating potentially proprietary software or commercial software such as Tradingview, ChartIQ or Trulioo is made potentially difficult due to licensing issues related to including it in the codebase and the implications of being reliant on a third-party service provider. 

**Solution Statement**

By creating a system to allow for modules, which in this context is snippets of code that override certain existing functionality or adds new functionality to the codebase without having it included in the main repository, we can allow for third-party software integrations without having to define explicit support for it, allow for the standardization of commonly repeated additions, potentially improve the security of said additions as they can be vetted by the open market versus having individual developers build custom integrations for each exchange. 

Here's a Potential Integration Scenario, using Chart.IQ (as I'm sure everyone's sick of hearing about TradingView all the time),
 integration can be broken apart into two parts, the code that overwrites the existing charting library and the proprietary code, which can be dropped in (in this case, the licensed/trial ChartIQ javascript library)

![Module Example](https://user-images.githubusercontent.com/12676885/64653313-c1942e80-d3eb-11e9-9519-fd7f22a58ca7.png)

**Introduced Complications**

Since Peatio is handling crypto, the obvious issue of allowing third-party plugins overwrite anything can be raised. As well as the potential security implications of having potentially unvetted third-party code on a production server, it can be said this is a horrible idea in practice. One way we can mitigate the aforementioned issue is by limiting what a "module" can have access to. While it won't protect a motivated party, it can be used as a litmus test when analyzing modules.  

I know that proposals are a dime a dozen and that this specific feature proposal introduces a lot of potential issues, so I thought I'd put this out there as a starting point of conversation to go deeper into expanding the sideways functionality of the OpenWare implementation of Peatio. 

Let me know what y'all think!

**Comment by martianatwork** [comment]
I think your example is old.
From 2.0 the trading UI has been removed from the peatio completely and you are free to implement your own UI.

I feel like your approach is similar to what WordPress does, you can install a plugin and it can overwrite exiting functions.

About the overwriting files and extending the functionality, it will help a lot in managing the custom functionalities, but also comes with a big risk, a potential risk of getting unwanted code which was in a third-party module. 

All in all, I'd say you can create custom Docker image in which you can copy the required files to the proper location and you can use the image.

**Comment by HysMagus** [comment]
I'm closing this issue as @martianatwork is correct
