### ISSUE TITLE
Issue viewing documents in admin panel at «Verify Account» page

### ISSUE THREAD

**Issue by paulokinho** [openware/peatio#237]
@yivo , How to approve/verify an account in "Verify account" page in the admin panel, I'm facing this issue when I click in View: 

`App 27185 stdout:   Rendered admin/id_documents/show.html.erb within layouts/admin (202.7ms)
App 27185 stdout: Completed 500 Internal Server Error in 250ms (ActiveRecord: 9.2ms)
App 27185 stdout:
App 27185 stdout: ActionView::Template::Error (undefined method `admin_asset_tag' for #<#<Class:0x000000047a4960>:0x00000005e66748>):
App 27185 stdout:     86:           <label><%= t('.id_document_file') %></label>
App 27185 stdout:     87:         </div>
App 27185 stdout:     88:         <div class="col-xs-18">
App 27185 stdout:     89:           <%= admin_asset_tag @id_document.id_document_file %>
App 27185 stdout:     90:         </div>
App 27185 stdout:     91:       </div>
App 27185 stdout:     92:       <div class="row">
App 27185 stdout:   app/views/admin/id_documents/show.html.erb:89:in `_app_views_admin_id_documents_show_html_erb___3183061794213905802_51283600'
App 27185 stdout:   lib/middleware/security.rb:11:in `call'`

**Comment by mod** [comment]
Hello Paul, Master might be unstable until the next tag 0.2.5
Thanks for reporting, I think it's a bug we will work on it ASAP,

We hope to release 0.2.5 this Friday.

**Comment by yivo** [comment]
@paulokinho Thank you for your report. I can confirm this is a bug. We will try to fix ASAP.

**Comment by yivo** [comment]
Progress in #238.

**Comment by yivo** [comment]
@paulokinho Fixed in #238.
