### ISSUE TITLE
Major issue between order submit api and order_processor daemon

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#2399]
https://github.com/openware/peatio/blob/a26755914d5bb6ccd217736759c20088a3ae4970/app/api/v2/order_helpers.rb#L19

On this line we check if the user has enough balance but the balance is never locked.
If queue is too long the daemons wont be able to process the messages as soon as user submits the order and the check_balance will always be true and accept additional orders which totals more than the balance. order_processor daemon will give "Can not lock funds" error and reject the order when processing this additional orders.

The  api should lock the funds or should check against sum of balance - pending_orders.origin_locked

**Comment by mnaichuk** [comment]
@martianatwork Nice point, we will add your idea to backlog!
