### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by kroim** [openware/peatio#2479]
After bundle exec rails server, If I call http://127.0.0.1:3000 it is showing one line error text on browser.
![image](https://user-images.githubusercontent.com/33049672/76718716-90b5fd00-6772-11ea-94d1-d66958103d64.png)

**Comment by mnaichuk** [comment]
@kroim, you can try http://127.0.0.1:3000/api/v2/public and you will see it works
for private and admin endpoints you will need to use gateway and authz dummy.
you can use these instructions https://github.com/openware/peatio#installation
