### ISSUE TITLE
ERC20 token deposits sometimes have not been collected automatically

### ISSUE THREAD

**Issue by mikoim** [openware/peatio#2495]
When collection fee tx is not confirmed on the blockchain before deposit_collection consumes the job, a token has never been collected automatically, and deposit is marked as skip.
![](https://i.imgur.com/BrUc17G.png)

## Expected behavior
deposit_collection starts a job collecting token after collection fee tx is confirmed.

**Comment by mnaichuk** [comment]
@mikoim yes it's known issue we will improve this flow in future versions.

**Comment by DaOverlord** [comment]
we fixed by adding a sleep period, before peatio attempts collection, maybe a 5 minutes wait, by then collection txn is confirmed

**Comment by uti91** [comment]
> we fixed by adding a sleep period, before peatio attempts collection, maybe a 5 minutes wait, by then collection txn is confirmed

Can you share me detail?
