### ISSUE TITLE
Bitcoin & ethereum JSON RPC client should pass endpoint path if provided

### ISSUE THREAD

**Issue by afk11** [openware/peatio#2511]
Bitcoin versions since v0.15 support multiple wallets over the RPC by using ./wallet/$WALLETNAME as the url path. Currently it's not possible to use these URL's with peatio because the client passes the hard coded path '/' in the request. 
https://github.com/openware/peatio/blob/e811e643349f330f8ba42a21040ad9b1edffa783/lib/peatio/bitcoin/client.rb#L22

I've made a PR for this https://github.com/openware/peatio/pull/2512

Per comments from @mikoim (and @martianatwork I think), I've done the same for the ethereum client.

**Comment by martianatwork** [comment]
This should be done for ETH as well

**Comment by afk11** [comment]
@martianatwork thanks, someone else mentioned that as well. I've updated the issue to reflect this - it's already in the pull request
