### ISSUE TITLE
peatio-2.4.7/config/application.rb:40:in `fetch': key not found: "TIMEZONE" (KeyError)

### ISSUE THREAD

**Issue by shamart** [openware/peatio#2529]
<pre>
/bin/bash -c "/usr/share/rvm/bin/rvm ruby-2.6.5 do /usr/share/rvm/rubies/ruby-2.6.5/bin/ruby /home/jeff/repo/peatio-2.4.7/bin/rails server -b 0.0.0.0 -p 3000 -e development"
Traceback (most recent call last):
	29: from /home/jeff/repo/peatio-2.4.7/bin/rails:8:in `<main>'
	28: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
	27: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	26: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
	25: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	24: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	23: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	22: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	21: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	20: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<main>'
	19: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/command.rb:46:in `invoke'
	18: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/command/base.rb:69:in `perform'
	17: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	16: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	15: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	14: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `perform'
	13: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `tap'
	12: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	11: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
	10: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	 9: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
	 8: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 7: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 6: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 5: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 4: from /home/jeff/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 3: from /home/jeff/repo/peatio-2.4.7/config/application.rb:14:in `<main>'
	 2: from /home/jeff/repo/peatio-2.4.7/config/application.rb:15:in `<module:Peatio>'
	 1: from /home/jeff/repo/peatio-2.4.7/config/application.rb:40:in `<class:Application>'
/home/jeff/repo/peatio-2.4.7/config/application.rb:40:in `fetch': key not found: "TIMEZONE" (KeyError)
</pre>

i am using 2.4.7 release.

**Comment by venkateshsys** [comment]
I also have the same problem. Did you resolve your issue? @shamart

**Comment by shamart** [comment]
> I also have the same problem. Did you resolve your issue? @shamart

 u need run init script first
