### ISSUE TITLE
peatio-1.9.24 Build - Curling Question 

### ISSUE THREAD

**Issue by Diminutivecoin** [openware/peatio#2535]
Just a question if anyone could answer with the older builds 

peatio-1.9.24/lib/blockchain_client/bitcoin.rb

 Line 32 
> json_rpc(:sendtoaddress, [normalize_address(recipient.fetch(:address)), **amount]**)

curl --user test --pass testing -X POST --data '{"jsonrpc":"2.0","method":"sendtoaddress","params":["E3dEW5m8CqzWNAXjmgqpxvD5HFypepAc3L" , "0.0000001" ]}'

{"result":null,"error":{"code":-1,"message":"value is type str, expected real"},"id":null}

Is there any way of changing that to call ' instead of " in the curl or where i could look at modifying the output on this? 

Thanks

**Comment by martianatwork** [comment]
Seems like you are using bitcoin connector for a old protocol

**Comment by Diminutivecoin** [comment]
Yes it's a bit older , openware took over and 
now it's a all for nothing . A big butt is why "walletaddress" "amount" instead of "walletaddress" amount which normal wallets operate on- I just wanted to know how to mod or atleast check where it's coming from . 

But yes not sure why I even try

**Comment by martianatwork** [comment]
https://github.com/openware/peatio/blob/7178c8d2457a1aaba66c64791b7e26d1ccd9c937/lib/wallet_client/bitcoind.rb#L49

**Comment by Diminutivecoin** [comment]
On JSON 1 it does the same with "amount" being in double quotation marks .

**Comment by krewshul** [comment]
using either " or ' in a json file is fine. you have to just make sure you are using the same type opening and closing. so a ' must close with an ' and a " must close with a "
