### ISSUE TITLE
Remove malformed currency symbol from title at page «Trade»

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#258]
In markets in head => should not displaying icons
![screen shot 2018-01-09 at 8 00 13 pm](https://user-images.githubusercontent.com/29736025/34735536-7b9b8322-f578-11e7-9c45-2e250ac88c73.png)

**Comment by yivo** [comment]
Progress in #263.

**Comment by yivo** [comment]
Closed via #263.
