### ISSUE TITLE
Fix markets sorting

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#260]
On page Markets > hover on left sidebar to get list of "sorting by markets"
Markets sorting by XRP should display sorting by: 
-XRP/USD
-BTC/XRP
Markets sorting by BTC should display sorting by: 
-BTC/USD
-BTC/XRP

**Comment by spavlishak** [comment]
You can close it.

**Comment by yivo** [comment]
Issue is related to missing entries in config/markers.yml, not to code.

**Comment by yivo** [comment]
@mkuvshynnikov @spavlishak up
