### ISSUE TITLE
Peatio Integration with R3 Corda

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#2628]
Hi Team,

I am planning to integrate Peatio with R3 Corda blockchain but not sure about the steps. Can you please suggest me how to proceed in this direction?

**Comment by calj** [comment]
Hello,

You can have a look to existing plugins here: https://github.com/openware/peatio-contrib

Main code here: https://github.com/openware/peatio-contrib/tree/master/peatio-litecoin/lib/peatio/litecoin
And tests: https://github.com/openware/peatio-contrib/tree/master/peatio-litecoin/spec/peatio/litecoin

Feel free to create a PR on peatio-contrib :heart:

**Comment by mnaichuk** [comment]
Hello, and there is an integration doc: [peatio coin development](https://www.openware.com/sdk/docs/peatio/coins/development.html)
