### ISSUE TITLE
ERC20 deposits are being ignored

### ISSUE THREAD

**Issue by gabrielnaoto** [openware/peatio#2637]
Currently peatio only fetch and build transactions that have `tx.fetch('to')` being either a `payment_address.address` or a `currency.options[:erc20_contract_address]`

```rb
# ethereum/blockchain.rb | peatio version 2.2.25

def fetch_block!(block_number)
# ...
next if @erc20.find { |c| c.dig(:options, :erc20_contract_address) == normalize_address(tx.fetch('to')) }.blank?

#...

def build_erc20_transactions(txn_receipt)
# ...
# Skip if ERC20 contract address doesn't match.
currencies = @erc20.select { |c| c.dig(:options, :erc20_contract_address) == log.fetch('address') }
next if currencies.blank?
```

### However, you can write smart contracts to support mutisig for ETH

> Unlike Bitcoin, ETH does not have any native addressing mechanism for multisig. You can write a simple smart contract to achieve this. Please see this link for reference. https://github.com/openware/peatio/issues/621#issuecomment-371249264

This means, that transfers using multisig won't be collected because their `to` address will be to the multisig smart contract.

![image](https://user-images.githubusercontent.com/13211186/87994564-a2623500-cac3-11ea-8adb-a024364b8415.png)

So, how can we enable deposit collection for multisig erc20 transactions in peatio?

**Comment by alinetskyi** [comment]
> Currently peatio only fetch and build transactions that have `tx.fetch('to')` being either a `payment_address.address` or a `currency.options[:erc20_contract_address]`
> 
> ```ruby
> # ethereum/blockchain.rb | peatio version 2.2.25
> 
> def fetch_block!(block_number)
> # ...
> next if @erc20.find { |c| c.dig(:options, :erc20_contract_address) == normalize_address(tx.fetch('to')) }.blank?
> 
> #...
> 
> def build_erc20_transactions(txn_receipt)
> # ...
> # Skip if ERC20 contract address doesn't match.
> currencies = @erc20.select { |c| c.dig(:options, :erc20_contract_address) == log.fetch('address') }
> next if currencies.blank?
> ```
> 
> ### However, you can write smart contracts to support mutisig for ETH
> > Unlike Bitcoin, ETH does not have any native addressing mechanism for multisig. You can write a simple smart contract to achieve this. Please see this link for reference. [#621 (comment)](https://github.com/openware/peatio/issues/621#issuecomment-371249264)
> 
> This means, that transfers using multisig won't be collected because their `to` address will be to the multisig smart contract.
> 
> ![image](https://user-images.githubusercontent.com/13211186/87994564-a2623500-cac3-11ea-8adb-a024364b8415.png)
> 
> So, how can we enable deposit collection for multisig erc20 transactions in peatio?

Hi, this issue was addressed by our team at mobidax.io 
You can contact us for the solution.
