### ISSUE TITLE
Can I create a new table and test from rails console

### ISSUE THREAD

**Issue by venkateshsys** [openware/peatio#2639]
Hey Guys,

I want to create a new table (table_testing) and do some testing from rails console

Is it possible to execute the below commands:
- rails generate migration table_testing
- rails db:migrate

When I execute rails commands, it throws an error:  `fetch': key not found: "TIMEZONE" (KeyError).
I didn't understand how it will work for the development by adding some new tables / doing some changes to existing tables.

Thanks you.

**Comment by mnaichuk** [comment]
Please follow Readme https://github.com/openware/peatio#installation you didn't run `./bin/setup` .
