### ISSUE TITLE
Market orders by price instead of volume

### ISSUE THREAD

**Issue by Hopperman** [openware/peatio#264]
Question:

Is it possible to submit a market order by amount you want to spend, rather than volume you want to buy?
e.g. Submit order to purchase $1 of BTC versus purchasing `n` of BTC and estimate required funds

**Comment by Hopperman** [comment]
Any feedback? :)

**Comment by yivo** [comment]
@mkuvshynnikov ping

**Comment by mkuvsh** [comment]
@Hopperman hello, 
There is no such feature as "to filter orders by price instead of volume" but anyway before the submit market order(e.g. market USD/BTC), in field "Summary" you can see how much USD you will get/spend.

**Comment by yivo** [comment]
@Hopperman I hope your question is answered. You may open the issue again if you have more to ask.
