### ISSUE TITLE
ERC20 can be partially verified by using input

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#2717]
For ERC20 we don't always need to run `eth_getTransactionReceipt`.
We can use input field in the transaction which is available in `eth_getBlockByNumber` to verify the ERC20 method and sender as well as the amount.
The input for transfer always consist of `a9059cbb` followed by 64 bit address and 64 bit hex amount.

using this data we can partially verify the transaction.

The only problem is that we will have to change architecture a little bit to support checking of the addresses.
once we confirm that the address exists in the system we can use `eth_getTransactionReceipt` to verify the transaction status.

May be you guys have considered this as an option and didnt implement it because of system architecture but i believe we should reconsider about this option as ETH is creating a lot of blocks per minute and the blockchain daemon is always 100-500 blocks behind because USDT transactions are too many.

Implementing this will also reduce the load on geth and blockchain daemon as well as it will be possible to implement infura for blockhain provider.
or we can partially implement this to check the method and minimum deposit amount.

**Comment by calj** [comment]
Thanks a lot, this is extremely relevant!
We will improve the blockchain plugin to reduce drastically the call to  `eth_getTransactionReceipt` using the approach.

**Comment by calj** [comment]
I have implemented this approach in in this commit:
https://github.com/openware/peatio/pull/2901/commits/5d36538db82209bfdcaf4e616e3c7246f4107482#

I expect to introduce it from 2.6 version

**Comment by martianatwork** [comment]
@calj Hey, I think you should also consider some edge cases such as `transfer(address,unit)`

This is a rare case but I have seen some contracts using this.

May be add a section in documentation.

**Comment by calj** [comment]
I don't see it in ERC20 interface, but I see this one we should probably support:
`function transferFrom(address _from, address _to, uint256 _value) public returns (bool success)`

**Comment by calj** [comment]
I changed the logic to not check the function called at all, we look for a deposit address at the first and second arguments.
Then we fetch the receipt of the tx for details, so it should be safe:

https://github.com/openware/peatio/pull/2901/commits/416584f68f440a868312b0d7b49e4abb72652250#diff-60704fde013034ea8204faf965741a3ee41e8d2023c369e1e8bd62ad4856a470R72

**Comment by calj** [comment]
Merged in #2908
