### ISSUE TITLE
How to authenticate websocket with peatio?

### ISSUE THREAD

**Issue by ItsShadowl** [openware/peatio#2734]
I have access_key and secret_key like from [here](https://openware.com/sdk/api/peatio/trading-api.html), how would this be used to authenticate the websocket?

And, I find it hard to know/understand the usefulness of the websocket API, is it only to get notified of trades entry and some market related actions?

Or, does it allow me send trade requests too?

I would be glad to know more about this as i have a project that depends on it...

Thanks..

**Comment by huuhait** [comment]
use header authenticate => jwt

**Comment by ya3er** [comment]
> use header authenticate => jwt

How to create JWT token with API key and API secret in user level?
