### ISSUE TITLE
BountyHunt : Integrating Peatio Management API V2

### ISSUE THREAD

**Issue by devshaaran** [openware/peatio#2737]
I have tried querying the management API V2 but it gives me a 404 Error.

=>. Followed the endpoints specified in the following swagger
[https://app.swaggerhub.com/apis/fantasygold/peatio-management_api_v_2/2.4.0](url)

![Screenshot 2020-11-09 at 12 48 04 AM](https://user-images.githubusercontent.com/34472894/98482136-3d268100-2225-11eb-8ce3-8b4cdb29e053.png)

Request:
`response = requests.post('http://www.bitfair.pro/api/v2/management/withdraws/new', headers=headers, data=data, verify=True)`

Request from Browser:
![Screenshot 2020-11-09 at 12 51 33 AM](https://user-images.githubusercontent.com/34472894/98482200-cfc72000-2225-11eb-823c-c26515796435.png)

50$ worth of XLM will be transferred :)

**Comment by shingonoide** [comment]
Management API is not deploy to outside world by default.
Find me on Telegram to help you.

**Comment by martianatwork** [comment]
Check authz_rules.yaml of your installation.

Management rule should under pass section

**Comment by devshaaran** [comment]
Fixed and the hunt is over
