### ISSUE TITLE
Fee collection transaction with amount 0 on ERC20 

### ISSUE THREAD

**Issue by lisandromaselli** [openware/peatio#2748]
https://github.com/openware/peatio/blob/e1617e936836bc9813f89423dcf6f303baf08d01/app/services/wallet_service.rb#L131
```
if original_amount < destination_wallets.pluck(:min_collection_amount).min
      return []
    end
```

https://github.com/openware/peatio/blob/e1617e936836bc9813f89423dcf6f303baf08d01/lib/peatio/ethereum/wallet.rb#L62
```      
      fees = convert_from_base_unit(options.fetch(:gas_limit).to_i * options.fetch(:gas_price).to_i)
      transaction.amount = fees * deposit_spread.size
      transaction.options = options
```
if the deposit of the transaction is less than all of the destination wallets min_collection_amounts then deposit_spread is [] and sends a collection fee transaction with amount 0. This results in a waste of gas

**Comment by mnaichuk** [comment]
@lisandromaselli Hello! Yeah, good point. We will fix the send of the empty tx.

**Comment by uti91** [comment]
@mnaichuk do you have fix for peatio 2-5 ?
