### ISSUE TITLE
Confusing min deposit strict

### ISSUE THREAD

**Issue by lisandromaselli** [openware/peatio#2749]
https://github.com/openware/peatio/blob/e1617e936836bc9813f89423dcf6f303baf08d01/app/services/blockchain_service.rb#L75
If the deposit amount is exact as the currency's min deposit, the transaction is not taken into account.
this is confusing for the users and tedious for the admins

**Comment by mnaichuk** [comment]
@lisandromaselli we will change it soon, thanks
