### ISSUE TITLE
Remove hardcoded currencies

### ISSUE THREAD

**Issue by yivo** [openware/peatio#279]

**Comment by yivo** [comment]
Move config/currencies.yml to database layer:
* Remove hardcoded currencies from many places in the project including assets/ public/templates and Rails views.
* Don't cache currencies since they may be updated from admin panel in future.
* Create db/seed.rb which should add USD & BTC if no currencies exist at all in DB.
* Update existing code to reflect changes to currency model.
* Write smart validation for model.

Create currency model with such specs:
* id, unsigned int 11, PK, AI
* key, varchar(30), not null
* code, varchar(30), not null, should be always UPPERCASE (do canonicalization)
* name, varchar(30), not null
* symbol, char(1), optional
* type, varchar(30), not null, default: coin, possible values: fiat, coin, token
* json_rpc_endpoint, varchar(200), optional, validated as URL
* rest_api_endpoint, varchar(200), optional, validated as URL
* hot_wallet_address, varchar(200), not null
* options, varchar(1000), default: {}, not null, serializable attribute of JSON type
* wallet_url_template, varchar(200), not null, validated as URL
* transaction_url_template, varchar(200), not null, validated as URL
* quick_withdraw_limit, decimal(23, 10), unsigned int, not null, default zero
* AR timestamps, not null

**Comment by yivo** [comment]
@mitjok Please, submit your WIP PR ASAP and target it to `devel` branch, should be based on `devel`.

**Comment by subaru9** [comment]
@yivo I'll start the task within an hour. Do you need a pull request of my wip work to review befor merge in `devel`?

**Comment by yivo** [comment]
@mitjok Yes, submit the PR as you will push the first commit.

**Comment by subaru9** [comment]
> code, varchar(30), not null, should be always UPPERCASE (do canonicalization)
> options, varchar(1000), default: {}, not null, serializable attribute of JSON type

@yivo tyring to do on db level, any objections?

**Comment by yivo** [comment]
@mitjok 

`code, varchar(30), not null, should be always UPPERCASE (do canonicalization)`
Do this in `def code=(code)`.

`options, varchar(1000), default: {}, not null, serializable attribute of JSON type`
If we would not need to support such databases as MSSQL (more are coming) I would prefer JSON data type in DB layer. I am not familiar with MSSQL so I consider implement it in compatible way.

**Comment by subaru9** [comment]
@yivo updated the thread and noticed your `Rush` label, questions not actual anymore

`UPPERCASE ` implemented via trigger

**Comment by yivo** [comment]
@mitjok Please do it without DB triggers.

**Comment by yivo** [comment]
Do it in Ruby.

**Comment by subaru9** [comment]
sure

**Comment by subaru9** [comment]
@yivo just writing to let you know that I'm in the transition from my current project (40h/week) to `peatio`. Time lags as today are possible..

**Comment by subaru9** [comment]
@yivo https://www.evernote.com/l/AYMaHzP3dHZGkLSyOrFcbgiis8fb-rP9LQkB/image.png
don't have permissions to create a branch for pull request, pls fix

**Comment by yivo** [comment]
@mitjok Consider using GitHub forking.

**Comment by yivo** [comment]
ping @mkuvshynnikov

**Comment by subaru9** [comment]
> Write smart validation for model.

@yivo I consider dry-validatio for controller
https://mensfeld.pl/2017/03/dry-validation-as-a-schema-validation-layer-for-ruby-on-rails-api/
https://gist.github.com/solnic/7e0c395ca92e0c6d8ad9

**Comment by mitjok** [comment]
@yivo any ideas why while creating account in account_specs.rb:297
the creation fails with validation message `Currency is not included in the list`?

**Comment by mitjok** [comment]
@yivo the question above not actual anymore

**Comment by subaru9** [comment]
@yivo FYI:

- Remove hardcoded currencies from many places in the project including assets/ public/templates and Rails views. **(partially done)**
- Don't cache currencies since they may be updated from admin panel in future.
- Create db/seed.rb which should add USD & BTC if no currencies exist at all in DB. **(done)**
- Update existing code to reflect changes to currency model. **(partially done)**
- Write smart validation for model **(done)**

**Comment by yivo** [comment]
Closed via #488.
