### ISSUE TITLE
Remove Pusher Dependency

### ISSUE THREAD

**Issue by ryanisab** [openware/peatio#283]
Pusher locks this project into using their service to scale websocket connections. Ideally this project should stand up a websocket server and the implementor should then be able to decide how to scale the websocket traffic independently instead of being locked in to one specific vendor. This is especially important if running the project as a component in a locked down SOA deployment as scaling will need to happen on the web facing proxy end.

**Comment by dmk** [comment]
Hello @ryanisab!

We're going to migrate to Rails 5 soon, then we will replace pusher with ActionCable.

**Comment by yivo** [comment]
Hello @ryanisab 

I think you can ride with https://github.com/stevegraham/slanger before we will migrate to ActionCable.

**Comment by JoeWallCrypt0** [comment]
Hi

@dkkoval @yivo When do you think is the migratoin to ActionCable? Is it in a week, in a month or much more later?

Thank you

**Comment by yivo** [comment]
@ryanisab @dkkoval @JoeWallCrypt0 Hi guys

I can confirm pusher slanger works well with peatio, including funds & markets page.

**Comment by tzman89** [comment]
@yivo 
it looks like slanger is not working with ruby 2.5.0. it gives "ERROR: Failed to build gem native extension." Only solution is to run slanger on another server with lower version of ruby

**Comment by myujang** [comment]
I am using slanger with ruby 2.3.1 install via rbenv
It works perfectly with Peatio 1.5.0

**Comment by tzman89** [comment]
@myujang 
I installed it on remote server with ruby 2.3.1 and it's running but didn't test if it works on peatio.
Do you use the same id for PUSHER_APP: and PUSHER_CLIENT_KEY: or slanger have an option to give you pusher app id

**Comment by myujang** [comment]
@tzman89 Yes. When i debug. its all goes to slanger. you can put any secret key and id in slanger.

**Comment by yivo** [comment]
@tzman89 You can put any value to PUSHER_APP. I for example put IP address.

**Comment by yivo** [comment]
If you are using slanger, of course.

**Comment by arruah** [comment]
@yivo In which files do I need change the settings in order to replace the pusher to the slanger?

**Comment by hardywu** [comment]
More ideally, a standalone ActionCable can be used to build a replacement for slanger.

**Comment by yivo** [comment]
Moved to #1360.
