### ISSUE TITLE
how to get passphase in exchange generated ethereum address for private key?

### ISSUE THREAD

**Issue by zeus-dev** [openware/peatio#2857]
accidently my friend deposited huge ether in his exchange wallet address, but my exchange is testnet, he deposited mainnet coin, and i found private key in but i couldnt unlock the exchange created new ethereum address,

please help me to recover the funds,
thanks in advance :+1:

**Comment by calj** [comment]
Hello @zeus-dev,

By luck ethereum network use the same wallets for testnet and mainnet so it should be recoverable.

Are you using parity?
If yes you should be able to [export the account from parity](https://www.openware.com/sdk/2.6/guides/cryptonodes/administration/ethereum-parity-cryptocurrency-node-administration-guide.html) testnet node and import it on a mainnet parity node.

**Comment by zeus-dev** [comment]
yes im using parity, but i dont know the passphase of exchange created address, and i got json file  for that account,

**Comment by mnaichuk** [comment]
Hello @zeus-dev,

You can get it from the rails console of deposit_coin_address deamon:

Example:

```ruby
PaymentAddress.find_by(address: "your_address").secret
```

**Comment by zeus-dev** [comment]
app@c01aaaa66bf7:~$ PaymentAddress.find_by(address: "0xF1e58B50C526a544cBE1653b880C41252514Fd77").secret
bash: syntax error near unexpected token `address:'

**Comment by mnaichuk** [comment]
@zeus-dev you should do it in rails console `bundle exec rails c` and after the command that I sent before
