### ISSUE TITLE
Balance should be rounded with higher precision

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#287]
In Summary dropdown field currencies rounding by 2 digits after dot
Should rounding by 4 or 5 digits after the dot. 
![screen shot 2018-01-12 at 6 25 59 pm](https://user-images.githubusercontent.com/29736025/34884995-28f3408c-f7c7-11e7-82d6-b97c05645a75.png)

**Comment by k1T4eR** [comment]
![image](https://user-images.githubusercontent.com/15076128/35440301-7612a8fe-02a7-11e8-87a4-c9ba4f13ef2f.png)

**Comment by yivo** [comment]
Closed in #379.
