### ISSUE TITLE
coininfo page

### ISSUE THREAD

**Issue by amarian12** [openware/peatio#303]
Will be nice to have a coininfo page, to show the wallet info as version, actual block and number of connections.. maybe also peers details

**Comment by yivo** [comment]
Hello @amarian12 

I believe this is not a scope of Peatio exchange. You should understand Peatio like cryptocurrency exchange provider which you can add to your project. But it is not a website which has everything ready out of box.

@mod ping

**Comment by amarian12** [comment]
Idea was that anyone can verify that the exchange wallets are on correct block, correct version

**Comment by yivo** [comment]
@amarian12 consider contacting @mod for this.

**Comment by yivo** [comment]
@amarian12 I am closing the issue. I hope you have contacted Louis and received the response. You may open the issue or create the new if you have any question.
