### ISSUE TITLE
Per Trade fee 

### ISSUE THREAD

**Issue by nandhini-ramanujam** [openware/peatio#304]
Hi, I have setup the Markets.yml with 0.1 as trading fee. But the same is not getting reduced in user account balance. Do we need any other configurations beyond this?

**Comment by yivo** [comment]
Hello @nandhini-ramanujam 

These fees are used as transaction fees. Peatio doesn't support trading fees.

@mod ping

**Comment by nandhini-ramanujam** [comment]
Hi @yivo,
Thanks for your quick reply.
Transaction fees refers what? Each bid and Ask fees?

in order strike method
def strike(trade)
    raise "Cannot strike on cancelled or done order. id: #{id}, state: #{state}" unless state == Order::WAIT

    real_sub, add = get_account_changes trade
    real_fee      = add * fee
    real_add      = add - real_fee

    hold_account.unlock_and_sub_funds \
      real_sub, locked: real_sub,
      reason: Account::STRIKE_SUB, ref: trade

    expect_account.plus_funds \
      real_add, fee: real_fee,
      reason: Account::STRIKE_ADD, ref: trade
I could see the fee deduction. But this is applied in which scenario.
Please explain

**Comment by yivo** [comment]
@nandhini-ramanujam I will check it later. Now you can use `git-blame` to find out what this piece of code was used for. 

@yssavchuk Could you please help with this?

**Comment by ysv** [comment]
@nandhini-ramanujam Hi
Transaction fees refers to each order either bid or ask.
Imagine peatio maches bid order (1btc/10_000usd) with ask order (10_000usd/1btc)
Btcusd market bid fee is 0.1 and ask fee is 0.05
It means that member created bid order will receive 9_000usd and member created ask order will receive 0.95btc
So peatio takes fee from amount member receive

**Comment by nandhini-ramanujam** [comment]
HI @yssavchuk & @yivo 

Thanks for your reply. I will look into it.  if 0.1% btc is deducted from user account, then how this fee got credited into exchange's BTC account. I couldn't find any code related to that. Is it implemented in Peatio?

**Comment by ysv** [comment]
Actually it isn't implemented yet

**Comment by yivo** [comment]
I think the question is solved. Please, reopen if anything else. Thanks.
