### ISSUE TITLE
A limits on the amount for withdrawal

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#306]
Withdraw limits:

- daily

- weekly

- monthly
needs to be added for more security

**Comment by yivo** [comment]
Please, describe details. I don't understand.

**Comment by yivo** [comment]
ping @mkuvshynnikov

**Comment by fansyfs** [comment]
It means should have a daily/weekly/monthly withdraw upper limits.
e.g. 
daily limit: 1btc (User cannot withdraw more then 1btc per day)
weekly limit: 5btc (User's all withdrawals in one week cannot exceed 5btc)
monthly limit: 10btc (...) 

If user want to make a big withdrawal, they should submit the request somewhere and audit manually by admin.

**Comment by ghost** [comment]
withdraw limit: Daily / weekly / monthly (enum ?)
over limit withdrawal: Withdraw Enquiry table add one column -> Audit Manually. (Email Alert maybe the next step but not in the mainstream development)

**Comment by yivo** [comment]
Hello. Currently Peatio has only `quick_withdraw_max` option which controls the max amount for single withdraw. I think we will add more options soon.

**Comment by ysv** [comment]
Dynamic withdraw limits could be added with [applogic](https://github.com/rubykube/applogic)
