### ISSUE TITLE
BTC Deposit : Address not showing   

### ISSUE THREAD

**Issue by parthagorai** [openware/peatio#308]
Hi, i have setup peatio in Ubuntu 14.04, latest from master branch every thing is working but  in BTC Deposit Address showing blank. When i am clicking in New Address nothing happen. 

i have check all the daemons and bitcoin is up and working

**Comment by yivo** [comment]
Hello @Microinstance 

Deposit address generation works very well on the latest master.

You should check:
* Bitcoind is fully synced
* Correct RPC values in currencies.yml
* Daemon amqp:deposit_coin_address is running

**Comment by yivo** [comment]
You can also run Peatio using https://github.com/rubykube/peatio-workbench.

**Comment by parthagorai** [comment]
Hi @yivo , thanks for your quick reply.

i have checked values in currencies.yml and daemon amqp:deposit_coin_address is also running but bit coin address is not showing

**Comment by parthagorai** [comment]
i have tried to install from https://github.com/rubykube/peatio-workbench. but it is showing error for ngx-cryptobase

**Comment by yivo** [comment]
Hello @Microinstance 

Could you please share the errors you get from peatio-workbench?

Also have you checked that your Bitcoin node is fully synced?

Our team doesn't have any issues running Peatio from master. But we actively use Docker for it. 

I would advise you to try manually generate your address by calling Bitcoind JSON RPC:

`curl --user RPC_USER:RPC_PASSWORD --data '{"jsonrpc": "1.0", "method": "getnewaddress", "params": [] }' -H 'Content-Type: application/json;' http://RPC_HOST:RPC_PORT`

Replace RPC_* values with yours and try to exec. If it fails it means Bitcoind isn't fully synced or you have broken installation of Bitcoind.

**Comment by yivo** [comment]
It should return something like `{"result":"mrdWWRtyhiEcR2yzRZA8p3eHWnuxHUyuHF","error":null,"id":null}`.

**Comment by rickguedes** [comment]
Hey guys,
Same problem here, running from peatio-workbench. (Had to remove ngx-cryptobase to make it work).
I tested generating a new address manually and it's returning properly. Everything correct in currencies.yml too. No errors are showing up, it's only the address that is always blank.
I'm running v0.2.5 from master. Any ideas?

![image](https://user-images.githubusercontent.com/5911443/35417480-be779b24-0214-11e8-8e2d-cae9e6c76536.png)

**Comment by yivo** [comment]
Hello @duduric 

Does Rails has access to RabbitMQ? I mean open port & correct binding. 

Run amqp:deposit_coin_address daemon manually via `RAILS_ROOT=$(pwd) bundle exec ruby lib/daemons/amqp_daemon.rb deposit_coin_address` and manually enqueue generation of address via:

```
class PaymentAddress
  def gen_address
    payload = { payment_address_id: id, currency: currency }
    attrs   = { persistent: true }
    AMQPQueue.enqueue(:deposit_coin_address, payload, attrs)
  end
end
```

Also try cleaning RabbitMQ & MySQL before.

**Comment by CombatCode** [comment]
Same here, clean installation on local environment and development server.
Connection to rabbitmq works fine, BTC deposit address is missing, XRP works fine.


Maybe this issue is also connected with : 
```
Showing /home/app/app/views/private/assets/_liability_tabs.html.erb where line #21 raised:

undefined method `sum' for nil:NilClass
Extracted source (around line #21):
19
20
21
22
23
24
              
          <span class="currency">
            <%= t('currency.icon.btc').html_safe %>
            <%= @btc_proof.sum %>
          </span>
        </div>
        <%= render 'liability_data', account: @btc_account, proof: @btc_proof %>

Trace of template inclusion: app/views/private/assets/_liability_proof.html.erb, app/views/private/assets/index.html.erb

Rails.root: /home/app

Application Trace | Framework Trace | Full Trace
app/views/private/assets/_liability_tabs.html.erb:21:in `_app_views_private_assets__liability_tabs_html_erb___1190901760359109198_69827606990300'
app/views/private/assets/_liability_proof.html.erb:9:in `_app_views_private_assets__liability_proof_html_erb__947065663649108543_69827607001340'
app/views/private/assets/index.html.erb:19:in `block in _app_views_private_assets_index_html_erb___2638481645618551309_69827607133900'
app/views/private/assets/index.html.erb:1:in `_app_views_private_assets_index_html_erb___2638481645618551309_69827607133900'
lib/middleware/security.rb:11:in `call'
lib/middleware/i18n_js.rb:9:in `call'
```
after cilicking on Solvency menu item

**Comment by yivo** [comment]
@duduric Your should run Rake task to enable «Solvency» to work well. Check .travis.yml for details. We will update docs soon.

I am closing the issue since BTC address generation works stable with both BitGo & Bitcoind.

You may reopen the issue if you still are having troubles with deposit address.

**Comment by ghost** [comment]
@duduric  Hello, did you resolve it? I got it too.  It's OK to generate a new address manually, but the address still be blank.

**Comment by valuttiDev** [comment]
@sosospicy not yet i'm afraid. I actually stopped working on it, i'll get back to this in the next day.
though it does work in the original peatio, just not in this fork, so i'm at loss here

**Comment by rickguedes** [comment]
@sosospicy  not yet i'm afraid. I actually stopped working on it, i'll get back to this in the next days.
though it does work in the original peatio, just not in this fork, so i'm at loss here

**Comment by ghost** [comment]
@duduric  
Problem fixed. In my case it was a mysql connect error. (Saw it from ./log/daemons/amqp_deposit_coin_address.log,  the log is created by god daemon)
