### ISSUE TITLE
Trad page showing blank 

### ISSUE THREAD

**Issue by parthagorai** [openware/peatio#309]
Trad page showing blank

**Comment by yivo** [comment]
Hello @Microinstance 

Could you please share the details? For me trade page works well in clean Peatio installation.

You can also run Peatio using https://github.com/rubykube/peatio-workbench.

**Comment by Alex-Shilman** [comment]
@yivo, I'm not seeing the actual candles on the trade page. I think that's what @Microinstance meant. Should there be any? Or is there missing API configuration? Thanks

**Comment by parthagorai** [comment]
Thnaks @Alex-Shilman  actual candles on the trade page is not Showing

**Comment by yivo** [comment]
Hi @Alex-Shilman @Microinstance 

I am sure you did something wrong when installing Peatio. Could you please share output from DevTools?

Personally I don't have such problem. 

<img width="1280" alt="screen shot 2018-01-21 at 2 01 34 pm" src="https://user-images.githubusercontent.com/7421323/35193975-c18cc85c-feb3-11e7-9386-3c4d6b80670a.png">
(from master)

**Comment by yivo** [comment]
If you still the problem you may reopen the issue. Thanks.
