### ISSUE TITLE
Not seeing candle sticks on trade page

### ISSUE THREAD

**Issue by Alex-Shilman** [openware/peatio#324]
I am not seeing any candle sticks on the Trade page `/markets/btcusd`. The only thing I see is a loading spinner.

![screen shot 2018-01-20 at 12 18 26 am](https://user-images.githubusercontent.com/3674429/35180151-8c929be6-fd77-11e7-8d42-cedbda46f6c3.png)

Am I missing some kind of an `access_key`. Perhaps could be a good idea to add some instructions in the Readme file.

**Comment by GH0STL1N3R** [comment]
Did you execute some demo orders/trades? If you haven't, no charts (candle stick/line) will show up

**Comment by yivo** [comment]
Hello @Alex-Shilman 

Could you please share the output from DevTools console? 

Maybe you have some issues with assets. What browser do you use?

**Comment by yivo** [comment]
My staging server with Peatio works well, but I use Docker for deployment. Do you?

**Comment by Alex-Shilman** [comment]
@yivo, No I don't use docker. Should I be using Docker?

**Comment by yivo** [comment]
@Alex-Shilman It is better to use Docker since it is more stable environment. I recommend you to check this issue on devel (it will soon be merged into master). You may open the issue if bug still exists. Thanks.
