### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by parthagorai** [openware/peatio#325]
Hi, Can you please update the installation document, i am interested to install in production mode.

**Comment by yivo** [comment]
Hello @Microinstance 

Unfortunately, docs aren't fresh now. We will try to update the docs along with 0.2.5 release on the next week. Now you can use `Dockerfile` & `travis.yml` to get Peatio running.

Production install supports only Docker deployment.

**Comment by stedrew** [comment]
Hi yivo,

Just wondering if you have plans in updating the docs to build a production environment.
I tried using Dockerfile and .travis.yml to build a docker image. And I managed to push the docker image built by Travis CI to a docker repo. But when I tried to run a container spun up from the image, it still requires MySQL server information and setting env variables didn't seem to work.

Would really appreciate if you could update the docs to at least help get the basic production deployment running.

**Comment by pkucherenk0** [comment]
Please app date README.md API section. Links are removed or broken.

**Comment by yivo** [comment]
Partially closed via #1062 #1041.
