### ISSUE TITLE
ActionView::Template::Error (couldn't find file 'yarn_components/raven-js/dist/raven' with type 'application/javascript'

### ISSUE THREAD

**Issue by Miro-Marinov** [openware/peatio#326]
`ActionView::Template::Error (couldn't find file 'yarn_components/raven-js/dist/raven' with type 'application/javascript'
Checked in these paths: 
  /home/miro/peatio/app/assets/images
  /home/miro/peatio/app/assets/javascripts
  /home/miro/peatio/app/assets/stylesheets
  /home/miro/peatio/vendor/assets/javascripts
  /home/miro/peatio/vendor/assets/stylesheets
  /var/lib/gems/2.3.0/gems/clipboard-rails-1.7.1/vendor/assets/javascripts
  /var/lib/gems/2.3.0/gems/clipboard-rails-1.7.1/vendor/assets/stylesheets
  /var/lib/gems/2.3.0/gems/grape-swagger-ui-2.2.8/vendor/assets/fonts
  /var/lib/gems/2.3.0/gems/grape-swagger-ui-2.2.8/vendor/assets/images
  /var/lib/gems/2.3.0/gems/grape-swagger-ui-2.2.8/vendor/assets/javascripts
  /var/lib/gems/2.3.0/gems/grape-swagger-ui-2.2.8/vendor/assets/stylesheets
  /var/lib/gems/2.3.0/gems/momentjs-rails-2.17.1/vendor/assets/javascripts
  /var/lib/gems/2.3.0/gems/bourbon-4.3.4/app/assets/stylesheets
  /var/lib/gems/2.3.0/gems/angularjs-rails-1.3.15/vendor/assets/javascripts
  /var/lib/gems/2.3.0/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /var/lib/gems/2.3.0/gems/coffee-rails-4.2.2/lib/assets/javascripts
  /var/lib/gems/2.3.0/gems/datagrid-1.5.7/app/assets/stylesheets
  /var/lib/gems/2.3.0/gems/bootstrap-sass-3.2.0.2/assets/stylesheets
  /var/lib/gems/2.3.0/gems/bootstrap-sass-3.2.0.2/assets/javascripts
  /var/lib/gems/2.3.0/gems/bootstrap-sass-3.2.0.2/assets/fonts
  /var/lib/gems/2.3.0/gems/bootstrap-sass-3.2.0.2/assets/images
  /var/lib/gems/2.3.0/gems/font-awesome-sass-4.7.0/assets/stylesheets
  /var/lib/gems/2.3.0/gems/font-awesome-sass-4.7.0/assets/fonts):
    1: <div class="container">
    2:   <div class="logo">
    3:     <a href="https://peatio.tech" target="blank">
    4:       <img src="<%= ENV['LOGO_URL'] || image_path('logo.svg') %>">
    5:     </a>
    6:   </div>
    7: 
  app/assets/javascripts/admin.js:1
  app/views/welcome/index.html.erb:4:in _app_views_welcome_index_html_erb__918132180626797990_47254631302740'
  lib/middleware/security.rb:11:in call'
  lib/middleware/i18n_js.rb:9:in call'
  Rendered /var/lib/gems/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (36.4ms)
  Rendered /var/lib/gems/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (19.1ms)
  Rendered /var/lib/gems/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.4ms)
  Rendered /var/lib/gems/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (129.2ms)
`

Tried installing the `raven-js` dependency globally via `sudo npm i -g yarn` but to no avail - still getting the above-mentioned error. Any help would be greatly appreciated.

**Comment by Miro-Marinov** [comment]
Solved via: bundle exec rake tmp:create yarn:install assets:precompile

**Comment by yivo** [comment]
Hello @Miro-Marinov  

Unfortunately, docs aren't fresh now. We will try to update the docs along with 0.2.5 release on the next week. Now you can use `Dockerfile` & `travis.yml` to get Peatio running.

For your issue running `bundle exec rake yarn:install` will be enough.

**Comment by ilerrajtadros** [comment]
I am having this same isue:
ActionView::Template::Error (couldn't find file 'yarn_components/raven-js/dist/raven' with type 'application/javascript'

Tried bundle exec rake yarn:install but didn't get it to work
