### ISSUE TITLE
bundle exec rake assets:precompile issue

### ISSUE THREAD

**Issue by parthagorai** [openware/peatio#328]
Hi, i am installing peatio in Production but geting error while runing bundle exec rake assets:precompile issue please help 
![error](https://user-images.githubusercontent.com/6851996/35211516-c3b62fd2-ff7c-11e7-8e8e-ad93825641b0.jpeg)

**Comment by yivo** [comment]
Hello @Microinstance 

You need to install missing deps: `bundle exec rake yarn:install`.

**Comment by yivo** [comment]
You can get the full steps for running Peatio in Dockerfile or travis.yml.

**Comment by parthagorai** [comment]
Hi, 
After runing **bundle exec rake yarn:install** when i am runing bundle exec rake assets:precompile nothing is happning

**Comment by yivo** [comment]
Hi @Microinstance 

You should consider reading about [asset pipeline](http://guides.rubyonrails.org/asset_pipeline.html). There are many cases why it will not run or output nothing.
