### ISSUE TITLE
Add support for Litecoin

### ISSUE THREAD

**Issue by yivo** [openware/peatio#333]

**Comment by yivo** [comment]
1. Read Peatio source code for BTC & XRP
2. Add LTC the same way

**Comment by yivo** [comment]
3. Deposit, withdraw, trading should work

**Comment by GildedHonour** [comment]
I'll take this.

**Comment by yivo** [comment]
@GildedHonour Please base your branch on v2.0 and target your PR to the same branch. Push PR as you start working.

**Comment by GildedHonour** [comment]
There're several tasks for v2.0. Shouldn't I create a separate branch for this issue -- issue_333? 

Why should I create a PR right as I start working?

**Comment by yivo** [comment]
@GildedHonour Fork repo & create new branch per issue. Branches should be based on v2.0. Submit PR as you start working. We would like to see the progress.

**Comment by yivo** [comment]
Closed via #402.
