### ISSUE TITLE
Add support for Ethereum (daemon)

### ISSUE THREAD

**Issue by yivo** [openware/peatio#334]

**Comment by GildedHonour** [comment]
I'll take this too.

**Comment by yivo** [comment]
https://github.com/ethereum/wiki/wiki/JSON-RPC

**Comment by yivo** [comment]
@GildedHonour Please base your branch on v2.0 and target your PR to the same branch. Push PR as you start working.

**Comment by GildedHonour** [comment]
I'm mostly finished with it. @yivo Should the CoinRPC::Ethereum class provide all the methods that  that are exposed from Ethereum RPC?

**Comment by yivo** [comment]
Hello @GildedHonour 

I don't think we need all of the methods. Only some important are required.

Yesterday we have merged into devel unified interface for cryptocoin APIs.
You can view it here – https://github.com/rubykube/peatio/blob/devel/lib/coin_api.rb.
It has poor docs now (I am going to fix this week) and no examples.

Can you try implementing some drafts for this interface in v2.0 but with fallbacks to old interface?
I recommend you to connect to bitcoin node and play with API so you will learn what structures new interface returns.

**Comment by GildedHonour** [comment]
@yivo  I've implemented some of the methods of Ethereum RPC, draft version, not tested.  I think I'll implement them all because most of them have similar interface.

I've checked out https://github.com/rubykube/peatio/blob/devel/lib/coin_api.rb. I'll first implement Ethereum RPC as is, using the same methods names from ETH RPC, and then we should be able to incorporate it into coin_api.rb easier.

**Comment by yivo** [comment]
@GildedHonour You can also refer to BitGo Express REST API since we recently started use BitGo actively. API ref is here – https://www.bitgo.com/api/v2/.

**Comment by GildedHonour** [comment]
I'm finished with a draft version of ETH RPC. Testing and refactoring is what's left.

**Comment by GildedHonour** [comment]
@yivo I'm finished with it. Not tested yet, I'll test it. 
Since it's a rush, you might want to merge it as is. Or create a subtask and I'll test it afterwards.

**Comment by yivo** [comment]
Closed via #569.
