### ISSUE TITLE
Move hardcoded config files into database and make them dynamic

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#344]

**Comment by subaru9** [comment]
https://www.evernote.com/l/AYPS6GpMBNVGcrArsrBPSMxzU2LTuYKmjPYB/image.png
just to make sure.. @mkuvshynnikov we are talking about this files, right?

**Comment by yivo** [comment]
@mitjok I will write the details tomorrow. Don't start the task.

**Comment by yivo** [comment]
@mkuvshynnikov Configs are not hardcoded. Configs are configs.

**Comment by ashanaakh** [comment]
😆

**Comment by subaru9** [comment]
@mkuvshynnikov, @yivo any updates here, thx

**Comment by yivo** [comment]
Hello @mitjok 

Your task is described here – https://github.com/rubykube/peatio/issues/279

**Comment by yivo** [comment]
@mkuvshynnikov ping
