### ISSUE TITLE
Add support for Monero

### ISSUE THREAD

**Issue by yivo** [openware/peatio#345]

**Comment by GildedHonour** [comment]
I can take this.

**Comment by yivo** [comment]
Linked issue #113.

**Comment by EarlVadim** [comment]
I do not understand. Why a new issue thread? 
It would be better to create a solution to the problem than another thread.

**Comment by EarlVadim** [comment]
Sorry, When to expect this improvement?

**Comment by wolflingsu** [comment]
Any news?

**Comment by mrheinen** [comment]
Is this still planned ?  Does anyone know a peatio fork that added cryptonote already ?

**Comment by mrheinen** [comment]
Is this a good example change @yivo ?
https://github.com/rubykube/peatio/commit/c22336243fb2fb1e6c24f3efba92bd15ef0df7c8

I'm a dev for a cryptonote coin called Ombre. I can allocate time to add Ombre and people will be able to use it as an example to add other cryptonote coins.

**Comment by vitorgamer58** [comment]
Exchange Graviex have support for Monero and Cryptonote Coins, Her list Niobio Cash (CN-Heavy) and Blood Donatio Coin (Cryptonight V0). 
https://github.com/gravio-net/graviex
PEATIO BASED

**Comment by EarlVadim** [comment]
In Graviex-repo no cryptonight support.

**Comment by vitorgamer58** [comment]
I could swear CNT within that file referred to **Cryptonote**
https://github.com/gravio-net/graviex/blob/master/app/services/coin_rpc.rb#L29

**Comment by EarlVadim** [comment]
it's half-work only ... there need daemon... it hardest...

**Comment by vitorgamer58** [comment]
really I took a look and Graviex despite having added the BBRC in the code, does not seem to have put all the details, probably made the sharing without being in github.

**Comment by jonn4y** [comment]
did anyone take this issue on?

**Comment by nnzo** [comment]
It would be really great if this gets done, there are more and more cryptonote/monero based coins appearing

**Comment by GonzoTheDev** [comment]
3 years and no solution, wow
