### ISSUE TITLE
Update aasm to 4.x

### ISSUE THREAD

**Issue by yivo** [openware/peatio#352]

**Comment by yivo** [comment]
@yssavchuk Pls check this commit – https://github.com/yivo/peatio/commit/a486e55ccaaaed868990be3736c4c9eba5cf60a1

Test it and push if everything is OK.

**Comment by yivo** [comment]
Also pls remove debug statements.

**Comment by ysv** [comment]
Everything is okay with deposit
But withdraw_coin doesn't work need to debug it

**Comment by yivo** [comment]
@yssavchuk Sure. Can you start?

**Comment by ysv** [comment]
@yivo It was my fault review please #369

**Comment by yivo** [comment]
Closed via #369.
