### ISSUE TITLE
SocketError

### ISSUE THREAD

**Issue by JustinSeidl** [openware/peatio#36]
Trying to setup the project locally for the first time. When I start the server and navigate to the application I get the following SocketError. Followed the MacOS instructions and don't know what I am missing.

<img width="1408" alt="screen shot 2017-12-01 at 2 47 10 pm" src="https://user-images.githubusercontent.com/502625/33503110-19227e56-d6a8-11e7-95e6-0839f6addec0.png">

**Comment by JustinSeidl** [comment]
Here is the console error in full:

```
Started GET "/" for 127.0.0.1 at 2017-12-01 18:48:05 -0600
  ActiveRecord::SchemaMigration Load (1.2ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by WelcomeController#index as HTML
  Member Load (0.4ms)  SELECT `members`.* FROM `members` WHERE `members`.`disabled` = 0 AND `members`.`id` IS NULL ORDER BY `members`.`id` ASC LIMIT 1
Completed 500 Internal Server Error in 19ms

SocketError - getaddrinfo: nodename nor servname provided, or not known:
  app/models/global.rb:59:in `ticker'
  app/models/market.rb:54:in `ticker'
  app/controllers/application_controller.rb:119:in `set_gon'
  lib/middleware/security.rb:11:in `call'
  lib/middleware/i18n_js.rb:9:in `call'

Started POST "/__better_errors/f2bf849bbb6ec229/variables" for 127.0.0.1 at 2017-12-01 18:48:05 -0600
```

Any help would be greatly appreciated.

**Comment by JustinSeidl** [comment]
@yivo @dkkoval ^

**Comment by dmk** [comment]
You can't read Rails cache so I guess your app can't connect to Redis. Make sure your Redis server is running and you have `REDIS_URL` in `config/application.yaml`.

**Comment by yivo** [comment]
@JustinSeidl By default app.yml sets `REDIS_URL` to `redis://redis:6379`. You have got this error since your machine can't resolve IP address to host `redis`. If you will change `redis` to `localhost`, for example, it should work. Either add `127.0.0.1 redis` to your hosts. We probably should change it by default.

**Comment by JustinSeidl** [comment]
@dkkoval @yivo thanks for the help! I'm all setup and hoping to contribute in the near future.

**Comment by dmk** [comment]
@JustinSeidl we will be happy to see you among our contributors! 😉
