### ISSUE TITLE
File system exhaustion on exception while handling AMPQ messages

### ISSUE THREAD

**Issue by ang-st** [openware/peatio#364]
Hi,

i noticed that when an exception occurs in handling an ampq message, peatio happily flood its log file until ENOSPC.

It happens on any ampq queue but an easy step to reproduce is : 
```
/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"bla", "channel_key":"notexist"}'
```

As the message isn't pull off the queue, peatio throw the error in loop, append to log, repeat ... ad-nauseam 

I'm not sure about what could be a sane behaviour here, as it can happen, when for example, SMTP server is down, and on other side, we don't want to miss a notification.

**Comment by yivo** [comment]
Hi @ang-st 

This is designed behavior. Peatio will infinitely repeat job fetched from queue. I think we will refactor this when we will move to Rails 5. Now you should consider enabling log rotation for your logs.

**Comment by ang-st** [comment]
Ok, seems it will do the jobs as a workaround.
Thanks for your quick reply

**Comment by yivo** [comment]
@ang-st No problem. We have added this behavior since Peatio doesn't requeue messages which it fails to process (actually RabbitMQ does it but if you running single daemons instance (1 consumer) it doesn't receive message again). A little bit complicated, but for now it works well.

**Comment by yivo** [comment]
If you have any questions please reopen or create new issue. Thanks.
