### ISSUE TITLE
Getting 404 from Google when trying to login 

### ISSUE THREAD

**Issue by DanielGorlo** [openware/peatio#370]
I'm using an EC2 with a non-docker installation.

After logging in with Google, I'm being redirected to localhost, which is inaccessible from the outside of the EC2 instance.

Where can I find the google redirection config?
![image](https://user-images.githubusercontent.com/567232/35390018-a04caa5e-01e2-11e8-8df7-f04362509f9f.png)

**Comment by yivo** [comment]
Hello @DanielGorlo 

Try to tweak URL_* config vars [here](https://github.com/rubykube/peatio/blob/master/lib/generators/config/templates/application.yml.erb#L12).

**Comment by DanielGorlo** [comment]
@yivo - thanks for the quick response. Unfortunately, by tweaking it to the host of the EC2 I'm getting an error from google mentioning they don't have a callback registered for this url:

![image](https://user-images.githubusercontent.com/567232/35390450-303a3b6c-01e4-11e8-937b-6aea9c916bcc.png)

**Comment by yivo** [comment]
@DanielGorlo You should configure redirect URL at your Google App.

**Comment by DanielGorlo** [comment]
@yivo - Thanks!!
