### ISSUE TITLE
Importing existing order books

### ISSUE THREAD

**Issue by DanielGorlo** [openware/peatio#371]
Is there an option to import order books and data from external exchanges?

I want to kickstart the system to see how it works in action.

**Comment by yivo** [comment]
Hello @DanielGorlo 

Unfortunately there is no way to do it automatically now. The current implementation is too shitty and too complicated. You may try to import some testnet money and trade with your friends, either request demo from https://peatio.tech either write your own script which feeds database with some orders. If your question is solved please close an issue. Thanks

**Comment by nebchan** [comment]
really interested in this, if i can get something simple working i will submit here

**Comment by nebchan** [comment]
@yivo would it be possible to do this (query external orderbook and present on platform) by just using the extracted trading UI on rails, instead of the whole implementation?

**Comment by yivo** [comment]
@b1naryc0re Hi. I can't answer for this questions right now. We would like to find most flexible way of separating UI and API.
