### ISSUE TITLE
Fiat deposit screen

### ISSUE THREAD

**Issue by rickguedes** [openware/peatio#374]
How is the fiat deposit screen supposed to work?
The "Deposit account" combo is always empty. Clicking on "Manage" returns a javascript error (actually a typo on the link, "javascripts:" ).
Nothing happens when I submit.
Am I missing some config file related to this? Couldn't find anything related in the docs.

Running 0.2.5 with peatio-workbench.

![image](https://user-images.githubusercontent.com/5911443/35417603-4c0299f8-0215-11e8-9de4-73a099fabba3.png)

**Comment by yivo** [comment]
Hello @duduric 

If you click "Manage" you will see modal window which you can use for adding deposit account. For me it works, ever with `javascripts` protocol. I checked this in Chrome & Opera. But you are right – probably this is the reason why it doesn't work for you. We will fix protocol name. Thanks.

**Comment by yivo** [comment]
@yssavchuk Could you please check whole project for such procol name?

**Comment by rickguedes** [comment]
That was the problem indeed. Not working on Firefox due to the typo in the protocol, just fixed it in my end. Thanks!

**Comment by yivo** [comment]
@duduric Fixed in #378.
