### ISSUE TITLE
Naviagating to /admin/ reroutes to root

### ISSUE THREAD

**Issue by DanielGorlo** [openware/peatio#377]

**Comment by yivo** [comment]
Hello @DanielGorlo 

Could you please give details?

**Comment by DanielGorlo** [comment]
@yivo - sure.

I'm trying to login as an admin, so to my understanding I need to find the admin login and login using the admin credentials.

Unfortunately, when navigating to /admin route I'm getting an error which redirects me back to home screen.

Am I using the wrong route?

**Comment by yivo** [comment]
@DanielGorlo There is no any logins for admin. Add your email to application.yml in ADMIN and you will be admin.

<img width="341" alt="screen shot 2018-01-26 at 5 05 12 pm" src="https://user-images.githubusercontent.com/7421323/35445704-1a00f55c-02bb-11e8-9200-11efc2abe172.png">
