### ISSUE TITLE
Access admin module and approve profile

### ISSUE THREAD

**Issue by arshad-bilawat** [openware/peatio#382]
Hi,

I have set up peatio successfully. I have following questions

1. .How to I access admin module.
2. How do we approve account.
3. The user registration is removed from peatio and is moved to Auth0?

Regards,
Arshad Ali.

**Comment by yivo** [comment]
Hello @arshad-bilawat 

There was similar question. You can inspect it [here](https://github.com/rubykube/peatio/issues/377).

To verify account first get to admin panel and click "Verity account". Then you will see list of members and you can click button at the right to navigate to the form. Then click "Approve".

If your question is resolved pls close the issue.

Thanks.

**Comment by arshad-bilawat** [comment]
@yivo  Yes, Thank you. Closing the issue.

**Comment by sang-tech** [comment]
Hello @arshad-bilawat, I have added my email to ADMIN in application.yml but i see no admin button at the top right menu. am i missing something?
