### ISSUE TITLE
Can't connect Mysql

### ISSUE THREAD

**Issue by hungthinhcntt** [openware/peatio#390]
When run bundle exec rake db:setup
Error:
/home/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_str
ing_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarni
ngs::StandardWarning)/home/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/applicat
ion.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "tr
ue". (StructuredWarnings::StandardWarning)Access denied for user 'root'@'localhost' (using password: NO)Please prov
ide the root password for your MySQL installation

How to fix it
Thank so much

**Comment by shal** [comment]
Hi @GiangCoin 

You should specify your mysql root password in `config/database.yml` configuration file.

**Comment by hungthinhcntt** [comment]
Thanks for reply
I'm install Peatio v0.2.5 on ubuntu 16.0.4

I'm run: bundle exec rails server
but erro not working
/home/beanvn22/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)/home/beanvn22/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)=> Booting Puma
=> Rails 4.2.10 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop

**Comment by shal** [comment]
@GiangCoin Peatio is running on `localhost:3000`. It just warning from `Figaro`.

**Comment by hungthinhcntt** [comment]
Thank you for reply!
But it not work on my External IP address http://35.202.149.170:3000
