### ISSUE TITLE
few overlaps found 

### ISSUE THREAD

**Issue by Namresiac** [openware/peatio#395]
Found 3 minus overlaps : First one on https://platform.coinfield.work/settings and the twice others on https://platform.coinfield.work/markets/btcusd
![capture du 2018-01-29 13-51-17](https://user-images.githubusercontent.com/22836830/35511678-8a941ff0-0505-11e8-98c4-656603ded9c6.png)
![capture du 2018-01-29 14-12-15](https://user-images.githubusercontent.com/22836830/35511679-8aba9856-0505-11e8-993b-b2e05fc4075a.png)
![capture du 2018-01-29 14-32-30](https://user-images.githubusercontent.com/22836830/35511680-8ad990ee-0505-11e8-915b-00491f65f8a1.png)

**Comment by yivo** [comment]
Hello @Namresiac 

Could you pls describe what OS and browser you have used for testing (including versions)?

**Comment by Namresiac** [comment]
Hello @yivo 
Iwas using Ubuntu 16.04 LTS with Firefox Quantum 58.0

**Comment by yivo** [comment]
Closed via #576.
