### ISSUE TITLE
Confirmation mail

### ISSUE THREAD

**Issue by Namresiac** [openware/peatio#397]
When a deposit or a withdraw is done, the confirmation mail comes fast but it comes in "spam" of email box. Maybe just put a classical warning ? like "if not, please verify your spam box"
![capture du 2018-01-29 16-42-42](https://user-images.githubusercontent.com/22836830/35516335-2d72efea-0514-11e8-86f4-4c6aba5185ea.png)

**Comment by yivo** [comment]
Hello @Namresiac 

Thanks for your advice. We will review this feature.

**Comment by yivo** [comment]
Hi @Namresiac 

This issue is related to the way how you deliver the emails so it is sure not Peatio. Also we are looking to remove mailing completely from Peatio (#758).
