### ISSUE TITLE
Can't deposit funds

### ISSUE THREAD

**Issue by DanielGorlo** [openware/peatio#399]
When trying to deposit funds, I can't pick any 'Deposit account':

![image](https://user-images.githubusercontent.com/567232/35520086-b01fdc32-051e-11e8-9b5d-b6edb55d7fa7.png)

**Comment by yivo** [comment]
Hello @DanielGorlo 

Click `Manage`.

**Comment by yivo** [comment]
@DanielGorlo if your question is resolved pls close the issue. Thanks.
