### ISSUE TITLE
Production deployment v2.0

### ISSUE THREAD

**Issue by BitenCoin** [openware/peatio#401]
Is it possible to deploy v2.0 (0.2.5) branch the same way as the old master branch.
To be precise is it possible to deploy it with this https://github.com/rubykube/peatio/blob/master/docs/ops/deploy/ubuntu.md

**Comment by yivo** [comment]
Hello @BitenCoin 

At the moment docs are now up to date. We are going to update them soon when Peatio will became stable. We have such issue already (#325).

**Comment by yivo** [comment]
But you can try Docker deployment. It is up to date.
