### ISSUE TITLE
New feature proposition - Coin list voting

### ISSUE THREAD

**Issue by tzman89** [openware/peatio#403]
What do you think about this?
It should be like 1 free vote per week and paid votes with choosen coin.
This feature can earn decent amount of coins to exchange.
I see a lot of exchanges with this feature lately

**Comment by yivo** [comment]
Hello @tzman89 

I think coin listing is not in scope of exchange. It is more likely separate simple Node.js app with mostly static pages.

cc @mod @mkuvshynnikov

**Comment by tzman89** [comment]
@yivo Yes but it's usually connected with in app wallets and users are paying from their balances, also users can be forced to have some amount on the balance in order to be able to vote for free.That can increase amount of trades and active users on exchange.

I saw exchanges earning over 100BTC monthly just from coin list voting.

**Comment by yivo** [comment]
@tzman89 This sound exciting. I think you should contact @mkuvshynnikov for the details. Maybe we can find some solution.

**Comment by yivo** [comment]
@tzman89 I am closing this issue since Peatio is becoming more enterprise and in future it will be microservice with API only for wallets & trading.
