### ISSUE TITLE
Markets page should update list of orders when order is created

### ISSUE THREAD

**Issue by yivo** [openware/peatio#405]

**Comment by amir-budaychiev** [comment]
Hi @yivo. I was checking that issue, after creating order, markets page make updating the list of orders. It's ok for me. I don't see anything problem here. You can check my screencast: https://drive.google.com/open?id=1a4ddoOwZee0jpP_KH0z_1OLOhLZxePnd

**Comment by yivo** [comment]
Hello @amir-budaychiev 

Thank you for taking a part in it! 

Can you find a way to refresh list of orders without manually reloading page?

**Comment by yivo** [comment]
ping @mkuvshynnikov

**Comment by amir-budaychiev** [comment]
@yivo Sure. I can do that via realtime feature(gem pusher). What do you think about it?

**Comment by yivo** [comment]
@amir-budaychiev Can you please check if this feature is already implemented? I think it is but it is broken or disabled.

**Comment by amir-budaychiev** [comment]
@yivo all clear!

**Comment by amir-budaychiev** [comment]
Hello @yivo. I did double check. I think it works fine. Let's check again my screencast please: https://drive.google.com/open?id=133SUoMjxsKlE4YRC1LEif3VFmVPJ5FMC

**Comment by amir-budaychiev** [comment]
@yivo UPD I've fixed it, also it works fine from UI: https://drive.google.com/open?id=1m0wIqhbLMOWQC4XKDETn2gHQkfluX_Ts

**Comment by yivo** [comment]
@mkuvshynnikov Can you check what @amir-budaychiev prepared?

**Comment by yivo** [comment]
Closed. See https://github.com/rubykube/peatio/pull/455#issuecomment-363463859 and https://github.com/rubykube/peatio/pull/455#issuecomment-363740795.
