### ISSUE TITLE
After adding new coin Old users didint see it

### ISSUE THREAD

**Issue by ghost** [openware/peatio#409]
Hi,

I added coins, but old users dont see new coin how to fix it?

**Comment by ysv** [comment]
Hi @senisende! 
Thanks for you issue
Actually such problem exists because Member has many Accounts.
And accounts are created when user sign up.
Probably it's high priority issue and we need to fix it asap.
For now you can add Accounts manually or create new user.
@yivo ping

**Comment by yivo** [comment]
Hello @senisende 

It is known issue but not critical. You can run `bundle exec rails r "Member.find_each(&:touch_accounts)"`.

You can either setup cron job for it or run it manually when you add new coin.

**Comment by yivo** [comment]
If your question is resolved pls close the issue. Thanks.

**Comment by ghost** [comment]
Thanks "bundle exec rails r "Member.find_each(&:touch_accounts)" works fine.
