### ISSUE TITLE
Signatures randomly don't match when using keypair token authentication

### ISSUE THREAD

**Issue by yivo** [openware/peatio#41]
When using generating signature params should be normalized (normally sort by name alphabetically). See https://github.com/rubykube/peatio/blob/master/app/api/api_v2/auth/keypair_authenticator.rb#L67

This error may be produced when client and server used params to generate signature in different order. This error is related to non-proper data structure used to store params – hash since it doesn't provider order guarantees.

**Comment by mod** [comment]
does the bug exist? maybe grape will have a better token implementation

**Comment by yivo** [comment]
@mod The bug exists and is not related to grape (it is custom shared secret implementation) and can be easily fixed in 5 mins

**Comment by yivo** [comment]
@mod We just need to sort params
