### ISSUE TITLE
ReferenceError: log is not defined (JavaScript error at /documents/api_v2)

### ISSUE THREAD

**Issue by ymasiuk** [openware/peatio#420]
log is not defined for log("Loaded SwaggerUI") 
Swagger Issue 
![deepinscreenshot_select-area_20180131180946](https://user-images.githubusercontent.com/26141524/35633615-557cfc8e-06b2-11e8-9345-b641ebc781ee.png)

**Comment by yivo** [comment]
Please, work in devel.

**Comment by yivo** [comment]
Arshak90 decided to omit this task.
