### ISSUE TITLE
After adding new coin admin/withdraw/coins doesnt work

### ISSUE THREAD

**Issue by ghost** [openware/peatio#421]
Hi,

/admin/withdraws/coins peage gives me error "We're sorry, but something went wrong."

Bitcoin, bank and other altcoins /admin/withdraws working perfect.

**Comment by yivo** [comment]
Hello @senisende 

Can you please share the logs? Better to run app in dev env to get more output information. I am sure you have probably missed some file.

**Comment by ghost** [comment]
I solved problem. Actually i made mistake that coins.rb folder.
