### ISSUE TITLE
Market Notify on/off doesnt work

### ISSUE THREAD

**Issue by ghost** [openware/peatio#426]
Hi,

Market > Notify on/off doesnt work. How to fix it. Thanks.

**Comment by ghost** [comment]
any solution?

**Comment by yivo** [comment]
Hello @senisende 

Out UI expect will check it soon.

**Comment by dinesh-skyach** [comment]
Hi @yivo, Please could you let me know which notifications are being referred here and when does these notifications get triggered.

**Comment by prashantdhamija** [comment]
![notify](https://user-images.githubusercontent.com/35146363/37112352-28c91ef8-2268-11e8-9b53-06b8b489ba08.png)
Hi @dinesh-skyach Please check the attached screenshot. I think that is the issue being referred to here as the user is not able to toggle between notify on and off.

@yivo Please correct me if I'm wrong.

Thanks!

**Comment by ghost** [comment]
@yivo I already solved Notify issue.

`notifier.js.coffee  >  @setStatus(false) to @setState(false)`

**Comment by yivo** [comment]
@senisende @prashantdhamija Thank you!

@dinesh-skyach Could you please check these comments?

**Comment by dinesh-skyach** [comment]
@yivo I have tested this and found there is no issue with market notify toggle on/off button. 

In Addition the notifications seems to be working fine.

**Comment by yivo** [comment]
@dinesh-skyach What browser have you used? Can you check this in Firefox?

**Comment by dinesh-skyach** [comment]
@yivo I have tested this for chrome. Anyways I have found the issue. Please disregard my above comment.
