### ISSUE TITLE
Remove doorkeeper entirely

### ISSUE THREAD

**Issue by yivo** [openware/peatio#43]

**Comment by mod** [comment]
doerkeeper should be an oauth server,
you can use git blame or bisect to understand which commit introduce it.
paste it here

**Comment by yivo** [comment]
@mod It is https://github.com/rubykube/peatio/commit/1632ccb7d12095ceeb1383d354d456b751a5b143

**Comment by rhombl4** [comment]
@mod How do you plan to process authentication/authorization of client-application's requests to api?

**Comment by yivo** [comment]
@rhombl4 Server-to-server authentication is possible using keypair mechanism. While client-to-server works on top of OAuth2 protocol & JWT. You will need your own OAuth2 server (or you can use services ike Auth0).
