### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by mangeshgangwar** [openware/peatio#432]
Hi is there any way to make peatio fully responsive so that it can be viewed on mobile devices as well.

Thanks

**Comment by sang-tech** [comment]
short answer, yes.

The front end styling is completely separate from the back end mechanics. 

Technically you could restyle the exisiting with ccs or create a whole new front end. I'm toying with both ideas now but i need to sort out my admin access issue first...

**Comment by sang-tech** [comment]
more specifically i will be working on a responsive front-end either way as soon as i have the technical issue sorted out.

details to follow...

**Comment by yivo** [comment]
Hello @sang-tech @mangeshgangwar 

We have plans for recoding UI to Bootstrap 4 or som SPA framework like React.

**Comment by mangeshgangwar** [comment]
@yivo Thanks Thats great..
