### ISSUE TITLE
Example Setup MySQL 

### ISSUE THREAD

**Issue by endofthepain** [openware/peatio#433]
Hi, i need example for config mysql server  because i still get error

/usr/local/rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)Access denied for user 'root'@'localhost' (using password: NO)Please provide the root password for your MySQL installation
>

**Comment by GildedHonour** [comment]
I can take this.

**Comment by yivo** [comment]
Hello @endofthepain 

Consider reading MySQL docs first. Your issue is related to missing password for MySQL user.

When your question is resolved pls close the issue.

**Comment by endofthepain** [comment]
here my example 

`default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['localhost'] %>
  username: <%= ENV['root'] %>
  password: <%= ENV['mypassword'] %>

development:
  <<: *default
  database: peatio_development

test:
  <<: *default
  database: peatio_test

production:
  <<: *default
  url: <%= ENV['localhost'] %>
  pool: 10
  database: peatio_production`

.___. and still get error

**Comment by yivo** [comment]
Hello @endofthepain 

This is not an error. It opens prompt for password. Tweak your config for appropriate passwords and logins.
