### ISSUE TITLE
Docker tag mismatch 0.2.4 and 0.2.5

### ISSUE THREAD

**Issue by sandrodz** [openware/peatio#439]
<img width="396" alt="screen shot 2018-02-03 at 1 03 36 pm" src="https://user-images.githubusercontent.com/8479569/35765688-ba918446-08e2-11e8-8086-198439348fc0.png">
<img width="375" alt="screen shot 2018-02-03 at 1 03 42 pm" src="https://user-images.githubusercontent.com/8479569/35765689-baae12e6-08e2-11e8-88d8-c1f4db28708b.png">

I've pulled 0.2.5 release from this repo, but docker image was tagged 0.2.4

**Comment by yivo** [comment]
Hello @sandrodz 

We will assign someone to check this. Thanks for the report. Also consider using the devel branch since it is the most up to date.

**Comment by yivo** [comment]
Fixed in #458.
