### ISSUE TITLE
Adding Trollbox in Market

### ISSUE THREAD

**Issue by ghost** [openware/peatio#440]
How to add chat feature in Peatio?

**Comment by yivo** [comment]
Hello @senisende 

You should refer to chat docs for this feature. I am sure they have guides.

Please, close an issue when your question is resolved. Thanks.

**Comment by ghost** [comment]
@yivo 

Chat docs: https://github.com/peatio/chatroom

**Comment by yivo** [comment]
@senisende I think you can find docs there.

**Comment by yivo** [comment]
@senisende I am closing your issue since it is more related to chat implementation but not Peatio. Peatio doesn't include one-line chat integration for services like Trollbox.
