### ISSUE TITLE
Can't access admin. Have added email to application.yml

### ISSUE THREAD

**Issue by sang-tech** [openware/peatio#441]
I have seen the other two threads on the subject already but it did not solve the issue for me.

Am I missing something?

**Comment by sang-tech** [comment]
I'm assuming i login with google and not oauth

**Comment by yivo** [comment]
Hello @sang-tech 

The login method makes no difference. Can you provider your current application.yml?

Please, close an issue when your question is resolved. Thanks.

**Comment by sang-tech** [comment]
Hi @yivo,

Thanks for that. It was the application.yml. More specifically I had entered my email at the top but missed the google oauth section further down the file.

I'm still not in admin but this not due to the app, it is due to my lack of knowledge regarding configuring oauth callbacks on localhost. But I'll get there this is all new to me. Once I get my head around the architecture of this app and ruby/rails in general I'll be giving right back.

Keep up the good work all...
