### ISSUE TITLE
No signin/signup buttons on kubernetes deployment

### ISSUE THREAD

**Issue by mfaizanse** [openware/peatio#444]
Hi,
I have deployed peatio using this [guide](https://github.com/rubykube/peatio/blob/master/docs/ops/deploy/kubernetes.md), everything is successful but when I access the service, the page does not display any buttons.
![capture](https://user-images.githubusercontent.com/9897945/35774974-eb040324-09a0-11e8-8126-730c222d9eb5.PNG)

I am using rubykube/peatio:0.2.4 image. What could be the issue?

**Comment by mod** [comment]
Hello,

You need to activate one of the login system, google, auth0, or barong.

**Comment by mfaizanse** [comment]
@mod I have set the following environment variables:
```
GOOGLE_OAUTH2_SIGN_IN:      on
GOOGLE_CLIENT_ID:           1044454023387-emhp5vmfnp5cf1n9juk09g8gcckrova7.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET:       tAFZvO200-0z3MpCyOpkPH0G
```

But still no button. There is no error in kubectl logs. Is there anywhere else I can see the status?

**Comment by yivo** [comment]
Hello @mfaizanse 

What Docker image tag have you used?

**Comment by mfaizanse** [comment]
@yivo I am using rubykube/peatio:0.2.4 image

**Comment by yivo** [comment]
@mfaizanse I think we have some issue with tagging. Check https://github.com/rubykube/peatio/issues/439

Can you try using image from devel branch? It is much up to date.

**Comment by mfaizanse** [comment]
@yivo Should I create my own container image of peatio using the [devel branch](https://github.com/rubykube/peatio/blob/devel/docs/ops/deploy/kubernetes.md)? As the helm chart in devel branch is also referring to dockerhub rubykube/peatio:0.2.2.

**Comment by yivo** [comment]
@mfaizanse Hello. Unfortunately we haven't updated the chart which lives in public. We provide such services for enterprise clients only.

**Comment by yivo** [comment]
@mfaizanse Just set `OAUTH2_SIGN_IN_PROVIDER: google`. This solution may be applied only to devel branch.

**Comment by yivo** [comment]
If you still expect troubled with sign in you may reopen the issue.
