### ISSUE TITLE
Real Name Auth has problem

### ISSUE THREAD

**Issue by ghost** [openware/peatio#448]
Hi,

Members shouldnt edit "id_documents/edit" Real name auth. After they verfy account, it shouldnt be edit.

**Comment by yivo** [comment]
Hello @senisende 

I think this is useful feature. We will revise it. Thanks.

**Comment by yivo** [comment]
Actually Peatio's KyC is going to be fully moved to Barong. You may request this feature at https://github.com/rubykube/barong.
