### ISSUE TITLE
Add opportunity set value withdraw fee

### ISSUE THREAD

**Issue by ymasiuk** [openware/peatio#451]
![deepinscreenshot_select-area_20180205174215](https://user-images.githubusercontent.com/26141524/35813441-49fdaac8-0a9c-11e8-8895-a16ce4d5d53f.png)

**Comment by emasiuk** [comment]
![deepinscreenshot_select-area_20180205174215](https://user-images.githubusercontent.com/26141524/35813417-3f7291ea-0a9c-11e8-9926-f0c037028391.png)

**Comment by yivo** [comment]
Closed via #456.
