### ISSUE TITLE
Deposit address is displayed with offset to down (out of the box)

### ISSUE THREAD

**Issue by Namresiac** [openware/peatio#453]
![capture du 2018-02-05 19-46-41](https://user-images.githubusercontent.com/22836830/35820318-e9ac2a2a-0aad-11e8-8045-dc563cf5e8c0.png)

**Comment by yivo** [comment]
Hello @Namresiac 

This problem can be solved by making address container inline-block and setting to it white-space: nowrap.

**Comment by dinesh-skyach** [comment]
Hi @yivo Please can you let me know how do we generate the deposit address?

**Comment by yivo** [comment]
@dinesh-skyach You must have fully 100% working Peatio locally.

**Comment by yivo** [comment]
Closed via #605.
