### ISSUE TITLE
Withdraw in Fiat do not works, gives 403 Forbidden  Error

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#459]
![screen shot 2018-02-06 at 4 52 06 pm](https://user-images.githubusercontent.com/29736025/35866046-cec43372-0b5e-11e8-8a9c-38cd247553a8.png)

**Comment by yivo** [comment]
We found that this error is popped out only if you don't select withdraw destination. I think this is both UI & backend problem.

**Comment by yivo** [comment]
Fixed by https://github.com/rubykube/peatio/issues/588.
