### ISSUE TITLE
Markets switcher doesn't work

### ISSUE THREAD

**Issue by yivo** [openware/peatio#460]
<img width="461" alt="screen shot 2018-02-06 at 5 03 16 pm" src="https://user-images.githubusercontent.com/7421323/35866383-bf19f76c-0b5f-11e8-8803-211e03425def.png">

**Comment by yivo** [comment]
Fixed in #465.

**Comment by ysv** [comment]
@yivo need to open this issue once more because switcher was broken after https://github.com/rubykube/peatio/pull/411

**Comment by yivo** [comment]
@yssavchuk Damn. I have reopened it.

**Comment by yivo** [comment]
Fixed in #472.
