### ISSUE TITLE
Alternative for pusher

### ISSUE THREAD

**Issue by tzman89** [openware/peatio#464]
Did you make any alternative to pusher since it's not cheap option ?
I was checking maybe you can make it with https://github.com/joewalnes/websocketd it's simple but powerful and I think it will merge into peatio without any problems

**Comment by yivo** [comment]
Hello @tzman89 

I think https://github.com/stevegraham/slanger will fit your needs.

If your question is resolved please close an issue. Thanks.

**Comment by yivo** [comment]
Duplicate of #283.

**Comment by vitorgamer58** [comment]
how to configure the Slanger correctly together with Peatio, I tried and did not succeed.

```
  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8081 //Slanger also uses port 8080, thus generating a port conflict

  # pusher settings
  # --------------------------------------------------------------
  PUSHER_APP: ******
  PUSHER_KEY: *****
  PUSHER_SECRET: ******
  PUSHER_HOST: 127.0.0.1
  PUSHER_PORT: 4567
  PUSHER_WS_PORT: 8080
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true

```
but the generation of new addresses and deposits stopped working.
```
I, [2018-07-10T12:56:09.277452 #5482]  INFO -- : Started POST "/deposits/fermats/gen_address" for 108.162.212.184 at 2018-07-10 12:56:09 +0000
I, [2018-07-10T12:56:09.289475 #5482]  INFO -- : Processing by Private::Deposits::FermatsController#gen_address as HTML
I, [2018-07-10T12:56:09.289693 #5482]  INFO -- :   Parameters: {"fermat"=>{}}
I, [2018-07-10T12:56:09.310898 #5482]  INFO -- :   Rendered text template (0.0ms)
I, [2018-07-10T12:56:09.311209 #5482]  INFO -- : Completed 403 Forbidden in 21ms (Views: 0.7ms | ActiveRecord: 2.8ms)
```
but it worked again as soon as I undo the changes, it generated an address for each user who did not have it yet.
![](https://raw.githubusercontent.com/vitorgamer58/vitorgamer58-images/master/Screenshot_113.png)
