### ISSUE TITLE
Still a problem with the withdraw, here with BTC

### ISSUE THREAD

**Issue by Namresiac** [openware/peatio#467]
![capture du 2018-02-06 21-17-41](https://user-images.githubusercontent.com/22836830/35879231-59e619c4-0b83-11e8-9e2d-91b883004722.png)

**Comment by yivo** [comment]
I think this is related to https://github.com/rubykube/peatio/issues/446.

**Comment by yivo** [comment]
@yssavchuk Can you please check this with BitGo and confirm the bug? Please generate access token at BitGo (set spending limits only for BTC and specify IP address).

**Comment by ysv** [comment]
@yivo Actually such problem does exists with current version of BitGo
Here is output of broken sendcoins transactions from coinhub
`error 400: insufficient funds`
```local_express [07/Feb/2018:14:30:50 +0000] "POST /api/v2/tbtc/wallet/5a7b0a0d027fd29107d6aa0ecbd5f169/sendcoins HTTP/1.1" 400 118 "-" "Faraday v0.12.2"```

**Comment by yivo** [comment]
@yssavchuk Yeah. Can you just remove almost_done status and in case of error mark withdraw as failed?

**Comment by yivo** [comment]
Most of your changes would be in withdraw_worker.rb and some in views and locales.

**Comment by yivo** [comment]
Closed in #478.
