### ISSUE TITLE
On the trading interface

### ISSUE THREAD

**Issue by Namresiac** [openware/peatio#468]
- I've been credited: 650 CAD, but I don't have anything like this in my fund
- There are not LTC in the choice of the differents markets in the top left hand corner

**Comment by yivo** [comment]
@mkuvshynnikov Can you check this and prepare list of issues?

**Comment by yivo** [comment]
@mkuvshynnikov @Namresiac I think this issue was created by mistake. We haven't reproduced anything similar to this.
