### ISSUE TITLE
Google Auth error "Wrong customer ID or password,please try again."

### ISSUE THREAD

**Issue by tigwyk** [openware/peatio#470]
I've got Peatio running in docker. When I attempt to login via Google Auth, I get an error: "Wrong customer ID or password,please try again." But I am able to login via Auth0 and then choosing Google on the Auth0 screen.

This error occurred before I'd even created an account, but even after signing in for the first time using Auth0+Google and creating my account, I get the same error if I just choose Google Auth on the Peatio front page.

Currently running the v2 branch in Docker. I had this happening in the master branch too.

**Comment by yivo** [comment]
Hello @tigwyk 

I will check Google auth again. BTW it works well for me.

**Comment by yivo** [comment]
Linked issue #457.

**Comment by rayonx** [comment]
@tigwyk This might be a problem with Google+ API. To use OAuth you must enable Google+ API go to [google console](https://console.developers.google.com/apis/api/plus.googleapis.com/overview) and click Enable.

**Comment by tigwyk** [comment]
@rayonx That was precisely the issue. I had setup oauth credentials in the Google developer console but I didn't enable the Google+ API. Thank you!
