### ISSUE TITLE
Create api call to destroy withdraw addresses

### ISSUE THREAD

**Issue by ec** [openware/peatio#473]

**Comment by yivo** [comment]
@mafarain Is this very urgent?

**Comment by yivo** [comment]
I need to define priority: low, middle, high.

**Comment by ec** [comment]
I have a wip patch on the front side, that waits for api call. We have adding withdraw now, but not deleting, so it's quite urgent. Middle, i hope

**Comment by yivo** [comment]
@mafarain you can implement it by yourself. Implementation seems to be very similar to https://github.com/rubykube/peatio/blob/devel/app/api/api_v2/withdraws.rb#L54.

Use well-formed English desc and use REST JSON API conventions.

**Comment by yivo** [comment]
Accept HTTP DELETE and respond with 200.

**Comment by ec** [comment]
Ok, working on it

**Comment by ec** [comment]
https://github.com/rubykube/peatio/pull/479
you should check, i hope

**Comment by yivo** [comment]
Closed #479.
