### ISSUE TITLE
Not recognizing my email as Admin in application.yml

### ISSUE THREAD

**Issue by yozef** [openware/peatio#480]
I've added in `/lib/generators/config/templates/application.yml.erb`:
```
# admin role account
  ADMIN: 'my_email@gmail.com'
```

While ignoring Google OAuth for now, I've set to AUTH0 (from registering & getting API keys here: https://manage.auth0.com/#/apis ):
```
  AUTH0_OAUTH2_SIGN_IN: 'on' # Set to "on" to enable.
  AUTH0_OAUTH2_DOMAIN: peatt-dev.eu.auth0.com
  AUTH0_OAUTH2_CLIENT_ID: dZXXXXXXXXYl8gv3KXeb6SRPV
  AUTH0_OAUTH2_CLIENT_SECRET: kw3EZXXXXXXXXXXXXXXXXX_cah_T_BmzBYuXXXXXXXXXXAaXIE09JrG
  AUTH0_OAUTH2_REDIRECT_URL:  ~ # Specify URL address to which user will be redirected after successful sign in.
```

...then run again: `bundle exec rails server`
... goto: **http://localhost:3000**

I register for an account with email: my_email@gmail.com **with Auth0**; Then login, with my_email@gmail.com, however I don't see admin in the email dropdown after logging in. I don't think it knows that this user is admin, even though it's in application.yml
<img width="229" alt="2018-02-07 at 7 53 54 pm" src="https://user-images.githubusercontent.com/287256/35949672-b01a5f7c-0c40-11e8-88ae-a4ecccd4a67a.png">

Maybe I'm missing something?

**Comment by yivo** [comment]
`I've added in /lib/generators/config/templates/application.yml.erb:`

This is not correct. You should run `bin/init_config` and edit config/application.yml.

Better to use devel branch for now since it is going to be merged into master soon.

If you still expect this problem pls reopen issue.

**Comment by yozef** [comment]
Thank you @yivo :) 

Needed : `bin/init_config` & update `config/application.yml`
Then `bundle exec rake tmp:create yarn:install assets:precompile`
then run rails server: `bundle exec rails server`

**Comment by yivo** [comment]
@yozef No need for `assets:precompile` unless you are running production.
