### ISSUE TITLE
Cannot find translation at bank deposit/withdraw page

### ISSUE THREAD

**Issue by fansyfs** [openware/peatio#481]
<img width="1067" alt="untitled" src="https://user-images.githubusercontent.com/538516/35966151-fa987c34-0cf7-11e8-9d50-2f050bfaac96.png">

**Comment by yivo** [comment]
Hello @fansyfs 

Sprockets has cached dumped translations for JS. Just clear assets cache.

If you have still issue with this you may reopen ticket. Thanks.
