### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by yivo** [openware/peatio#490]

**Comment by yivo** [comment]
We need to check an ensure all Peatio models work with PG.

**Comment by subaru9** [comment]
@yivo what will be the indicators that "models work with PG"?
What version of `postgresql` should be tested?

**Comment by yivo** [comment]
@mitjok Pls test latest stable available. Project must be 100% compatible.

**Comment by yivo** [comment]
Closed via #572.
