### ISSUE TITLE
Add support for SQLite

### ISSUE THREAD

**Issue by yivo** [openware/peatio#491]

**Comment by yivo** [comment]
We need to check an ensure all Peatio models work with SQLite.

**Comment by nleo** [comment]
I curios why?

I'm glad you add support PostgreSQL. I love this DB and not understand initial developers which choose MySQL.

But SQLite? Really somebody will develop peatio with SQLite?? Or even run in production?

**Comment by yivo** [comment]
Hi @nleo,

I am sure anyone will not run Peatio with SQLite in production. This feature is more specific for QA guys and for automated testing in limited environment. I think Peatio already is OK with SQLite but this must be checked.

**Comment by yivo** [comment]
Not sure we will need this one.
