### ISSUE TITLE
market order

### ISSUE THREAD

**Issue by arshad-bilawat** [openware/peatio#498]
Market order is not enabled in the trading page. Right now only limit order is supported in trading page.

**Comment by yivo** [comment]
Hello @arshad-bilawat 

Can you provide the details?

**Comment by arshad-bilawat** [comment]
There are atleast two types order in any exchange:
1. Market Order
2. Limit Order.

The peatio supports only limit order as of now. Can we please add market order support.

**Comment by arshad-bilawat** [comment]
@yivo ping

**Comment by yivo** [comment]
@arshad-bilawat You can submit PR or contact https://peatio.tech/ for this feature.
