### ISSUE TITLE
Support for Ripple

### ISSUE THREAD

**Issue by proactive-dev** [openware/peatio#508]
Hi, @dkkoval @mod I wanna integrate ripple in Peatio.
I saw this branch has ripple, but has lots of differences between this branch and default peatio.
I wanna discuss sth about ripple.
Please feel free to ping me any time.
Waiting replies.

**Comment by yivo** [comment]
Hello @Apollo-IT 

Issues are not good place for business. Check https://peatio.tech/

Thanks
