### ISSUE TITLE
Yarn Error

### ISSUE THREAD

**Issue by davidanoel** [openware/peatio#512]
Guys getting this error when loading the site. Any ideas ? I think the instructions needs to be updated. e.g. It currently points to install ruby version Ruby 2.2.8

Template::Error (couldn't find file 'yarn_components/raven-js/dist/raven' with type 'application/javascript'

**Comment by yozef** [comment]
replicate: https://github.com/rubykube/peatio/issues/392

**Comment by davidanoel** [comment]
tnx
