### ISSUE TITLE
Charts doesn't work for BCH/CAD

### ISSUE THREAD

**Issue by ymasiuk** [openware/peatio#532]
![deepinscreenshot_select-area_20180216014346](https://user-images.githubusercontent.com/26141524/36287060-3ecbdc34-12bb-11e8-977a-98100da8f7d3.png)
while trading on BCH/CAD the charts won't show up after trade

**Comment by frezeq0** [comment]
bittrex opensource: https://github.com/frezeq0/bittrex-opensource

**Comment by Sambusik** [comment]
ok @frezeq0 stop spamming this repo.

**Comment by dinesh-skyach** [comment]
Hi @yivo, I have tested this and didn't get any issues with BCH/CAD.

![screen shot 2018-03-01 at 3 22 04 pm](https://user-images.githubusercontent.com/35770481/36838220-9e9a8d32-1d64-11e8-8dfb-00fff8e11c6b.png)

**Comment by yivo** [comment]
@dinesh-skyach Thanks. Seems like configuration issue.
