### ISSUE TITLE
Recommended approach to transfer exchange funds to cold wallet

### ISSUE THREAD

**Issue by nandhini-ramanujam** [openware/peatio#537]
Hi @yivo,

I have few questions regarding exchange wallet

1. What is the recommended approach to transfer bitcoins from hot wallet to any cold storage(80% in cold wallet and 20% in hot wallet for safety purpose)
2. If exchange's hot wallet has low amount, what is the recommended approach to transfer to exchange wallet?.
please clarify
Thanks in advance

**Comment by yivo** [comment]
Hello @nandhini-ramanujam

You would better ping @mod for this question.

As for my opinion I think your steps are correct: keep 80% in cold wallet, 20% in operational, and if operational wallet's balance is too low just transfer some from cold. I believe you will better understand and find the best approach when you will run your own exchange and play with real money.

**Comment by nandhini-ramanujam** [comment]
Hi @yivo,

Thanks for your response. I'll contact @mod for further details.

@mod can you explain the best approach to transfer fund from exchange hot wallet to any other paperwallet.

Once transferred to paper wallet , how to transfer it to exchange wallet again? (using any admin account?)

The address in the currencies.yml  seems to be unused. What is the purpose of adding it?

Please clarify.

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource

**Comment by yivo** [comment]
Hi @nandhini-ramanujam 

We have updated currencies.yml a lot. Please, check config/templates/seed/currencies.yml.erb for new options.

For any consultation about running an exchange I would better ping hello@peatio.tech
