### ISSUE TITLE
Error in production

### ISSUE THREAD

**Issue by hamid1989** [openware/peatio#540]
I managed to run peatio in development and it works great but when I run it in production I get this:
"An unhandled lowlevel error occurred. The application logs may have details."

Application log is empty

**Comment by yivo** [comment]
Hello @hamid1989 

We don't support passenger. Run app in docker and you will get output. Or you can update config/environments/shared/logger.rb to suit your needs.

**Comment by tzman89** [comment]
I didn't used passenger, I deployed it with docker and using localhost:3000, when I run rails server with RAILS_ENV=production I get this and no logs can be found.
I'm going to create new layout for peatio and I'm learning it's code so I can know what changes can cause app working problems.

**Comment by tzman89** [comment]
@hamid1989 

You need to update secret key in /config/secrets.yml
Just run "bundle exec rake secret" and copy the key to secret_key_base:
