### ISSUE TITLE
Incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by ysv** [openware/peatio#541]

**Comment by ysv** [comment]
Actually here is the problem itself ![screen shot 2018-02-18 at 3 02 26 pm](https://user-images.githubusercontent.com/19859122/36352212-1b2026f0-14be-11e8-8674-c7d4175a9337.png)

**Comment by ysv** [comment]
in this line '- ' wrong character https://github.com/rubykube/peatio/blob/6eb317c1b9a247ccc8f79e12a82148f8fe9eb248/lib/generators/config/templates/application.yml.erb#L121

**Comment by yivo** [comment]
Closed via linked commits.
