### ISSUE TITLE
Implement new fiat withdraw story

### ISSUE THREAD

**Issue by yivo** [openware/peatio#548]

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource

**Comment by ysv** [comment]
- [x] Add options to withdraw model

- [x] Refactoring fund_uid -> address & fund_extra -> label 

- [x] Update specs

- [x] Bank withdrawal fields

- [x] Refactor fund_sourcable

- [x] Update user view

- [x] Update admin views

- [x] WithdrawDestination model

- [x] Update Withdraw model to use WithdrawDestination

- [x] Update Withdraw controllers

- [x] Update API

- [x] WithdrawDestinationController

- [x] FundSource leftovers remove, drop tables & unused columns

- [x] Squash migrations

**Comment by stannak7** [comment]
Bittrex sourcecode: https://github.com/stannak7/bittrex-source-code

**Comment by ysv** [comment]
@yivo I think we need to rename issue

**Comment by yivo** [comment]
@yssavchuk Sure, any suggestions?
