### ISSUE TITLE
Address Generation Message

### ISSUE THREAD

**Issue by Namresiac** [openware/peatio#553]
When you ask to generate a new address, the message "You sure about... " appears.
Like every kind of button I push "Enter" by defaut, but an other message appear and is overlayed. As many messages as I push enter, and then I've to validate each one of them one after one... 
![push-enter](https://user-images.githubusercontent.com/22836830/36386746-7560a428-159f-11e8-87db-c0f6fd7912e9.png)

**Comment by Namresiac** [comment]
![push-enter-2](https://user-images.githubusercontent.com/22836830/36386912-132a3b6a-15a0-11e8-91f7-34820958c5ff.png)

For exemple after 10 pushes of "Enter" it's getting draker and darker

**Comment by yivo** [comment]
Closed via #593.
