### ISSUE TITLE
User BTC withdraw are auto-rejected?

### ISSUE THREAD

**Issue by Sambusik** [openware/peatio#560]
Trying to figure out if there is a setting somewhere as to why when a user withdraws BTC, these requests are automatically rejected?

Tried withdrawing 1 BTC & 0.01 BTC (dosen't seem to be the amount, nor the verification status of the user, as that user is verified)

Client Side:
<img width="300" alt="user_withdraw_history" src="https://user-images.githubusercontent.com/36517706/36463227-8130c3ee-1696-11e8-9956-6434fabc2ab8.png">

Admin:
<img width="300" alt="admin" src="https://user-images.githubusercontent.com/36517706/36463169-0cd00140-1696-11e8-9616-9e5fb22a7f7a.png">

**Comment by yivo** [comment]
Hello @Sambusik 

There are multiple cases why transaction may be rejected. Consider reading app/models/withdraw && app/models/workers/withdraw_coin.rb

**Comment by Sambusik** [comment]
thanks @yivo ;)
