### ISSUE TITLE
Ability to retrieve API key through API

### ISSUE THREAD

**Issue by calj** [openware/peatio#565]
That might sounds strange, but we would need to display the trading API keys on custom UI.
So we need a way to retrieve API keys using a JWT token.

**Comment by yivo** [comment]
@calj I think we need to discuss this with @mod

**Comment by frezeq0** [comment]
bittrex opensource: https://github.com/frezeq0/bittrex-opensource

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource

**Comment by yivo** [comment]
@calj I am closing this since we are going to keep only JWT for now. See #622 & #623.
