### ISSUE TITLE
Mysql url format

### ISSUE THREAD

**Issue by tzman89** [openware/peatio#568]
Hello,

Can anyone tell me how mysql url should look like in database.yml?
I'm trying to connect database from seperated server to use peatio with multi servers.
Also does peatio support new versions of mysql with phpmyadmin?

I will try my best to contribute here once I manage to fully run peatio

Thanks,

**Comment by yivo** [comment]
Hi @tzman89 

It depends on your DB and is related to Rails config not Peatio. Check http://edgeguides.rubyonrails.org/configuring.html#configuring-a-database

**Comment by yivo** [comment]
If you have any question pls open the issue. Thanks.
