### ISSUE TITLE
"undefined method `sum' for nil:NilClass" error when i click on "Solvency" page/menu item

### ISSUE THREAD

**Issue by allenmillen** [openware/peatio#577]
Guys, any idea how to fix this problem? Is this configuration issue?

It is happening on my local installation of Peatio, which i fetched yesterday

**Comment by yivo** [comment]
Hi @allenmillen 

Check https://github.com/rubykube/peatio/issues/73.

**Comment by sosospicy** [comment]
Same problem. Already run 'rake solvency:liability_proof' before start server, but error still be there.
