### ISSUE TITLE
When try to view details of failed withdrawal (as admin) i get following error

### ISSUE THREAD

**Issue by allenmillen** [openware/peatio#580]
“undefined method `id' for nil:NilClass”
http://localhost:3000/admin/withdraws/satoshis/1
<span><%= t('admin.withdraws.coins.show.withdraw', sn: @withdraw.id) %></span>

**Comment by yivo** [comment]
Thanks. I will check it.

**Comment by ysv** [comment]
@allenmillen thanks for report. Actually this bug exists. I will fix it asap

**Comment by yivo** [comment]
Closed in #595.
