### ISSUE TITLE
Themes support [proposal]

### ISSUE THREAD

**Issue by dutchakdev** [openware/peatio#584]
### Abstract
There is opensource project (capitan), so potentially anyone can use this project. But when anyone wants to customize something in views, they need to change it. It can create a problem with updating of codebase.

### Solutions
Remove views and SSR from a project, create views as third-party frontend on React, React Native, Angular etc.

**Comment by yivo** [comment]
Hi @dutchakdev 

We have this on TODO list.

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource

**Comment by stannak7** [comment]
Bittrex sourcecode: https://github.com/stannak7/bittrex-source-code

**Comment by yivo** [comment]
We are going to implement this in Peatio 2.0.
