### ISSUE TITLE
sql error when run " bundle exec rake db:setup "

### ISSUE THREAD

**Issue by ghost** [openware/peatio#586]
Error:
> -- initialize_schema_migrations_table()
>    -> 0.0043s
> rake aborted!
> ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'read_marks.reader_id' in 'where clause': DELETE FROM `read_marks` WHERE `read_marks`.`reader_id` = 1 AND `read_marks`.`reader_type` = 'Member' AND `read_marks`.`readable_type` = 'Comment'

Then I checked the table:
```
mysql> show columns from  read_marks;     
+---------------+-------------+------+-----+---------+----------------+
| Field         | Type        | Null | Key | Default | Extra          |
+---------------+-------------+------+-----+---------+----------------+
| id            | int(11)     | NO   | PRI | NULL    | auto_increment |
| readable_id   | int(11)     | YES  |     | NULL    |                |
| member_id     | int(11)     | NO   | MUL | NULL    |                |
| readable_type | varchar(20) | NO   | MUL | NULL    |                |
| timestamp     | datetime    | YES  |     | NULL    |                |
+---------------+-------------+------+-----+---------+----------------+
```

I don't know where to fix this sql err. Any help? Thanks!

**Comment by ghost** [comment]
I'll update my code and retry..

**Comment by yivo** [comment]
Hi @sosospicy 

I am sure you are using wrong fork of Peatio. We don't maintain this table anymore. You can read migration file and see that there is not such table.

**Comment by ghost** [comment]
Yes, I clone a wrong fork because I copy  "git clone git://github.com/peatio/peatio.git"  in step 9 (https://github.com/rubykube/peatio/blob/master/docs/setup-ubuntu.md) without recheck the link.
Sorry to disturb.

**Comment by yivo** [comment]
@sosospicy No problem :)
