### ISSUE TITLE
how can i desposit USD?

### ISSUE THREAD

**Issue by myriky** [openware/peatio#592]
i've cloned peatio v1.1.3. but i couldn't know how can i deposit USD.

could you tell me? what am i supposed to do.

<img width="1189" alt="2018-02-26 10 55 59" src="https://user-images.githubusercontent.com/581861/36649944-e77ab7a8-1ae3-11e8-80b0-63d4f1d3a920.png">

**Comment by myriky** [comment]
i've also read this issue #399. but i think it was mention about old version. i can't find 'Manage' button.

**Comment by dutchakdev** [comment]
same problem

**Comment by yivo** [comment]
@myriky @dutchakdev Hi

Navigate to admin panel -> Deposits -> Bank deposits -> Click «New deposit» -> Input bank details, member SN (on your screenshot it is called «Reference number») -> Fill amount -> Click «Accept» -> You are navigated to deposit list -> Finally, confirm deposit -> Money are loaded.

If you have issues with this please reopen ticket.
