### ISSUE TITLE
Withdrawal not getting through to test.bitgo account and testnet

### ISSUE THREAD

**Issue by batraamar** [openware/peatio#599]
As checked in the logs, withdrawals resulting into 404 Page not found for following url:
https://test.bitgo.com/api/v2/tbtc/wallet/5a8dd0cb76de85d7070a60e163789ec9/sendcoins

Returns 404 Page not found.

**Comment by yivo** [comment]
Hi @batraamar,

To use BitGo for withdrawal operations you should use BitGo Express Proxy: https://github.com/BitGo/BitGoJS/blob/master/src/expressApp.js

Please, read their docs: https://platform.bitgo.com/bitgo-express/ https://www.bitgo.com/api/v2/
