### ISSUE TITLE
JWT security issues

### ISSUE THREAD

**Issue by sergii-savchenko** [openware/peatio#600]
JWT dev and test shared secret contains both Private and Public keys

Peatio uses both operations: JWT.decode and JWT.encode (private key is needed for this operation)

JWT.encode is:

**/app/models/member.rb: 156. Member.jwt**
Method jwt should be removed permanently

-/spec/api_v2/auth/jwt_authenticator_specs.rb (low risk. Test/Dev keys only)
-/spec/api_v2/auth/middleware_spec.rb (low risk. Test/Dev keys only)

Description in config/secrets.yml of shared secrets generation should (probably) be moved to Barong  

```
  # This secret key is used for verifying JSON Web Tokens.
  #
  # Request this key from your JWT provider or generate one by running:
  #
  #   ruby -e "require 'openssl'; require 'base64'; print Base64.urlsafe_encode64(OpenSSL::PKey::RSA.generate(2048).to_pem)"
  #
  # Then send this token to your JWT provider.
  # Peatio and JWT provider should have the same key.
  # You may want to adjust key length or cipher.
  #
  # Development and test environments already include sample secret keys.
  #
  # You can generate valid JWT by running:
  #
  #   JWT.encode(payload, APIv2::Auth::Utils.jwt_shared_secret_key, 'RS256')
  #
  # To authenticate using JWT send it's value in "Authorization" header:
  #
  #   curl -H "Authorization: Bearer TOKEN" http://localhost:3000/api/v2/members/me
```
  
Or changed like that:

```
require "base64"
require "openssl"

privateKey = OpenSSL::PKey::RSA.generate(2048)
publicKey = privateKey.public_key

puts "BARONG KEY =>>>", Base64.urlsafe_encode64(privateKey.to_pem)
puts "PEATIO KEY =>>>", Base64.urlsafe_encode64(publicKey.to_pem)
```

To avoid possible problems on production environment, I recommend checking on start 

```
Utils.jwt_shared_secret_key.private? == false
Utils.jwt_shared_secret_key.public? == true
```
Administrators should be aware, that only public keys must be stored on Peatio side.

**Comment by yivo** [comment]
Closed via #669, #659, #660, #666.
