### ISSUE TITLE
When viewing details of withdrawal i get the following error

### ISSUE THREAD

**Issue by allenmillen** [openware/peatio#609]
http://peatio:8000/admin/withdraws/satoshis/2
undefined method `find_withdraw' for #<Admin::Withdraws::SatoshisController:0x00007ff4a82e9088>
      @app.call(env)

Can be fixed by making mehtond find_wihdraw public (not sure if this proper fix thought)

**Comment by ysv** [comment]
@yivo this bug is confirmed
just reproduced localy

**Comment by frezeq0** [comment]
bittrex opensource: https://github.com/frezeq0/bittrex-opensource

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource

**Comment by stannak7** [comment]
Bittrex sourcecode: https://github.com/stannak7/bittrex-source-code
