### ISSUE TITLE
Ripple Security Issue

### ISSUE THREAD

**Issue by proactive-dev** [openware/peatio#612]
@dkkoval  Hi. I've checked your branch. (https://github.com/dkkoval/peatio )
Thanks for your ripple work.
But I've found some issues in generating new address in ripple.

1. You used ripple Api v1 to generate address. Is it Ok now? now ripple api v2 is used. v1 api looks deprecated.
2. if  you generate new address with api, where secret key of new address is saved?
 for security, it should not be saved in ripple api node (https://api.altnet.rippletest.net:5990).

Can you answer to this questions?
Waiting your replies.
Regards.

**Comment by dmk** [comment]
Hello @Apollo-IT. Please make sure you are using latest master in [rubykube/peatio repository](https://github.com/rubykube/peatio). We are not using that Ripple API now.

I'm closing this issue since it's not related to the fresh peatio version. Feel free to reopen if you have questions about the latest master.

**Comment by Apollo-IT** [comment]
thanks.

**Comment by proactive-dev** [comment]
hi @dkkoval 
please check this
i think this uses old api v1
https://github.com/rubykube/peatio/pull/602/commits/147843521f015407b92f1cb343cfe0bb7c3247d1

also i asked 2 questions above. but you've not answered

**Comment by yivo** [comment]
Hi @Apollo-IT,

We are working on new Rippled API client implementation. It will be compatible with latest Ripple JSON RPC.

**Comment by proactive-dev** [comment]
but i cant find any code for it.
I mean generating new addess.

**Comment by yivo** [comment]
@Apollo-IT It is WIP.

**Comment by proactive-dev** [comment]
i can help WIP
I'm working on ripple too

**Comment by proactive-dev** [comment]
can you share with me ripple code?
