### ISSUE TITLE
It is not possible to select some timeranges at markets

### ISSUE THREAD

**Issue by shal** [openware/peatio#613]
Hi
I can't choose `1m` on trading page, I think because styles broken by dropdown with markets.

![video](https://user-images.githubusercontent.com/15674738/36755628-737a3ca6-1c15-11e8-8d89-21c486385000.gif)

**Comment by frezeq0** [comment]
bittrex opensource: https://github.com/frezeq0/bittrex-opensource

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource
