### ISSUE TITLE
Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components

### ISSUE THREAD

**Issue by alebeta90** [openware/peatio#614]
Hello friends, when running:

alebeta@peatio-ex01:~/peatio$ bundle exec rake db:setup --trace

I get the next message: 
Im running Ruby 2.5.0

alebeta@peatio-ex01:~/peatio$ bundle exec rake db:setup --trace
/home/alebeta/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
peatio_development already exists
peatio_test already exists
** Invoke environment (first_time)
** Execute environment
rake aborted!
Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components

thanks

**Comment by ghost** [comment]
Got same problem. Please check https://github.com/rubykube/peatio/issues/392 . Need to install yarn.

**Comment by yivo** [comment]
Hi @alebeta90 

Install Node.js, Yarn, and run `bundle exec rake tmp:create yarn:install`.
