### ISSUE TITLE
Funds not working - getting redirected to /settings

### ISSUE THREAD

**Issue by Mishul-G** [openware/peatio#615]
Whenever I try to access the "Funds" page, I get redirected to localhost:3000/settings

I see other people have this problem too but no one has directly written a solution regarding this. We have our google authenticator setup for 2FA. Another Problem - our mobile phone does not work for verification.

We are trying to setup a demo to demonstrate trades on the platform - is there a way around this? Would appreciate help in this as well.

Thank you.

**Comment by yivo** [comment]
Hi @Mishul-G,

This fork doesn't include 2FA or phone verification. So this can't be a problem.

I believe you posted the issue in wrong fork of Peatio.
