### ISSUE TITLE
Multisig Wallet Ethereum

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#621]
Hi Team,

I am exploring BitGo for multisig wallet having compatibility with Peatio. As per my understanding it is used only for Bitcoin. So I am searching for a multisig wallet for Ethereum that can connect with Peatio. Please let me know if any opensource wallet is available to achieve the same.

Regards
Abhishek

**Comment by stannak7** [comment]
Bittrex sourcecode: https://github.com/stannak7/bittrex-source-code

**Comment by prashantdhamija** [comment]
Hi Abhishek, Unlike Bitcoin, ETH does not have any native addressing mechanism for multisig. You can write a simple smart contract to achieve this. Please see this [link](https://github.com/ethereum/dapp-bin/blob/master/wallet/wallet.sol) for reference.

**Comment by yivo** [comment]
Hope your question is solved.
