### ISSUE TITLE
On the fly member registration in API by using JWT payload

### ISSUE THREAD

**Issue by yivo** [openware/peatio#623]

**Comment by stannak7** [comment]
Bittrex sourcecode: https://github.com/stannak7/bittrex-source-code

**Comment by mod** [comment]
@yivo this is the highest priority for us to continue testing on workbench the integration
https://github.com/rubykube/barong/commit/3196b9ca0ff749be7158c6dbbf6b8c13a6ca9999

We will also try to change the login flow on cryptobase @calj

**Comment by yivo** [comment]
Closed via #657.
