### ISSUE TITLE
Remove USD market

### ISSUE THREAD

**Issue by anbuhckr** [openware/peatio#628]
how to remove USD market and bank deposit/withdraw.

**Comment by yivo** [comment]
Hi

It is not possible to remove fiat ccy. But you can still disable deposit, withraw & trading for it via configs deposit_channels.yml, withdraw_channels.yml & markets.yml. Check bin/init_config.

**Comment by anbuhckr** [comment]
Hi,

Thanks for helping.
Now I can disable USD on market and funds page, but for withdraw and deposit on btc still showing the bank.
![untitled](https://user-images.githubusercontent.com/36891836/36958456-8d635960-206e-11e8-8d99-b30dacd7c1c6.jpg)
