### ISSUE TITLE
List markets path

### ISSUE THREAD

**Issue by tzman89** [openware/peatio#632]
Did you change path to market list (BTC markets,LTC markets...) Changing it in market.scss and client.yml is not doing anything.Also when click on those I dont get any pairs, there is only ltc-btc and btc-ltc 

![market](https://user-images.githubusercontent.com/35830811/36964669-a90b8f8c-2057-11e8-83a7-471e7884200a.png)

**Comment by yivo** [comment]
@tzman89 Hi

Could you please add more details? I did not get your issue.

**Comment by tzman89** [comment]
hi,
1. How to remove markets from the list which pops out on the right side, deleting it in market.scss and client.yml doesn't do anything?
2. Why when I choose any of the markets there is nothing shown, only "All Markets" show all pairs?

I managed to learn everything about peatio but market is bugging me after you made latest changes.

Also after adding currencies in mysql will it be easier to add new coins? I was about to make a shell script which will generate all files for new coins but adding it in mysql is making it hard.

**Comment by tzman89** [comment]
problem was in base and quote unit, I fixed it..thanks
