### ISSUE TITLE
Dynamic models, controllers, routes, and code itself for currencies

### ISSUE THREAD

**Issue by yivo** [openware/peatio#646]

**Comment by tzman89** [comment]
What do you think about shell script for automated adding new currencies.
Maybe with those steps:
1. Put configuration (coin name,rpc, on which coin it's based...)
2. Clone currency on which new currency is based
3. Rename files and content of new (cloned) currency with $SED -i 
After running script only thing left to do will be create pairs and test everything.

I know current files will need changes but this script can save alot of time when adding new currencies.

**Comment by yivo** [comment]
Hi @tzman89 

Adding new currencies is based on three steps:
1) Add currency config to config/seed/currencies.yml
2) rake db:seed
3) Code API client

That's all. We are going away from peatio/peatio way of duplicating tons of lines of code. We recently refactored the whole project to be able to fetch currencies from database, not ActiveYAMLBase.

**Comment by yivo** [comment]
The idea it to unify all of these into three:
![image](https://user-images.githubusercontent.com/7421323/37148358-e4b0566c-22d2-11e8-8e9f-eac3c90727c6.png)

* BaseController
* BanksController
* CoinsController

**Comment by tzman89** [comment]
I see, thanks for explanation I wasn't sure how currencies in db thing works but now it's much clear.

So as I understand controllers for other currencies should be the same if the currency is based on any of the current ones,we can use key from currencies.yml to determine new currency controller.

I'm following your work here and you did a great job with this, you got it to almost perfect platform.
It will be fantastic when you implement ActionCable and also only Monero is left to add and it will have all currency types.
