### ISSUE TITLE
Peatio API does not cancel all orders

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#650]
Peatio API does not cancel all orders | Endpoint: peatio.tech/api/v2/orders/clear
-- | --
  | Method: POST
  | Params: (Optional) side:buy/sell
  | Result: All orders are returned back, just like getting all orders

**Comment by yivo** [comment]
Put on hold until we get reply.

**Comment by mkuvsh** [comment]
Fixed by latest version of Peatio
