### ISSUE TITLE
Peatio publishes too many messages in Pusher

### ISSUE THREAD

**Issue by yivo** [openware/peatio#652]
We need to find out which component does this crap and fix.

**Comment by yivo** [comment]
We found that global_state.rb is responsible for this.

We calculated that total events this daemon publishes is `60/(20+1*0.1+3)*(20+1)*60*24=355765`

where 20 is number of markets
3 is delay

**Comment by dinesh-skyach** [comment]
Channel:- markets-global
![screen shot 2018-03-12 at 6 26 31 pm](https://user-images.githubusercontent.com/35770481/37284806-f6a966f8-2622-11e8-99ba-b2d48998e7c5.png)

Channel:- market-btcusd-global
![screen shot 2018-03-12 at 6 23 13 pm](https://user-images.githubusercontent.com/35770481/37284821-06e5a464-2623-11e8-9272-dbe89c505052.png)

**Comment by yivo** [comment]
@dinesh-skyach Thanks.

**Comment by dinesh-skyach** [comment]
@yivo I have tested this via 5 sec and 10 sec delay and it does not have much effect on markets page. So we can use 5 or 10 sec delay.

**Comment by yivo** [comment]
@dinesh-skyach @mod @mkuvshynnikov Bug not confirmed. All these events are mandatory for markets to work great.
