### ISSUE TITLE
no mina-slack.git ??

### ISSUE THREAD

**Issue by ssltrustcomau** [openware/peatio#654]
getting error when doing bundle install:

fatal: remote error: 
  Repository not found.
Git error: command `git clone 'git://github.com/peatio/mina-slack.git' "/var/lib/gems/1.9.1/cache/bundler/git/mina-slack-0215d920fc3f3fb7ee3183c70ce0af9e737a0649"
--bare --no-hardlinks` in directory /usr/local/share/peatio has failed.

**Comment by zyfu90** [comment]
Hi, can you share how did you solve this problem?

**Comment by ssltrustcomau** [comment]
I havn’t, it is becoming a big problem to get this to work as all the install docs are out of date.

**Comment by yivo** [comment]
@ssltrustcomau @zyfu90 Guys, please post the issues in peatio fork you are using! We stripped this gem several months ago!

**Comment by zyfu90** [comment]
@yivo I tried his fork: https://github.com/InfraexDev/peatio 
Although there are still some issues, but they can be easily fixed.
