### ISSUE TITLE
Error on Database Setup: Use strings for Figaro configuration.

### ISSUE THREAD

**Issue by ssltrustcomau** [openware/peatio#655]
root@exchange:/usr/local/share/peatio# bundle exec rake db:setup --trace
/usr/local/rvm/gems/ruby-2.2.8/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)
rake aborted!
SyntaxError: /usr/local/share/peatio/lib/tasks/barong.rake:25: syntax error, unexpected keyword_rescue, expecting keyword_end
      rescue => e
            ^
/usr/local/rvm/gems/ruby-2.2.8/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.8/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.2.8/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.8/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.8/gems/railties-4.2.10/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.8/gems/railties-4.2.10/lib/rails/engine.rb:658:in `each'
/usr/local/rvm/gems/ruby-2.2.8/gems/railties-4.2.10/lib/rails/engine.rb:658:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.8/gems/railties-4.2.10/lib/rails/application.rb:452:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.8/gems/railties-4.2.10/lib/rails/engine.rb:453:in `load_tasks'
/usr/local/rvm/gems/ruby-2.2.8/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.2.8/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/share/peatio/Rakefile:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/lib/rake/application.rb:82:in `block in run'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.8/gems/redis-rack-2.0.3/bin/rake:17:in `load'
/usr/local/rvm/gems/ruby-2.2.8/gems/redis-rack-2.0.3/bin/rake:17:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.8/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.2.8/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.8/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.8/bin/ruby_executable_hooks:15:in `<main>'

**Comment by yivo** [comment]
Hi @ssltrustcomau 

1. This is not an error, it is warning from Figaro.
2. Your error is `rake aborted! SyntaxError: /usr/local/share/peatio/lib/tasks/barong.rake:25`
3. Use Ruby 2.5
