### ISSUE TITLE
Api for getting stats from aggregated orders

### ISSUE THREAD

**Issue by ghost** [openware/peatio#670]
It is necessary to have api for aggregate orders
Output values should be ready to use with average on period, max, min, volume

**Comment by calj** [comment]
A good design is to duplicate orders in AMQP queues and have workers aggregating those queues in average, max, min, volume per periods (10m, 15m, hourly, daily, ...)

Redis is a good candidate to store the aggregated data plots.

**Comment by yivo** [comment]
@akhlopiachyi @calj What is the priority for it?

**Comment by ysv** [comment]
We have discussed with calJ, this issue could be closed

**Comment by yivo** [comment]
@yssavchuk Thanks!
