### ISSUE TITLE
/usr/local/share/peatio/Gemfile:65: syntax error, unexpected ':', expecting $end

### ISSUE THREAD

**Issue by ssltrustcomau** [openware/peatio#671]
getting this error when doing bundle install:

/usr/local/share/peatio/Gemfile:65: syntax error, unexpected ':', expecting $end
gem 'god', '~> 0.13.7', require: false

versions:
root@exchange:/usr/local/share/peatio# gem -v
2.7.3
root@exchange:/usr/local/share/peatio# ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

**Comment by yivo** [comment]
Hi @ssltrustcomau 

Could you pls provide full log?

**Comment by yivo** [comment]
@ssltrustcomau I am closing this as no feedback for 7+ days. We haven't ever had this issue. If this still  relevant for you please reopen. Thanks.
