### ISSUE TITLE
Peatio doesn't not update order status after it is executed

### ISSUE THREAD

**Issue by yivo** [openware/peatio#683]
We need to confirm this bug.

> Once order is executed the status does not change to "done" and therefore does not show up on in `/api/v2/orders?state=done&market=btccad`.

**Comment by dinesh-skyach** [comment]
Hi @yivo I have tested this and it's working fine.
![screen shot 2018-03-13 at 4 15 13 pm](https://user-images.githubusercontent.com/35770481/37338147-8be059f2-26dc-11e8-86f2-1805f6294429.png)
![screen shot 2018-03-13 at 4 17 58 pm](https://user-images.githubusercontent.com/35770481/37338148-8c389036-26dc-11e8-8174-64d94c5d4bb2.png)

**Comment by yivo** [comment]
@mkuvshynnikov ping

**Comment by yivo** [comment]
Bug not confirmed.
