### ISSUE TITLE
Charge the FEE in the "base currency" 

### ISSUE THREAD

**Issue by MariaBog** [openware/peatio#695]
JDAX wants always charge the fee in the “base currency”. This means that if the user buys BTC on BTC/ZAR, the fee is in BTC. If they sell BTC on BTC/ZAR, the fee is BTC. If the buy ETH on ETH/BTC, the fee is in ETH. If they sell ETH on ETH/BTC the fee is in ETH.
Maria: Please make prioritization and how much time it will take to implement it.

**Comment by yivo** [comment]
This can be customized in markets.yml.
