### ISSUE TITLE
BitcoinCash address should be converted to legacy format

### ISSUE THREAD

**Issue by yivo** [openware/peatio#704]

**Comment by ysv** [comment]
- Official specs
https://github.com/bitcoincashorg/spec/blob/master/cashaddr.md
- Service
https://cashaddr.bitcoincash.org/
- Source code (go)
https://github.com/schancel/cashaddr-converter
- Source code (javascirpt)
https://github.com/bitcoincashjs/bchaddrjs
- Source code (javascript)
https://github.com/bitcoincashjs/cashaddrjs

**Comment by yivo** [comment]
@yssavchuk I will put this task on hold.

**Comment by ysv** [comment]
@yivo also take a look here https://github.com/sipa/bech32/tree/master/ref/ruby
