### ISSUE TITLE
What is account Summary? How it is working?

### ISSUE THREAD

**Issue by khalidNascenia** [openware/peatio#706]
In markets page, at the top, there is a dropdown named "Summary". What is this and how do this work?

Would appreciate if anyone please elaborate me on this. Thanks in advance.

![screen shot 2018-03-19 at 12 28 43 pm](https://user-images.githubusercontent.com/7381563/37581089-2ae2ce8e-2b71-11e8-8b30-1cb520086354.png)

**Comment by Sambusik** [comment]
How did you get USDT?
I think USDT runs on the Omni Network... have you managed to get that going with their JSONRPC?

**Comment by yivo** [comment]
Hi @khalidNascenia 

Maybe this screenshot will give you better understanding:
![image](https://user-images.githubusercontent.com/7421323/37603277-e4543586-2b96-11e8-88ec-4ef70b2be80c.png)

**Comment by murugan116** [comment]
@khalidNascenia DId you get USDT integrated ? Can you provide some help in integrating ?

**Comment by satheshhmax** [comment]
@khalidNascenia DId you get USDT integrated ? Can you provide some help in integrating ?

**Comment by khalidNascenia** [comment]
No. Not integrated!
