### ISSUE TITLE
Markets switcher doesn't work  

### ISSUE THREAD

**Issue by ysv** [openware/peatio#707]

**Comment by ysv** [comment]
![deepinscreenshot_select-area_20180319143023](https://user-images.githubusercontent.com/19859122/37595965-487de7b4-2b83-11e8-8c51-336fd91664a9.png)

**Comment by yivo** [comment]
@ashanaakh You test this at peatio.trade

**Comment by yivo** [comment]
Moved to https://github.com/rubykube/peatio-trading-ui/issues/7.
