### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by italocoin-project** [openware/peatio#712]
When i compile peatio i get this error

`ilie88@vps145866:/usr/local/share/peatio$ bundle exec rake db:setup
rake aborted!
NoMethodError: undefined method `yield_self' for false:FalseClass
/usr/local/share/peatio/config/plugins.rb:1:in `<top (required)>'
/usr/local/share/peatio/config/application.rb:10:in `require_relative'
/usr/local/share/peatio/config/application.rb:10:in `<top (required)>'
/usr/local/share/peatio/Rakefile:5:in `require'
/usr/local/share/peatio/Rakefile:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)`

I can't figure out why 'yield_self' is undefined.

**Comment by yivo** [comment]
Hi @italocoin-project 

Use Ruby 2.5

**Comment by italocoin-project** [comment]
I will try now, thanks
