### ISSUE TITLE
Seperated trading UI

### ISSUE THREAD

**Issue by tzman89** [openware/peatio#713]
Hi, 
How trading ui is deployed in development?
Is it automaticly included in peatio if we docker deploy it ?

**Comment by endofthepain** [comment]
yeah i need to know to

**Comment by yivo** [comment]
Hi @tzman89 @endofthepain 

Please, check https://github.com/rubykube/peatio/blob/master/docs/releases/1.5.0.md#breaking-changes for more details about trading UI. You will find all links there. Reply here if you have questions. In dev you should setup NGINX with conf from ci/nginx/server.conf and run Peatio at peatio.local (don't forget to configure URL_HOST at config/application.yml). As for trading UI: run it on port 4000 and put PLATFORM_ROOT_URL to http://peatio.local. That's should work.

**Comment by top1st** [comment]
Hello @yivo  we must use only docker on development mode also?
after docker pull where i can find them downloaded path?
And i want to customize the peatio-trading-ui with new
What is the solution?

**Comment by yivo** [comment]
@top1st You are free to choose. I personally don't use Docker for dev.

**Comment by top1st** [comment]
Oh great. I downloaded the peatio-trading-ui but i don't know how to add it to current peatio installed 
And you said you used rails 5.1 for trading ui. What is the solution that i can use them without docker and at once as development mode?

**Comment by yivo** [comment]
@tzman89 Please read my comments above.

**Comment by top1st** [comment]
hello @yivo  should i change rabbitmq channel_key from satoshi to btc?

**Comment by tzman89** [comment]
@yivo thanks for the comment

I figure it out, I didnt see that peatio-trading-ui is acting as seperate app and needs to be started with rails server.I just installed screen to run both seperatly and fixed nginx and it works.

Sorry for stupid questions I'm learning ruby, 2 months ago I didn't even know that ruby exist

**Comment by yivo** [comment]
@top1st I think you need to change it to account_id: https://github.com/rubykube/peatio/blob/master/app/models/payment_address.rb#L14

@tzman89 No problem. If your issue is resolved please close the ticket.

**Comment by not-a-dev0** [comment]
Could someone please share their NGINX config changes they made for the trading ui to show up. I am trying to deploy it on AWS
