### ISSUE TITLE
Respect field «state» from OmniAuth data

### ISSUE THREAD

**Issue by yivo** [openware/peatio#722]

**Comment by yivo** [comment]
1. Ensure barong updates state at the member after document approval or any other ops
2. I need the current omniauth payload from barong so I can test peatio again
3. Update specs at Peatio and code updating process of state at Peatio
4. Update Barong with docs for field state

**Comment by mod** [comment]
We should unify creation and verification in a gem if it helps, what is the issue reported ?

I just understand we use the wrong state

**Comment by yivo** [comment]
@mod We got some misunderstanding between Account#state & Profile#state in barong.

**Comment by yivo** [comment]
Fixed by #724.
