### ISSUE TITLE
AssetsController #partial_tree is broken

### ISSUE THREAD

**Issue by ysv** [openware/peatio#723]
I'm not sure we still use this route
Probably the solution is ```@json      = account.partial_trees.last.to_json.html_safe```
![deepinscreenshot_select-area_20180322135335](https://user-images.githubusercontent.com/19859122/37769879-2d80c5d0-2ddb-11e8-9804-95dae8d57866.png)

**Comment by yivo** [comment]
@yssavchuk If it is not used anywhere we can remove this action and route.

**Comment by yivo** [comment]
Or if it is used we need to make it work.

**Comment by yivo** [comment]
Closed by #741.
