### ISSUE TITLE
Base fiat currency is not specified

### ISSUE THREAD

**Issue by top1st** [openware/peatio#731]
@yivo 
I have problem with your last version 
Could you help me what is my problem?

![image](https://user-images.githubusercontent.com/23559697/37807163-019c24ba-2e7f-11e8-8402-d3e07839eecf.png)

Where i have to set base fiat currency?

**Comment by ysv** [comment]
@top1st you need to run rake currencies:seed first of all

**Comment by ysv** [comment]
you can find answer in realest notes for 1.3
https://github.com/rubykube/peatio/blob/master/docs/releases/1.3.0.md

**Comment by yivo** [comment]
@top1st Hi. @yssavchuk poster you an answer. If you still have issue with this please reopen the ticker. Thank you.

**Comment by top1st** [comment]
okay i have done rake db:seed
@yivo 
I think you don't need the coin.rake file
am i right?
