### ISSUE TITLE
Your account has been disabled, contact admin if you have any problem.

### ISSUE THREAD

**Issue by endofthepain** [openware/peatio#732]
![screenshot_367](https://user-images.githubusercontent.com/11496089/37824273-a5324bf6-2ebe-11e8-86da-483796dad9c6.png)

i try to re install with fresh database on peatio and barong and i get this error

**Comment by yivo** [comment]
Hi @endofthepain 

Have you confirmed your email at barong?

**Comment by yivo** [comment]
Also please put here versions which you use for peatio & barong.

**Comment by endofthepain** [comment]
![screenshot_368](https://user-images.githubusercontent.com/11496089/37824809-72b208cc-2ec0-11e8-8203-d0bffbaa2111.png)

on barong i generate account use bundle exec rake db:seed

**Comment by yivo** [comment]
@endofthepain I think this issue is related to Barong. Could you please show account state at Barong? You will be `disabled` at Peatio unless the state on Barong equals to `active`.

**Comment by yivo** [comment]
ping @gfedorenko

**Comment by endofthepain** [comment]
![screenshot_369](https://user-images.githubusercontent.com/11496089/37825249-b958f7a8-2ec1-11e8-97db-941a1c3bea1b.png)

**Comment by yivo** [comment]
@endofthepain We resolved this issue yesterday. Could you please get edge Barong version?

**Comment by yivo** [comment]
@endofthepain https://github.com/rubykube/barong/pull/279

**Comment by gfedorenko** [comment]
@endofthepain @yivo 
PR still wasn't merged. 
https://github.com/rubykube/barong/pull/279

**Comment by yivo** [comment]
@endofthepain We have just merged 279 at barong. You can try master. If problem still occurs please reopen the issue. Thanks.

cc @gfedorenko
