### ISSUE TITLE
Specs are failing with seed 59081

### ISSUE THREAD

**Issue by yivo** [openware/peatio#733]

**Comment by dinesh-skyach** [comment]
Hi @yivo ,

I am getting this error while running Rspec. Is this the same error that we have to fix?

![screen shot 2018-03-29 at 18 14 17](https://user-images.githubusercontent.com/35770481/38089451-16202c8a-337d-11e8-8516-f2a7d59f9177.png)

**Comment by yivo** [comment]
@dinesh-skyach You have 5 failing specs but I can see on screenshot only last 2. I think these failures are related to this issue.

**Comment by yivo** [comment]
Closed via #796.
