### ISSUE TITLE
Help me understand how wallet works

### ISSUE THREAD

**Issue by feiyan-cs** [openware/peatio#736]
Hello, I am trying to understand how peatio wallet works. Do all the coins deposited immediately transferred to a central hot wallet? For example if a user A deposits 10 ETH to his peatio wallet. Does this 10 ETH immediately automatically transfers again into peatio's central hot wallet?

And when this user withdraw his ETH, does the ETH comes from central wallet?

**Comment by feiyan-cs** [comment]
If there's no central wallet, what if this user somehow gets more ETH than he originally deposited (by trading successfully), and want to withdraw?

**Comment by yivo** [comment]
Hi @feiyan-cs 

The implementation details depend on the currency and currency service you are using (such as BitGo or classic currency daemon).

Simple answer: imagine there is one single wallet which can produce unlimited amount of addresses using BIP32 technology. Each address is associated with member on peatio and used to track his transactions. But really there are no any addresses and balances, there is only single balance. So withdraw after trading will work for any amount less than total money on peatio.

Complex answer: you will need to find time to read existing peatio source code and get familiar with existing currencies. It is hard to describe how does it work now.

Please, clone an issue if your question is resolved.

Thanks.

**Comment by feiyan-cs** [comment]
Thank you for your reply. I am particular asking for native ethereum implementation. AFAIK there's no BIP32 support for native ethereum / geth? 

I tried to read through peatio source code but cannot find much info regarding hotwallet and its logic.

That's why Im asking here see if anyone know this on top of his/her head.

**Comment by feiyan-cs** [comment]
When signing an ETH transaction, one has to specify "from" address. Assuming such a HD wallet exists that has the balance of all its sub addresses, what the "from" address should be? The first address?

**Comment by feiyan-cs** [comment]
Seems there are usually two approaches:
1 is to deploy smart contract for each user to automatically forward any ether tokens to the main wallet
2 is to manually "sweep" any deposited tokens to the main wallet by exchange

I assume peatio is 2 but I cannot find any related code within source.

**Comment by yivo** [comment]
@feiyan-cs The main code for these kind of things lives in app/models/workers/ and in lib/daemons/.

**Comment by yivo** [comment]
@feiyan-cs Please, reopen issue if you still have questions about wallets. Thanks!
