### ISSUE TITLE
Trade not working

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#738]
I have taken the latest code and make the peatio server up. But trade screen seems broken and giving the below error: 

The URL you requested was not found.
Rails.root: /usr/local/share/peatio

Application Trace | Framework Trace | Full Trace
app/routers/routing_essentials.rb:3:in `not_found!'
app/routers/black_hole_router.rb:5:in `call'
lib/middleware/security.rb:11:in `call'
lib/middleware/i18n_js.rb:9:in `call'

Please help me how to resolve this issue.

**Comment by yivo** [comment]
Hi @sharmaabhishek2207 

Please, take a loot at release notes for 1.5: https://github.com/rubykube/peatio/blob/master/docs/releases/1.5.0.md

It will help you to resolve issue.

**Comment by archana209** [comment]
Running on macOS 10.12.6 (16G1036)
I have setup nginx proxy and configured both apps on 3000 and 4000 port but I still get

The URL you requested was not found.
Rails.root: /Users/myname/rubykube/peatio

value of PLATFORM_ROOT_URL  is set as http://localhost:3000 in peatio-trading-ui/config/application.yml

My nginx.conf file below

server {
        listen       80 default_server;

        server_name  localhost;
        location ~ ^/(?:trading|trading-ui-assets)\/ {
        proxy_pass http://127.0.0.1:4000;
        }

        location / {
        proxy_pass http://127.0.0.1:3000;
        }

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
}

**Comment by yivo** [comment]
@archana209 Don't use localhost. It behaves differently. Use some domain.

**Comment by archana209** [comment]
Thanks @yivo : it worked now

**Comment by ghost** [comment]
its working now but its look as if css is broken
