### ISSUE TITLE
KeyError: key not found: "REDIS_URL"

### ISSUE THREAD

**Issue by hamid1989** [openware/peatio#739]
When trying rake db:setup or any rake db I'm keep getting KeyError: key not found: "REDIS_URL" and "PUSHER APP CLIENT" and go on.
It looks like all <%= ENV[''] %> are not recognized

What am I missing ?
I even tried with doing everything from begining but the same result

**Comment by yivo** [comment]
Hi @hamid1989 

Exec `bin/init_config` and try again.

**Comment by hamid1989** [comment]
Thanks, I dont know how I missed this
