### ISSUE TITLE
Deposit address not generated

### ISSUE THREAD

**Issue by tzman89** [openware/peatio#746]
I've everything setup, deamons work,rabbitmq work, json work but there is no address shown in account.
I tried with multiple currencies and always the same problem
I added pics which shows everything
This is fresh install of Peatio 1.5.0
What can cause this problem ?

![address](https://user-images.githubusercontent.com/35830811/37906283-d771ab12-3101-11e8-95ad-419d32e71edb.png)
![addressacc](https://user-images.githubusercontent.com/35830811/37906196-90b8e4ec-3101-11e8-8a55-610106dad8a0.png)
![god status](https://user-images.githubusercontent.com/35830811/37906197-90e08286-3101-11e8-973f-24c58fa39e4b.png)
![rabbit](https://user-images.githubusercontent.com/35830811/37906198-9106f7fe-3101-11e8-8d26-9aa61e6ab4d5.png)

**Comment by tzman89** [comment]
I fixed it, for everyone here. If you want this to work you need to put all user,pass,port info in currencies.yml before rake db:seed.
If you have already have done rake db:seed then you need to delete currency from db and run rake db:seed again

**Comment by sosospicy** [comment]
Hi, same problem.
I checked the table ` currencies`.  I guess the key is the value of `json_rpc_endpoint`.
like this:  
`"api_client":"BTC",
"json_rpc_endpoint":"http://*****:************@127.0.0.1:18332"`
But it seems right.... I use curl to getnewaddress and I got right response.
I deleted all from table currencies,  checked json_rpc_endpoint value in config/seed/currencies.yml ,  and run 'rake db:seed' , rows in table are all same as before, and the BTC address still be empty.
