### ISSUE TITLE
Unable to add coin withdrawals address

### ISSUE THREAD

**Issue by abdoukarim** [openware/peatio#747]
"Add" button is not working on 1.5.0 release.
<img width="795" alt="withdraws" src="https://user-images.githubusercontent.com/589039/37908048-6589e98e-30f6-11e8-81d9-7ed333ee11b8.png">

**Comment by yivo** [comment]
Hi @abdoukarim 

Try clearing your cache browser & Sprockets cache.

**Comment by yivo** [comment]
If you still has issues with this please reopen the ticker. Thanks.
