### ISSUE TITLE
bundle exec rake db:setup failure

### ISSUE THREAD

**Issue by feiyan-cs** [openware/peatio#748]
I am trying to set up a instance under ubuntu 14.04LTS manually because that workbench way doesn't work. However I ran into this error

rake aborted!
NoMethodError: undefined method `yield_self' for false:FalseClass
/root/peatio/config/plugins.rb:1:in `<top (required)>'
/root/peatio/config/application.rb:10:in `require_relative'
/root/peatio/config/application.rb:10:in `<top (required)>'
/root/peatio/Rakefile:5:in `require'
/root/peatio/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.8/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.8/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.8/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by yivo** [comment]
Please, use ruby 2.5

**Comment by feiyan-cs** [comment]
You really should update your documents as it still uses ruby 2.2.8

**Comment by ShaileshPrajapati-BTC** [comment]
same issue
rake aborted!
```
NoMethodError: undefined method `yield_self' for false:FalseClass
/home/botree/project/peatio/config/plugins.rb:4:in `<top (required)>'
/home/botree/project/peatio/config/application.rb:15:in `require_relative'
/home/botree/project/peatio/config/application.rb:15:in `<top (required)>'
/home/botree/project/peatio/Rakefile:8:in `<top (required)>'
/home/botree/.rvm/gems/ruby-2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
```
(See full trace by running task with --trace)

**Comment by babman92** [comment]
@yivo can you help me, please
I got this error but little bit difference

> deploy@instance-1:~/peatio/current/config$ bundle exec rake db:setup
(in /home/deploy/peatio/current)
rake aborted!
LoadError: cannot load such file -- bump
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:33:in `require'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/acti
ve_support/dependencies.rb:291:in `block in require'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/acti
ve_support/dependencies.rb:257:in `load_dependency'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/acti
ve_support/dependencies.rb:291:in `require'
/home/deploy/peatio/current/lib/tasks/release.rake:1:in `<main>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/acti
ve_support/dependencies.rb:285:in `block in load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/acti
ve_support/dependencies.rb:257:in `load_dependency'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/acti
ve_support/dependencies.rb:285:in `load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/eng
ine.rb:650:in `block in run_tasks_blocks'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/eng
ine.rb:650:in `each'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/eng
ine.rb:650:in `run_tasks_blocks'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/app
lication.rb:515:in `run_tasks_blocks'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/eng
ine.rb:459:in `load_tasks'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rai
ltie.rb:190:in `public_send'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rai
ltie.rb:190:in `method_missing'
/home/deploy/peatio/current/Rakefile:10:in `<top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `
<top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `
eval'
/home/deploy/peatio/current/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `
<main>'
(See full trace by running task with --trace)

___

This is my env:
OS: Ubuntu 14.04 on GCP
> deploy@instance-1:~/peatio/current/config$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
deploy@instance-1:~/peatio/current/config$ rails -v
Rails 5.2.3

Thanks you all very much.
