### ISSUE TITLE
Market wont accept any buy or sell orders

### ISSUE THREAD

**Issue by tzman89** [openware/peatio#749]
Hi,
What can be the reason for market not accept any buy sell order, also there is no possibility to put price lower than 0.001 (I have currencies on balance), see image
![market](https://user-images.githubusercontent.com/35830811/37950273-392311fc-3198-11e8-8f85-cfe42e533bce.png)
![balance](https://user-images.githubusercontent.com/35830811/37950516-16a0f9fe-3199-11e8-8226-d0e1f51d54f7.png)

Also what can be the reason for deposits not showing on funds page but coins get to main wallet and address is generated

**Comment by tzman89** [comment]
I get this when running trading, I tried run it with docker but I get the same result

`ActionController::RoutingError (No route matches [GET] "/trading-ui-assets/locales/en-cf080e53748d764904c12591bc05eb0d6997696148e7ee1d5ddf45fc00e51535.js"):

actionpack (5.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.5) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.5) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.4) lib/rack/method_override.rb:22:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.5) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
railties (5.1.5) lib/rails/engine.rb:522:in `call'
puma (3.11.3) lib/puma/configuration.rb:225:in `call'
puma (3.11.3) lib/puma/server.rb:624:in `handle_request'
puma (3.11.3) lib/puma/server.rb:438:in `process_client'
puma (3.11.3) lib/puma/server.rb:302:in `block in run'
puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
`

**Comment by yivo** [comment]
@tzman89 Hi. Please, send us all the configs you have. Also clear sprockets cache and use dev env for RAILS_ENV. There many tricks for getting it up. Better try workbench.

**Comment by tzman89** [comment]
@yivo thanks for answering
Its clearly problem with rabbitmq, since I have it on remote server, I even added new user since guest is not working for remote but still getting connection problems.I can generate deposit address but not coins received to funds page and withdraws wont go trough.

since channel keys are out how can we setup wallet notify from bitcoind
Current:
> walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'

EDIT:
I just saw in https://github.com/rubykube/peatio/commit/535532b56e088f18d01e55eedba6f1b1ba27007a
that instead channel_key there is currency, so it will be 

> walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "currency":"btc"}

is this ok ?

**Comment by tzman89** [comment]
@yivo 
since channel keys are out how can we setup wallet notify from bitcoind
Current:

> walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'

**Comment by yivo** [comment]
@tzman89 Exactly.

![image](https://user-images.githubusercontent.com/7421323/38096506-b0c6953c-337b-11e8-8095-5d167228b8a7.png)

**Comment by legends420** [comment]
i have tried this but still get message published but NOT routed.. is there another way?

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
