### ISSUE TITLE
All data in trade page is blank

### ISSUE THREAD

**Issue by AddzMDev** [openware/peatio#750]
This maybe duplicate with [#742](https://github.com/rubykube/peatio/issues/742) but I'm still cannot find the solution and I'm also read [https://github.com/rubykube/peatio/blob/master/docs/releases/1.5.0.md](https://github.com/rubykube/peatio/blob/master/docs/releases/1.5.0.md)  and found 

> The trading UI app will first download variables for specified market_id (like btcusd) from Peatio by issuing HTTP GET https://peatio.io/markets/btcusd.json, and then render Rails views according to received variables.

but https://peatio.io/markets/btcusd.json is invalid and I'm also not sure whether this link should be point to https://peatio.io/markets/btcusd.json or to http://localhost:3000/markets/btcusd.json in my localhost if it need to point to http://localhost:3000/markets/btcusd.json I've found that all data of each market contain only zero value like

```
"markets": [
  {
    "id":"btcusd",
    "name":"BTC/USD",
    "quote_unit":"usd",
    "base_unit":"btc",
    "ticker":{
      "low":"0.0",
      "high":"0.0",
      "last":"0.0",
      "volume":"0.0",
      "open":"0.0",
      "sell":"0.0",
      "buy":"0.0",
      "at":1522224522
    }
  },
  {
    "id":"xrpusd",
    "name":"XRP/USD",
    "quote_unit":"usd",
    "base_unit":"xrp",
    "ticker": {
      "low":"0.0",
      "high":"0.0",
      "last":"0.0",
      "volume":"0.0",
      "open":"0.0",
      "sell":"0.0",
      "buy":"0.0",
      "at":1522224522
    }
  },
  ....,
  ..,
  .,
]
```
Did I've miss something please advise

**Comment by tzman89** [comment]
@AddzMDev 
1. Put peatio and peatio-trading-ui in the same folder (run bundle install for peatio-trading-ui) 
2. Change configs for both and setup nginx with config from /ci/nginx/server.conf
3. Follow instructions for peatio as usual
4. Install screen (read how to use multiple windows) on your server
5. In one screen window bundle exec rails server and in another bundle exec rails server -p 4000

This should work, I made it work like this

**Comment by tzman89** [comment]
@AddzMDev 
peatio.io is only sample, ofc you will use your own domain
All data is stored into database, so .json will show you zero value until you make some transactions in your market.

Also I think that you need to use domain with nginx config from ci/nginx/server.conf to get market working.

**Comment by yivo** [comment]
@AddzMDev Please, check website peatio.trade and see how does it work. Please, ping here if you still have issues. We have successfully deployed peatio 1.5 using both docker-compose & k8s with trading UI and it works.

**Comment by yivo** [comment]
@AddzMDev Feel free to reopen the issue if you still expect problems.

**Comment by nchigwamba** [comment]
@AddzMDev Have a look at https://github.com/rubykube/workbench/pull/40. Hope it helps.

**Comment by ianeinser** [comment]
Hi @yivo i checked peatio.trade. It is not available. Can you suggest me other url?

@tzman89 would you please explain more precisely how to do transactions?
