### ISSUE TITLE
Hiring: Setup of platform and Dividends Token&Referral Implimentation

### ISSUE THREAD

**Issue by CryptoTT** [openware/peatio#753]
I am looking for a developer for this platform, who is able to setup in cloud security (complete setup - hot wallet/cold wallet procedures - bank account API/fintech, etc.)
I did try to contact the peatio team, but they did not seem interested in any custom development.

The following has to be implemented:
Setup platform securily (all above)
Trading Fees Dividends of a Custom ERC20 token on the system (75% trading fees distributed to holders according to their holders)
Referral Program 10% of users trading fees are to be taken from the 25% earned to the platform, so when a referred member fee is distributed; 75% to custom ERC20 token Holders, 15%(referred)/25%(not referred) to platform and 10% for the user who referred.

Basic Notes:
- Dividends and referral is to be distributed daily
- Referral Program the percent (10%) is to be taken from the 25% earned to the platform, so when a referred member fee is distributed; 75% to custom ERC20 token Holders, 15/25% to platform, 10% for the user who referred, if referred)
- System feature to payout referral once daily (time to be set in administration panel) - payout in all the different traded coins respectively to them
- The percentages should be able to be changed in the administration panel.
- Generally all settings implimented should be able to be changed in the administration panel.
- Able to freeze withdrawl on Custom ERC20 token via. admin panel.

Initial Trading pairs(before exchange launch):       
-Custom ERC20 token/USD - enabled
-Custom ERC20 token/ETH - enabled
-Custom ERC20 token/BTC - enabled
-BTC/USD - disabled
-ETH/USD - disabled
-ETH/BTC - disabled
I will be able to go into detail if somebody here is interested with the experience, most likely somebody has already implemented these features for a previous client.
Please leave an estimated price for the project.

**Comment by ashanaakh** [comment]
Hi, @CryptoTT.

You may contact `hello@peatio.tech` to get professional help of https://www.peatio.tech platform installation.

**Comment by ashanaakh** [comment]
Hi, @CryptoTT.

You may contact `hello@peatio.tech` to get professional help of www.peatio.tech platform installation.

**Comment by shal** [comment]
Hi, @CryptoTT.

You may contact hello@peatio.tech to get professional help of www.peatio.tech platform installation.

**Comment by CryptoTT** [comment]
I did try and talk to peatio.tech, but it seemed they were not interested in any custom development, as they had bigger customers - thats why I went here.
As for why I asked for security experience is because I have only developed myself in .net and windows - so I would like somebody with experience, as installing myself is possible, I would want to know that it is secure (and ofcause somebody who should develope above features, should also have security experience for the platform+OS)

**Comment by yivo** [comment]
@CryptoTT Hi, I think this is not right place for things of this kind. You would better contact peatio.tech.
