### ISSUE TITLE
MISCONF Redis is configured to save RDB snapshots

### ISSUE THREAD

**Issue by khalidMahmod** [openware/peatio#754]
I'm getting following error at a regular interval:

Redis::CommandError in Private::FundsController#index
MISCONF Redis is configured to save RDB snapshots but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error. 

daemons log file size is huge. and it also gives following error:

The application could not be started.

Exception type: Passenger::SystemException
Error message: Cannot create a temporary directory in the format of '/tmp/passenger-spawn-debug.XXX': No space left on device (errno=28)
Backtrace:
in 'void Passenger::SpawningKit::SmartSpawner::startPreloader()' (SmartSpawner.h:209) in 'virtual Passenger::SpawningKit::Result Passenger::SpawningKit::SmartSpawner::spawn(const Options&)' (SmartSpawner.h:801) in 'void Passenger::ApplicationPool2::Group::spawnThreadRealMain(const SpawnerPtr&, const Passenger::ApplicationPool2::Options&, unsigned int)' (SpawningAndRestarting.cpp:95)

Could anyone please help me?

**Comment by yivo** [comment]
Hi @khalidMahmod 

You are running out of your disk space. Just clean your disk & configure logrotate (or disable logs).
