### ISSUE TITLE
USD Deposits behaviour

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#760]
![image](https://user-images.githubusercontent.com/11189687/38108075-60ba4698-33b1-11e8-9b0f-1b40bc2cda96.png)

I'm getting this screen on deposits, how can add a request to add funds??

**Comment by yivo** [comment]
@martianatwork You need to navigate to /admin/deposits/usd/new and create new deposit, then accept it.

**Comment by martianatwork** [comment]
Im getting this on submit
![image](https://user-images.githubusercontent.com/11189687/38132876-82693280-342a-11e8-93eb-0f2e87793618.png)

Also, how can user request for funds??

**Comment by yivo** [comment]
@martianatwork check the reference number for validity. User can't request funds.
