### ISSUE TITLE
API for fetching saved addresses for ccy doesn't work

### ISSUE THREAD

**Issue by ymasiuk** [openware/peatio#764]
![deepinscreenshot_select-area_20180330122830](https://user-images.githubusercontent.com/26141524/38133094-628a7b5e-3416-11e8-89df-a027a7788cfc.png)

**Comment by yivo** [comment]
@emasiuk The URL address is not correct. Please, check https://github.com/rubykube/peatio/blob/master/docs/releases/1.4.0.md.
