### ISSUE TITLE
After canceling order it is not saving in History

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#765]
One an order is matched, the resulting trade should go to user's history. Right now, when an order is fully matched the order goes to state "done". But the problem arises when the order is partially matched and the user cancels the order. This results in no history and the user not knowing what happened.

**Comment by dinesh-skyach** [comment]
Hi @mkuvshynnikov @yivo 

I have checked the issue. And found that the functionality is working accordingly i.e if the order is fully fulfilled then the order state is changed to done and when the order is partially fulfilled then it shows open and if we cancel the partial order then the state is changed to cancel. As currently we have three states i.e wait, done and cancel.

![screenshot from 2018-04-06 15-46-04](https://user-images.githubusercontent.com/35770481/38419402-f4aa6844-39bd-11e8-8628-b1b1f5c749de.png)

**Comment by yivo** [comment]
@mkuvshynnikov @dinesh-skyach This is definitely issue with UI. I am closing it since we don't want too much work on the existing UI.
