### ISSUE TITLE
Peatio API V2 Service

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#767]
Hi,

I want to use v2 api to perform deposit/withdraw operation. I am completely new to it and not sure what all steps i have to perform to enable the same. Please help me to understand what all configurations and request/response format i need to use to achieve it.

**Comment by yivo** [comment]
Hi @sharmaabhishek2207 

Unfortunately we currently don't have complete documentation for all the stuff you requested. For this moment you can check API reference which is almost up to date: https://test.kayen.io/documents/api_v2 

Hope this helps you.
