### ISSUE TITLE
getting warning while rake db:create

### ISSUE THREAD

**Issue by nantestdeveloper** [openware/peatio#778]
ruby version using 2.5.0
$ rake db:create
/home/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)/home/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 180 was converted to "180". (StructuredWarnings::StandardWarning)/home/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3000 was converted to "3000". (StructuredWarnings::StandardWarning)/home/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)ruby_kube_peatio_development already exists
ruby_kube_peatio_test already exists

**Comment by yivo** [comment]
Hi @nantestdevoloper 

These warnings are OK. They come from figaro gem.
