### ISSUE TITLE
Change of the server

### ISSUE THREAD

**Issue by MariaBog** [openware/peatio#780]
Is it possible and what is the process would be to have the exchange installed onto customer's servers and whether the customer would have access to the code?

**Comment by oskanddr** [comment]
Hello @MariaBog 
I am Ruby on Rails engineer with solid experience in Peatio.
I can help you with deployment and configuration.
Reply if you are interested. Thank you.

**Comment by yivo** [comment]
@MariaBog I don't think this is the good place for such kind of things.

**Comment by yivo** [comment]
Ping peatio.tech for this service.
