### ISSUE TITLE
When Accept Deposit from Admin UI, get error undefined method `may_submit?' for #<Deposits::Fiat>

### ISSUE THREAD

**Issue by lizhuomeng71** [openware/peatio#795]
Version Peatio 1.6 
STR: 
1. Login in as admin via Barong
2. Go to admin UI
3. Click Deposit -> USD -> submit an deposit
4. Click Deposit -> USD -> click view for the newly submitted deposit

Expect
Accept form

Actual
Error Message: please see screen shot for error message.

Last known working version 1.5

![image](https://user-images.githubusercontent.com/7528736/38399925-2c4d1308-3902-11e8-85eb-6b3a03d3a0c2.png)

Did I miss config something?

**Comment by yivo** [comment]
@lizhuomeng71 Thank you for the report. I will fix it soon!

**Comment by yssavchuk** [comment]
Probably problem in this line 859031d#diff-a33daedbd6f42e19fca2e90e6a85cd51L36

**Comment by ysv** [comment]
Probably problem in this line 
https://github.com/rubykube/peatio/commit/859031d5c74c2cb0ec7e10f6cc7344d0541c7cc0#diff-a33daedbd6f42e19fca2e90e6a85cd51L36

**Comment by yivo** [comment]
@yssavchuk The PR is waiting for QA https://github.com/rubykube/peatio/pull/806
