### ISSUE TITLE
Definitely BIG problems with BitGo API

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#801]
We expect big problems with BitGo API which is documented at https://www.bitgo.com/api/v2/

1. The method for creation of addresses doesn't return valid response: https://www.bitgo.com/api/v2/#create-wallet-address.

Response from creation of BTC address:
![image_2018-04-04_16-48-03](https://user-images.githubusercontent.com/29736025/38410374-10667234-398d-11e8-9657-01ecea5b9e92.png)

Response from creation of ETH address (it ever doesn't include ETH address):
![image_2018-04-04_16-47-40](https://user-images.githubusercontent.com/29736025/38410463-4e5bcb48-398d-11e8-9742-aad1c3d3454d.png)

2. API for XRP says "Service unavailable".

We use both free and enterprise accounts. We use testnet. Can you help with these? What is going on?

We've got response from the BitGo engineer:

"
1. Please see the "Generating addresses" section of https://www.bitgo.com/api/v2/#ethereum API docs. Ethereum works differently than the bitcoin-like coins in that when you create an address, it takes some time for it to be properly generated because address creation requires a transaction to be confirmed on the Ethereum network, so we don't return the address until it's creation is confirmed on the network. This is just how Ethereum contracts work, if we didn't do it this way, then you could mistakenly send your coin to an address that wasn't created yet and lose the coin.

2.
Thank you for bringing this to our attention! This was a problem with one of our internal components that I've since fixed, you'll see it returning valid response now."

**Comment by yivo** [comment]
@mkuvshynnikov They still havent answered why response for bitcoin generation is WRONG.

**Comment by yivo** [comment]
Fixed in #797.
