### ISSUE TITLE
Email notification 'ETHD withdrawal has been successfully submitted' is sent, when withdraw was rejected 

### ISSUE THREAD

**Issue by TasyaBykova** [openware/peatio#812]
Withdraw can be rejected if withdraw address is wrong.

email notification sample: 

'The request of your ETHD withdrawal has been successfully submitted, We will process it as soon as possible. Please be patient with us. Contact us if you have any questions.

If it's not you, please contact us ASAP.

Thanks,
The Peatio Team'

### Expected result: 

Option 1: Email notification is not sent at all. 

Option 2: Correct email notification is sent, like 'Your withdraw was rejected, because..'

**Comment by yivo** [comment]
@TasyaBykova Hi. Emails doesn't work for you because of deployment issue. Contact Valentine.

Also don't care much about mails now. See #758.
