### ISSUE TITLE
Switch to slanger by default

### ISSUE THREAD

**Issue by mod** [openware/peatio#830]

**Comment by yivo** [comment]
@mod Really there are nothing to do with. Peatio already works well with Pusher. Recently we merged patch which simplifies Peatio configuration for Slanger: https://github.com/rubykube/peatio/commit/22bad80ac27c1f69523ab96c9dd87e9746cfaf85#diff-81b753b02c902d26e3b837d7814c5244

So the only thing I can do is upgrading pusher.js

**Comment by arruah** [comment]
How to run slanger?

**Comment by yivo** [comment]
I believe this is closed via https://github.com/kaigara-images/slanger

If not please reopen.
