### ISSUE TITLE
rake aborted!  (bundle exec rake tmp:create yarn:install assets:precompile)

### ISSUE THREAD

**Issue by EarlVadim** [openware/peatio#853]
Hello.
I tried install of Peatio, but got error...

**deploy@vmi176246:~/peatio/current$ bundle exec rake tmp:create yarn:install assets:precompile**
/usr/bin/env: ‘node’: No such file or directory
rake aborted!
Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
/home/deploy/peatio/current/config/initializers/assets.rb:32:in `chdir'
/home/deploy/peatio/current/config/initializers/assets.rb:32:in `<top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'

**Nodejs**
deploy@vmi176246:~/peatio/current$ nodejs -v
v4.2.6

**Yarn**
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/lib
└── yarn@1.5.1

**Comment by yivo** [comment]
Check the second line.
