### ISSUE TITLE
Charts building issue 

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#854]
This issue can be found in exchange of UAH/* and if you have option "Candlestick" active.
![selection_048](https://user-images.githubusercontent.com/38254545/38684366-354ee280-3e78-11e8-9d39-f6cdc332b717.png)

Next issue can be recreated if the chart are empty at the first place like below:
![selection_053](https://user-images.githubusercontent.com/38254545/38685261-26c6d9e6-3e7a-11e8-8ec9-aab0a756c60e.png)
Make any transaction and you will get forever loading
![selection_052](https://user-images.githubusercontent.com/38254545/38685327-54a6fc6a-3e7a-11e8-9cb8-535972f49947.png)

**Comment by yivo** [comment]
@pkucherenk0 Please move this issue to trading Ui. Thanks.
