### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by ghost** [openware/peatio#857]
So I had the exchange running for a day, then I noticed the ubuntu machine was out of space?? So I narrowed down the issue and found this.

![Ummm](https://i.imgur.com/PwLH2VB.png)

**Comment by yivo** [comment]
Hi @Tach-Yon 

This is not memory leak, this is disk usage because of logs. I am wondering where did you get these logs. We don't write anything to files. You should update version of Peatio either use logrotate.

**Comment by ghost** [comment]
I seriously don’t know how they spawned into existence. Now there’s no logs written anymore so I guess that was odd.
