### ISSUE TITLE
NoMethodError: undefined method `deep_symbolize_keys'

### ISSUE THREAD

**Issue by tauryuan** [openware/peatio#858]
when i run bundle exec rake db:setup
console show error:

NoMethodError: undefined method `deep_symbolize_keys' for #<String:0x000055c969034d68>
/home/rick/peatio/config/initializers/jwt.rb:10:in `<top (required)>'

**Comment by tauryuan** [comment]
i mark  management_api_v1.yam line 1,2,3 and end line
run again is OK

**Comment by glaksmono** [comment]
@tauryuan what do you mean by you "mark management_api_v1.yml"?
