### ISSUE TITLE
error:  cannot load such file -- em-http    

### ISSUE THREAD

**Issue by sg552** [openware/peatio#859]
hi @yivo ,

  I met this error:  cannot load such file -- em-http.  
![screenshot from 2018-04-13 15-54-03-em-http](https://user-images.githubusercontent.com/234533/38723285-27f11afc-3f33-11e8-9cc0-854d8aba4316.png)

  I managed to configure all the settings ( including pusher) , but met this problem. 

my branch:   1.6.0  ( both peatio and peatio-trading-ui),  
os: ubuntu 14.
ruby:  2.5.0
database:  mysql 

   could you please give me a clue?   thanks a lot. 
   (BTW,  if I comment out this line of code , seems most functions work well. )

Siwei

**Comment by yivo** [comment]
Hi @sg552 

I am wondering what gem requires `em-http`. I don't ever see this dependency in Gemfile.lock.

I think the problem is in your gems. Try cleaning all and reinstall.

Also, we don't ubuntu installation. Please, use docker.

**Comment by sg552** [comment]
thank you so much @yivo.    

I will install it using docker.

**Comment by sg552** [comment]
BTW  , to solve this problem ,just adding this line to your Gemfile and then `bundle` and restart. :

```
gem 'em-http-request'
```

https://github.com/igrigorik/em-http-request
