### ISSUE TITLE
Depositing Daemon Issues

### ISSUE THREAD

**Issue by ghost** [openware/peatio#861]
So I was trying to figure this one out for a couple days. Essentially what is happening is that whenever I try to deposit a coin, nothing gets updated unless I completely re-run god:

```god -c lib/daemons/daemons.god```

Do you suppose this may be connected to the depositing issue?

I should add that withdrawing works perfectly fine.

System: Ubuntu 16.04

However, I was looking through the foreground console of god (-D parameter) and found this

```I [2018-04-13 10:02:55]  INFO: coins [ok] process is not running (ProcessRunning)
F [2018-04-13 10:02:57] FATAL: Unhandled exception (StandardError): No buffer space available
/usr/local/rvm/gems/ruby-2.5.0/gems/god-0.13.7/lib/god/event_handler.rb:62:in `handle_events'
/usr/local/rvm/gems/ruby-2.5.0/gems/god-0.13.7/lib/god/event_handler.rb:62:in `block (2 levels) in start'
/usr/local/rvm/gems/ruby-2.5.0/gems/god-0.13.7/lib/god/event_handler.rb:60:in `loop'
/usr/local/rvm/gems/ruby-2.5.0/gems/god-0.13.7/lib/god/event_handler.rb:60:in `block in start'```

**Comment by yivo** [comment]
Hi @Tach-Yon 

I feel this issue is related to god itself or to your system. We don't support non-docker deployment so please use stable Docker env. We don't expect this issued and we never had it. Please, also check the free space on your disk.

**Comment by yivo** [comment]
We are looking to get away from god and use sneakers in future.
