### ISSUE TITLE
Unable to disable Web / API access at admin panel

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#862]
![Selection_066.png](https://images.zenhubusercontent.com/5acdedd34b5806bc2bcea023/f99310f7-7676-4fce-ab65-929f25e330fe)

http://peatio.trade/admin/members 
This functions seems to do nothing.

**Comment by Sambusik** [comment]
n.b. Its not updating the text on click, however if you refresh the page, you'll see the updated status

**Comment by yivo** [comment]
Bug was not confirmed.
