### ISSUE TITLE
UI issues with the left navigation bar at admin panel

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#863]
![Selection_060.png](https://images.zenhubusercontent.com/5acdedd34b5806bc2bcea023/3a1ff17a-9a9d-4ae0-9080-219d0d919e43)
![Selection_061.png](https://images.zenhubusercontent.com/5acdedd34b5806bc2bcea023/c22cc616-8be0-4ff4-b9d0-30f9165d2c78)
![Selection_064.png](https://images.zenhubusercontent.com/5acdedd34b5806bc2bcea023/da0ce145-6695-4e4f-b400-4e8ba9ba4690)

**Comment by pkucherenk0** [comment]
![selection_073](https://user-images.githubusercontent.com/38254545/38746587-a58fac0e-3f50-11e8-838d-d49100d2e8a1.png)

**Comment by webmix** [comment]
@pkucherenk0 
Fixed here: https://github.com/rubykube/peatio/pull/880

- sidebar is now scrollable
- disabled for now sidebar toggle
- footer now at the bottom

About duplications: are they really a problem ?

**Comment by pkucherenk0** [comment]
Duplication is irrelevant at the moment.
Some issues with scrolling:
1. If sidebar and main menu will be scroll able move the cursor to the sidebar and scroll. Both will be scrolled at the same time.
2. if you will make your browser window small the page will become scroll able horizontally. Pull right.
(http://peatio.trade/admin/deposits/btc)

![selection_101](https://user-images.githubusercontent.com/38254545/38876337-f5b9ba82-4264-11e8-952f-4086bcafc990.png)

**Comment by yivo** [comment]
Fixed in #912.
