### ISSUE TITLE
Remove the Pusher panel and code

### ISSUE THREAD

**Issue by yivo** [openware/peatio#864]
It is sticky. 

![image](https://user-images.githubusercontent.com/7421323/38744456-870579a4-3f4a-11e8-8fe4-59a460da6fd9.png)

**Comment by webmix** [comment]
@yivo It should be sticky you mean?

**Comment by yivo** [comment]
@webmix No, just remove this panel.

**Comment by webmix** [comment]
@yivo 
You ask to remove also code. I noticed that those alerts were using a generic alert template.
How to know it won't be used by any other alert ?

This is not really front-end related task.
Please assign to a backend dev

**Comment by anbuhckr** [comment]
I think the container in _alert.html.erb is the problem.

**Comment by yivo** [comment]
Closed by #922
