### ISSUE TITLE
Update styles for admin/currencies  

### ISSUE THREAD

**Issue by ysv** [openware/peatio#865]
![deepinscreenshot_select-area_20180413185036](https://user-images.githubusercontent.com/19859122/38744840-9006d682-3f4b-11e8-8d5e-ad1538770caf.png)
![deepinscreenshot_select-area_20180413185104](https://user-images.githubusercontent.com/19859122/38744844-910a92f8-3f4b-11e8-840d-394bbb5827e7.png)

**Comment by ysv** [comment]
also add currencies to nav bar

**Comment by yivo** [comment]
@yssavchuk I have added missing rubric in https://github.com/rubykube/peatio/pull/901

**Comment by yivo** [comment]
Fixed in #917.
