### ISSUE TITLE
UI Proofs -> Edit improvements 

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#866]
![Selection_071.png](https://images.zenhubusercontent.com/5acdedd34b5806bc2bcea023/cee9d6f3-0d73-4888-8e00-e05e97bbab8c)
![Selection_070.png](https://images.zenhubusercontent.com/5acdedd34b5806bc2bcea023/5ce19b94-8807-47df-97b9-00683384f41f)

**Comment by yivo** [comment]
Closed via #924 #925.
