### ISSUE TITLE
UI improvements of Deposits (UAH) and Withdraws (all) 

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#867]
2. Deposits (UAH) -> View  (http://peatio.trade/admin/deposits/uah/255)
![Selection_063.png](https://images.zenhubusercontent.com/5acdedd34b5806bc2bcea023/69ae58a5-36a9-44a5-8c34-2f22ac8c3234)

3. Withdraws -> UAH -> View (http://peatio.trade/admin/withdraws/uah/312)
![Selection_069.png](https://images.zenhubusercontent.com/5acdedd34b5806bc2bcea023/ff1fe5fa-0351-4076-a8e8-034d9228a410)

**Comment by yivo** [comment]
@webmix Please, skip 1. You can do 2 (only color) and fully 3.

**Comment by webmix** [comment]
@pkucherenk0 Please provide more details when you report issues, just a screenshot isn't enough, I have difficulties to find the pages.

Please provide:
- URL
- Step to reproduce the issue (if necessary)

Also, please note:
- Texts: I am not responsible of text contents. Everything that is in the UI was here previously. 
- Color codes: same thing, I am just using the color codes that were here previously
Those are UX things, I can help of them if you need but I don't think it's related with front-end framework migration

**Comment by yivo** [comment]
@pkucherenk0 Please confirm this issue is still actual.

**Comment by pkucherenk0** [comment]
![selection_134](https://user-images.githubusercontent.com/38254545/39044664-86237a78-4499-11e8-8d99-6b383784b992.png)
Can confirm that issue is actual.

**Comment by pkucherenk0** [comment]
@webmix Please remove nonworking copy icons.

**Comment by yivo** [comment]
Closed by #936 #937.
