### ISSUE TITLE
rake db:seed probably breaks

### ISSUE THREAD

**Issue by ab320012** [openware/peatio#869]
Hi guys, thanks for working on this library. I was looking at your implementation and found that rake db:seed is probably broken.

It is calling rake currencies:seed which looks in config/seeds/currencies.yml but does not find the file. on the master branch, let me know. Markets is the same story.

**Comment by ghost** [comment]
`markets:seed` is broken, though the `currencies:seed` works fine. My suggestion is just to manually update the market if you want to add a coin until it's fixed?

**Comment by ab320012** [comment]
Hmm weird that it works maybe you have an untracked file or something because the current master does not have config/seeds/currencies.yml file as far as I can see

**Comment by ghost** [comment]
`config/seeds` is generated from the template files through `bin/init_config` though. All the files are there, it's only `markets:seed` that screw up.

**Comment by ab320012** [comment]
Oh nice thank you for the explanation I will close the issue
