### ISSUE TITLE
UI improvements to a funds page

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#872]
![selection_082](https://user-images.githubusercontent.com/38254545/38805031-111440b0-417d-11e8-8666-cdb3007cc22e.png)

**Comment by yivo** [comment]
Fixed in #917.

**Comment by nantestdeveloper** [comment]
@pkucherenk0  How do I customise the UI of funds? new to rails angular stack . Not able to customise the ng  classes and table view.
