### ISSUE TITLE
UI improvements to a Members page in admin panel

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#873]
![selection_083](https://user-images.githubusercontent.com/38254545/38805242-d10b8572-417d-11e8-9e44-43ceb157bb45.png)

**Comment by webmix** [comment]
@pkucherenk0 can you confirm this issue is still on master?
I can't reproduce it

**Comment by yivo** [comment]
@webmix I can confirm this issue exists.

![image](https://user-images.githubusercontent.com/7421323/38817772-c2bfb0a0-41a1-11e8-818d-4d245c1778a8.png)

**Comment by webmix** [comment]
This is strange I can't reproduce.
We have to check if some column got any fixed value that would increase it's width so much.
Now I just see .col-1 which is supposed to be a small value.
I will investigate

**Comment by yivo** [comment]
Fixed in #917.
