### ISSUE TITLE
Funds withdraw issue, the Withdraw History isn't updating to the last status. 

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#875]
Try to withdraw any currency (do not matter where).
First you will the the missing translation:
![selection_085](https://user-images.githubusercontent.com/38254545/38805890-2cfc977a-4180-11e8-8c99-1ae879ab5458.png)

Then the status updates twice but will never get to the Fail or Success status without manual page update.
![selection_078](https://user-images.githubusercontent.com/38254545/38805585-f7e2614c-417e-11e8-8063-af996af4d5c5.png)

**Comment by shal** [comment]
@yivo I confirm this bug

**Comment by yivo** [comment]
@ashanaakh Confirmed on peatio.trade?

**Comment by yivo** [comment]
@ashanaakh Can you please add missing translations?

**Comment by yivo** [comment]
Closed by #965
