### ISSUE TITLE
Spec is failing (seed 13602)

### ISSUE THREAD

**Issue by yivo** [openware/peatio#88]
This spec is marked as pending (feature still in development) but I am curious if sub-features work correctly because it fails now with different messages. We probably need to check if it is "pending" still.

![deepinscreenshot_select-area_20171213165346](https://user-images.githubusercontent.com/7421323/33945285-4071841a-e027-11e7-9fbf-7ebc6d75e323.png)

**Comment by ysv** [comment]
@yivo I found this test to be in development still because when we click on cancel order we expected order to be deleted but it doesn't
![screen shot 2018-01-04 at 2 50 21 pm](https://user-images.githubusercontent.com/19859122/34564295-c2794cca-f15e-11e7-8a20-4cd779b28470.png)

**Comment by yivo** [comment]
@yssavchuk This issues is related to unimplemented deletion of orders. Continued in #248.
