### ISSUE TITLE
Unexpected URL for fiat deposit page (admin panel)

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#883]
STR:

1. as an admin user go to http://peatio.trade/admin/
2. click on Deposits 
3. from the drop down list chose UAH or USD (remember the choice) then click on it
4. click on New Deposit button 
Note: that one account have only one SN (it is the same for UAH and USD)
5. fill up all fields with valid data (like: "Amount: 100", "Currency: *(opposite from your choice in step 3)", "SN: SNF6129D21A9")
![selection_097](https://user-images.githubusercontent.com/38254545/38865475-8ecc2224-4246-11e8-8088-9844c15de9dd.png)

Find that the currency you will deposit will depend on you chose in step 3, not from the Currency in the New Deposit drop down list.

**Comment by yivo** [comment]
I think we need to remove select and start trusting URL.

**Comment by yivo** [comment]
Closed by #992.
