### ISSUE TITLE
is there a guide to add new BTC based coin (altcoin)?

### ISSUE THREAD

**Issue by gitgut1000** [openware/peatio#889]
The guide in /docs/peatio/ seems to be not updated.
Thanks

**Comment by yivo** [comment]
There is no guide for it. For BTC based just add entry to currencies seed file and specify APi client as BTC.

**Comment by gitgut1000** [comment]
hmmm. added coin id 8, as you said, recompiled the assets (i don't know if even needed), restarted rails, still don't see it in the admin panel ... any ideas?

**Comment by gitgut1000** [comment]
solved :)

**Comment by rraallvv** [comment]
@gitgut1000 What version did you installed the coin in, is it `1-8-stable`?
