### ISSUE TITLE
non bitgo coin wallet address

### ISSUE THREAD

**Issue by gitgut1000** [openware/peatio#891]
hi,

in the original peatio the local wallet address was set here (under currencies.yml):

assets:
    accounts:
      -
        address: 0x4bA2474e063Aec44e23F2Bf7Fb9e4e2878dBaB44

how is it in rubykube?

**Comment by yivo** [comment]
Not required.

**Comment by gitgut1000** [comment]
deposits are not accepted, not exists on db.

trying to send the message manually, still no go

rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"e9b67938ea8809ff7df14a10d60b50761feba43f2e2b9941b8f331a351091a38", "channel_key":"thecoin"}'
