### ISSUE TITLE
deposits not accepted

### ISSUE THREAD

**Issue by gitgut1000** [openware/peatio#893]
deposits are not accepted, not exists on DB.

trying to send the message manually, still no go. message sent, not received. 

rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"e9b67938ea8809ff7df14a10d60b50761feba43f2e2b9941b8f331a351091a38", "channel_key":"thecoin"}'

any idea?

**Comment by yivo** [comment]
@gitgut1000 Please DON'T USE legacy peatio docs. We are VERY different. For questions you may use Telegram chat (link in README). We don't have any channel_key anymore. Use currency.
