### ISSUE TITLE
UI fix horizontal scrolling 

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#900]
Some issues with scrolling:
1. If sidebar and main menu will be scroll able move the cursor to the sidebar and scroll. Both will be scrolled at the same time.
2. if you will make your browser window small the page will become scroll able horizontally. Pull right.
(http://peatio.trade/admin/deposits/btc)

![selection_101](https://user-images.githubusercontent.com/38254545/38926125-4cd2883a-430a-11e8-8408-ca797b936b62.png)

**Comment by webmix** [comment]
Fixed in https://github.com/rubykube/peatio/pull/912
