### ISSUE TITLE
Unrecognized currency on proof page

### ISSUE THREAD

**Issue by ec** [openware/peatio#902]
All currencies in proof section on admin panel of peatio are not displaying right
Attaching screenshot
![image 2](https://user-images.githubusercontent.com/25320212/38927052-346d2ac2-430d-11e8-883e-84944f5c5121.png)

**Comment by yivo** [comment]
This was already fixed. Upgrade pls.

**Comment by yivo** [comment]
Need to backport to 1.5

**Comment by yivo** [comment]
#737

**Comment by ysv** [comment]
@yivo close please

**Comment by yivo** [comment]
Closed in #910.
