### ISSUE TITLE
Footer in admin pannel

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#903]
In case if the page do not have much information footer will be to high.(http://peatio.trade/admin/deposits/uah/273)
1. go to admin opanel
2. click Deposits
3. click UAH or USD
4. click on any View 

(http://peatio.trade/admin/deposits/usd/new)
1. go to admin opanel
2. click Deposits
3. click UAH or USD
4. click on New Deposit 
![selection_107](https://user-images.githubusercontent.com/38254545/38927145-855ec896-430d-11e8-97ae-5f4a2be71c3d.png)

**Comment by webmix** [comment]
Already fixed
