### ISSUE TITLE
Bid/Ask fee change bug

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#905]
In case you will change ask/bid fee in the Admin panel -> Markets -> View (of any currency pare) for more than 0.5.
![selection_112](https://user-images.githubusercontent.com/38254545/38930951-4e376bf4-431a-11e8-8265-519be5334450.png)
You will confront the situation when the exchange transaction will not be finished.
![selection_109](https://user-images.githubusercontent.com/38254545/38930999-6dd864ea-431a-11e8-84be-b36b827f4a4c.png)

**Comment by yivo** [comment]
Nothing clear to me. Steps needed.

**Comment by pkucherenk0** [comment]
STR:

1. go to admin panel
2. proceed to Markets
3. find any pare you would like to establish fee and trade
4. click View
5. establish Bid and/or Ask to higher then 0.5
6. go to trade panel
7. find pare where you have change the fee
8. leave an ask fee and much bid fee on same or another account
9. Observe panel with all the offers; Observe panel with your offers; Observe account Order history

Then you can undo this stacked transaction simply by decreasing the Ask/Bid fee to 0.5 or less.

**Comment by pkucherenk0** [comment]
I have founded out that this Ask/Bid fee basically takes a percentage from the trade.
So if you will input fee 0.5 it will be same as 50% fee from transaction.
I suppose the Ask/Bid fee should not save more than 0.5 and show a warning in case some one will try to, as taking 50% from the bargain is already absurd high fee.

**Comment by yivo** [comment]
Closed by #954 #955 #956
