### ISSUE TITLE
Withdraw issue or lost 0.00000001

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#911]
Preset: 
-You should have a coin with amount 100 or higher (easiest with XRP) 
            
-Set the "Quick withdraw limit" to 100+ and "Withdraw fee" to 0.0, in the http://peatio.trade/admin/currencies (not necessary, just to make clear point)

-Some Bitgo test addres to send to (like rfUKVVX5KJQ2FsWYrjS6JMedz3jdjPhRPZ?dt=3)

STR:
1. Go to the funds menu 
2. Open Withdraw of coin currency that you have more than 100 
3. Input address to "Withdraw address" field you will withdraw to
4. Input 90.1 or 80.48 to "Withdraw amount" filed
5. Observe "Actual Amount" and State/Action column.

Expected: The "Actual Amount" should show you the amount that was withdrawn minus "Withdraw fee" (if you have it). The status should be "Done".

Actual: The "Actual Amount" will be incorrect (80.48999999 or 90.09999999). The status will be "Failed"

![selection_122](https://user-images.githubusercontent.com/38254545/38941998-5f0c27aa-4336-11e8-9f16-92cd427e44f8.png)

Some times it will happen to smaller amount but rarely.

 
![selection_123](https://user-images.githubusercontent.com/38254545/38942123-b24bec5c-4336-11e8-8b92-7aee48ca6e13.png)

**Comment by yivo** [comment]
The status «failed» is due to bitgo restrictions for precision. But the issue with losing 0.00000001 is real.

**Comment by yivo** [comment]
I think this is the issue with front. Probably it does something scary. Can you repeat and include XHR request / response?

**Comment by yivo** [comment]
cc @pkucherenk0

**Comment by pkucherenk0** [comment]
[2_Full.txt](https://github.com/rubykube/peatio/files/1927313/2_Full.txt)


POST http://peatio.trade/withdraws/xrp HTTP/1.1
Host: peatio.trade
Connection: keep-alive
Content-Length: 90
Accept: application/json, text/plain, */*
Origin: http://peatio.trade
X-CSRF-Token: CD+VAWCOYTbE9yLL1yx7Kr36JPp+NGn15es87Lh6L6BwAWPjU34h/+hlHaCzBZFiT35PW36zAckhhYMzxryDQQ==
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/65.0.3325.181 Chrome/65.0.3325.181 Safari/537.36
Content-Type: application/json;charset=UTF-8
Referer: http://peatio.trade/funds
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: _peatio_session=34cf6ec8349765a1dfe2367d883a4e20; sound=true; range_switch=60; type_switch=candlestick; main_indicator_switch=MA; indicator_switch=MACD

{"withdraw":{"currency":"xrp","sum":90.1,"rid":"rfUKVVX5KJQ2FsWYrjS6JMedz3jdjPhRPZ?dt=3"}}
HTTP/1.1 **204 No Content**
Server: nginx
Date: Thu, 19 Apr 2018 08:37:23 GMT
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Sat, 03 Jan 2009 00:00:00 GMT
Set-Cookie: _peatio_session=34cf6ec8349765a1dfe2367d883a4e20; path=/; expires=Thu, 19 Apr 2018 09:37:23 -0000; HttpOnly
X-Request-Id: 480a5eb0-d050-494b-8f70-ae8f38493d32
X-Runtime: 0.077943

**Comment by yivo** [comment]
Reproduction steps: `Order.new(fee: 90.1)`.

**Comment by yivo** [comment]
Closed by #963 #962 #958
