### ISSUE TITLE
Trading ccy-to-ccy with price less than 0.01 fails on 1-5-stable version.

### ISSUE THREAD

**Issue by ec** [openware/peatio#916]
In trading page all trades ccy-to-ccy failes when you are inserting price lower than 0.01

It makes sense to have price lower than 0.01 when you are trying, for example, buy 
1 XRP for BTC

**Comment by yivo** [comment]
@mafarain I need all the configs (really all please) for this to reproduce this bug. Please, also include reproduction steps. I could not reproduce this issue with steps that I have followed.

**Comment by yivo** [comment]
Linked issue https://github.com/rubykube/peatio-trading-ui/issues/25

**Comment by yivo** [comment]
MASTER

![image](https://user-images.githubusercontent.com/7421323/39252462-5d9922a6-48ae-11e8-92d1-4b64778405e5.png)

**Comment by yivo** [comment]
1.5

![image](https://user-images.githubusercontent.com/7421323/39253246-1e7c7f12-48b0-11e8-830b-2bcaf80a22a4.png)

![image](https://user-images.githubusercontent.com/7421323/39253273-2ece73ca-48b0-11e8-9e5a-1a60bd8e3f0c.png)

![image](https://user-images.githubusercontent.com/7421323/39253330-45abbcec-48b0-11e8-85ae-63a3df572e66.png)

**Comment by yivo** [comment]
@mafarain As you can see it works well on 1.5 and up. You just need to tweak configuration (markets.yml).
