### ISSUE TITLE
Unable to access peatio (peatio_daemons also throwing a lot of exceptions)

### ISSUE THREAD

**Issue by umaimehm** [openware/peatio#934]
**Environment:**
Peatio v 1.7 stable
barong v 1.7 stable
workbench v 1.6 stable
Tried on vagrant as well as a seperate ubuntu vm

**Issue:**
Peatio cannot be access through peatio:8001 OR localhost:8001
The console output shows,

Attaching to peatio
peatio            | Puma starting in single mode...
peatio            | * Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
peatio            | * Min threads: 5, max threads: 5
peatio            | * Environment: development
peatio            | /opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "REDIS_URL". Already set in ENV. (StructuredWarnings::
..... (a lot of similar warnings for environment varaibles)
Listening on tcp://0.0.0.0:3000
peatio            | Use Ctrl-C to stop

On running,  "docker logs peatio-daemons" I saw the following errors:

[amqp:matching at 2018-04-24 01:07:36] /opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.0/lib/bunny/session.rb:329:in `rescue in start': Could not establish TCP connection to any of the configured hosts (Bunny::TCPConnectionFailedForAllHosts)
[amqp:matching at 2018-04-24 01:07:36] 	from /opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.0/lib/bunny/session.rb:297:in `start'
[amqp:matching at 2018-04-24 01:07:36] 	from lib/daemons/amqp_daemon.rb:8:in `<main>'
[amqp:matching at 2018-04-24 01:07:36] W, [2018-04-24T01:07:36.316806 #122]  WARN -- #<Bunny::Session:0x55de9c826e48 guest@localhost:5672, vhost=/, addresses=[localhost:5672]>: Could not establish TCP connection to localhost:5672: Network is unreachable - connect(2) for [::1]:5672
[global_state at 2018-04-24 01:07:38] /opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect': Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory") (Mysql2::Error)
[global_state at 2018-04-24 01:07:38] 	from /opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
[gl

The error repeats for 
amqp:deposit_coin
hot_wallets
amqp:market_ticker
payment_transaction
coins
withdraw_audit
pusher_market

**Comment by yivo** [comment]
Hi @umaimehm 

From logs I can see your rabbitmq is not running or connection settings are broken. The same stands for MySQL. Please validate manually this two.

**Comment by umaimehm** [comment]
Found out that     
env_file:
      - ../config/peatio/application.env
was missing in app.yaml
