### ISSUE TITLE
Fiat withdrawal, lower amount than withdrawal limit issue.

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#940]
STR:

1. go to the peatio.trade admin panel.
2. go to Currencies -> USD (fiat).
3. set up Withdrawal limit to 1000, fee to 0.0 to make a clear point.
4. go to the funds and try to withdraw amount that is lower the limit (100-999 USD).

Expected: the withdrawal will proceed automatically.
Actual: the withdrawal will be stuck with Proceed status and will never finish.  
![selection_162](https://user-images.githubusercontent.com/38254545/39192469-e605e7d2-47e1-11e8-9ec3-1d82e742c631.png)

![selection_161](https://user-images.githubusercontent.com/38254545/39192415-cb658f36-47e1-11e8-9e72-27c631db233a.png)

**Comment by yivo** [comment]
Progress in #944 #943 #942
