### ISSUE TITLE
Withdrawal process cant be canceled 

### ISSUE THREAD

**Issue by pkucherenk0** [openware/peatio#945]
When you are making a withdrawal request of fiat, lower the withdrawal limit, the request will be processed right away, living you with no possibility to cancel. 
The possibility is missing from user interface an admin panel.
![selection_168](https://user-images.githubusercontent.com/38254545/39197899-5e4de9a4-47ee-11e8-860e-653ecd3e5027.png)

**Comment by yivo** [comment]
Progress in #952 #951 #949
