### ISSUE TITLE
Ability to create multiple deposit address per user per coin

### ISSUE THREAD

**Issue by NQA1** [openware/peatio#964]
There is a one to one relationship between a user and a coin address. In many exchanges, a user can create multiple deposit address so as to mask the user tx history as a privacy feature. Some users also like to label each deposit. So it should be a one to many relationship.

**Comment by yivo** [comment]
@mod Lets better use ZenHub pipelines instead of GitHub labels. I use labels for guys who don't have ZenHub installed as accessibility thing.

**Comment by mod** [comment]
we can, I will look into it asap,
meanwhile, what is your opinion on adding multiple deposit address

**Comment by Sambusik** [comment]
I agree with @NQA1 that Deposit addresses would be better for the user's privacy to deposit to a different address, rather than the same address each time. 

Previously Peatio used to allow adding new Deposit Addresses, however not sure why it was removed.

**Comment by yivo** [comment]
Closed by #1282.
