### ISSUE TITLE
Trading page gives 404

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#981]
the trading ui is configured at port 3000.

when i go to trading/1 or trading/btcusd it gives 404

**Comment by yivo** [comment]
@martianatwork Please, no ports and no localhosts. Use NGINX and config under ci directory. The GitHub issues are not for support. Use telegram channel.

**Comment by martianatwork** [comment]
@yivo Hey, I dont have the telegram channel information.
also i have used proper nginx config, it seems to me that markets structure has been updated in peatio but peatio trading ui is not.

heres link to my site http://coinarchs.com/trading/1

as you can see the error is `no implicit conversion of Integer into String`

so peatio was using url structure as 'trading/btcusd' now it is using 'trading/1' if you visit 'trading/btcusd' it gives 404
