### ISSUE TITLE
Implement event «market.btcusd.new_order»

### ISSUE THREAD

**Issue by kriskelly** [openware/peatio#996]
I'm interested in using the Events API to watch market orders, and I'm not seeing any events published to RabbitMQ. ~~Is there a config setting that would enable these? I'm using master @ be26879935ec4b164847bc75302e237b5fba5a62 .~~ Is there a roadmap in place to implement that in an upcoming release?

**Comment by yivo** [comment]
Hi @kriskelly 

No, there is no such event currently in the code. We are going to add it in the next few days.

**Comment by yivo** [comment]
Added in #1053.
