### ISSUE TITLE
market does not have a valid value

### ISSUE THREAD

**Issue by martianatwork** [openware/peatio#999]
On peatio trading page it calls {domain}/api/v2/k_with_pending_trades.json?market=1&limit=768&period=60&trade_id=0

but it gives '422 (Unprocessable Entity)' on console and on the
{domain}/api/v2/k_with_pending_trades.json?market=1&limit=768&period=60&trade_id=0 

page it gives
`{"error":{"code":1001,"message":"market does not have a valid value"}}`

**Comment by yivo** [comment]
@martianatwork Hi

Market ID is string starting from 1.6 and up. You haven't completed the migration in correct way: run `bin/init_config && bundle exec rake db:drop db:create db:migrate db:seed`.

**Comment by yivo** [comment]
Also please use the same versions for Peatio & Trading UI, like 1.7 & 1.7.
